/*
 * Currency unicode characters.
 *
 * This file was automatically converted from 'currency.dtsi',
 * included in the zmk-helpers module.
 */

#pragma once

#define UC_CURR_DOLLAR             0x24    0  // $(Dollar)
#define UC_CURR_CENT               0xa2    0  // ¢(Cent)
#define UC_CURR_POUND              0xa3    0  // £(Pound)
#define UC_CURR_CURRENCY           0xa4    0  // ¤(Currency)
#define UC_CURR_YEN                0xa5    0  // ¥(Yen)
#define UC_CURR_ARMENIAN_DRAM      0x58f   0  // ֏(ArmenianDram)
#define UC_CURR_AFGHANI_DRAM       0x60b   0  // ؋(Afghani)
#define UC_CURR_NKO_DOROME         0x7fe   0  // ߾(NkoDorome)
#define UC_CURR_BENGALI_RUPEE1     0x9f2   0  // ৲(BengaliRupeeMark)
#define UC_CURR_BENGALI_RUPEE2     0x9f3   0  // ৳(BengaliRupee)
#define UC_CURR_BENGALI_GANDA      0x9fb   0  // ৻(BengaliGandaMark)
#define UC_CURR_GUJARATI_RUPEE     0xaf1   0  // ૱(GujaratiRupee)
#define UC_CURR_TAMIL_RUPEE        0xbf9   0  // ௹(TamilRupee)
#define UC_CURR_THAI_BAHT          0xe3f   0  // ฿(ThaiBaht)
#define UC_CURR_KHMER_RIEL         0x17db  0  // ៛(KhmerRiel)
#define UC_CURR_COLON              0x20a1  0  // ₡(colon)
#define UC_CURR_CRUZEIRO           0x20a2  0  // ₢(Cruzeiro)
#define UC_CURR_FRENCH_FRANC       0x20a3  0  // ₣(FrenchFranc)
#define UC_CURR_LIRA               0x20a4  0  // ₣(Lira)
#define UC_CURR_MILL               0x20a5  0  // ₥(Mill)
#define UC_CURR_NAIRA              0x20a6  0  // ₦(Naira)
#define UC_CURR_PESETA             0x20a7  0  // ₧(Peseta)
#define UC_CURR_LEGACY_RUPEE       0x20a8  0  // ₨(LegacyRupee)
#define UC_CURR_WON                0x20a9  0  // ₩(Won)
#define UC_CURR_NEW_SHEQEL         0x20aa  0  // ₪(NewSheqel)
#define UC_CURR_DONG               0x20ab  0  // ₫(Dong)
#define UC_CURR_EURO               0x20ac  0  // €(Euro)
#define UC_CURR_KIP                0x20ad  0  // ₭(Kip)
#define UC_CURR_TUGRIK             0x20ae  0  // ₮(Tugrik)
#define UC_CURR_DRACHMA            0x20af  0  // ₯(Drachma)
#define UC_CURR_GERMAN_PENNY       0x20b0  0  // ₰(GermanPenny)
#define UC_CURR_PESO               0x20b1  0  // ₱(Peso)
#define UC_CURR_GUARANI            0x20b2  0  // ₲(Guarani)
#define UC_CURR_AUSTRAL            0x20b3  0  // ₳(Austral)
#define UC_CURR_HRYVNIA            0x20b4  0  // ₴(Hryvnia)
#define UC_CURR_CEDI               0x20b5  0  // ₵(Cedi)
#define UC_CURR_LIVRE_TOURNOIS     0x20b6  0  // ₶(LivreTournois)
#define UC_CURR_SPESMILO           0x20b7  0  // ₷(Spesmilo)
#define UC_CURR_TENGE              0x20b8  0  // ₸(Tenge)
#define UC_CURR_INDIAN_RUPEE       0x20b9  0  // ₹(IndianRupee)
#define UC_CURR_TURKISH_LIRA       0x20ba  0  // ₺(TurkishLira)
#define UC_CURR_NORDIC_MARK        0x20bb  0  // ₻(NordicMark)
#define UC_CURR_MANAT              0x20bc  0  // ₼(Manat)
#define UC_CURR_RUBLE              0x20bd  0  // ₽(Ruble)
#define UC_CURR_LARI               0x20be  0  // ₾(Lari)
#define UC_CURR_BITCOIN            0x20bf  0  // ₿(Bitcoin)
#define UC_CURR_SOM                0x20c0  0  // ⃀(Som)
#define UC_CURR_NORTH_INDIC_RUPEE  0xa838  0  // ꠸(NorthIndicRupee)
#define UC_CURR_RIAL               0xfdfc  0  // ﷼(Rial)
#define UC_CURR_WANCHO_NGUN        0xfdfc  0  // 𞋿(WanchoNgun)
