#pragma once

#include <zmk-unicode/keys/catalan.h>
#include <zmk-unicode/keys/currency.h>
#include <zmk-unicode/keys/czech.h>
#include <zmk-unicode/keys/danish.h>
#include <zmk-unicode/keys/faroese.h>
#include <zmk-unicode/keys/french.h>
#include <zmk-unicode/keys/german.h>
#include <zmk-unicode/keys/greek.h>
#include <zmk-unicode/keys/polish.h>
#include <zmk-unicode/keys/portuguese.h>
#include <zmk-unicode/keys/romanian.h>
#include <zmk-unicode/keys/russian.h>
#include <zmk-unicode/keys/serbian.h>
#include <zmk-unicode/keys/slovak.h>
#include <zmk-unicode/keys/spanish.h>
#include <zmk-unicode/keys/swedish.h>
#include <zmk-unicode/keys/ukrainian.h>
