#pragma once

#include <zmk-unicode/keys/blocks/adlam.h>
#include <zmk-unicode/keys/blocks/aegean_numbers.h>
#include <zmk-unicode/keys/blocks/ahom.h>
#include <zmk-unicode/keys/blocks/alchemical_symbols.h>
#include <zmk-unicode/keys/blocks/alphabetic_presentation_forms.h>
#include <zmk-unicode/keys/blocks/anatolian_hieroglyphs.h>
#include <zmk-unicode/keys/blocks/ancient_greek_musical_notation.h>
#include <zmk-unicode/keys/blocks/ancient_greek_numbers.h>
#include <zmk-unicode/keys/blocks/ancient_symbols.h>
#include <zmk-unicode/keys/blocks/arabic_extended_a.h>
#include <zmk-unicode/keys/blocks/arabic_extended_b.h>
#include <zmk-unicode/keys/blocks/arabic_extended_c.h>
#include <zmk-unicode/keys/blocks/arabic.h>
#include <zmk-unicode/keys/blocks/arabic_mathematical_alphabetic_symbols.h>
#include <zmk-unicode/keys/blocks/arabic_presentation_forms_a.h>
#include <zmk-unicode/keys/blocks/arabic_presentation_forms_b.h>
#include <zmk-unicode/keys/blocks/arabic_supplement.h>
#include <zmk-unicode/keys/blocks/armenian.h>
#include <zmk-unicode/keys/blocks/arrows.h>
#include <zmk-unicode/keys/blocks/avestan.h>
#include <zmk-unicode/keys/blocks/balinese.h>
#include <zmk-unicode/keys/blocks/bamum.h>
#include <zmk-unicode/keys/blocks/bamum_supplement.h>
#include <zmk-unicode/keys/blocks/basic_latin.h>
#include <zmk-unicode/keys/blocks/bassa_vah.h>
#include <zmk-unicode/keys/blocks/batak.h>
#include <zmk-unicode/keys/blocks/bengali.h>
#include <zmk-unicode/keys/blocks/bhaiksuki.h>
#include <zmk-unicode/keys/blocks/block_elements.h>
#include <zmk-unicode/keys/blocks/bopomofo_extended.h>
#include <zmk-unicode/keys/blocks/bopomofo.h>
#include <zmk-unicode/keys/blocks/box_drawing.h>
#include <zmk-unicode/keys/blocks/brahmi.h>
#include <zmk-unicode/keys/blocks/braille_patterns.h>
#include <zmk-unicode/keys/blocks/buginese.h>
#include <zmk-unicode/keys/blocks/buhid.h>
#include <zmk-unicode/keys/blocks/byzantine_musical_symbols.h>
#include <zmk-unicode/keys/blocks/carian.h>
#include <zmk-unicode/keys/blocks/caucasian_albanian.h>
#include <zmk-unicode/keys/blocks/chakma.h>
#include <zmk-unicode/keys/blocks/cham.h>
#include <zmk-unicode/keys/blocks/cherokee.h>
#include <zmk-unicode/keys/blocks/cherokee_supplement.h>
#include <zmk-unicode/keys/blocks/chess_symbols.h>
#include <zmk-unicode/keys/blocks/chorasmian.h>
#include <zmk-unicode/keys/blocks/cjk_compatibility_forms.h>
#include <zmk-unicode/keys/blocks/cjk_compatibility.h>
#include <zmk-unicode/keys/blocks/cjk_compatibility_ideographs.h>
#include <zmk-unicode/keys/blocks/cjk_compatibility_ideographs_supplement.h>
#include <zmk-unicode/keys/blocks/cjk_radicals_supplement.h>
#include <zmk-unicode/keys/blocks/cjk_strokes.h>
#include <zmk-unicode/keys/blocks/cjk_symbols_and_punctuation.h>
#include <zmk-unicode/keys/blocks/cjk_unified_ideographs_extension_a.h>
#include <zmk-unicode/keys/blocks/cjk_unified_ideographs_extension_b.h>
#include <zmk-unicode/keys/blocks/cjk_unified_ideographs_extension_c.h>
#include <zmk-unicode/keys/blocks/cjk_unified_ideographs_extension_d.h>
#include <zmk-unicode/keys/blocks/cjk_unified_ideographs_extension_e.h>
#include <zmk-unicode/keys/blocks/cjk_unified_ideographs_extension_f.h>
#include <zmk-unicode/keys/blocks/cjk_unified_ideographs_extension_g.h>
#include <zmk-unicode/keys/blocks/cjk_unified_ideographs_extension_h.h>
#include <zmk-unicode/keys/blocks/cjk_unified_ideographs_extension_i.h>
#include <zmk-unicode/keys/blocks/cjk_unified_ideographs.h>
#include <zmk-unicode/keys/blocks/common_indic_number_forms.h>
#include <zmk-unicode/keys/blocks/control_pictures.h>
#include <zmk-unicode/keys/blocks/coptic_epact_numbers.h>
#include <zmk-unicode/keys/blocks/coptic.h>
#include <zmk-unicode/keys/blocks/counting_rod_numerals.h>
#include <zmk-unicode/keys/blocks/cuneiform.h>
#include <zmk-unicode/keys/blocks/cuneiform_numbers_and_punctuation.h>
#include <zmk-unicode/keys/blocks/currency_symbols.h>
#include <zmk-unicode/keys/blocks/cypriot_syllabary.h>
#include <zmk-unicode/keys/blocks/cypro_minoan.h>
#include <zmk-unicode/keys/blocks/cyrillic_extended_b.h>
#include <zmk-unicode/keys/blocks/cyrillic_extended_c.h>
#include <zmk-unicode/keys/blocks/cyrillic_extended_d.h>
#include <zmk-unicode/keys/blocks/cyrillic.h>
#include <zmk-unicode/keys/blocks/cyrillic_supplement.h>
#include <zmk-unicode/keys/blocks/deseret.h>
#include <zmk-unicode/keys/blocks/devanagari_extended_a.h>
#include <zmk-unicode/keys/blocks/devanagari_extended.h>
#include <zmk-unicode/keys/blocks/devanagari.h>
#include <zmk-unicode/keys/blocks/dingbats.h>
#include <zmk-unicode/keys/blocks/dives_akuru.h>
#include <zmk-unicode/keys/blocks/dogra.h>
#include <zmk-unicode/keys/blocks/domino_tiles.h>
#include <zmk-unicode/keys/blocks/duployan.h>
#include <zmk-unicode/keys/blocks/early_dynastic_cuneiform.h>
#include <zmk-unicode/keys/blocks/egyptian_hieroglyph_format_controls.h>
#include <zmk-unicode/keys/blocks/egyptian_hieroglyphs_extended_a.h>
#include <zmk-unicode/keys/blocks/egyptian_hieroglyphs.h>
#include <zmk-unicode/keys/blocks/elbasan.h>
#include <zmk-unicode/keys/blocks/elymaic.h>
#include <zmk-unicode/keys/blocks/emoticons.h>
#include <zmk-unicode/keys/blocks/enclosed_alphanumerics.h>
#include <zmk-unicode/keys/blocks/enclosed_alphanumeric_supplement.h>
#include <zmk-unicode/keys/blocks/enclosed_cjk_letters_and_months.h>
#include <zmk-unicode/keys/blocks/enclosed_ideographic_supplement.h>
#include <zmk-unicode/keys/blocks/ethiopic_extended_a.h>
#include <zmk-unicode/keys/blocks/ethiopic_extended_b.h>
#include <zmk-unicode/keys/blocks/ethiopic_extended.h>
#include <zmk-unicode/keys/blocks/ethiopic.h>
#include <zmk-unicode/keys/blocks/ethiopic_supplement.h>
#include <zmk-unicode/keys/blocks/garay.h>
#include <zmk-unicode/keys/blocks/general_punctuation.h>
#include <zmk-unicode/keys/blocks/geometric_shapes_extended.h>
#include <zmk-unicode/keys/blocks/geometric_shapes.h>
#include <zmk-unicode/keys/blocks/georgian_extended.h>
#include <zmk-unicode/keys/blocks/georgian.h>
#include <zmk-unicode/keys/blocks/georgian_supplement.h>
#include <zmk-unicode/keys/blocks/glagolitic.h>
#include <zmk-unicode/keys/blocks/gothic.h>
#include <zmk-unicode/keys/blocks/grantha.h>
#include <zmk-unicode/keys/blocks/greek_and_coptic.h>
#include <zmk-unicode/keys/blocks/greek_extended.h>
#include <zmk-unicode/keys/blocks/gujarati.h>
#include <zmk-unicode/keys/blocks/gunjala_gondi.h>
#include <zmk-unicode/keys/blocks/gurmukhi.h>
#include <zmk-unicode/keys/blocks/gurung_khema.h>
#include <zmk-unicode/keys/blocks/halfwidth_and_fullwidth_forms.h>
#include <zmk-unicode/keys/blocks/hangul_compatibility_jamo.h>
#include <zmk-unicode/keys/blocks/hangul_jamo_extended_a.h>
#include <zmk-unicode/keys/blocks/hangul_jamo_extended_b.h>
#include <zmk-unicode/keys/blocks/hangul_jamo.h>
#include <zmk-unicode/keys/blocks/hangul_syllables.h>
#include <zmk-unicode/keys/blocks/hanifi_rohingya.h>
#include <zmk-unicode/keys/blocks/hanunoo.h>
#include <zmk-unicode/keys/blocks/hatran.h>
#include <zmk-unicode/keys/blocks/hebrew.h>
#include <zmk-unicode/keys/blocks/hiragana.h>
#include <zmk-unicode/keys/blocks/ideographic_description_characters.h>
#include <zmk-unicode/keys/blocks/ideographic_symbols_and_punctuation.h>
#include <zmk-unicode/keys/blocks/imperial_aramaic.h>
#include <zmk-unicode/keys/blocks/indic_siyaq_numbers.h>
#include <zmk-unicode/keys/blocks/inscriptional_pahlavi.h>
#include <zmk-unicode/keys/blocks/inscriptional_parthian.h>
#include <zmk-unicode/keys/blocks/ipa_extensions.h>
#include <zmk-unicode/keys/blocks/javanese.h>
#include <zmk-unicode/keys/blocks/kaithi.h>
#include <zmk-unicode/keys/blocks/kaktovik_numerals.h>
#include <zmk-unicode/keys/blocks/kana_extended_a.h>
#include <zmk-unicode/keys/blocks/kana_extended_b.h>
#include <zmk-unicode/keys/blocks/kana_supplement.h>
#include <zmk-unicode/keys/blocks/kanbun.h>
#include <zmk-unicode/keys/blocks/kangxi_radicals.h>
#include <zmk-unicode/keys/blocks/kannada.h>
#include <zmk-unicode/keys/blocks/katakana.h>
#include <zmk-unicode/keys/blocks/katakana_phonetic_extensions.h>
#include <zmk-unicode/keys/blocks/kawi.h>
#include <zmk-unicode/keys/blocks/kayah_li.h>
#include <zmk-unicode/keys/blocks/kharoshthi.h>
#include <zmk-unicode/keys/blocks/khitan_small_script.h>
#include <zmk-unicode/keys/blocks/khmer.h>
#include <zmk-unicode/keys/blocks/khmer_symbols.h>
#include <zmk-unicode/keys/blocks/khojki.h>
#include <zmk-unicode/keys/blocks/khudawadi.h>
#include <zmk-unicode/keys/blocks/kirat_rai.h>
#include <zmk-unicode/keys/blocks/lao.h>
#include <zmk-unicode/keys/blocks/latin_1_supplement.h>
#include <zmk-unicode/keys/blocks/latin_extended_additional.h>
#include <zmk-unicode/keys/blocks/latin_extended_a.h>
#include <zmk-unicode/keys/blocks/latin_extended_b.h>
#include <zmk-unicode/keys/blocks/latin_extended_c.h>
#include <zmk-unicode/keys/blocks/latin_extended_d.h>
#include <zmk-unicode/keys/blocks/latin_extended_e.h>
#include <zmk-unicode/keys/blocks/latin_extended_f.h>
#include <zmk-unicode/keys/blocks/latin_extended_g.h>
#include <zmk-unicode/keys/blocks/lepcha.h>
#include <zmk-unicode/keys/blocks/letterlike_symbols.h>
#include <zmk-unicode/keys/blocks/limbu.h>
#include <zmk-unicode/keys/blocks/linear_a.h>
#include <zmk-unicode/keys/blocks/linear_b_ideograms.h>
#include <zmk-unicode/keys/blocks/linear_b_syllabary.h>
#include <zmk-unicode/keys/blocks/lisu.h>
#include <zmk-unicode/keys/blocks/lisu_supplement.h>
#include <zmk-unicode/keys/blocks/lycian.h>
#include <zmk-unicode/keys/blocks/lydian.h>
#include <zmk-unicode/keys/blocks/mahajani.h>
#include <zmk-unicode/keys/blocks/mahjong_tiles.h>
#include <zmk-unicode/keys/blocks/makasar.h>
#include <zmk-unicode/keys/blocks/malayalam.h>
#include <zmk-unicode/keys/blocks/mandaic.h>
#include <zmk-unicode/keys/blocks/manichaean.h>
#include <zmk-unicode/keys/blocks/marchen.h>
#include <zmk-unicode/keys/blocks/masaram_gondi.h>
#include <zmk-unicode/keys/blocks/mathematical_alphanumeric_symbols.h>
#include <zmk-unicode/keys/blocks/mathematical_operators.h>
#include <zmk-unicode/keys/blocks/mayan_numerals.h>
#include <zmk-unicode/keys/blocks/medefaidrin.h>
#include <zmk-unicode/keys/blocks/meetei_mayek_extensions.h>
#include <zmk-unicode/keys/blocks/meetei_mayek.h>
#include <zmk-unicode/keys/blocks/mende_kikakui.h>
#include <zmk-unicode/keys/blocks/meroitic_cursive.h>
#include <zmk-unicode/keys/blocks/meroitic_hieroglyphs.h>
#include <zmk-unicode/keys/blocks/miao.h>
#include <zmk-unicode/keys/blocks/miscellaneous_mathematical_symbols_a.h>
#include <zmk-unicode/keys/blocks/miscellaneous_mathematical_symbols_b.h>
#include <zmk-unicode/keys/blocks/miscellaneous_symbols_and_arrows.h>
#include <zmk-unicode/keys/blocks/miscellaneous_symbols_and_pictographs.h>
#include <zmk-unicode/keys/blocks/miscellaneous_symbols.h>
#include <zmk-unicode/keys/blocks/miscellaneous_technical.h>
#include <zmk-unicode/keys/blocks/modifier_tone_letters.h>
#include <zmk-unicode/keys/blocks/modi.h>
#include <zmk-unicode/keys/blocks/mongolian.h>
#include <zmk-unicode/keys/blocks/mongolian_supplement.h>
#include <zmk-unicode/keys/blocks/mro.h>
#include <zmk-unicode/keys/blocks/multani.h>
#include <zmk-unicode/keys/blocks/musical_symbols.h>
#include <zmk-unicode/keys/blocks/myanmar_extended_a.h>
#include <zmk-unicode/keys/blocks/myanmar_extended_b.h>
#include <zmk-unicode/keys/blocks/myanmar_extended_c.h>
#include <zmk-unicode/keys/blocks/myanmar.h>
#include <zmk-unicode/keys/blocks/nabataean.h>
#include <zmk-unicode/keys/blocks/nag_mundari.h>
#include <zmk-unicode/keys/blocks/nandinagari.h>
#include <zmk-unicode/keys/blocks/newa.h>
#include <zmk-unicode/keys/blocks/new_tai_lue.h>
#include <zmk-unicode/keys/blocks/nko.h>
#include <zmk-unicode/keys/blocks/number_forms.h>
#include <zmk-unicode/keys/blocks/nushu.h>
#include <zmk-unicode/keys/blocks/nyiakeng_puachue_hmong.h>
#include <zmk-unicode/keys/blocks/ogham.h>
#include <zmk-unicode/keys/blocks/ol_chiki.h>
#include <zmk-unicode/keys/blocks/old_hungarian.h>
#include <zmk-unicode/keys/blocks/old_italic.h>
#include <zmk-unicode/keys/blocks/old_north_arabian.h>
#include <zmk-unicode/keys/blocks/old_permic.h>
#include <zmk-unicode/keys/blocks/old_persian.h>
#include <zmk-unicode/keys/blocks/old_sogdian.h>
#include <zmk-unicode/keys/blocks/old_south_arabian.h>
#include <zmk-unicode/keys/blocks/old_turkic.h>
#include <zmk-unicode/keys/blocks/old_uyghur.h>
#include <zmk-unicode/keys/blocks/ol_onal.h>
#include <zmk-unicode/keys/blocks/optical_character_recognition.h>
#include <zmk-unicode/keys/blocks/oriya.h>
#include <zmk-unicode/keys/blocks/ornamental_dingbats.h>
#include <zmk-unicode/keys/blocks/osage.h>
#include <zmk-unicode/keys/blocks/osmanya.h>
#include <zmk-unicode/keys/blocks/ottoman_siyaq_numbers.h>
#include <zmk-unicode/keys/blocks/pahawh_hmong.h>
#include <zmk-unicode/keys/blocks/palmyrene.h>
#include <zmk-unicode/keys/blocks/pau_cin_hau.h>
#include <zmk-unicode/keys/blocks/phags_pa.h>
#include <zmk-unicode/keys/blocks/phaistos_disc.h>
#include <zmk-unicode/keys/blocks/phoenician.h>
#include <zmk-unicode/keys/blocks/phonetic_extensions.h>
#include <zmk-unicode/keys/blocks/phonetic_extensions_supplement.h>
#include <zmk-unicode/keys/blocks/playing_cards.h>
#include <zmk-unicode/keys/blocks/psalter_pahlavi.h>
#include <zmk-unicode/keys/blocks/rejang.h>
#include <zmk-unicode/keys/blocks/rumi_numeral_symbols.h>
#include <zmk-unicode/keys/blocks/runic.h>
#include <zmk-unicode/keys/blocks/samaritan.h>
#include <zmk-unicode/keys/blocks/saurashtra.h>
#include <zmk-unicode/keys/blocks/sharada.h>
#include <zmk-unicode/keys/blocks/shavian.h>
#include <zmk-unicode/keys/blocks/siddham.h>
#include <zmk-unicode/keys/blocks/sinhala_archaic_numbers.h>
#include <zmk-unicode/keys/blocks/sinhala.h>
#include <zmk-unicode/keys/blocks/small_form_variants.h>
#include <zmk-unicode/keys/blocks/small_kana_extension.h>
#include <zmk-unicode/keys/blocks/sogdian.h>
#include <zmk-unicode/keys/blocks/sora_sompeng.h>
#include <zmk-unicode/keys/blocks/soyombo.h>
#include <zmk-unicode/keys/blocks/spacing_modifier_letters.h>
#include <zmk-unicode/keys/blocks/specials.h>
#include <zmk-unicode/keys/blocks/sundanese.h>
#include <zmk-unicode/keys/blocks/sundanese_supplement.h>
#include <zmk-unicode/keys/blocks/sunuwar.h>
#include <zmk-unicode/keys/blocks/superscripts_and_subscripts.h>
#include <zmk-unicode/keys/blocks/supplemental_arrows_a.h>
#include <zmk-unicode/keys/blocks/supplemental_arrows_b.h>
#include <zmk-unicode/keys/blocks/supplemental_arrows_c.h>
#include <zmk-unicode/keys/blocks/supplemental_mathematical_operators.h>
#include <zmk-unicode/keys/blocks/supplemental_punctuation.h>
#include <zmk-unicode/keys/blocks/supplemental_symbols_and_pictographs.h>
#include <zmk-unicode/keys/blocks/sutton_signwriting.h>
#include <zmk-unicode/keys/blocks/syloti_nagri.h>
#include <zmk-unicode/keys/blocks/symbols_and_pictographs_extended_a.h>
#include <zmk-unicode/keys/blocks/symbols_for_legacy_computing.h>
#include <zmk-unicode/keys/blocks/symbols_for_legacy_computing_supplement.h>
#include <zmk-unicode/keys/blocks/syriac.h>
#include <zmk-unicode/keys/blocks/syriac_supplement.h>
#include <zmk-unicode/keys/blocks/tagalog.h>
#include <zmk-unicode/keys/blocks/tagbanwa.h>
#include <zmk-unicode/keys/blocks/tai_le.h>
#include <zmk-unicode/keys/blocks/tai_tham.h>
#include <zmk-unicode/keys/blocks/tai_viet.h>
#include <zmk-unicode/keys/blocks/tai_xuan_jing_symbols.h>
#include <zmk-unicode/keys/blocks/takri.h>
#include <zmk-unicode/keys/blocks/tamil.h>
#include <zmk-unicode/keys/blocks/tamil_supplement.h>
#include <zmk-unicode/keys/blocks/tangsa.h>
#include <zmk-unicode/keys/blocks/tangut_components.h>
#include <zmk-unicode/keys/blocks/telugu.h>
#include <zmk-unicode/keys/blocks/thaana.h>
#include <zmk-unicode/keys/blocks/thai.h>
#include <zmk-unicode/keys/blocks/tibetan.h>
#include <zmk-unicode/keys/blocks/tifinagh.h>
#include <zmk-unicode/keys/blocks/tirhuta.h>
#include <zmk-unicode/keys/blocks/todhri.h>
#include <zmk-unicode/keys/blocks/toto.h>
#include <zmk-unicode/keys/blocks/transport_and_map_symbols.h>
#include <zmk-unicode/keys/blocks/tulu_tigalari.h>
#include <zmk-unicode/keys/blocks/ugaritic.h>
#include <zmk-unicode/keys/blocks/unified_canadian_aboriginal_syllabics_extended_a.h>
#include <zmk-unicode/keys/blocks/unified_canadian_aboriginal_syllabics_extended.h>
#include <zmk-unicode/keys/blocks/unified_canadian_aboriginal_syllabics.h>
#include <zmk-unicode/keys/blocks/vai.h>
#include <zmk-unicode/keys/blocks/vedic_extensions.h>
#include <zmk-unicode/keys/blocks/vertical_forms.h>
#include <zmk-unicode/keys/blocks/vithkuqi.h>
#include <zmk-unicode/keys/blocks/wancho.h>
#include <zmk-unicode/keys/blocks/warang_citi.h>
#include <zmk-unicode/keys/blocks/yezidi.h>
#include <zmk-unicode/keys/blocks/yijing_hexagram_symbols.h>
#include <zmk-unicode/keys/blocks/yi_radicals.h>
#include <zmk-unicode/keys/blocks/yi_syllables.h>
#include <zmk-unicode/keys/blocks/zanabazar_square.h>
#include <zmk-unicode/keys/blocks/znamenny_musical_notation.h>
