/*
 * Unicode keys for U+FB50 .. U+FDFF
 *
 * This file was generated from Unicode 16.0.0.
 *
 * See http://www.unicode.org/versions/Unicode16.0.0 for source data.
 */

#pragma once

#define UC_ARABIC_LETTER_ALEF_WASLA_ISOLATED_FORM                                               0xFB50  0  // ﭐ
#define UC_ARABIC_LETTER_ALEF_WASLA_FINAL_FORM                                                  0xFB51  0  // ﭑ
#define UC_ARABIC_LETTER_BEEH_ISOLATED_FORM                                                     0xFB52  0  // ﭒ
#define UC_ARABIC_LETTER_BEEH_FINAL_FORM                                                        0xFB53  0  // ﭓ
#define UC_ARABIC_LETTER_BEEH_INITIAL_FORM                                                      0xFB54  0  // ﭔ
#define UC_ARABIC_LETTER_BEEH_MEDIAL_FORM                                                       0xFB55  0  // ﭕ
#define UC_ARABIC_LETTER_PEH_ISOLATED_FORM                                                      0xFB56  0  // ﭖ
#define UC_ARABIC_LETTER_PEH_FINAL_FORM                                                         0xFB57  0  // ﭗ
#define UC_ARABIC_LETTER_PEH_INITIAL_FORM                                                       0xFB58  0  // ﭘ
#define UC_ARABIC_LETTER_PEH_MEDIAL_FORM                                                        0xFB59  0  // ﭙ
#define UC_ARABIC_LETTER_BEHEH_ISOLATED_FORM                                                    0xFB5A  0  // ﭚ
#define UC_ARABIC_LETTER_BEHEH_FINAL_FORM                                                       0xFB5B  0  // ﭛ
#define UC_ARABIC_LETTER_BEHEH_INITIAL_FORM                                                     0xFB5C  0  // ﭜ
#define UC_ARABIC_LETTER_BEHEH_MEDIAL_FORM                                                      0xFB5D  0  // ﭝ
#define UC_ARABIC_LETTER_TTEHEH_ISOLATED_FORM                                                   0xFB5E  0  // ﭞ
#define UC_ARABIC_LETTER_TTEHEH_FINAL_FORM                                                      0xFB5F  0  // ﭟ
#define UC_ARABIC_LETTER_TTEHEH_INITIAL_FORM                                                    0xFB60  0  // ﭠ
#define UC_ARABIC_LETTER_TTEHEH_MEDIAL_FORM                                                     0xFB61  0  // ﭡ
#define UC_ARABIC_LETTER_TEHEH_ISOLATED_FORM                                                    0xFB62  0  // ﭢ
#define UC_ARABIC_LETTER_TEHEH_FINAL_FORM                                                       0xFB63  0  // ﭣ
#define UC_ARABIC_LETTER_TEHEH_INITIAL_FORM                                                     0xFB64  0  // ﭤ
#define UC_ARABIC_LETTER_TEHEH_MEDIAL_FORM                                                      0xFB65  0  // ﭥ
#define UC_ARABIC_LETTER_TTEH_ISOLATED_FORM                                                     0xFB66  0  // ﭦ
#define UC_ARABIC_LETTER_TTEH_FINAL_FORM                                                        0xFB67  0  // ﭧ
#define UC_ARABIC_LETTER_TTEH_INITIAL_FORM                                                      0xFB68  0  // ﭨ
#define UC_ARABIC_LETTER_TTEH_MEDIAL_FORM                                                       0xFB69  0  // ﭩ
#define UC_ARABIC_LETTER_VEH_ISOLATED_FORM                                                      0xFB6A  0  // ﭪ
#define UC_ARABIC_LETTER_VEH_FINAL_FORM                                                         0xFB6B  0  // ﭫ
#define UC_ARABIC_LETTER_VEH_INITIAL_FORM                                                       0xFB6C  0  // ﭬ
#define UC_ARABIC_LETTER_VEH_MEDIAL_FORM                                                        0xFB6D  0  // ﭭ
#define UC_ARABIC_LETTER_PEHEH_ISOLATED_FORM                                                    0xFB6E  0  // ﭮ
#define UC_ARABIC_LETTER_PEHEH_FINAL_FORM                                                       0xFB6F  0  // ﭯ
#define UC_ARABIC_LETTER_PEHEH_INITIAL_FORM                                                     0xFB70  0  // ﭰ
#define UC_ARABIC_LETTER_PEHEH_MEDIAL_FORM                                                      0xFB71  0  // ﭱ
#define UC_ARABIC_LETTER_DYEH_ISOLATED_FORM                                                     0xFB72  0  // ﭲ
#define UC_ARABIC_LETTER_DYEH_FINAL_FORM                                                        0xFB73  0  // ﭳ
#define UC_ARABIC_LETTER_DYEH_INITIAL_FORM                                                      0xFB74  0  // ﭴ
#define UC_ARABIC_LETTER_DYEH_MEDIAL_FORM                                                       0xFB75  0  // ﭵ
#define UC_ARABIC_LETTER_NYEH_ISOLATED_FORM                                                     0xFB76  0  // ﭶ
#define UC_ARABIC_LETTER_NYEH_FINAL_FORM                                                        0xFB77  0  // ﭷ
#define UC_ARABIC_LETTER_NYEH_INITIAL_FORM                                                      0xFB78  0  // ﭸ
#define UC_ARABIC_LETTER_NYEH_MEDIAL_FORM                                                       0xFB79  0  // ﭹ
#define UC_ARABIC_LETTER_TCHEH_ISOLATED_FORM                                                    0xFB7A  0  // ﭺ
#define UC_ARABIC_LETTER_TCHEH_FINAL_FORM                                                       0xFB7B  0  // ﭻ
#define UC_ARABIC_LETTER_TCHEH_INITIAL_FORM                                                     0xFB7C  0  // ﭼ
#define UC_ARABIC_LETTER_TCHEH_MEDIAL_FORM                                                      0xFB7D  0  // ﭽ
#define UC_ARABIC_LETTER_TCHEHEH_ISOLATED_FORM                                                  0xFB7E  0  // ﭾ
#define UC_ARABIC_LETTER_TCHEHEH_FINAL_FORM                                                     0xFB7F  0  // ﭿ
#define UC_ARABIC_LETTER_TCHEHEH_INITIAL_FORM                                                   0xFB80  0  // ﮀ
#define UC_ARABIC_LETTER_TCHEHEH_MEDIAL_FORM                                                    0xFB81  0  // ﮁ
#define UC_ARABIC_LETTER_DDAHAL_ISOLATED_FORM                                                   0xFB82  0  // ﮂ
#define UC_ARABIC_LETTER_DDAHAL_FINAL_FORM                                                      0xFB83  0  // ﮃ
#define UC_ARABIC_LETTER_DAHAL_ISOLATED_FORM                                                    0xFB84  0  // ﮄ
#define UC_ARABIC_LETTER_DAHAL_FINAL_FORM                                                       0xFB85  0  // ﮅ
#define UC_ARABIC_LETTER_DUL_ISOLATED_FORM                                                      0xFB86  0  // ﮆ
#define UC_ARABIC_LETTER_DUL_FINAL_FORM                                                         0xFB87  0  // ﮇ
#define UC_ARABIC_LETTER_DDAL_ISOLATED_FORM                                                     0xFB88  0  // ﮈ
#define UC_ARABIC_LETTER_DDAL_FINAL_FORM                                                        0xFB89  0  // ﮉ
#define UC_ARABIC_LETTER_JEH_ISOLATED_FORM                                                      0xFB8A  0  // ﮊ
#define UC_ARABIC_LETTER_JEH_FINAL_FORM                                                         0xFB8B  0  // ﮋ
#define UC_ARABIC_LETTER_RREH_ISOLATED_FORM                                                     0xFB8C  0  // ﮌ
#define UC_ARABIC_LETTER_RREH_FINAL_FORM                                                        0xFB8D  0  // ﮍ
#define UC_ARABIC_LETTER_KEHEH_ISOLATED_FORM                                                    0xFB8E  0  // ﮎ
#define UC_ARABIC_LETTER_KEHEH_FINAL_FORM                                                       0xFB8F  0  // ﮏ
#define UC_ARABIC_LETTER_KEHEH_INITIAL_FORM                                                     0xFB90  0  // ﮐ
#define UC_ARABIC_LETTER_KEHEH_MEDIAL_FORM                                                      0xFB91  0  // ﮑ
#define UC_ARABIC_LETTER_GAF_ISOLATED_FORM                                                      0xFB92  0  // ﮒ
#define UC_ARABIC_LETTER_GAF_FINAL_FORM                                                         0xFB93  0  // ﮓ
#define UC_ARABIC_LETTER_GAF_INITIAL_FORM                                                       0xFB94  0  // ﮔ
#define UC_ARABIC_LETTER_GAF_MEDIAL_FORM                                                        0xFB95  0  // ﮕ
#define UC_ARABIC_LETTER_GUEH_ISOLATED_FORM                                                     0xFB96  0  // ﮖ
#define UC_ARABIC_LETTER_GUEH_FINAL_FORM                                                        0xFB97  0  // ﮗ
#define UC_ARABIC_LETTER_GUEH_INITIAL_FORM                                                      0xFB98  0  // ﮘ
#define UC_ARABIC_LETTER_GUEH_MEDIAL_FORM                                                       0xFB99  0  // ﮙ
#define UC_ARABIC_LETTER_NGOEH_ISOLATED_FORM                                                    0xFB9A  0  // ﮚ
#define UC_ARABIC_LETTER_NGOEH_FINAL_FORM                                                       0xFB9B  0  // ﮛ
#define UC_ARABIC_LETTER_NGOEH_INITIAL_FORM                                                     0xFB9C  0  // ﮜ
#define UC_ARABIC_LETTER_NGOEH_MEDIAL_FORM                                                      0xFB9D  0  // ﮝ
#define UC_ARABIC_LETTER_NOON_GHUNNA_ISOLATED_FORM                                              0xFB9E  0  // ﮞ
#define UC_ARABIC_LETTER_NOON_GHUNNA_FINAL_FORM                                                 0xFB9F  0  // ﮟ
#define UC_ARABIC_LETTER_RNOON_ISOLATED_FORM                                                    0xFBA0  0  // ﮠ
#define UC_ARABIC_LETTER_RNOON_FINAL_FORM                                                       0xFBA1  0  // ﮡ
#define UC_ARABIC_LETTER_RNOON_INITIAL_FORM                                                     0xFBA2  0  // ﮢ
#define UC_ARABIC_LETTER_RNOON_MEDIAL_FORM                                                      0xFBA3  0  // ﮣ
#define UC_ARABIC_LETTER_HEH_WITH_YEH_ABOVE_ISOLATED_FORM                                       0xFBA4  0  // ﮤ
#define UC_ARABIC_LETTER_HEH_WITH_YEH_ABOVE_FINAL_FORM                                          0xFBA5  0  // ﮥ
#define UC_ARABIC_LETTER_HEH_GOAL_ISOLATED_FORM                                                 0xFBA6  0  // ﮦ
#define UC_ARABIC_LETTER_HEH_GOAL_FINAL_FORM                                                    0xFBA7  0  // ﮧ
#define UC_ARABIC_LETTER_HEH_GOAL_INITIAL_FORM                                                  0xFBA8  0  // ﮨ
#define UC_ARABIC_LETTER_HEH_GOAL_MEDIAL_FORM                                                   0xFBA9  0  // ﮩ
#define UC_ARABIC_LETTER_HEH_DOACHASHMEE_ISOLATED_FORM                                          0xFBAA  0  // ﮪ
#define UC_ARABIC_LETTER_HEH_DOACHASHMEE_FINAL_FORM                                             0xFBAB  0  // ﮫ
#define UC_ARABIC_LETTER_HEH_DOACHASHMEE_INITIAL_FORM                                           0xFBAC  0  // ﮬ
#define UC_ARABIC_LETTER_HEH_DOACHASHMEE_MEDIAL_FORM                                            0xFBAD  0  // ﮭ
#define UC_ARABIC_LETTER_YEH_BARREE_ISOLATED_FORM                                               0xFBAE  0  // ﮮ
#define UC_ARABIC_LETTER_YEH_BARREE_FINAL_FORM                                                  0xFBAF  0  // ﮯ
#define UC_ARABIC_LETTER_YEH_BARREE_WITH_HAMZA_ABOVE_ISOLATED_FORM                              0xFBB0  0  // ﮰ
#define UC_ARABIC_LETTER_YEH_BARREE_WITH_HAMZA_ABOVE_FINAL_FORM                                 0xFBB1  0  // ﮱ
#define UC_ARABIC_SYMBOL_DOT_ABOVE                                                              0xFBB2  0  // ﮲
#define UC_ARABIC_SYMBOL_DOT_BELOW                                                              0xFBB3  0  // ﮳
#define UC_ARABIC_SYMBOL_TWO_DOTS_ABOVE                                                         0xFBB4  0  // ﮴
#define UC_ARABIC_SYMBOL_TWO_DOTS_BELOW                                                         0xFBB5  0  // ﮵
#define UC_ARABIC_SYMBOL_THREE_DOTS_ABOVE                                                       0xFBB6  0  // ﮶
#define UC_ARABIC_SYMBOL_THREE_DOTS_BELOW                                                       0xFBB7  0  // ﮷
#define UC_ARABIC_SYMBOL_THREE_DOTS_POINTING_DOWNWARDS_ABOVE                                    0xFBB8  0  // ﮸
#define UC_ARABIC_SYMBOL_THREE_DOTS_POINTING_DOWNWARDS_BELOW                                    0xFBB9  0  // ﮹
#define UC_ARABIC_SYMBOL_FOUR_DOTS_ABOVE                                                        0xFBBA  0  // ﮺
#define UC_ARABIC_SYMBOL_FOUR_DOTS_BELOW                                                        0xFBBB  0  // ﮻
#define UC_ARABIC_SYMBOL_DOUBLE_VERTICAL_BAR_BELOW                                              0xFBBC  0  // ﮼
#define UC_ARABIC_SYMBOL_TWO_DOTS_VERTICALLY_ABOVE                                              0xFBBD  0  // ﮽
#define UC_ARABIC_SYMBOL_TWO_DOTS_VERTICALLY_BELOW                                              0xFBBE  0  // ﮾
#define UC_ARABIC_SYMBOL_RING                                                                   0xFBBF  0  // ﮿
#define UC_ARABIC_SYMBOL_SMALL_TAH_ABOVE                                                        0xFBC0  0  // ﯀
#define UC_ARABIC_SYMBOL_SMALL_TAH_BELOW                                                        0xFBC1  0  // ﯁
#define UC_ARABIC_SYMBOL_WASLA_ABOVE                                                            0xFBC2  0  // ﯂
#define UC_ARABIC_LETTER_NG_ISOLATED_FORM                                                       0xFBD3  0  // ﯓ
#define UC_ARABIC_LETTER_NG_FINAL_FORM                                                          0xFBD4  0  // ﯔ
#define UC_ARABIC_LETTER_NG_INITIAL_FORM                                                        0xFBD5  0  // ﯕ
#define UC_ARABIC_LETTER_NG_MEDIAL_FORM                                                         0xFBD6  0  // ﯖ
#define UC_ARABIC_LETTER_U_ISOLATED_FORM                                                        0xFBD7  0  // ﯗ
#define UC_ARABIC_LETTER_U_FINAL_FORM                                                           0xFBD8  0  // ﯘ
#define UC_ARABIC_LETTER_OE_ISOLATED_FORM                                                       0xFBD9  0  // ﯙ
#define UC_ARABIC_LETTER_OE_FINAL_FORM                                                          0xFBDA  0  // ﯚ
#define UC_ARABIC_LETTER_YU_ISOLATED_FORM                                                       0xFBDB  0  // ﯛ
#define UC_ARABIC_LETTER_YU_FINAL_FORM                                                          0xFBDC  0  // ﯜ
#define UC_ARABIC_LETTER_U_WITH_HAMZA_ABOVE_ISOLATED_FORM                                       0xFBDD  0  // ﯝ
#define UC_ARABIC_LETTER_VE_ISOLATED_FORM                                                       0xFBDE  0  // ﯞ
#define UC_ARABIC_LETTER_VE_FINAL_FORM                                                          0xFBDF  0  // ﯟ
#define UC_ARABIC_LETTER_KIRGHIZ_OE_ISOLATED_FORM                                               0xFBE0  0  // ﯠ
#define UC_ARABIC_LETTER_KIRGHIZ_OE_FINAL_FORM                                                  0xFBE1  0  // ﯡ
#define UC_ARABIC_LETTER_KIRGHIZ_YU_ISOLATED_FORM                                               0xFBE2  0  // ﯢ
#define UC_ARABIC_LETTER_KIRGHIZ_YU_FINAL_FORM                                                  0xFBE3  0  // ﯣ
#define UC_ARABIC_LETTER_E_ISOLATED_FORM                                                        0xFBE4  0  // ﯤ
#define UC_ARABIC_LETTER_E_FINAL_FORM                                                           0xFBE5  0  // ﯥ
#define UC_ARABIC_LETTER_E_INITIAL_FORM                                                         0xFBE6  0  // ﯦ
#define UC_ARABIC_LETTER_E_MEDIAL_FORM                                                          0xFBE7  0  // ﯧ
#define UC_ARABIC_LETTER_UIGHUR_KAZAKH_KIRGHIZ_ALEF_MAKSURA_INITIAL_FORM                        0xFBE8  0  // ﯨ
#define UC_ARABIC_LETTER_UIGHUR_KAZAKH_KIRGHIZ_ALEF_MAKSURA_MEDIAL_FORM                         0xFBE9  0  // ﯩ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_ALEF_ISOLATED_FORM                         0xFBEA  0  // ﯪ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_ALEF_FINAL_FORM                            0xFBEB  0  // ﯫ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_AE_ISOLATED_FORM                           0xFBEC  0  // ﯬ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_AE_FINAL_FORM                              0xFBED  0  // ﯭ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_WAW_ISOLATED_FORM                          0xFBEE  0  // ﯮ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_WAW_FINAL_FORM                             0xFBEF  0  // ﯯ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_U_ISOLATED_FORM                            0xFBF0  0  // ﯰ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_U_FINAL_FORM                               0xFBF1  0  // ﯱ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_OE_ISOLATED_FORM                           0xFBF2  0  // ﯲ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_OE_FINAL_FORM                              0xFBF3  0  // ﯳ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_YU_ISOLATED_FORM                           0xFBF4  0  // ﯴ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_YU_FINAL_FORM                              0xFBF5  0  // ﯵ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_E_ISOLATED_FORM                            0xFBF6  0  // ﯶ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_E_FINAL_FORM                               0xFBF7  0  // ﯷ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_E_INITIAL_FORM                             0xFBF8  0  // ﯸ
#define UC_ARABIC_LIGATURE_UIGHUR_KIRGHIZ_YEH_WITH_HAMZA_ABOVE_WITH_ALEF_MAKSURA_ISOLATED_FORM  0xFBF9  0  // ﯹ
#define UC_ARABIC_LIGATURE_UIGHUR_KIRGHIZ_YEH_WITH_HAMZA_ABOVE_WITH_ALEF_MAKSURA_FINAL_FORM     0xFBFA  0  // ﯺ
#define UC_ARABIC_LIGATURE_UIGHUR_KIRGHIZ_YEH_WITH_HAMZA_ABOVE_WITH_ALEF_MAKSURA_INITIAL_FORM   0xFBFB  0  // ﯻ
#define UC_ARABIC_LETTER_FARSI_YEH_ISOLATED_FORM                                                0xFBFC  0  // ﯼ
#define UC_ARABIC_LETTER_FARSI_YEH_FINAL_FORM                                                   0xFBFD  0  // ﯽ
#define UC_ARABIC_LETTER_FARSI_YEH_INITIAL_FORM                                                 0xFBFE  0  // ﯾ
#define UC_ARABIC_LETTER_FARSI_YEH_MEDIAL_FORM                                                  0xFBFF  0  // ﯿ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_JEEM_ISOLATED_FORM                         0xFC00  0  // ﰀ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_HAH_ISOLATED_FORM                          0xFC01  0  // ﰁ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_MEEM_ISOLATED_FORM                         0xFC02  0  // ﰂ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_ALEF_MAKSURA_ISOLATED_FORM                 0xFC03  0  // ﰃ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_YEH_ISOLATED_FORM                          0xFC04  0  // ﰄ
#define UC_ARABIC_LIGATURE_BEH_WITH_JEEM_ISOLATED_FORM                                          0xFC05  0  // ﰅ
#define UC_ARABIC_LIGATURE_BEH_WITH_HAH_ISOLATED_FORM                                           0xFC06  0  // ﰆ
#define UC_ARABIC_LIGATURE_BEH_WITH_KHAH_ISOLATED_FORM                                          0xFC07  0  // ﰇ
#define UC_ARABIC_LIGATURE_BEH_WITH_MEEM_ISOLATED_FORM                                          0xFC08  0  // ﰈ
#define UC_ARABIC_LIGATURE_BEH_WITH_ALEF_MAKSURA_ISOLATED_FORM                                  0xFC09  0  // ﰉ
#define UC_ARABIC_LIGATURE_BEH_WITH_YEH_ISOLATED_FORM                                           0xFC0A  0  // ﰊ
#define UC_ARABIC_LIGATURE_TEH_WITH_JEEM_ISOLATED_FORM                                          0xFC0B  0  // ﰋ
#define UC_ARABIC_LIGATURE_TEH_WITH_HAH_ISOLATED_FORM                                           0xFC0C  0  // ﰌ
#define UC_ARABIC_LIGATURE_TEH_WITH_KHAH_ISOLATED_FORM                                          0xFC0D  0  // ﰍ
#define UC_ARABIC_LIGATURE_TEH_WITH_MEEM_ISOLATED_FORM                                          0xFC0E  0  // ﰎ
#define UC_ARABIC_LIGATURE_TEH_WITH_ALEF_MAKSURA_ISOLATED_FORM                                  0xFC0F  0  // ﰏ
#define UC_ARABIC_LIGATURE_TEH_WITH_YEH_ISOLATED_FORM                                           0xFC10  0  // ﰐ
#define UC_ARABIC_LIGATURE_THEH_WITH_JEEM_ISOLATED_FORM                                         0xFC11  0  // ﰑ
#define UC_ARABIC_LIGATURE_THEH_WITH_MEEM_ISOLATED_FORM                                         0xFC12  0  // ﰒ
#define UC_ARABIC_LIGATURE_THEH_WITH_ALEF_MAKSURA_ISOLATED_FORM                                 0xFC13  0  // ﰓ
#define UC_ARABIC_LIGATURE_THEH_WITH_YEH_ISOLATED_FORM                                          0xFC14  0  // ﰔ
#define UC_ARABIC_LIGATURE_JEEM_WITH_HAH_ISOLATED_FORM                                          0xFC15  0  // ﰕ
#define UC_ARABIC_LIGATURE_JEEM_WITH_MEEM_ISOLATED_FORM                                         0xFC16  0  // ﰖ
#define UC_ARABIC_LIGATURE_HAH_WITH_JEEM_ISOLATED_FORM                                          0xFC17  0  // ﰗ
#define UC_ARABIC_LIGATURE_HAH_WITH_MEEM_ISOLATED_FORM                                          0xFC18  0  // ﰘ
#define UC_ARABIC_LIGATURE_KHAH_WITH_JEEM_ISOLATED_FORM                                         0xFC19  0  // ﰙ
#define UC_ARABIC_LIGATURE_KHAH_WITH_HAH_ISOLATED_FORM                                          0xFC1A  0  // ﰚ
#define UC_ARABIC_LIGATURE_KHAH_WITH_MEEM_ISOLATED_FORM                                         0xFC1B  0  // ﰛ
#define UC_ARABIC_LIGATURE_SEEN_WITH_JEEM_ISOLATED_FORM                                         0xFC1C  0  // ﰜ
#define UC_ARABIC_LIGATURE_SEEN_WITH_HAH_ISOLATED_FORM                                          0xFC1D  0  // ﰝ
#define UC_ARABIC_LIGATURE_SEEN_WITH_KHAH_ISOLATED_FORM                                         0xFC1E  0  // ﰞ
#define UC_ARABIC_LIGATURE_SEEN_WITH_MEEM_ISOLATED_FORM                                         0xFC1F  0  // ﰟ
#define UC_ARABIC_LIGATURE_SAD_WITH_HAH_ISOLATED_FORM                                           0xFC20  0  // ﰠ
#define UC_ARABIC_LIGATURE_SAD_WITH_MEEM_ISOLATED_FORM                                          0xFC21  0  // ﰡ
#define UC_ARABIC_LIGATURE_DAD_WITH_JEEM_ISOLATED_FORM                                          0xFC22  0  // ﰢ
#define UC_ARABIC_LIGATURE_DAD_WITH_HAH_ISOLATED_FORM                                           0xFC23  0  // ﰣ
#define UC_ARABIC_LIGATURE_DAD_WITH_KHAH_ISOLATED_FORM                                          0xFC24  0  // ﰤ
#define UC_ARABIC_LIGATURE_DAD_WITH_MEEM_ISOLATED_FORM                                          0xFC25  0  // ﰥ
#define UC_ARABIC_LIGATURE_TAH_WITH_HAH_ISOLATED_FORM                                           0xFC26  0  // ﰦ
#define UC_ARABIC_LIGATURE_TAH_WITH_MEEM_ISOLATED_FORM                                          0xFC27  0  // ﰧ
#define UC_ARABIC_LIGATURE_ZAH_WITH_MEEM_ISOLATED_FORM                                          0xFC28  0  // ﰨ
#define UC_ARABIC_LIGATURE_AIN_WITH_JEEM_ISOLATED_FORM                                          0xFC29  0  // ﰩ
#define UC_ARABIC_LIGATURE_AIN_WITH_MEEM_ISOLATED_FORM                                          0xFC2A  0  // ﰪ
#define UC_ARABIC_LIGATURE_GHAIN_WITH_JEEM_ISOLATED_FORM                                        0xFC2B  0  // ﰫ
#define UC_ARABIC_LIGATURE_GHAIN_WITH_MEEM_ISOLATED_FORM                                        0xFC2C  0  // ﰬ
#define UC_ARABIC_LIGATURE_FEH_WITH_JEEM_ISOLATED_FORM                                          0xFC2D  0  // ﰭ
#define UC_ARABIC_LIGATURE_FEH_WITH_HAH_ISOLATED_FORM                                           0xFC2E  0  // ﰮ
#define UC_ARABIC_LIGATURE_FEH_WITH_KHAH_ISOLATED_FORM                                          0xFC2F  0  // ﰯ
#define UC_ARABIC_LIGATURE_FEH_WITH_MEEM_ISOLATED_FORM                                          0xFC30  0  // ﰰ
#define UC_ARABIC_LIGATURE_FEH_WITH_ALEF_MAKSURA_ISOLATED_FORM                                  0xFC31  0  // ﰱ
#define UC_ARABIC_LIGATURE_FEH_WITH_YEH_ISOLATED_FORM                                           0xFC32  0  // ﰲ
#define UC_ARABIC_LIGATURE_QAF_WITH_HAH_ISOLATED_FORM                                           0xFC33  0  // ﰳ
#define UC_ARABIC_LIGATURE_QAF_WITH_MEEM_ISOLATED_FORM                                          0xFC34  0  // ﰴ
#define UC_ARABIC_LIGATURE_QAF_WITH_ALEF_MAKSURA_ISOLATED_FORM                                  0xFC35  0  // ﰵ
#define UC_ARABIC_LIGATURE_QAF_WITH_YEH_ISOLATED_FORM                                           0xFC36  0  // ﰶ
#define UC_ARABIC_LIGATURE_KAF_WITH_ALEF_ISOLATED_FORM                                          0xFC37  0  // ﰷ
#define UC_ARABIC_LIGATURE_KAF_WITH_JEEM_ISOLATED_FORM                                          0xFC38  0  // ﰸ
#define UC_ARABIC_LIGATURE_KAF_WITH_HAH_ISOLATED_FORM                                           0xFC39  0  // ﰹ
#define UC_ARABIC_LIGATURE_KAF_WITH_KHAH_ISOLATED_FORM                                          0xFC3A  0  // ﰺ
#define UC_ARABIC_LIGATURE_KAF_WITH_LAM_ISOLATED_FORM                                           0xFC3B  0  // ﰻ
#define UC_ARABIC_LIGATURE_KAF_WITH_MEEM_ISOLATED_FORM                                          0xFC3C  0  // ﰼ
#define UC_ARABIC_LIGATURE_KAF_WITH_ALEF_MAKSURA_ISOLATED_FORM                                  0xFC3D  0  // ﰽ
#define UC_ARABIC_LIGATURE_KAF_WITH_YEH_ISOLATED_FORM                                           0xFC3E  0  // ﰾ
#define UC_ARABIC_LIGATURE_LAM_WITH_JEEM_ISOLATED_FORM                                          0xFC3F  0  // ﰿ
#define UC_ARABIC_LIGATURE_LAM_WITH_HAH_ISOLATED_FORM                                           0xFC40  0  // ﱀ
#define UC_ARABIC_LIGATURE_LAM_WITH_KHAH_ISOLATED_FORM                                          0xFC41  0  // ﱁ
#define UC_ARABIC_LIGATURE_LAM_WITH_MEEM_ISOLATED_FORM                                          0xFC42  0  // ﱂ
#define UC_ARABIC_LIGATURE_LAM_WITH_ALEF_MAKSURA_ISOLATED_FORM                                  0xFC43  0  // ﱃ
#define UC_ARABIC_LIGATURE_LAM_WITH_YEH_ISOLATED_FORM                                           0xFC44  0  // ﱄ
#define UC_ARABIC_LIGATURE_MEEM_WITH_JEEM_ISOLATED_FORM                                         0xFC45  0  // ﱅ
#define UC_ARABIC_LIGATURE_MEEM_WITH_HAH_ISOLATED_FORM                                          0xFC46  0  // ﱆ
#define UC_ARABIC_LIGATURE_MEEM_WITH_KHAH_ISOLATED_FORM                                         0xFC47  0  // ﱇ
#define UC_ARABIC_LIGATURE_MEEM_WITH_MEEM_ISOLATED_FORM                                         0xFC48  0  // ﱈ
#define UC_ARABIC_LIGATURE_MEEM_WITH_ALEF_MAKSURA_ISOLATED_FORM                                 0xFC49  0  // ﱉ
#define UC_ARABIC_LIGATURE_MEEM_WITH_YEH_ISOLATED_FORM                                          0xFC4A  0  // ﱊ
#define UC_ARABIC_LIGATURE_NOON_WITH_JEEM_ISOLATED_FORM                                         0xFC4B  0  // ﱋ
#define UC_ARABIC_LIGATURE_NOON_WITH_HAH_ISOLATED_FORM                                          0xFC4C  0  // ﱌ
#define UC_ARABIC_LIGATURE_NOON_WITH_KHAH_ISOLATED_FORM                                         0xFC4D  0  // ﱍ
#define UC_ARABIC_LIGATURE_NOON_WITH_MEEM_ISOLATED_FORM                                         0xFC4E  0  // ﱎ
#define UC_ARABIC_LIGATURE_NOON_WITH_ALEF_MAKSURA_ISOLATED_FORM                                 0xFC4F  0  // ﱏ
#define UC_ARABIC_LIGATURE_NOON_WITH_YEH_ISOLATED_FORM                                          0xFC50  0  // ﱐ
#define UC_ARABIC_LIGATURE_HEH_WITH_JEEM_ISOLATED_FORM                                          0xFC51  0  // ﱑ
#define UC_ARABIC_LIGATURE_HEH_WITH_MEEM_ISOLATED_FORM                                          0xFC52  0  // ﱒ
#define UC_ARABIC_LIGATURE_HEH_WITH_ALEF_MAKSURA_ISOLATED_FORM                                  0xFC53  0  // ﱓ
#define UC_ARABIC_LIGATURE_HEH_WITH_YEH_ISOLATED_FORM                                           0xFC54  0  // ﱔ
#define UC_ARABIC_LIGATURE_YEH_WITH_JEEM_ISOLATED_FORM                                          0xFC55  0  // ﱕ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAH_ISOLATED_FORM                                           0xFC56  0  // ﱖ
#define UC_ARABIC_LIGATURE_YEH_WITH_KHAH_ISOLATED_FORM                                          0xFC57  0  // ﱗ
#define UC_ARABIC_LIGATURE_YEH_WITH_MEEM_ISOLATED_FORM                                          0xFC58  0  // ﱘ
#define UC_ARABIC_LIGATURE_YEH_WITH_ALEF_MAKSURA_ISOLATED_FORM                                  0xFC59  0  // ﱙ
#define UC_ARABIC_LIGATURE_YEH_WITH_YEH_ISOLATED_FORM                                           0xFC5A  0  // ﱚ
#define UC_ARABIC_LIGATURE_THAL_WITH_SUPERSCRIPT_ALEF_ISOLATED_FORM                             0xFC5B  0  // ﱛ
#define UC_ARABIC_LIGATURE_REH_WITH_SUPERSCRIPT_ALEF_ISOLATED_FORM                              0xFC5C  0  // ﱜ
#define UC_ARABIC_LIGATURE_ALEF_MAKSURA_WITH_SUPERSCRIPT_ALEF_ISOLATED_FORM                     0xFC5D  0  // ﱝ
#define UC_ARABIC_LIGATURE_SHADDA_WITH_DAMMATAN_ISOLATED_FORM                                   0xFC5E  0  // ﱞ
#define UC_ARABIC_LIGATURE_SHADDA_WITH_KASRATAN_ISOLATED_FORM                                   0xFC5F  0  // ﱟ
#define UC_ARABIC_LIGATURE_SHADDA_WITH_FATHA_ISOLATED_FORM                                      0xFC60  0  // ﱠ
#define UC_ARABIC_LIGATURE_SHADDA_WITH_DAMMA_ISOLATED_FORM                                      0xFC61  0  // ﱡ
#define UC_ARABIC_LIGATURE_SHADDA_WITH_KASRA_ISOLATED_FORM                                      0xFC62  0  // ﱢ
#define UC_ARABIC_LIGATURE_SHADDA_WITH_SUPERSCRIPT_ALEF_ISOLATED_FORM                           0xFC63  0  // ﱣ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_REH_FINAL_FORM                             0xFC64  0  // ﱤ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_ZAIN_FINAL_FORM                            0xFC65  0  // ﱥ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_MEEM_FINAL_FORM                            0xFC66  0  // ﱦ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_NOON_FINAL_FORM                            0xFC67  0  // ﱧ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_ALEF_MAKSURA_FINAL_FORM                    0xFC68  0  // ﱨ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_YEH_FINAL_FORM                             0xFC69  0  // ﱩ
#define UC_ARABIC_LIGATURE_BEH_WITH_REH_FINAL_FORM                                              0xFC6A  0  // ﱪ
#define UC_ARABIC_LIGATURE_BEH_WITH_ZAIN_FINAL_FORM                                             0xFC6B  0  // ﱫ
#define UC_ARABIC_LIGATURE_BEH_WITH_MEEM_FINAL_FORM                                             0xFC6C  0  // ﱬ
#define UC_ARABIC_LIGATURE_BEH_WITH_NOON_FINAL_FORM                                             0xFC6D  0  // ﱭ
#define UC_ARABIC_LIGATURE_BEH_WITH_ALEF_MAKSURA_FINAL_FORM                                     0xFC6E  0  // ﱮ
#define UC_ARABIC_LIGATURE_BEH_WITH_YEH_FINAL_FORM                                              0xFC6F  0  // ﱯ
#define UC_ARABIC_LIGATURE_TEH_WITH_REH_FINAL_FORM                                              0xFC70  0  // ﱰ
#define UC_ARABIC_LIGATURE_TEH_WITH_ZAIN_FINAL_FORM                                             0xFC71  0  // ﱱ
#define UC_ARABIC_LIGATURE_TEH_WITH_MEEM_FINAL_FORM                                             0xFC72  0  // ﱲ
#define UC_ARABIC_LIGATURE_TEH_WITH_NOON_FINAL_FORM                                             0xFC73  0  // ﱳ
#define UC_ARABIC_LIGATURE_TEH_WITH_ALEF_MAKSURA_FINAL_FORM                                     0xFC74  0  // ﱴ
#define UC_ARABIC_LIGATURE_TEH_WITH_YEH_FINAL_FORM                                              0xFC75  0  // ﱵ
#define UC_ARABIC_LIGATURE_THEH_WITH_REH_FINAL_FORM                                             0xFC76  0  // ﱶ
#define UC_ARABIC_LIGATURE_THEH_WITH_ZAIN_FINAL_FORM                                            0xFC77  0  // ﱷ
#define UC_ARABIC_LIGATURE_THEH_WITH_MEEM_FINAL_FORM                                            0xFC78  0  // ﱸ
#define UC_ARABIC_LIGATURE_THEH_WITH_NOON_FINAL_FORM                                            0xFC79  0  // ﱹ
#define UC_ARABIC_LIGATURE_THEH_WITH_ALEF_MAKSURA_FINAL_FORM                                    0xFC7A  0  // ﱺ
#define UC_ARABIC_LIGATURE_THEH_WITH_YEH_FINAL_FORM                                             0xFC7B  0  // ﱻ
#define UC_ARABIC_LIGATURE_FEH_WITH_ALEF_MAKSURA_FINAL_FORM                                     0xFC7C  0  // ﱼ
#define UC_ARABIC_LIGATURE_FEH_WITH_YEH_FINAL_FORM                                              0xFC7D  0  // ﱽ
#define UC_ARABIC_LIGATURE_QAF_WITH_ALEF_MAKSURA_FINAL_FORM                                     0xFC7E  0  // ﱾ
#define UC_ARABIC_LIGATURE_QAF_WITH_YEH_FINAL_FORM                                              0xFC7F  0  // ﱿ
#define UC_ARABIC_LIGATURE_KAF_WITH_ALEF_FINAL_FORM                                             0xFC80  0  // ﲀ
#define UC_ARABIC_LIGATURE_KAF_WITH_LAM_FINAL_FORM                                              0xFC81  0  // ﲁ
#define UC_ARABIC_LIGATURE_KAF_WITH_MEEM_FINAL_FORM                                             0xFC82  0  // ﲂ
#define UC_ARABIC_LIGATURE_KAF_WITH_ALEF_MAKSURA_FINAL_FORM                                     0xFC83  0  // ﲃ
#define UC_ARABIC_LIGATURE_KAF_WITH_YEH_FINAL_FORM                                              0xFC84  0  // ﲄ
#define UC_ARABIC_LIGATURE_LAM_WITH_MEEM_FINAL_FORM                                             0xFC85  0  // ﲅ
#define UC_ARABIC_LIGATURE_LAM_WITH_ALEF_MAKSURA_FINAL_FORM                                     0xFC86  0  // ﲆ
#define UC_ARABIC_LIGATURE_LAM_WITH_YEH_FINAL_FORM                                              0xFC87  0  // ﲇ
#define UC_ARABIC_LIGATURE_MEEM_WITH_ALEF_FINAL_FORM                                            0xFC88  0  // ﲈ
#define UC_ARABIC_LIGATURE_MEEM_WITH_MEEM_FINAL_FORM                                            0xFC89  0  // ﲉ
#define UC_ARABIC_LIGATURE_NOON_WITH_REH_FINAL_FORM                                             0xFC8A  0  // ﲊ
#define UC_ARABIC_LIGATURE_NOON_WITH_ZAIN_FINAL_FORM                                            0xFC8B  0  // ﲋ
#define UC_ARABIC_LIGATURE_NOON_WITH_MEEM_FINAL_FORM                                            0xFC8C  0  // ﲌ
#define UC_ARABIC_LIGATURE_NOON_WITH_NOON_FINAL_FORM                                            0xFC8D  0  // ﲍ
#define UC_ARABIC_LIGATURE_NOON_WITH_ALEF_MAKSURA_FINAL_FORM                                    0xFC8E  0  // ﲎ
#define UC_ARABIC_LIGATURE_NOON_WITH_YEH_FINAL_FORM                                             0xFC8F  0  // ﲏ
#define UC_ARABIC_LIGATURE_ALEF_MAKSURA_WITH_SUPERSCRIPT_ALEF_FINAL_FORM                        0xFC90  0  // ﲐ
#define UC_ARABIC_LIGATURE_YEH_WITH_REH_FINAL_FORM                                              0xFC91  0  // ﲑ
#define UC_ARABIC_LIGATURE_YEH_WITH_ZAIN_FINAL_FORM                                             0xFC92  0  // ﲒ
#define UC_ARABIC_LIGATURE_YEH_WITH_MEEM_FINAL_FORM                                             0xFC93  0  // ﲓ
#define UC_ARABIC_LIGATURE_YEH_WITH_NOON_FINAL_FORM                                             0xFC94  0  // ﲔ
#define UC_ARABIC_LIGATURE_YEH_WITH_ALEF_MAKSURA_FINAL_FORM                                     0xFC95  0  // ﲕ
#define UC_ARABIC_LIGATURE_YEH_WITH_YEH_FINAL_FORM                                              0xFC96  0  // ﲖ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_JEEM_INITIAL_FORM                          0xFC97  0  // ﲗ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_HAH_INITIAL_FORM                           0xFC98  0  // ﲘ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_KHAH_INITIAL_FORM                          0xFC99  0  // ﲙ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_MEEM_INITIAL_FORM                          0xFC9A  0  // ﲚ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_HEH_INITIAL_FORM                           0xFC9B  0  // ﲛ
#define UC_ARABIC_LIGATURE_BEH_WITH_JEEM_INITIAL_FORM                                           0xFC9C  0  // ﲜ
#define UC_ARABIC_LIGATURE_BEH_WITH_HAH_INITIAL_FORM                                            0xFC9D  0  // ﲝ
#define UC_ARABIC_LIGATURE_BEH_WITH_KHAH_INITIAL_FORM                                           0xFC9E  0  // ﲞ
#define UC_ARABIC_LIGATURE_BEH_WITH_MEEM_INITIAL_FORM                                           0xFC9F  0  // ﲟ
#define UC_ARABIC_LIGATURE_BEH_WITH_HEH_INITIAL_FORM                                            0xFCA0  0  // ﲠ
#define UC_ARABIC_LIGATURE_TEH_WITH_JEEM_INITIAL_FORM                                           0xFCA1  0  // ﲡ
#define UC_ARABIC_LIGATURE_TEH_WITH_HAH_INITIAL_FORM                                            0xFCA2  0  // ﲢ
#define UC_ARABIC_LIGATURE_TEH_WITH_KHAH_INITIAL_FORM                                           0xFCA3  0  // ﲣ
#define UC_ARABIC_LIGATURE_TEH_WITH_MEEM_INITIAL_FORM                                           0xFCA4  0  // ﲤ
#define UC_ARABIC_LIGATURE_TEH_WITH_HEH_INITIAL_FORM                                            0xFCA5  0  // ﲥ
#define UC_ARABIC_LIGATURE_THEH_WITH_MEEM_INITIAL_FORM                                          0xFCA6  0  // ﲦ
#define UC_ARABIC_LIGATURE_JEEM_WITH_HAH_INITIAL_FORM                                           0xFCA7  0  // ﲧ
#define UC_ARABIC_LIGATURE_JEEM_WITH_MEEM_INITIAL_FORM                                          0xFCA8  0  // ﲨ
#define UC_ARABIC_LIGATURE_HAH_WITH_JEEM_INITIAL_FORM                                           0xFCA9  0  // ﲩ
#define UC_ARABIC_LIGATURE_HAH_WITH_MEEM_INITIAL_FORM                                           0xFCAA  0  // ﲪ
#define UC_ARABIC_LIGATURE_KHAH_WITH_JEEM_INITIAL_FORM                                          0xFCAB  0  // ﲫ
#define UC_ARABIC_LIGATURE_KHAH_WITH_MEEM_INITIAL_FORM                                          0xFCAC  0  // ﲬ
#define UC_ARABIC_LIGATURE_SEEN_WITH_JEEM_INITIAL_FORM                                          0xFCAD  0  // ﲭ
#define UC_ARABIC_LIGATURE_SEEN_WITH_HAH_INITIAL_FORM                                           0xFCAE  0  // ﲮ
#define UC_ARABIC_LIGATURE_SEEN_WITH_KHAH_INITIAL_FORM                                          0xFCAF  0  // ﲯ
#define UC_ARABIC_LIGATURE_SEEN_WITH_MEEM_INITIAL_FORM                                          0xFCB0  0  // ﲰ
#define UC_ARABIC_LIGATURE_SAD_WITH_HAH_INITIAL_FORM                                            0xFCB1  0  // ﲱ
#define UC_ARABIC_LIGATURE_SAD_WITH_KHAH_INITIAL_FORM                                           0xFCB2  0  // ﲲ
#define UC_ARABIC_LIGATURE_SAD_WITH_MEEM_INITIAL_FORM                                           0xFCB3  0  // ﲳ
#define UC_ARABIC_LIGATURE_DAD_WITH_JEEM_INITIAL_FORM                                           0xFCB4  0  // ﲴ
#define UC_ARABIC_LIGATURE_DAD_WITH_HAH_INITIAL_FORM                                            0xFCB5  0  // ﲵ
#define UC_ARABIC_LIGATURE_DAD_WITH_KHAH_INITIAL_FORM                                           0xFCB6  0  // ﲶ
#define UC_ARABIC_LIGATURE_DAD_WITH_MEEM_INITIAL_FORM                                           0xFCB7  0  // ﲷ
#define UC_ARABIC_LIGATURE_TAH_WITH_HAH_INITIAL_FORM                                            0xFCB8  0  // ﲸ
#define UC_ARABIC_LIGATURE_ZAH_WITH_MEEM_INITIAL_FORM                                           0xFCB9  0  // ﲹ
#define UC_ARABIC_LIGATURE_AIN_WITH_JEEM_INITIAL_FORM                                           0xFCBA  0  // ﲺ
#define UC_ARABIC_LIGATURE_AIN_WITH_MEEM_INITIAL_FORM                                           0xFCBB  0  // ﲻ
#define UC_ARABIC_LIGATURE_GHAIN_WITH_JEEM_INITIAL_FORM                                         0xFCBC  0  // ﲼ
#define UC_ARABIC_LIGATURE_GHAIN_WITH_MEEM_INITIAL_FORM                                         0xFCBD  0  // ﲽ
#define UC_ARABIC_LIGATURE_FEH_WITH_JEEM_INITIAL_FORM                                           0xFCBE  0  // ﲾ
#define UC_ARABIC_LIGATURE_FEH_WITH_HAH_INITIAL_FORM                                            0xFCBF  0  // ﲿ
#define UC_ARABIC_LIGATURE_FEH_WITH_KHAH_INITIAL_FORM                                           0xFCC0  0  // ﳀ
#define UC_ARABIC_LIGATURE_FEH_WITH_MEEM_INITIAL_FORM                                           0xFCC1  0  // ﳁ
#define UC_ARABIC_LIGATURE_QAF_WITH_HAH_INITIAL_FORM                                            0xFCC2  0  // ﳂ
#define UC_ARABIC_LIGATURE_QAF_WITH_MEEM_INITIAL_FORM                                           0xFCC3  0  // ﳃ
#define UC_ARABIC_LIGATURE_KAF_WITH_JEEM_INITIAL_FORM                                           0xFCC4  0  // ﳄ
#define UC_ARABIC_LIGATURE_KAF_WITH_HAH_INITIAL_FORM                                            0xFCC5  0  // ﳅ
#define UC_ARABIC_LIGATURE_KAF_WITH_KHAH_INITIAL_FORM                                           0xFCC6  0  // ﳆ
#define UC_ARABIC_LIGATURE_KAF_WITH_LAM_INITIAL_FORM                                            0xFCC7  0  // ﳇ
#define UC_ARABIC_LIGATURE_KAF_WITH_MEEM_INITIAL_FORM                                           0xFCC8  0  // ﳈ
#define UC_ARABIC_LIGATURE_LAM_WITH_JEEM_INITIAL_FORM                                           0xFCC9  0  // ﳉ
#define UC_ARABIC_LIGATURE_LAM_WITH_HAH_INITIAL_FORM                                            0xFCCA  0  // ﳊ
#define UC_ARABIC_LIGATURE_LAM_WITH_KHAH_INITIAL_FORM                                           0xFCCB  0  // ﳋ
#define UC_ARABIC_LIGATURE_LAM_WITH_MEEM_INITIAL_FORM                                           0xFCCC  0  // ﳌ
#define UC_ARABIC_LIGATURE_LAM_WITH_HEH_INITIAL_FORM                                            0xFCCD  0  // ﳍ
#define UC_ARABIC_LIGATURE_MEEM_WITH_JEEM_INITIAL_FORM                                          0xFCCE  0  // ﳎ
#define UC_ARABIC_LIGATURE_MEEM_WITH_HAH_INITIAL_FORM                                           0xFCCF  0  // ﳏ
#define UC_ARABIC_LIGATURE_MEEM_WITH_KHAH_INITIAL_FORM                                          0xFCD0  0  // ﳐ
#define UC_ARABIC_LIGATURE_MEEM_WITH_MEEM_INITIAL_FORM                                          0xFCD1  0  // ﳑ
#define UC_ARABIC_LIGATURE_NOON_WITH_JEEM_INITIAL_FORM                                          0xFCD2  0  // ﳒ
#define UC_ARABIC_LIGATURE_NOON_WITH_HAH_INITIAL_FORM                                           0xFCD3  0  // ﳓ
#define UC_ARABIC_LIGATURE_NOON_WITH_KHAH_INITIAL_FORM                                          0xFCD4  0  // ﳔ
#define UC_ARABIC_LIGATURE_NOON_WITH_MEEM_INITIAL_FORM                                          0xFCD5  0  // ﳕ
#define UC_ARABIC_LIGATURE_NOON_WITH_HEH_INITIAL_FORM                                           0xFCD6  0  // ﳖ
#define UC_ARABIC_LIGATURE_HEH_WITH_JEEM_INITIAL_FORM                                           0xFCD7  0  // ﳗ
#define UC_ARABIC_LIGATURE_HEH_WITH_MEEM_INITIAL_FORM                                           0xFCD8  0  // ﳘ
#define UC_ARABIC_LIGATURE_HEH_WITH_SUPERSCRIPT_ALEF_INITIAL_FORM                               0xFCD9  0  // ﳙ
#define UC_ARABIC_LIGATURE_YEH_WITH_JEEM_INITIAL_FORM                                           0xFCDA  0  // ﳚ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAH_INITIAL_FORM                                            0xFCDB  0  // ﳛ
#define UC_ARABIC_LIGATURE_YEH_WITH_KHAH_INITIAL_FORM                                           0xFCDC  0  // ﳜ
#define UC_ARABIC_LIGATURE_YEH_WITH_MEEM_INITIAL_FORM                                           0xFCDD  0  // ﳝ
#define UC_ARABIC_LIGATURE_YEH_WITH_HEH_INITIAL_FORM                                            0xFCDE  0  // ﳞ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_MEEM_MEDIAL_FORM                           0xFCDF  0  // ﳟ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAMZA_ABOVE_WITH_HEH_MEDIAL_FORM                            0xFCE0  0  // ﳠ
#define UC_ARABIC_LIGATURE_BEH_WITH_MEEM_MEDIAL_FORM                                            0xFCE1  0  // ﳡ
#define UC_ARABIC_LIGATURE_BEH_WITH_HEH_MEDIAL_FORM                                             0xFCE2  0  // ﳢ
#define UC_ARABIC_LIGATURE_TEH_WITH_MEEM_MEDIAL_FORM                                            0xFCE3  0  // ﳣ
#define UC_ARABIC_LIGATURE_TEH_WITH_HEH_MEDIAL_FORM                                             0xFCE4  0  // ﳤ
#define UC_ARABIC_LIGATURE_THEH_WITH_MEEM_MEDIAL_FORM                                           0xFCE5  0  // ﳥ
#define UC_ARABIC_LIGATURE_THEH_WITH_HEH_MEDIAL_FORM                                            0xFCE6  0  // ﳦ
#define UC_ARABIC_LIGATURE_SEEN_WITH_MEEM_MEDIAL_FORM                                           0xFCE7  0  // ﳧ
#define UC_ARABIC_LIGATURE_SEEN_WITH_HEH_MEDIAL_FORM                                            0xFCE8  0  // ﳨ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_MEEM_MEDIAL_FORM                                          0xFCE9  0  // ﳩ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_HEH_MEDIAL_FORM                                           0xFCEA  0  // ﳪ
#define UC_ARABIC_LIGATURE_KAF_WITH_LAM_MEDIAL_FORM                                             0xFCEB  0  // ﳫ
#define UC_ARABIC_LIGATURE_KAF_WITH_MEEM_MEDIAL_FORM                                            0xFCEC  0  // ﳬ
#define UC_ARABIC_LIGATURE_LAM_WITH_MEEM_MEDIAL_FORM                                            0xFCED  0  // ﳭ
#define UC_ARABIC_LIGATURE_NOON_WITH_MEEM_MEDIAL_FORM                                           0xFCEE  0  // ﳮ
#define UC_ARABIC_LIGATURE_NOON_WITH_HEH_MEDIAL_FORM                                            0xFCEF  0  // ﳯ
#define UC_ARABIC_LIGATURE_YEH_WITH_MEEM_MEDIAL_FORM                                            0xFCF0  0  // ﳰ
#define UC_ARABIC_LIGATURE_YEH_WITH_HEH_MEDIAL_FORM                                             0xFCF1  0  // ﳱ
#define UC_ARABIC_LIGATURE_SHADDA_WITH_FATHA_MEDIAL_FORM                                        0xFCF2  0  // ﳲ
#define UC_ARABIC_LIGATURE_SHADDA_WITH_DAMMA_MEDIAL_FORM                                        0xFCF3  0  // ﳳ
#define UC_ARABIC_LIGATURE_SHADDA_WITH_KASRA_MEDIAL_FORM                                        0xFCF4  0  // ﳴ
#define UC_ARABIC_LIGATURE_TAH_WITH_ALEF_MAKSURA_ISOLATED_FORM                                  0xFCF5  0  // ﳵ
#define UC_ARABIC_LIGATURE_TAH_WITH_YEH_ISOLATED_FORM                                           0xFCF6  0  // ﳶ
#define UC_ARABIC_LIGATURE_AIN_WITH_ALEF_MAKSURA_ISOLATED_FORM                                  0xFCF7  0  // ﳷ
#define UC_ARABIC_LIGATURE_AIN_WITH_YEH_ISOLATED_FORM                                           0xFCF8  0  // ﳸ
#define UC_ARABIC_LIGATURE_GHAIN_WITH_ALEF_MAKSURA_ISOLATED_FORM                                0xFCF9  0  // ﳹ
#define UC_ARABIC_LIGATURE_GHAIN_WITH_YEH_ISOLATED_FORM                                         0xFCFA  0  // ﳺ
#define UC_ARABIC_LIGATURE_SEEN_WITH_ALEF_MAKSURA_ISOLATED_FORM                                 0xFCFB  0  // ﳻ
#define UC_ARABIC_LIGATURE_SEEN_WITH_YEH_ISOLATED_FORM                                          0xFCFC  0  // ﳼ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_ALEF_MAKSURA_ISOLATED_FORM                                0xFCFD  0  // ﳽ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_YEH_ISOLATED_FORM                                         0xFCFE  0  // ﳾ
#define UC_ARABIC_LIGATURE_HAH_WITH_ALEF_MAKSURA_ISOLATED_FORM                                  0xFCFF  0  // ﳿ
#define UC_ARABIC_LIGATURE_HAH_WITH_YEH_ISOLATED_FORM                                           0xFD00  0  // ﴀ
#define UC_ARABIC_LIGATURE_JEEM_WITH_ALEF_MAKSURA_ISOLATED_FORM                                 0xFD01  0  // ﴁ
#define UC_ARABIC_LIGATURE_JEEM_WITH_YEH_ISOLATED_FORM                                          0xFD02  0  // ﴂ
#define UC_ARABIC_LIGATURE_KHAH_WITH_ALEF_MAKSURA_ISOLATED_FORM                                 0xFD03  0  // ﴃ
#define UC_ARABIC_LIGATURE_KHAH_WITH_YEH_ISOLATED_FORM                                          0xFD04  0  // ﴄ
#define UC_ARABIC_LIGATURE_SAD_WITH_ALEF_MAKSURA_ISOLATED_FORM                                  0xFD05  0  // ﴅ
#define UC_ARABIC_LIGATURE_SAD_WITH_YEH_ISOLATED_FORM                                           0xFD06  0  // ﴆ
#define UC_ARABIC_LIGATURE_DAD_WITH_ALEF_MAKSURA_ISOLATED_FORM                                  0xFD07  0  // ﴇ
#define UC_ARABIC_LIGATURE_DAD_WITH_YEH_ISOLATED_FORM                                           0xFD08  0  // ﴈ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_JEEM_ISOLATED_FORM                                        0xFD09  0  // ﴉ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_HAH_ISOLATED_FORM                                         0xFD0A  0  // ﴊ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_KHAH_ISOLATED_FORM                                        0xFD0B  0  // ﴋ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_MEEM_ISOLATED_FORM                                        0xFD0C  0  // ﴌ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_REH_ISOLATED_FORM                                         0xFD0D  0  // ﴍ
#define UC_ARABIC_LIGATURE_SEEN_WITH_REH_ISOLATED_FORM                                          0xFD0E  0  // ﴎ
#define UC_ARABIC_LIGATURE_SAD_WITH_REH_ISOLATED_FORM                                           0xFD0F  0  // ﴏ
#define UC_ARABIC_LIGATURE_DAD_WITH_REH_ISOLATED_FORM                                           0xFD10  0  // ﴐ
#define UC_ARABIC_LIGATURE_TAH_WITH_ALEF_MAKSURA_FINAL_FORM                                     0xFD11  0  // ﴑ
#define UC_ARABIC_LIGATURE_TAH_WITH_YEH_FINAL_FORM                                              0xFD12  0  // ﴒ
#define UC_ARABIC_LIGATURE_AIN_WITH_ALEF_MAKSURA_FINAL_FORM                                     0xFD13  0  // ﴓ
#define UC_ARABIC_LIGATURE_AIN_WITH_YEH_FINAL_FORM                                              0xFD14  0  // ﴔ
#define UC_ARABIC_LIGATURE_GHAIN_WITH_ALEF_MAKSURA_FINAL_FORM                                   0xFD15  0  // ﴕ
#define UC_ARABIC_LIGATURE_GHAIN_WITH_YEH_FINAL_FORM                                            0xFD16  0  // ﴖ
#define UC_ARABIC_LIGATURE_SEEN_WITH_ALEF_MAKSURA_FINAL_FORM                                    0xFD17  0  // ﴗ
#define UC_ARABIC_LIGATURE_SEEN_WITH_YEH_FINAL_FORM                                             0xFD18  0  // ﴘ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_ALEF_MAKSURA_FINAL_FORM                                   0xFD19  0  // ﴙ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_YEH_FINAL_FORM                                            0xFD1A  0  // ﴚ
#define UC_ARABIC_LIGATURE_HAH_WITH_ALEF_MAKSURA_FINAL_FORM                                     0xFD1B  0  // ﴛ
#define UC_ARABIC_LIGATURE_HAH_WITH_YEH_FINAL_FORM                                              0xFD1C  0  // ﴜ
#define UC_ARABIC_LIGATURE_JEEM_WITH_ALEF_MAKSURA_FINAL_FORM                                    0xFD1D  0  // ﴝ
#define UC_ARABIC_LIGATURE_JEEM_WITH_YEH_FINAL_FORM                                             0xFD1E  0  // ﴞ
#define UC_ARABIC_LIGATURE_KHAH_WITH_ALEF_MAKSURA_FINAL_FORM                                    0xFD1F  0  // ﴟ
#define UC_ARABIC_LIGATURE_KHAH_WITH_YEH_FINAL_FORM                                             0xFD20  0  // ﴠ
#define UC_ARABIC_LIGATURE_SAD_WITH_ALEF_MAKSURA_FINAL_FORM                                     0xFD21  0  // ﴡ
#define UC_ARABIC_LIGATURE_SAD_WITH_YEH_FINAL_FORM                                              0xFD22  0  // ﴢ
#define UC_ARABIC_LIGATURE_DAD_WITH_ALEF_MAKSURA_FINAL_FORM                                     0xFD23  0  // ﴣ
#define UC_ARABIC_LIGATURE_DAD_WITH_YEH_FINAL_FORM                                              0xFD24  0  // ﴤ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_JEEM_FINAL_FORM                                           0xFD25  0  // ﴥ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_HAH_FINAL_FORM                                            0xFD26  0  // ﴦ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_KHAH_FINAL_FORM                                           0xFD27  0  // ﴧ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_MEEM_FINAL_FORM                                           0xFD28  0  // ﴨ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_REH_FINAL_FORM                                            0xFD29  0  // ﴩ
#define UC_ARABIC_LIGATURE_SEEN_WITH_REH_FINAL_FORM                                             0xFD2A  0  // ﴪ
#define UC_ARABIC_LIGATURE_SAD_WITH_REH_FINAL_FORM                                              0xFD2B  0  // ﴫ
#define UC_ARABIC_LIGATURE_DAD_WITH_REH_FINAL_FORM                                              0xFD2C  0  // ﴬ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_JEEM_INITIAL_FORM                                         0xFD2D  0  // ﴭ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_HAH_INITIAL_FORM                                          0xFD2E  0  // ﴮ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_KHAH_INITIAL_FORM                                         0xFD2F  0  // ﴯ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_MEEM_INITIAL_FORM                                         0xFD30  0  // ﴰ
#define UC_ARABIC_LIGATURE_SEEN_WITH_HEH_INITIAL_FORM                                           0xFD31  0  // ﴱ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_HEH_INITIAL_FORM                                          0xFD32  0  // ﴲ
#define UC_ARABIC_LIGATURE_TAH_WITH_MEEM_INITIAL_FORM                                           0xFD33  0  // ﴳ
#define UC_ARABIC_LIGATURE_SEEN_WITH_JEEM_MEDIAL_FORM                                           0xFD34  0  // ﴴ
#define UC_ARABIC_LIGATURE_SEEN_WITH_HAH_MEDIAL_FORM                                            0xFD35  0  // ﴵ
#define UC_ARABIC_LIGATURE_SEEN_WITH_KHAH_MEDIAL_FORM                                           0xFD36  0  // ﴶ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_JEEM_MEDIAL_FORM                                          0xFD37  0  // ﴷ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_HAH_MEDIAL_FORM                                           0xFD38  0  // ﴸ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_KHAH_MEDIAL_FORM                                          0xFD39  0  // ﴹ
#define UC_ARABIC_LIGATURE_TAH_WITH_MEEM_MEDIAL_FORM                                            0xFD3A  0  // ﴺ
#define UC_ARABIC_LIGATURE_ZAH_WITH_MEEM_MEDIAL_FORM                                            0xFD3B  0  // ﴻ
#define UC_ARABIC_LIGATURE_ALEF_WITH_FATHATAN_FINAL_FORM                                        0xFD3C  0  // ﴼ
#define UC_ARABIC_LIGATURE_ALEF_WITH_FATHATAN_ISOLATED_FORM                                     0xFD3D  0  // ﴽ
#define UC_ORNATE_LEFT_PARENTHESIS                                                              0xFD3E  0  // ﴾
#define UC_ORNATE_RIGHT_PARENTHESIS                                                             0xFD3F  0  // ﴿
#define UC_ARABIC_LIGATURE_RAHIMAHU_ALLAAH                                                      0xFD40  0  // ﵀
#define UC_ARABIC_LIGATURE_RADI_ALLAAHU_ANH                                                     0xFD41  0  // ﵁
#define UC_ARABIC_LIGATURE_RADI_ALLAAHU_ANHAA                                                   0xFD42  0  // ﵂
#define UC_ARABIC_LIGATURE_RADI_ALLAAHU_ANHUM                                                   0xFD43  0  // ﵃
#define UC_ARABIC_LIGATURE_RADI_ALLAAHU_ANHUMAA                                                 0xFD44  0  // ﵄
#define UC_ARABIC_LIGATURE_RADI_ALLAAHU_ANHUNNA                                                 0xFD45  0  // ﵅
#define UC_ARABIC_LIGATURE_SALLALLAAHU_ALAYHI_WA_AALIH                                          0xFD46  0  // ﵆
#define UC_ARABIC_LIGATURE_ALAYHI_AS_SALAAM                                                     0xFD47  0  // ﵇
#define UC_ARABIC_LIGATURE_ALAYHIM_AS_SALAAM                                                    0xFD48  0  // ﵈
#define UC_ARABIC_LIGATURE_ALAYHIMAA_AS_SALAAM                                                  0xFD49  0  // ﵉
#define UC_ARABIC_LIGATURE_ALAYHI_AS_SALAATU_WAS_SALAAM                                         0xFD4A  0  // ﵊
#define UC_ARABIC_LIGATURE_QUDDISA_SIRRAH                                                       0xFD4B  0  // ﵋
#define UC_ARABIC_LIGATURE_SALLALLAHU_ALAYHI_WAAALIHEE_WA_SALLAM                                0xFD4C  0  // ﵌
#define UC_ARABIC_LIGATURE_ALAYHAA_AS_SALAAM                                                    0xFD4D  0  // ﵍
#define UC_ARABIC_LIGATURE_TABAARAKA_WA_TAAALAA                                                 0xFD4E  0  // ﵎
#define UC_ARABIC_LIGATURE_RAHIMAHUM_ALLAAH                                                     0xFD4F  0  // ﵏
#define UC_ARABIC_LIGATURE_TEH_WITH_JEEM_WITH_MEEM_INITIAL_FORM                                 0xFD50  0  // ﵐ
#define UC_ARABIC_LIGATURE_TEH_WITH_HAH_WITH_JEEM_FINAL_FORM                                    0xFD51  0  // ﵑ
#define UC_ARABIC_LIGATURE_TEH_WITH_HAH_WITH_JEEM_INITIAL_FORM                                  0xFD52  0  // ﵒ
#define UC_ARABIC_LIGATURE_TEH_WITH_HAH_WITH_MEEM_INITIAL_FORM                                  0xFD53  0  // ﵓ
#define UC_ARABIC_LIGATURE_TEH_WITH_KHAH_WITH_MEEM_INITIAL_FORM                                 0xFD54  0  // ﵔ
#define UC_ARABIC_LIGATURE_TEH_WITH_MEEM_WITH_JEEM_INITIAL_FORM                                 0xFD55  0  // ﵕ
#define UC_ARABIC_LIGATURE_TEH_WITH_MEEM_WITH_HAH_INITIAL_FORM                                  0xFD56  0  // ﵖ
#define UC_ARABIC_LIGATURE_TEH_WITH_MEEM_WITH_KHAH_INITIAL_FORM                                 0xFD57  0  // ﵗ
#define UC_ARABIC_LIGATURE_JEEM_WITH_MEEM_WITH_HAH_FINAL_FORM                                   0xFD58  0  // ﵘ
#define UC_ARABIC_LIGATURE_JEEM_WITH_MEEM_WITH_HAH_INITIAL_FORM                                 0xFD59  0  // ﵙ
#define UC_ARABIC_LIGATURE_HAH_WITH_MEEM_WITH_YEH_FINAL_FORM                                    0xFD5A  0  // ﵚ
#define UC_ARABIC_LIGATURE_HAH_WITH_MEEM_WITH_ALEF_MAKSURA_FINAL_FORM                           0xFD5B  0  // ﵛ
#define UC_ARABIC_LIGATURE_SEEN_WITH_HAH_WITH_JEEM_INITIAL_FORM                                 0xFD5C  0  // ﵜ
#define UC_ARABIC_LIGATURE_SEEN_WITH_JEEM_WITH_HAH_INITIAL_FORM                                 0xFD5D  0  // ﵝ
#define UC_ARABIC_LIGATURE_SEEN_WITH_JEEM_WITH_ALEF_MAKSURA_FINAL_FORM                          0xFD5E  0  // ﵞ
#define UC_ARABIC_LIGATURE_SEEN_WITH_MEEM_WITH_HAH_FINAL_FORM                                   0xFD5F  0  // ﵟ
#define UC_ARABIC_LIGATURE_SEEN_WITH_MEEM_WITH_HAH_INITIAL_FORM                                 0xFD60  0  // ﵠ
#define UC_ARABIC_LIGATURE_SEEN_WITH_MEEM_WITH_JEEM_INITIAL_FORM                                0xFD61  0  // ﵡ
#define UC_ARABIC_LIGATURE_SEEN_WITH_MEEM_WITH_MEEM_FINAL_FORM                                  0xFD62  0  // ﵢ
#define UC_ARABIC_LIGATURE_SEEN_WITH_MEEM_WITH_MEEM_INITIAL_FORM                                0xFD63  0  // ﵣ
#define UC_ARABIC_LIGATURE_SAD_WITH_HAH_WITH_HAH_FINAL_FORM                                     0xFD64  0  // ﵤ
#define UC_ARABIC_LIGATURE_SAD_WITH_HAH_WITH_HAH_INITIAL_FORM                                   0xFD65  0  // ﵥ
#define UC_ARABIC_LIGATURE_SAD_WITH_MEEM_WITH_MEEM_FINAL_FORM                                   0xFD66  0  // ﵦ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_HAH_WITH_MEEM_FINAL_FORM                                  0xFD67  0  // ﵧ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_HAH_WITH_MEEM_INITIAL_FORM                                0xFD68  0  // ﵨ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_JEEM_WITH_YEH_FINAL_FORM                                  0xFD69  0  // ﵩ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_MEEM_WITH_KHAH_FINAL_FORM                                 0xFD6A  0  // ﵪ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_MEEM_WITH_KHAH_INITIAL_FORM                               0xFD6B  0  // ﵫ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_MEEM_WITH_MEEM_FINAL_FORM                                 0xFD6C  0  // ﵬ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_MEEM_WITH_MEEM_INITIAL_FORM                               0xFD6D  0  // ﵭ
#define UC_ARABIC_LIGATURE_DAD_WITH_HAH_WITH_ALEF_MAKSURA_FINAL_FORM                            0xFD6E  0  // ﵮ
#define UC_ARABIC_LIGATURE_DAD_WITH_KHAH_WITH_MEEM_FINAL_FORM                                   0xFD6F  0  // ﵯ
#define UC_ARABIC_LIGATURE_DAD_WITH_KHAH_WITH_MEEM_INITIAL_FORM                                 0xFD70  0  // ﵰ
#define UC_ARABIC_LIGATURE_TAH_WITH_MEEM_WITH_HAH_FINAL_FORM                                    0xFD71  0  // ﵱ
#define UC_ARABIC_LIGATURE_TAH_WITH_MEEM_WITH_HAH_INITIAL_FORM                                  0xFD72  0  // ﵲ
#define UC_ARABIC_LIGATURE_TAH_WITH_MEEM_WITH_MEEM_INITIAL_FORM                                 0xFD73  0  // ﵳ
#define UC_ARABIC_LIGATURE_TAH_WITH_MEEM_WITH_YEH_FINAL_FORM                                    0xFD74  0  // ﵴ
#define UC_ARABIC_LIGATURE_AIN_WITH_JEEM_WITH_MEEM_FINAL_FORM                                   0xFD75  0  // ﵵ
#define UC_ARABIC_LIGATURE_AIN_WITH_MEEM_WITH_MEEM_FINAL_FORM                                   0xFD76  0  // ﵶ
#define UC_ARABIC_LIGATURE_AIN_WITH_MEEM_WITH_MEEM_INITIAL_FORM                                 0xFD77  0  // ﵷ
#define UC_ARABIC_LIGATURE_AIN_WITH_MEEM_WITH_ALEF_MAKSURA_FINAL_FORM                           0xFD78  0  // ﵸ
#define UC_ARABIC_LIGATURE_GHAIN_WITH_MEEM_WITH_MEEM_FINAL_FORM                                 0xFD79  0  // ﵹ
#define UC_ARABIC_LIGATURE_GHAIN_WITH_MEEM_WITH_YEH_FINAL_FORM                                  0xFD7A  0  // ﵺ
#define UC_ARABIC_LIGATURE_GHAIN_WITH_MEEM_WITH_ALEF_MAKSURA_FINAL_FORM                         0xFD7B  0  // ﵻ
#define UC_ARABIC_LIGATURE_FEH_WITH_KHAH_WITH_MEEM_FINAL_FORM                                   0xFD7C  0  // ﵼ
#define UC_ARABIC_LIGATURE_FEH_WITH_KHAH_WITH_MEEM_INITIAL_FORM                                 0xFD7D  0  // ﵽ
#define UC_ARABIC_LIGATURE_QAF_WITH_MEEM_WITH_HAH_FINAL_FORM                                    0xFD7E  0  // ﵾ
#define UC_ARABIC_LIGATURE_QAF_WITH_MEEM_WITH_MEEM_FINAL_FORM                                   0xFD7F  0  // ﵿ
#define UC_ARABIC_LIGATURE_LAM_WITH_HAH_WITH_MEEM_FINAL_FORM                                    0xFD80  0  // ﶀ
#define UC_ARABIC_LIGATURE_LAM_WITH_HAH_WITH_YEH_FINAL_FORM                                     0xFD81  0  // ﶁ
#define UC_ARABIC_LIGATURE_LAM_WITH_HAH_WITH_ALEF_MAKSURA_FINAL_FORM                            0xFD82  0  // ﶂ
#define UC_ARABIC_LIGATURE_LAM_WITH_JEEM_WITH_JEEM_INITIAL_FORM                                 0xFD83  0  // ﶃ
#define UC_ARABIC_LIGATURE_LAM_WITH_JEEM_WITH_JEEM_FINAL_FORM                                   0xFD84  0  // ﶄ
#define UC_ARABIC_LIGATURE_LAM_WITH_KHAH_WITH_MEEM_FINAL_FORM                                   0xFD85  0  // ﶅ
#define UC_ARABIC_LIGATURE_LAM_WITH_KHAH_WITH_MEEM_INITIAL_FORM                                 0xFD86  0  // ﶆ
#define UC_ARABIC_LIGATURE_LAM_WITH_MEEM_WITH_HAH_FINAL_FORM                                    0xFD87  0  // ﶇ
#define UC_ARABIC_LIGATURE_LAM_WITH_MEEM_WITH_HAH_INITIAL_FORM                                  0xFD88  0  // ﶈ
#define UC_ARABIC_LIGATURE_MEEM_WITH_HAH_WITH_JEEM_INITIAL_FORM                                 0xFD89  0  // ﶉ
#define UC_ARABIC_LIGATURE_MEEM_WITH_HAH_WITH_MEEM_INITIAL_FORM                                 0xFD8A  0  // ﶊ
#define UC_ARABIC_LIGATURE_MEEM_WITH_HAH_WITH_YEH_FINAL_FORM                                    0xFD8B  0  // ﶋ
#define UC_ARABIC_LIGATURE_MEEM_WITH_JEEM_WITH_HAH_INITIAL_FORM                                 0xFD8C  0  // ﶌ
#define UC_ARABIC_LIGATURE_MEEM_WITH_JEEM_WITH_MEEM_INITIAL_FORM                                0xFD8D  0  // ﶍ
#define UC_ARABIC_LIGATURE_MEEM_WITH_KHAH_WITH_JEEM_INITIAL_FORM                                0xFD8E  0  // ﶎ
#define UC_ARABIC_LIGATURE_MEEM_WITH_KHAH_WITH_MEEM_INITIAL_FORM                                0xFD8F  0  // ﶏ
#define UC_ARABIC_LIGATURE_MEEM_WITH_JEEM_WITH_KHAH_INITIAL_FORM                                0xFD92  0  // ﶒ
#define UC_ARABIC_LIGATURE_HEH_WITH_MEEM_WITH_JEEM_INITIAL_FORM                                 0xFD93  0  // ﶓ
#define UC_ARABIC_LIGATURE_HEH_WITH_MEEM_WITH_MEEM_INITIAL_FORM                                 0xFD94  0  // ﶔ
#define UC_ARABIC_LIGATURE_NOON_WITH_HAH_WITH_MEEM_INITIAL_FORM                                 0xFD95  0  // ﶕ
#define UC_ARABIC_LIGATURE_NOON_WITH_HAH_WITH_ALEF_MAKSURA_FINAL_FORM                           0xFD96  0  // ﶖ
#define UC_ARABIC_LIGATURE_NOON_WITH_JEEM_WITH_MEEM_FINAL_FORM                                  0xFD97  0  // ﶗ
#define UC_ARABIC_LIGATURE_NOON_WITH_JEEM_WITH_MEEM_INITIAL_FORM                                0xFD98  0  // ﶘ
#define UC_ARABIC_LIGATURE_NOON_WITH_JEEM_WITH_ALEF_MAKSURA_FINAL_FORM                          0xFD99  0  // ﶙ
#define UC_ARABIC_LIGATURE_NOON_WITH_MEEM_WITH_YEH_FINAL_FORM                                   0xFD9A  0  // ﶚ
#define UC_ARABIC_LIGATURE_NOON_WITH_MEEM_WITH_ALEF_MAKSURA_FINAL_FORM                          0xFD9B  0  // ﶛ
#define UC_ARABIC_LIGATURE_YEH_WITH_MEEM_WITH_MEEM_FINAL_FORM                                   0xFD9C  0  // ﶜ
#define UC_ARABIC_LIGATURE_YEH_WITH_MEEM_WITH_MEEM_INITIAL_FORM                                 0xFD9D  0  // ﶝ
#define UC_ARABIC_LIGATURE_BEH_WITH_KHAH_WITH_YEH_FINAL_FORM                                    0xFD9E  0  // ﶞ
#define UC_ARABIC_LIGATURE_TEH_WITH_JEEM_WITH_YEH_FINAL_FORM                                    0xFD9F  0  // ﶟ
#define UC_ARABIC_LIGATURE_TEH_WITH_JEEM_WITH_ALEF_MAKSURA_FINAL_FORM                           0xFDA0  0  // ﶠ
#define UC_ARABIC_LIGATURE_TEH_WITH_KHAH_WITH_YEH_FINAL_FORM                                    0xFDA1  0  // ﶡ
#define UC_ARABIC_LIGATURE_TEH_WITH_KHAH_WITH_ALEF_MAKSURA_FINAL_FORM                           0xFDA2  0  // ﶢ
#define UC_ARABIC_LIGATURE_TEH_WITH_MEEM_WITH_YEH_FINAL_FORM                                    0xFDA3  0  // ﶣ
#define UC_ARABIC_LIGATURE_TEH_WITH_MEEM_WITH_ALEF_MAKSURA_FINAL_FORM                           0xFDA4  0  // ﶤ
#define UC_ARABIC_LIGATURE_JEEM_WITH_MEEM_WITH_YEH_FINAL_FORM                                   0xFDA5  0  // ﶥ
#define UC_ARABIC_LIGATURE_JEEM_WITH_HAH_WITH_ALEF_MAKSURA_FINAL_FORM                           0xFDA6  0  // ﶦ
#define UC_ARABIC_LIGATURE_JEEM_WITH_MEEM_WITH_ALEF_MAKSURA_FINAL_FORM                          0xFDA7  0  // ﶧ
#define UC_ARABIC_LIGATURE_SEEN_WITH_KHAH_WITH_ALEF_MAKSURA_FINAL_FORM                          0xFDA8  0  // ﶨ
#define UC_ARABIC_LIGATURE_SAD_WITH_HAH_WITH_YEH_FINAL_FORM                                     0xFDA9  0  // ﶩ
#define UC_ARABIC_LIGATURE_SHEEN_WITH_HAH_WITH_YEH_FINAL_FORM                                   0xFDAA  0  // ﶪ
#define UC_ARABIC_LIGATURE_DAD_WITH_HAH_WITH_YEH_FINAL_FORM                                     0xFDAB  0  // ﶫ
#define UC_ARABIC_LIGATURE_LAM_WITH_JEEM_WITH_YEH_FINAL_FORM                                    0xFDAC  0  // ﶬ
#define UC_ARABIC_LIGATURE_LAM_WITH_MEEM_WITH_YEH_FINAL_FORM                                    0xFDAD  0  // ﶭ
#define UC_ARABIC_LIGATURE_YEH_WITH_HAH_WITH_YEH_FINAL_FORM                                     0xFDAE  0  // ﶮ
#define UC_ARABIC_LIGATURE_YEH_WITH_JEEM_WITH_YEH_FINAL_FORM                                    0xFDAF  0  // ﶯ
#define UC_ARABIC_LIGATURE_YEH_WITH_MEEM_WITH_YEH_FINAL_FORM                                    0xFDB0  0  // ﶰ
#define UC_ARABIC_LIGATURE_MEEM_WITH_MEEM_WITH_YEH_FINAL_FORM                                   0xFDB1  0  // ﶱ
#define UC_ARABIC_LIGATURE_QAF_WITH_MEEM_WITH_YEH_FINAL_FORM                                    0xFDB2  0  // ﶲ
#define UC_ARABIC_LIGATURE_NOON_WITH_HAH_WITH_YEH_FINAL_FORM                                    0xFDB3  0  // ﶳ
#define UC_ARABIC_LIGATURE_QAF_WITH_MEEM_WITH_HAH_INITIAL_FORM                                  0xFDB4  0  // ﶴ
#define UC_ARABIC_LIGATURE_LAM_WITH_HAH_WITH_MEEM_INITIAL_FORM                                  0xFDB5  0  // ﶵ
#define UC_ARABIC_LIGATURE_AIN_WITH_MEEM_WITH_YEH_FINAL_FORM                                    0xFDB6  0  // ﶶ
#define UC_ARABIC_LIGATURE_KAF_WITH_MEEM_WITH_YEH_FINAL_FORM                                    0xFDB7  0  // ﶷ
#define UC_ARABIC_LIGATURE_NOON_WITH_JEEM_WITH_HAH_INITIAL_FORM                                 0xFDB8  0  // ﶸ
#define UC_ARABIC_LIGATURE_MEEM_WITH_KHAH_WITH_YEH_FINAL_FORM                                   0xFDB9  0  // ﶹ
#define UC_ARABIC_LIGATURE_LAM_WITH_JEEM_WITH_MEEM_INITIAL_FORM                                 0xFDBA  0  // ﶺ
#define UC_ARABIC_LIGATURE_KAF_WITH_MEEM_WITH_MEEM_FINAL_FORM                                   0xFDBB  0  // ﶻ
#define UC_ARABIC_LIGATURE_LAM_WITH_JEEM_WITH_MEEM_FINAL_FORM                                   0xFDBC  0  // ﶼ
#define UC_ARABIC_LIGATURE_NOON_WITH_JEEM_WITH_HAH_FINAL_FORM                                   0xFDBD  0  // ﶽ
#define UC_ARABIC_LIGATURE_JEEM_WITH_HAH_WITH_YEH_FINAL_FORM                                    0xFDBE  0  // ﶾ
#define UC_ARABIC_LIGATURE_HAH_WITH_JEEM_WITH_YEH_FINAL_FORM                                    0xFDBF  0  // ﶿ
#define UC_ARABIC_LIGATURE_MEEM_WITH_JEEM_WITH_YEH_FINAL_FORM                                   0xFDC0  0  // ﷀ
#define UC_ARABIC_LIGATURE_FEH_WITH_MEEM_WITH_YEH_FINAL_FORM                                    0xFDC1  0  // ﷁ
#define UC_ARABIC_LIGATURE_BEH_WITH_HAH_WITH_YEH_FINAL_FORM                                     0xFDC2  0  // ﷂ
#define UC_ARABIC_LIGATURE_KAF_WITH_MEEM_WITH_MEEM_INITIAL_FORM                                 0xFDC3  0  // ﷃ
#define UC_ARABIC_LIGATURE_AIN_WITH_JEEM_WITH_MEEM_INITIAL_FORM                                 0xFDC4  0  // ﷄ
#define UC_ARABIC_LIGATURE_SAD_WITH_MEEM_WITH_MEEM_INITIAL_FORM                                 0xFDC5  0  // ﷅ
#define UC_ARABIC_LIGATURE_SEEN_WITH_KHAH_WITH_YEH_FINAL_FORM                                   0xFDC6  0  // ﷆ
#define UC_ARABIC_LIGATURE_NOON_WITH_JEEM_WITH_YEH_FINAL_FORM                                   0xFDC7  0  // ﷇ
#define UC_ARABIC_LIGATURE_SALAAMUHU_ALAYNAA                                                    0xFDCF  0  // ﷏
#define UC_ARABIC_LIGATURE_SALLA_USED_AS_KORANIC_STOP_SIGN_ISOLATED_FORM                        0xFDF0  0  // ﷰ
#define UC_ARABIC_LIGATURE_QALA_USED_AS_KORANIC_STOP_SIGN_ISOLATED_FORM                         0xFDF1  0  // ﷱ
#define UC_ARABIC_LIGATURE_ALLAH_ISOLATED_FORM                                                  0xFDF2  0  // ﷲ
#define UC_ARABIC_LIGATURE_AKBAR_ISOLATED_FORM                                                  0xFDF3  0  // ﷳ
#define UC_ARABIC_LIGATURE_MOHAMMAD_ISOLATED_FORM                                               0xFDF4  0  // ﷴ
#define UC_ARABIC_LIGATURE_SALAM_ISOLATED_FORM                                                  0xFDF5  0  // ﷵ
#define UC_ARABIC_LIGATURE_RASOUL_ISOLATED_FORM                                                 0xFDF6  0  // ﷶ
#define UC_ARABIC_LIGATURE_ALAYHE_ISOLATED_FORM                                                 0xFDF7  0  // ﷷ
#define UC_ARABIC_LIGATURE_WASALLAM_ISOLATED_FORM                                               0xFDF8  0  // ﷸ
#define UC_ARABIC_LIGATURE_SALLA_ISOLATED_FORM                                                  0xFDF9  0  // ﷹ
#define UC_ARABIC_LIGATURE_SALLALLAHOU_ALAYHE_WASALLAM                                          0xFDFA  0  // ﷺ
#define UC_ARABIC_LIGATURE_JALLAJALALOUHOU                                                      0xFDFB  0  // ﷻ
#define UC_RIAL_SIGN                                                                            0xFDFC  0  // ﷼
#define UC_ARABIC_LIGATURE_BISMILLAH_AR_RAHMAN_AR_RAHEEM                                        0xFDFD  0  // ﷽
#define UC_ARABIC_LIGATURE_SUBHAANAHU_WA_TAAALAA                                                0xFDFE  0  // ﷾
#define UC_ARABIC_LIGATURE_AZZA_WA_JALL                                                         0xFDFF  0  // ﷿