/*
 * Unicode keys for U+0600 .. U+06FF
 *
 * This file was generated from Unicode 16.0.0.
 *
 * See http://www.unicode.org/versions/Unicode16.0.0 for source data.
 */

#pragma once

#define UC_ARABIC_INDIC_CUBE_ROOT                                         0x606  0  // ؆
#define UC_ARABIC_INDIC_FOURTH_ROOT                                       0x607  0  // ؇
#define UC_ARABIC_RAY                                                     0x608  0  // ؈
#define UC_ARABIC_INDIC_PER_MILLE_SIGN                                    0x609  0  // ؉
#define UC_ARABIC_INDIC_PER_TEN_THOUSAND_SIGN                             0x60A  0  // ؊
#define UC_AFGHANI_SIGN                                                   0x60B  0  // ؋
#define UC_ARABIC_COMMA                                                   0x60C  0  // ،
#define UC_ARABIC_DATE_SEPARATOR                                          0x60D  0  // ؍
#define UC_ARABIC_POETIC_VERSE_SIGN                                       0x60E  0  // ؎
#define UC_ARABIC_SIGN_MISRA                                              0x60F  0  // ؏
#define UC_ARABIC_SEMICOLON                                               0x61B  0  // ؛
#define UC_ARABIC_END_OF_TEXT_MARK                                        0x61D  0  // ؝
#define UC_ARABIC_TRIPLE_DOT_PUNCTUATION_MARK                             0x61E  0  // ؞
#define UC_ARABIC_QUESTION_MARK                                           0x61F  0  // ؟
#define UC_ARABIC_LETTER_KASHMIRI_YEH                                     0x620  0  // ؠ
#define UC_ARABIC_LETTER_HAMZA                                            0x621  0  // ء
#define UC_ARABIC_LETTER_ALEF_WITH_MADDA_ABOVE                            0x622  0  // آ
#define UC_ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE                            0x623  0  // أ
#define UC_ARABIC_LETTER_WAW_WITH_HAMZA_ABOVE                             0x624  0  // ؤ
#define UC_ARABIC_LETTER_ALEF_WITH_HAMZA_BELOW                            0x625  0  // إ
#define UC_ARABIC_LETTER_YEH_WITH_HAMZA_ABOVE                             0x626  0  // ئ
#define UC_ARABIC_LETTER_ALEF                                             0x627  0  // ا
#define UC_ARABIC_LETTER_BEH                                              0x628  0  // ب
#define UC_ARABIC_LETTER_TEH_MARBUTA                                      0x629  0  // ة
#define UC_ARABIC_LETTER_TEH                                              0x62A  0  // ت
#define UC_ARABIC_LETTER_THEH                                             0x62B  0  // ث
#define UC_ARABIC_LETTER_JEEM                                             0x62C  0  // ج
#define UC_ARABIC_LETTER_HAH                                              0x62D  0  // ح
#define UC_ARABIC_LETTER_KHAH                                             0x62E  0  // خ
#define UC_ARABIC_LETTER_DAL                                              0x62F  0  // د
#define UC_ARABIC_LETTER_THAL                                             0x630  0  // ذ
#define UC_ARABIC_LETTER_REH                                              0x631  0  // ر
#define UC_ARABIC_LETTER_ZAIN                                             0x632  0  // ز
#define UC_ARABIC_LETTER_SEEN                                             0x633  0  // س
#define UC_ARABIC_LETTER_SHEEN                                            0x634  0  // ش
#define UC_ARABIC_LETTER_SAD                                              0x635  0  // ص
#define UC_ARABIC_LETTER_DAD                                              0x636  0  // ض
#define UC_ARABIC_LETTER_TAH                                              0x637  0  // ط
#define UC_ARABIC_LETTER_ZAH                                              0x638  0  // ظ
#define UC_ARABIC_LETTER_AIN                                              0x639  0  // ع
#define UC_ARABIC_LETTER_GHAIN                                            0x63A  0  // غ
#define UC_ARABIC_LETTER_KEHEH_WITH_TWO_DOTS_ABOVE                        0x63B  0  // ػ
#define UC_ARABIC_LETTER_KEHEH_WITH_THREE_DOTS_BELOW                      0x63C  0  // ؼ
#define UC_ARABIC_LETTER_FARSI_YEH_WITH_INVERTED_V                        0x63D  0  // ؽ
#define UC_ARABIC_LETTER_FARSI_YEH_WITH_TWO_DOTS_ABOVE                    0x63E  0  // ؾ
#define UC_ARABIC_LETTER_FARSI_YEH_WITH_THREE_DOTS_ABOVE                  0x63F  0  // ؿ
#define UC_ARABIC_TATWEEL                                                 0x640  0  // ـ
#define UC_ARABIC_LETTER_FEH                                              0x641  0  // ف
#define UC_ARABIC_LETTER_QAF                                              0x642  0  // ق
#define UC_ARABIC_LETTER_KAF                                              0x643  0  // ك
#define UC_ARABIC_LETTER_LAM                                              0x644  0  // ل
#define UC_ARABIC_LETTER_MEEM                                             0x645  0  // م
#define UC_ARABIC_LETTER_NOON                                             0x646  0  // ن
#define UC_ARABIC_LETTER_HEH                                              0x647  0  // ه
#define UC_ARABIC_LETTER_WAW                                              0x648  0  // و
#define UC_ARABIC_LETTER_ALEF_MAKSURA                                     0x649  0  // ى
#define UC_ARABIC_LETTER_YEH                                              0x64A  0  // ي
#define UC_ARABIC_INDIC_DIGIT_ZERO                                        0x660  0  // ٠
#define UC_ARABIC_INDIC_DIGIT_ONE                                         0x661  0  // ١
#define UC_ARABIC_INDIC_DIGIT_TWO                                         0x662  0  // ٢
#define UC_ARABIC_INDIC_DIGIT_THREE                                       0x663  0  // ٣
#define UC_ARABIC_INDIC_DIGIT_FOUR                                        0x664  0  // ٤
#define UC_ARABIC_INDIC_DIGIT_FIVE                                        0x665  0  // ٥
#define UC_ARABIC_INDIC_DIGIT_SIX                                         0x666  0  // ٦
#define UC_ARABIC_INDIC_DIGIT_SEVEN                                       0x667  0  // ٧
#define UC_ARABIC_INDIC_DIGIT_EIGHT                                       0x668  0  // ٨
#define UC_ARABIC_INDIC_DIGIT_NINE                                        0x669  0  // ٩
#define UC_ARABIC_PERCENT_SIGN                                            0x66A  0  // ٪
#define UC_ARABIC_DECIMAL_SEPARATOR                                       0x66B  0  // ٫
#define UC_ARABIC_THOUSANDS_SEPARATOR                                     0x66C  0  // ٬
#define UC_ARABIC_FIVE_POINTED_STAR                                       0x66D  0  // ٭
#define UC_ARABIC_LETTER_DOTLESS_BEH                                      0x66E  0  // ٮ
#define UC_ARABIC_LETTER_DOTLESS_QAF                                      0x66F  0  // ٯ
#define UC_ARABIC_LETTER_ALEF_WASLA                                       0x671  0  // ٱ
#define UC_ARABIC_LETTER_ALEF_WITH_WAVY_HAMZA_ABOVE                       0x672  0  // ٲ
#define UC_ARABIC_LETTER_ALEF_WITH_WAVY_HAMZA_BELOW                       0x673  0  // ٳ
#define UC_ARABIC_LETTER_HIGH_HAMZA                                       0x674  0  // ٴ
#define UC_ARABIC_LETTER_HIGH_HAMZA_ALEF                                  0x675  0  // ٵ
#define UC_ARABIC_LETTER_HIGH_HAMZA_WAW                                   0x676  0  // ٶ
#define UC_ARABIC_LETTER_U_WITH_HAMZA_ABOVE                               0x677  0  // ٷ
#define UC_ARABIC_LETTER_HIGH_HAMZA_YEH                                   0x678  0  // ٸ
#define UC_ARABIC_LETTER_TTEH                                             0x679  0  // ٹ
#define UC_ARABIC_LETTER_TTEHEH                                           0x67A  0  // ٺ
#define UC_ARABIC_LETTER_BEEH                                             0x67B  0  // ٻ
#define UC_ARABIC_LETTER_TEH_WITH_RING                                    0x67C  0  // ټ
#define UC_ARABIC_LETTER_TEH_WITH_THREE_DOTS_ABOVE_DOWNWARDS              0x67D  0  // ٽ
#define UC_ARABIC_LETTER_PEH                                              0x67E  0  // پ
#define UC_ARABIC_LETTER_TEHEH                                            0x67F  0  // ٿ
#define UC_ARABIC_LETTER_BEHEH                                            0x680  0  // ڀ
#define UC_ARABIC_LETTER_HAH_WITH_HAMZA_ABOVE                             0x681  0  // ځ
#define UC_ARABIC_LETTER_HAH_WITH_TWO_DOTS_VERTICAL_ABOVE                 0x682  0  // ڂ
#define UC_ARABIC_LETTER_NYEH                                             0x683  0  // ڃ
#define UC_ARABIC_LETTER_DYEH                                             0x684  0  // ڄ
#define UC_ARABIC_LETTER_HAH_WITH_THREE_DOTS_ABOVE                        0x685  0  // څ
#define UC_ARABIC_LETTER_TCHEH                                            0x686  0  // چ
#define UC_ARABIC_LETTER_TCHEHEH                                          0x687  0  // ڇ
#define UC_ARABIC_LETTER_DDAL                                             0x688  0  // ڈ
#define UC_ARABIC_LETTER_DAL_WITH_RING                                    0x689  0  // ډ
#define UC_ARABIC_LETTER_DAL_WITH_DOT_BELOW                               0x68A  0  // ڊ
#define UC_ARABIC_LETTER_DAL_WITH_DOT_BELOW_AND_SMALL_TAH                 0x68B  0  // ڋ
#define UC_ARABIC_LETTER_DAHAL                                            0x68C  0  // ڌ
#define UC_ARABIC_LETTER_DDAHAL                                           0x68D  0  // ڍ
#define UC_ARABIC_LETTER_DUL                                              0x68E  0  // ڎ
#define UC_ARABIC_LETTER_DAL_WITH_THREE_DOTS_ABOVE_DOWNWARDS              0x68F  0  // ڏ
#define UC_ARABIC_LETTER_DAL_WITH_FOUR_DOTS_ABOVE                         0x690  0  // ڐ
#define UC_ARABIC_LETTER_RREH                                             0x691  0  // ڑ
#define UC_ARABIC_LETTER_REH_WITH_SMALL_V                                 0x692  0  // ڒ
#define UC_ARABIC_LETTER_REH_WITH_RING                                    0x693  0  // ړ
#define UC_ARABIC_LETTER_REH_WITH_DOT_BELOW                               0x694  0  // ڔ
#define UC_ARABIC_LETTER_REH_WITH_SMALL_V_BELOW                           0x695  0  // ڕ
#define UC_ARABIC_LETTER_REH_WITH_DOT_BELOW_AND_DOT_ABOVE                 0x696  0  // ږ
#define UC_ARABIC_LETTER_REH_WITH_TWO_DOTS_ABOVE                          0x697  0  // ڗ
#define UC_ARABIC_LETTER_JEH                                              0x698  0  // ژ
#define UC_ARABIC_LETTER_REH_WITH_FOUR_DOTS_ABOVE                         0x699  0  // ڙ
#define UC_ARABIC_LETTER_SEEN_WITH_DOT_BELOW_AND_DOT_ABOVE                0x69A  0  // ښ
#define UC_ARABIC_LETTER_SEEN_WITH_THREE_DOTS_BELOW                       0x69B  0  // ڛ
#define UC_ARABIC_LETTER_SEEN_WITH_THREE_DOTS_BELOW_AND_THREE_DOTS_ABOVE  0x69C  0  // ڜ
#define UC_ARABIC_LETTER_SAD_WITH_TWO_DOTS_BELOW                          0x69D  0  // ڝ
#define UC_ARABIC_LETTER_SAD_WITH_THREE_DOTS_ABOVE                        0x69E  0  // ڞ
#define UC_ARABIC_LETTER_TAH_WITH_THREE_DOTS_ABOVE                        0x69F  0  // ڟ
#define UC_ARABIC_LETTER_AIN_WITH_THREE_DOTS_ABOVE                        0x6A0  0  // ڠ
#define UC_ARABIC_LETTER_DOTLESS_FEH                                      0x6A1  0  // ڡ
#define UC_ARABIC_LETTER_FEH_WITH_DOT_MOVED_BELOW                         0x6A2  0  // ڢ
#define UC_ARABIC_LETTER_FEH_WITH_DOT_BELOW                               0x6A3  0  // ڣ
#define UC_ARABIC_LETTER_VEH                                              0x6A4  0  // ڤ
#define UC_ARABIC_LETTER_FEH_WITH_THREE_DOTS_BELOW                        0x6A5  0  // ڥ
#define UC_ARABIC_LETTER_PEHEH                                            0x6A6  0  // ڦ
#define UC_ARABIC_LETTER_QAF_WITH_DOT_ABOVE                               0x6A7  0  // ڧ
#define UC_ARABIC_LETTER_QAF_WITH_THREE_DOTS_ABOVE                        0x6A8  0  // ڨ
#define UC_ARABIC_LETTER_KEHEH                                            0x6A9  0  // ک
#define UC_ARABIC_LETTER_SWASH_KAF                                        0x6AA  0  // ڪ
#define UC_ARABIC_LETTER_KAF_WITH_RING                                    0x6AB  0  // ګ
#define UC_ARABIC_LETTER_KAF_WITH_DOT_ABOVE                               0x6AC  0  // ڬ
#define UC_ARABIC_LETTER_NG                                               0x6AD  0  // ڭ
#define UC_ARABIC_LETTER_KAF_WITH_THREE_DOTS_BELOW                        0x6AE  0  // ڮ
#define UC_ARABIC_LETTER_GAF                                              0x6AF  0  // گ
#define UC_ARABIC_LETTER_GAF_WITH_RING                                    0x6B0  0  // ڰ
#define UC_ARABIC_LETTER_NGOEH                                            0x6B1  0  // ڱ
#define UC_ARABIC_LETTER_GAF_WITH_TWO_DOTS_BELOW                          0x6B2  0  // ڲ
#define UC_ARABIC_LETTER_GUEH                                             0x6B3  0  // ڳ
#define UC_ARABIC_LETTER_GAF_WITH_THREE_DOTS_ABOVE                        0x6B4  0  // ڴ
#define UC_ARABIC_LETTER_LAM_WITH_SMALL_V                                 0x6B5  0  // ڵ
#define UC_ARABIC_LETTER_LAM_WITH_DOT_ABOVE                               0x6B6  0  // ڶ
#define UC_ARABIC_LETTER_LAM_WITH_THREE_DOTS_ABOVE                        0x6B7  0  // ڷ
#define UC_ARABIC_LETTER_LAM_WITH_THREE_DOTS_BELOW                        0x6B8  0  // ڸ
#define UC_ARABIC_LETTER_NOON_WITH_DOT_BELOW                              0x6B9  0  // ڹ
#define UC_ARABIC_LETTER_NOON_GHUNNA                                      0x6BA  0  // ں
#define UC_ARABIC_LETTER_RNOON                                            0x6BB  0  // ڻ
#define UC_ARABIC_LETTER_NOON_WITH_RING                                   0x6BC  0  // ڼ
#define UC_ARABIC_LETTER_NOON_WITH_THREE_DOTS_ABOVE                       0x6BD  0  // ڽ
#define UC_ARABIC_LETTER_HEH_DOACHASHMEE                                  0x6BE  0  // ھ
#define UC_ARABIC_LETTER_TCHEH_WITH_DOT_ABOVE                             0x6BF  0  // ڿ
#define UC_ARABIC_LETTER_HEH_WITH_YEH_ABOVE                               0x6C0  0  // ۀ
#define UC_ARABIC_LETTER_HEH_GOAL                                         0x6C1  0  // ہ
#define UC_ARABIC_LETTER_HEH_GOAL_WITH_HAMZA_ABOVE                        0x6C2  0  // ۂ
#define UC_ARABIC_LETTER_TEH_MARBUTA_GOAL                                 0x6C3  0  // ۃ
#define UC_ARABIC_LETTER_WAW_WITH_RING                                    0x6C4  0  // ۄ
#define UC_ARABIC_LETTER_KIRGHIZ_OE                                       0x6C5  0  // ۅ
#define UC_ARABIC_LETTER_OE                                               0x6C6  0  // ۆ
#define UC_ARABIC_LETTER_U                                                0x6C7  0  // ۇ
#define UC_ARABIC_LETTER_YU                                               0x6C8  0  // ۈ
#define UC_ARABIC_LETTER_KIRGHIZ_YU                                       0x6C9  0  // ۉ
#define UC_ARABIC_LETTER_WAW_WITH_TWO_DOTS_ABOVE                          0x6CA  0  // ۊ
#define UC_ARABIC_LETTER_VE                                               0x6CB  0  // ۋ
#define UC_ARABIC_LETTER_FARSI_YEH                                        0x6CC  0  // ی
#define UC_ARABIC_LETTER_YEH_WITH_TAIL                                    0x6CD  0  // ۍ
#define UC_ARABIC_LETTER_YEH_WITH_SMALL_V                                 0x6CE  0  // ێ
#define UC_ARABIC_LETTER_WAW_WITH_DOT_ABOVE                               0x6CF  0  // ۏ
#define UC_ARABIC_LETTER_E                                                0x6D0  0  // ې
#define UC_ARABIC_LETTER_YEH_WITH_THREE_DOTS_BELOW                        0x6D1  0  // ۑ
#define UC_ARABIC_LETTER_YEH_BARREE                                       0x6D2  0  // ے
#define UC_ARABIC_LETTER_YEH_BARREE_WITH_HAMZA_ABOVE                      0x6D3  0  // ۓ
#define UC_ARABIC_FULL_STOP                                               0x6D4  0  // ۔
#define UC_ARABIC_LETTER_AE                                               0x6D5  0  // ە
#define UC_ARABIC_START_OF_RUB_EL_HIZB                                    0x6DE  0  // ۞
#define UC_ARABIC_SMALL_WAW                                               0x6E5  0  // ۥ
#define UC_ARABIC_SMALL_YEH                                               0x6E6  0  // ۦ
#define UC_ARABIC_PLACE_OF_SAJDAH                                         0x6E9  0  // ۩
#define UC_ARABIC_LETTER_DAL_WITH_INVERTED_V                              0x6EE  0  // ۮ
#define UC_ARABIC_LETTER_REH_WITH_INVERTED_V                              0x6EF  0  // ۯ
#define UC_EXTENDED_ARABIC_INDIC_DIGIT_ZERO                               0x6F0  0  // ۰
#define UC_EXTENDED_ARABIC_INDIC_DIGIT_ONE                                0x6F1  0  // ۱
#define UC_EXTENDED_ARABIC_INDIC_DIGIT_TWO                                0x6F2  0  // ۲
#define UC_EXTENDED_ARABIC_INDIC_DIGIT_THREE                              0x6F3  0  // ۳
#define UC_EXTENDED_ARABIC_INDIC_DIGIT_FOUR                               0x6F4  0  // ۴
#define UC_EXTENDED_ARABIC_INDIC_DIGIT_FIVE                               0x6F5  0  // ۵
#define UC_EXTENDED_ARABIC_INDIC_DIGIT_SIX                                0x6F6  0  // ۶
#define UC_EXTENDED_ARABIC_INDIC_DIGIT_SEVEN                              0x6F7  0  // ۷
#define UC_EXTENDED_ARABIC_INDIC_DIGIT_EIGHT                              0x6F8  0  // ۸
#define UC_EXTENDED_ARABIC_INDIC_DIGIT_NINE                               0x6F9  0  // ۹
#define UC_ARABIC_LETTER_SHEEN_WITH_DOT_BELOW                             0x6FA  0  // ۺ
#define UC_ARABIC_LETTER_DAD_WITH_DOT_BELOW                               0x6FB  0  // ۻ
#define UC_ARABIC_LETTER_GHAIN_WITH_DOT_BELOW                             0x6FC  0  // ۼ
#define UC_ARABIC_SIGN_SINDHI_AMPERSAND                                   0x6FD  0  // ۽
#define UC_ARABIC_SIGN_SINDHI_POSTPOSITION_MEN                            0x6FE  0  // ۾
#define UC_ARABIC_LETTER_HEH_WITH_INVERTED_V                              0x6FF  0  // ۿ