/*
 * Unicode keys for U+12000 .. U+123FF
 *
 * This file was generated from Unidata 16.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode16.0.0 for source data.
 */

#pragma once

#define UC_CUNEIFORM_SIGN_A                                                     0x12000  0  // 𒀀
#define UC_CUNEIFORM_SIGN_A_TIMES_A                                             0x12001  0  // 𒀁
#define UC_CUNEIFORM_SIGN_A_TIMES_BAD                                           0x12002  0  // 𒀂
#define UC_CUNEIFORM_SIGN_A_TIMES_GAN2_TENU                                     0x12003  0  // 𒀃
#define UC_CUNEIFORM_SIGN_A_TIMES_HA                                            0x12004  0  // 𒀄
#define UC_CUNEIFORM_SIGN_A_TIMES_IGI                                           0x12005  0  // 𒀅
#define UC_CUNEIFORM_SIGN_A_TIMES_LAGAR_GUNU                                    0x12006  0  // 𒀆
#define UC_CUNEIFORM_SIGN_A_TIMES_MUSH                                          0x12007  0  // 𒀇
#define UC_CUNEIFORM_SIGN_A_TIMES_SAG                                           0x12008  0  // 𒀈
#define UC_CUNEIFORM_SIGN_A2                                                    0x12009  0  // 𒀉
#define UC_CUNEIFORM_SIGN_AB                                                    0x1200A  0  // 𒀊
#define UC_CUNEIFORM_SIGN_AB_TIMES_ASH2                                         0x1200B  0  // 𒀋
#define UC_CUNEIFORM_SIGN_AB_TIMES_DUN3_GUNU                                    0x1200C  0  // 𒀌
#define UC_CUNEIFORM_SIGN_AB_TIMES_GAL                                          0x1200D  0  // 𒀍
#define UC_CUNEIFORM_SIGN_AB_TIMES_GAN2_TENU                                    0x1200E  0  // 𒀎
#define UC_CUNEIFORM_SIGN_AB_TIMES_HA                                           0x1200F  0  // 𒀏
#define UC_CUNEIFORM_SIGN_AB_TIMES_IGI_GUNU                                     0x12010  0  // 𒀐
#define UC_CUNEIFORM_SIGN_AB_TIMES_IMIN                                         0x12011  0  // 𒀑
#define UC_CUNEIFORM_SIGN_AB_TIMES_LAGAB                                        0x12012  0  // 𒀒
#define UC_CUNEIFORM_SIGN_AB_TIMES_SHESH                                        0x12013  0  // 𒀓
#define UC_CUNEIFORM_SIGN_AB_TIMES_U_PLUS_U_PLUS_U                              0x12014  0  // 𒀔
#define UC_CUNEIFORM_SIGN_AB_GUNU                                               0x12015  0  // 𒀕
#define UC_CUNEIFORM_SIGN_AB2                                                   0x12016  0  // 𒀖
#define UC_CUNEIFORM_SIGN_AB2_TIMES_BALAG                                       0x12017  0  // 𒀗
#define UC_CUNEIFORM_SIGN_AB2_TIMES_GAN2_TENU                                   0x12018  0  // 𒀘
#define UC_CUNEIFORM_SIGN_AB2_TIMES_ME_PLUS_EN                                  0x12019  0  // 𒀙
#define UC_CUNEIFORM_SIGN_AB2_TIMES_SHA3                                        0x1201A  0  // 𒀚
#define UC_CUNEIFORM_SIGN_AB2_TIMES_TAK4                                        0x1201B  0  // 𒀛
#define UC_CUNEIFORM_SIGN_AD                                                    0x1201C  0  // 𒀜
#define UC_CUNEIFORM_SIGN_AK                                                    0x1201D  0  // 𒀝
#define UC_CUNEIFORM_SIGN_AK_TIMES_ERIN2                                        0x1201E  0  // 𒀞
#define UC_CUNEIFORM_SIGN_AK_TIMES_SHITA_PLUS_GISH                              0x1201F  0  // 𒀟
#define UC_CUNEIFORM_SIGN_AL                                                    0x12020  0  // 𒀠
#define UC_CUNEIFORM_SIGN_AL_TIMES_AL                                           0x12021  0  // 𒀡
#define UC_CUNEIFORM_SIGN_AL_TIMES_DIM2                                         0x12022  0  // 𒀢
#define UC_CUNEIFORM_SIGN_AL_TIMES_GISH                                         0x12023  0  // 𒀣
#define UC_CUNEIFORM_SIGN_AL_TIMES_HA                                           0x12024  0  // 𒀤
#define UC_CUNEIFORM_SIGN_AL_TIMES_KAD3                                         0x12025  0  // 𒀥
#define UC_CUNEIFORM_SIGN_AL_TIMES_KI                                           0x12026  0  // 𒀦
#define UC_CUNEIFORM_SIGN_AL_TIMES_SHE                                          0x12027  0  // 𒀧
#define UC_CUNEIFORM_SIGN_AL_TIMES_USH                                          0x12028  0  // 𒀨
#define UC_CUNEIFORM_SIGN_ALAN                                                  0x12029  0  // 𒀩
#define UC_CUNEIFORM_SIGN_ALEPH                                                 0x1202A  0  // 𒀪
#define UC_CUNEIFORM_SIGN_AMAR                                                  0x1202B  0  // 𒀫
#define UC_CUNEIFORM_SIGN_AMAR_TIMES_SHE                                        0x1202C  0  // 𒀬
#define UC_CUNEIFORM_SIGN_AN                                                    0x1202D  0  // 𒀭
#define UC_CUNEIFORM_SIGN_AN_OVER_AN                                            0x1202E  0  // 𒀮
#define UC_CUNEIFORM_SIGN_AN_THREE_TIMES                                        0x1202F  0  // 𒀯
#define UC_CUNEIFORM_SIGN_AN_PLUS_NAGA_OPPOSING_AN_PLUS_NAGA                    0x12030  0  // 𒀰
#define UC_CUNEIFORM_SIGN_AN_PLUS_NAGA_SQUARED                                  0x12031  0  // 𒀱
#define UC_CUNEIFORM_SIGN_ANSHE                                                 0x12032  0  // 𒀲
#define UC_CUNEIFORM_SIGN_APIN                                                  0x12033  0  // 𒀳
#define UC_CUNEIFORM_SIGN_ARAD                                                  0x12034  0  // 𒀴
#define UC_CUNEIFORM_SIGN_ARAD_TIMES_KUR                                        0x12035  0  // 𒀵
#define UC_CUNEIFORM_SIGN_ARKAB                                                 0x12036  0  // 𒀶
#define UC_CUNEIFORM_SIGN_ASAL2                                                 0x12037  0  // 𒀷
#define UC_CUNEIFORM_SIGN_ASH                                                   0x12038  0  // 𒀸
#define UC_CUNEIFORM_SIGN_ASH_ZIDA_TENU                                         0x12039  0  // 𒀹
#define UC_CUNEIFORM_SIGN_ASH_KABA_TENU                                         0x1203A  0  // 𒀺
#define UC_CUNEIFORM_SIGN_ASH_OVER_ASH_TUG2_OVER_TUG2_TUG2_OVER_TUG2_PAP        0x1203B  0  // 𒀻
#define UC_CUNEIFORM_SIGN_ASH_OVER_ASH_OVER_ASH                                 0x1203C  0  // 𒀼
#define UC_CUNEIFORM_SIGN_ASH_OVER_ASH_OVER_ASH_CROSSING_ASH_OVER_ASH_OVER_ASH  0x1203D  0  // 𒀽
#define UC_CUNEIFORM_SIGN_ASH2                                                  0x1203E  0  // 𒀾
#define UC_CUNEIFORM_SIGN_ASHGAB                                                0x1203F  0  // 𒀿
#define UC_CUNEIFORM_SIGN_BA                                                    0x12040  0  // 𒁀
#define UC_CUNEIFORM_SIGN_BAD                                                   0x12041  0  // 𒁁
#define UC_CUNEIFORM_SIGN_BAG3                                                  0x12042  0  // 𒁂
#define UC_CUNEIFORM_SIGN_BAHAR2                                                0x12043  0  // 𒁃
#define UC_CUNEIFORM_SIGN_BAL                                                   0x12044  0  // 𒁄
#define UC_CUNEIFORM_SIGN_BAL_OVER_BAL                                          0x12045  0  // 𒁅
#define UC_CUNEIFORM_SIGN_BALAG                                                 0x12046  0  // 𒁆
#define UC_CUNEIFORM_SIGN_BAR                                                   0x12047  0  // 𒁇
#define UC_CUNEIFORM_SIGN_BARA2                                                 0x12048  0  // 𒁈
#define UC_CUNEIFORM_SIGN_BI                                                    0x12049  0  // 𒁉
#define UC_CUNEIFORM_SIGN_BI_TIMES_A                                            0x1204A  0  // 𒁊
#define UC_CUNEIFORM_SIGN_BI_TIMES_GAR                                          0x1204B  0  // 𒁋
#define UC_CUNEIFORM_SIGN_BI_TIMES_IGI_GUNU                                     0x1204C  0  // 𒁌
#define UC_CUNEIFORM_SIGN_BU                                                    0x1204D  0  // 𒁍
#define UC_CUNEIFORM_SIGN_BU_OVER_BU_AB                                         0x1204E  0  // 𒁎
#define UC_CUNEIFORM_SIGN_BU_OVER_BU_UN                                         0x1204F  0  // 𒁏
#define UC_CUNEIFORM_SIGN_BU_CROSSING_BU                                        0x12050  0  // 𒁐
#define UC_CUNEIFORM_SIGN_BULUG                                                 0x12051  0  // 𒁑
#define UC_CUNEIFORM_SIGN_BULUG_OVER_BULUG                                      0x12052  0  // 𒁒
#define UC_CUNEIFORM_SIGN_BUR                                                   0x12053  0  // 𒁓
#define UC_CUNEIFORM_SIGN_BUR2                                                  0x12054  0  // 𒁔
#define UC_CUNEIFORM_SIGN_DA                                                    0x12055  0  // 𒁕
#define UC_CUNEIFORM_SIGN_DAG                                                   0x12056  0  // 𒁖
#define UC_CUNEIFORM_SIGN_DAG_KISIM5_TIMES_A_PLUS_MASH                          0x12057  0  // 𒁗
#define UC_CUNEIFORM_SIGN_DAG_KISIM5_TIMES_AMAR                                 0x12058  0  // 𒁘
#define UC_CUNEIFORM_SIGN_DAG_KISIM5_TIMES_BALAG                                0x12059  0  // 𒁙
#define UC_CUNEIFORM_SIGN_DAG_KISIM5_TIMES_BI                                   0x1205A  0  // 𒁚
#define UC_CUNEIFORM_SIGN_DAG_KISIM5_TIMES_GA                                   0x1205B  0  // 𒁛
#define UC_CUNEIFORM_SIGN_DAG_KISIM5_TIMES_GA_PLUS_MASH                         0x1205C  0  // 𒁜
#define UC_CUNEIFORM_SIGN_DAG_KISIM5_TIMES_GI                                   0x1205D  0  // 𒁝
#define UC_CUNEIFORM_SIGN_DAG_KISIM5_TIMES_GIR2                                 0x1205E  0  // 𒁞
#define UC_CUNEIFORM_SIGN_DAG_KISIM5_TIMES_GUD                                  0x1205F  0  // 𒁟
#define UC_CUNEIFORM_SIGN_DAG_KISIM5_TIMES_HA                                   0x12060  0  // 𒁠
#define UC_CUNEIFORM_SIGN_DAG_KISIM5_TIMES_IR                                   0x12061  0  // 𒁡
#define UC_CUNEIFORM_SIGN_DAG_KISIM5_TIMES_IR_PLUS_LU                           0x12062  0  // 𒁢
#define UC_CUNEIFORM_SIGN_DAG_KISIM5_TIMES_KAK                                  0x12063  0  // 𒁣
#define UC_CUNEIFORM_SIGN_DAG_KISIM5_TIMES_LA                                   0x12064  0  // 𒁤
#define UC_CUNEIFORM_SIGN_DAG_KISIM5_TIMES_LU                                   0x12065  0  // 𒁥
#define UC_CUNEIFORM_SIGN_DAG_KISIM5_TIMES_LU_PLUS_MASH2                        0x12066  0  // 𒁦
#define UC_CUNEIFORM_SIGN_DAG_KISIM5_TIMES_LUM                                  0x12067  0  // 𒁧
#define UC_CUNEIFORM_SIGN_DAG_KISIM5_TIMES_NE                                   0x12068  0  // 𒁨
#define UC_CUNEIFORM_SIGN_DAG_KISIM5_TIMES_PAP_PLUS_PAP                         0x12069  0  // 𒁩
#define UC_CUNEIFORM_SIGN_DAG_KISIM5_TIMES_SI                                   0x1206A  0  // 𒁪
#define UC_CUNEIFORM_SIGN_DAG_KISIM5_TIMES_TAK4                                 0x1206B  0  // 𒁫
#define UC_CUNEIFORM_SIGN_DAG_KISIM5_TIMES_U2_PLUS_GIR2                         0x1206C  0  // 𒁬
#define UC_CUNEIFORM_SIGN_DAG_KISIM5_TIMES_USH                                  0x1206D  0  // 𒁭
#define UC_CUNEIFORM_SIGN_DAM                                                   0x1206E  0  // 𒁮
#define UC_CUNEIFORM_SIGN_DAR                                                   0x1206F  0  // 𒁯
#define UC_CUNEIFORM_SIGN_DARA3                                                 0x12070  0  // 𒁰
#define UC_CUNEIFORM_SIGN_DARA4                                                 0x12071  0  // 𒁱
#define UC_CUNEIFORM_SIGN_DI                                                    0x12072  0  // 𒁲
#define UC_CUNEIFORM_SIGN_DIB                                                   0x12073  0  // 𒁳
#define UC_CUNEIFORM_SIGN_DIM                                                   0x12074  0  // 𒁴
#define UC_CUNEIFORM_SIGN_DIM_TIMES_SHE                                         0x12075  0  // 𒁵
#define UC_CUNEIFORM_SIGN_DIM2                                                  0x12076  0  // 𒁶
#define UC_CUNEIFORM_SIGN_DIN                                                   0x12077  0  // 𒁷
#define UC_CUNEIFORM_SIGN_DIN_KASKAL_U_GUNU_DISH                                0x12078  0  // 𒁸
#define UC_CUNEIFORM_SIGN_DISH                                                  0x12079  0  // 𒁹
#define UC_CUNEIFORM_SIGN_DU                                                    0x1207A  0  // 𒁺
#define UC_CUNEIFORM_SIGN_DU_OVER_DU                                            0x1207B  0  // 𒁻
#define UC_CUNEIFORM_SIGN_DU_GUNU                                               0x1207C  0  // 𒁼
#define UC_CUNEIFORM_SIGN_DU_SHESHIG                                            0x1207D  0  // 𒁽
#define UC_CUNEIFORM_SIGN_DUB                                                   0x1207E  0  // 𒁾
#define UC_CUNEIFORM_SIGN_DUB_TIMES_ESH2                                        0x1207F  0  // 𒁿
#define UC_CUNEIFORM_SIGN_DUB2                                                  0x12080  0  // 𒂀
#define UC_CUNEIFORM_SIGN_DUG                                                   0x12081  0  // 𒂁
#define UC_CUNEIFORM_SIGN_DUGUD                                                 0x12082  0  // 𒂂
#define UC_CUNEIFORM_SIGN_DUH                                                   0x12083  0  // 𒂃
#define UC_CUNEIFORM_SIGN_DUN                                                   0x12084  0  // 𒂄
#define UC_CUNEIFORM_SIGN_DUN3                                                  0x12085  0  // 𒂅
#define UC_CUNEIFORM_SIGN_DUN3_GUNU                                             0x12086  0  // 𒂆
#define UC_CUNEIFORM_SIGN_DUN3_GUNU_GUNU                                        0x12087  0  // 𒂇
#define UC_CUNEIFORM_SIGN_DUN4                                                  0x12088  0  // 𒂈
#define UC_CUNEIFORM_SIGN_DUR2                                                  0x12089  0  // 𒂉
#define UC_CUNEIFORM_SIGN_E                                                     0x1208A  0  // 𒂊
#define UC_CUNEIFORM_SIGN_E_TIMES_PAP                                           0x1208B  0  // 𒂋
#define UC_CUNEIFORM_SIGN_E_OVER_E_NUN_OVER_NUN                                 0x1208C  0  // 𒂌
#define UC_CUNEIFORM_SIGN_E2                                                    0x1208D  0  // 𒂍
#define UC_CUNEIFORM_SIGN_E2_TIMES_A_PLUS_HA_PLUS_DA                            0x1208E  0  // 𒂎
#define UC_CUNEIFORM_SIGN_E2_TIMES_GAR                                          0x1208F  0  // 𒂏
#define UC_CUNEIFORM_SIGN_E2_TIMES_MI                                           0x12090  0  // 𒂐
#define UC_CUNEIFORM_SIGN_E2_TIMES_SAL                                          0x12091  0  // 𒂑
#define UC_CUNEIFORM_SIGN_E2_TIMES_SHE                                          0x12092  0  // 𒂒
#define UC_CUNEIFORM_SIGN_E2_TIMES_U                                            0x12093  0  // 𒂓
#define UC_CUNEIFORM_SIGN_EDIN                                                  0x12094  0  // 𒂔
#define UC_CUNEIFORM_SIGN_EGIR                                                  0x12095  0  // 𒂕
#define UC_CUNEIFORM_SIGN_EL                                                    0x12096  0  // 𒂖
#define UC_CUNEIFORM_SIGN_EN                                                    0x12097  0  // 𒂗
#define UC_CUNEIFORM_SIGN_EN_TIMES_GAN2                                         0x12098  0  // 𒂘
#define UC_CUNEIFORM_SIGN_EN_TIMES_GAN2_TENU                                    0x12099  0  // 𒂙
#define UC_CUNEIFORM_SIGN_EN_TIMES_ME                                           0x1209A  0  // 𒂚
#define UC_CUNEIFORM_SIGN_EN_CROSSING_EN                                        0x1209B  0  // 𒂛
#define UC_CUNEIFORM_SIGN_EN_OPPOSING_EN                                        0x1209C  0  // 𒂜
#define UC_CUNEIFORM_SIGN_EN_SQUARED                                            0x1209D  0  // 𒂝
#define UC_CUNEIFORM_SIGN_EREN                                                  0x1209E  0  // 𒂞
#define UC_CUNEIFORM_SIGN_ERIN2                                                 0x1209F  0  // 𒂟
#define UC_CUNEIFORM_SIGN_ESH2                                                  0x120A0  0  // 𒂠
#define UC_CUNEIFORM_SIGN_EZEN                                                  0x120A1  0  // 𒂡
#define UC_CUNEIFORM_SIGN_EZEN_TIMES_A                                          0x120A2  0  // 𒂢
#define UC_CUNEIFORM_SIGN_EZEN_TIMES_A_PLUS_LAL                                 0x120A3  0  // 𒂣
#define UC_CUNEIFORM_SIGN_EZEN_TIMES_A_PLUS_LAL_TIMES_LAL                       0x120A4  0  // 𒂤
#define UC_CUNEIFORM_SIGN_EZEN_TIMES_AN                                         0x120A5  0  // 𒂥
#define UC_CUNEIFORM_SIGN_EZEN_TIMES_BAD                                        0x120A6  0  // 𒂦
#define UC_CUNEIFORM_SIGN_EZEN_TIMES_DUN3_GUNU                                  0x120A7  0  // 𒂧
#define UC_CUNEIFORM_SIGN_EZEN_TIMES_DUN3_GUNU_GUNU                             0x120A8  0  // 𒂨
#define UC_CUNEIFORM_SIGN_EZEN_TIMES_HA                                         0x120A9  0  // 𒂩
#define UC_CUNEIFORM_SIGN_EZEN_TIMES_HA_GUNU                                    0x120AA  0  // 𒂪
#define UC_CUNEIFORM_SIGN_EZEN_TIMES_IGI_GUNU                                   0x120AB  0  // 𒂫
#define UC_CUNEIFORM_SIGN_EZEN_TIMES_KASKAL                                     0x120AC  0  // 𒂬
#define UC_CUNEIFORM_SIGN_EZEN_TIMES_KASKAL_SQUARED                             0x120AD  0  // 𒂭
#define UC_CUNEIFORM_SIGN_EZEN_TIMES_KU3                                        0x120AE  0  // 𒂮
#define UC_CUNEIFORM_SIGN_EZEN_TIMES_LA                                         0x120AF  0  // 𒂯
#define UC_CUNEIFORM_SIGN_EZEN_TIMES_LAL_TIMES_LAL                              0x120B0  0  // 𒂰
#define UC_CUNEIFORM_SIGN_EZEN_TIMES_LI                                         0x120B1  0  // 𒂱
#define UC_CUNEIFORM_SIGN_EZEN_TIMES_LU                                         0x120B2  0  // 𒂲
#define UC_CUNEIFORM_SIGN_EZEN_TIMES_U2                                         0x120B3  0  // 𒂳
#define UC_CUNEIFORM_SIGN_EZEN_TIMES_UD                                         0x120B4  0  // 𒂴
#define UC_CUNEIFORM_SIGN_GA                                                    0x120B5  0  // 𒂵
#define UC_CUNEIFORM_SIGN_GA_GUNU                                               0x120B6  0  // 𒂶
#define UC_CUNEIFORM_SIGN_GA2                                                   0x120B7  0  // 𒂷
#define UC_CUNEIFORM_SIGN_GA2_TIMES_A_PLUS_DA_PLUS_HA                           0x120B8  0  // 𒂸
#define UC_CUNEIFORM_SIGN_GA2_TIMES_A_PLUS_HA                                   0x120B9  0  // 𒂹
#define UC_CUNEIFORM_SIGN_GA2_TIMES_A_PLUS_IGI                                  0x120BA  0  // 𒂺
#define UC_CUNEIFORM_SIGN_GA2_TIMES_AB2_TENU_PLUS_TAB                           0x120BB  0  // 𒂻
#define UC_CUNEIFORM_SIGN_GA2_TIMES_AN                                          0x120BC  0  // 𒂼
#define UC_CUNEIFORM_SIGN_GA2_TIMES_ASH                                         0x120BD  0  // 𒂽
#define UC_CUNEIFORM_SIGN_GA2_TIMES_ASH2_PLUS_GAL                               0x120BE  0  // 𒂾
#define UC_CUNEIFORM_SIGN_GA2_TIMES_BAD                                         0x120BF  0  // 𒂿
#define UC_CUNEIFORM_SIGN_GA2_TIMES_BAR_PLUS_RA                                 0x120C0  0  // 𒃀
#define UC_CUNEIFORM_SIGN_GA2_TIMES_BUR                                         0x120C1  0  // 𒃁
#define UC_CUNEIFORM_SIGN_GA2_TIMES_BUR_PLUS_RA                                 0x120C2  0  // 𒃂
#define UC_CUNEIFORM_SIGN_GA2_TIMES_DA                                          0x120C3  0  // 𒃃
#define UC_CUNEIFORM_SIGN_GA2_TIMES_DI                                          0x120C4  0  // 𒃄
#define UC_CUNEIFORM_SIGN_GA2_TIMES_DIM_TIMES_SHE                               0x120C5  0  // 𒃅
#define UC_CUNEIFORM_SIGN_GA2_TIMES_DUB                                         0x120C6  0  // 𒃆
#define UC_CUNEIFORM_SIGN_GA2_TIMES_EL                                          0x120C7  0  // 𒃇
#define UC_CUNEIFORM_SIGN_GA2_TIMES_EL_PLUS_LA                                  0x120C8  0  // 𒃈
#define UC_CUNEIFORM_SIGN_GA2_TIMES_EN                                          0x120C9  0  // 𒃉
#define UC_CUNEIFORM_SIGN_GA2_TIMES_EN_TIMES_GAN2_TENU                          0x120CA  0  // 𒃊
#define UC_CUNEIFORM_SIGN_GA2_TIMES_GAN2_TENU                                   0x120CB  0  // 𒃋
#define UC_CUNEIFORM_SIGN_GA2_TIMES_GAR                                         0x120CC  0  // 𒃌
#define UC_CUNEIFORM_SIGN_GA2_TIMES_GI                                          0x120CD  0  // 𒃍
#define UC_CUNEIFORM_SIGN_GA2_TIMES_GI4                                         0x120CE  0  // 𒃎
#define UC_CUNEIFORM_SIGN_GA2_TIMES_GI4_PLUS_A                                  0x120CF  0  // 𒃏
#define UC_CUNEIFORM_SIGN_GA2_TIMES_GIR2_PLUS_SU                                0x120D0  0  // 𒃐
#define UC_CUNEIFORM_SIGN_GA2_TIMES_HA_PLUS_LU_PLUS_ESH2                        0x120D1  0  // 𒃑
#define UC_CUNEIFORM_SIGN_GA2_TIMES_HAL                                         0x120D2  0  // 𒃒
#define UC_CUNEIFORM_SIGN_GA2_TIMES_HAL_PLUS_LA                                 0x120D3  0  // 𒃓
#define UC_CUNEIFORM_SIGN_GA2_TIMES_HI_PLUS_LI                                  0x120D4  0  // 𒃔
#define UC_CUNEIFORM_SIGN_GA2_TIMES_HUB2                                        0x120D5  0  // 𒃕
#define UC_CUNEIFORM_SIGN_GA2_TIMES_IGI_GUNU                                    0x120D6  0  // 𒃖
#define UC_CUNEIFORM_SIGN_GA2_TIMES_ISH_PLUS_HU_PLUS_ASH                        0x120D7  0  // 𒃗
#define UC_CUNEIFORM_SIGN_GA2_TIMES_KAK                                         0x120D8  0  // 𒃘
#define UC_CUNEIFORM_SIGN_GA2_TIMES_KASKAL                                      0x120D9  0  // 𒃙
#define UC_CUNEIFORM_SIGN_GA2_TIMES_KID                                         0x120DA  0  // 𒃚
#define UC_CUNEIFORM_SIGN_GA2_TIMES_KID_PLUS_LAL                                0x120DB  0  // 𒃛
#define UC_CUNEIFORM_SIGN_GA2_TIMES_KU3_PLUS_AN                                 0x120DC  0  // 𒃜
#define UC_CUNEIFORM_SIGN_GA2_TIMES_LA                                          0x120DD  0  // 𒃝
#define UC_CUNEIFORM_SIGN_GA2_TIMES_ME_PLUS_EN                                  0x120DE  0  // 𒃞
#define UC_CUNEIFORM_SIGN_GA2_TIMES_MI                                          0x120DF  0  // 𒃟
#define UC_CUNEIFORM_SIGN_GA2_TIMES_NUN                                         0x120E0  0  // 𒃠
#define UC_CUNEIFORM_SIGN_GA2_TIMES_NUN_OVER_NUN                                0x120E1  0  // 𒃡
#define UC_CUNEIFORM_SIGN_GA2_TIMES_PA                                          0x120E2  0  // 𒃢
#define UC_CUNEIFORM_SIGN_GA2_TIMES_SAL                                         0x120E3  0  // 𒃣
#define UC_CUNEIFORM_SIGN_GA2_TIMES_SAR                                         0x120E4  0  // 𒃤
#define UC_CUNEIFORM_SIGN_GA2_TIMES_SHE                                         0x120E5  0  // 𒃥
#define UC_CUNEIFORM_SIGN_GA2_TIMES_SHE_PLUS_TUR                                0x120E6  0  // 𒃦
#define UC_CUNEIFORM_SIGN_GA2_TIMES_SHID                                        0x120E7  0  // 𒃧
#define UC_CUNEIFORM_SIGN_GA2_TIMES_SUM                                         0x120E8  0  // 𒃨
#define UC_CUNEIFORM_SIGN_GA2_TIMES_TAK4                                        0x120E9  0  // 𒃩
#define UC_CUNEIFORM_SIGN_GA2_TIMES_U                                           0x120EA  0  // 𒃪
#define UC_CUNEIFORM_SIGN_GA2_TIMES_UD                                          0x120EB  0  // 𒃫
#define UC_CUNEIFORM_SIGN_GA2_TIMES_UD_PLUS_DU                                  0x120EC  0  // 𒃬
#define UC_CUNEIFORM_SIGN_GA2_OVER_GA2                                          0x120ED  0  // 𒃭
#define UC_CUNEIFORM_SIGN_GABA                                                  0x120EE  0  // 𒃮
#define UC_CUNEIFORM_SIGN_GABA_CROSSING_GABA                                    0x120EF  0  // 𒃯
#define UC_CUNEIFORM_SIGN_GAD                                                   0x120F0  0  // 𒃰
#define UC_CUNEIFORM_SIGN_GAD_OVER_GAD_GAR_OVER_GAR                             0x120F1  0  // 𒃱
#define UC_CUNEIFORM_SIGN_GAL                                                   0x120F2  0  // 𒃲
#define UC_CUNEIFORM_SIGN_GAL_GAD_OVER_GAD_GAR_OVER_GAR                         0x120F3  0  // 𒃳
#define UC_CUNEIFORM_SIGN_GALAM                                                 0x120F4  0  // 𒃴
#define UC_CUNEIFORM_SIGN_GAM                                                   0x120F5  0  // 𒃵
#define UC_CUNEIFORM_SIGN_GAN                                                   0x120F6  0  // 𒃶
#define UC_CUNEIFORM_SIGN_GAN2                                                  0x120F7  0  // 𒃷
#define UC_CUNEIFORM_SIGN_GAN2_TENU                                             0x120F8  0  // 𒃸
#define UC_CUNEIFORM_SIGN_GAN2_OVER_GAN2                                        0x120F9  0  // 𒃹
#define UC_CUNEIFORM_SIGN_GAN2_CROSSING_GAN2                                    0x120FA  0  // 𒃺
#define UC_CUNEIFORM_SIGN_GAR                                                   0x120FB  0  // 𒃻
#define UC_CUNEIFORM_SIGN_GAR3                                                  0x120FC  0  // 𒃼
#define UC_CUNEIFORM_SIGN_GASHAN                                                0x120FD  0  // 𒃽
#define UC_CUNEIFORM_SIGN_GESHTIN                                               0x120FE  0  // 𒃾
#define UC_CUNEIFORM_SIGN_GESHTIN_TIMES_KUR                                     0x120FF  0  // 𒃿
#define UC_CUNEIFORM_SIGN_GI                                                    0x12100  0  // 𒄀
#define UC_CUNEIFORM_SIGN_GI_TIMES_E                                            0x12101  0  // 𒄁
#define UC_CUNEIFORM_SIGN_GI_TIMES_U                                            0x12102  0  // 𒄂
#define UC_CUNEIFORM_SIGN_GI_CROSSING_GI                                        0x12103  0  // 𒄃
#define UC_CUNEIFORM_SIGN_GI4                                                   0x12104  0  // 𒄄
#define UC_CUNEIFORM_SIGN_GI4_OVER_GI4                                          0x12105  0  // 𒄅
#define UC_CUNEIFORM_SIGN_GI4_CROSSING_GI4                                      0x12106  0  // 𒄆
#define UC_CUNEIFORM_SIGN_GIDIM                                                 0x12107  0  // 𒄇
#define UC_CUNEIFORM_SIGN_GIR2                                                  0x12108  0  // 𒄈
#define UC_CUNEIFORM_SIGN_GIR2_GUNU                                             0x12109  0  // 𒄉
#define UC_CUNEIFORM_SIGN_GIR3                                                  0x1210A  0  // 𒄊
#define UC_CUNEIFORM_SIGN_GIR3_TIMES_A_PLUS_IGI                                 0x1210B  0  // 𒄋
#define UC_CUNEIFORM_SIGN_GIR3_TIMES_GAN2_TENU                                  0x1210C  0  // 𒄌
#define UC_CUNEIFORM_SIGN_GIR3_TIMES_IGI                                        0x1210D  0  // 𒄍
#define UC_CUNEIFORM_SIGN_GIR3_TIMES_LU_PLUS_IGI                                0x1210E  0  // 𒄎
#define UC_CUNEIFORM_SIGN_GIR3_TIMES_PA                                         0x1210F  0  // 𒄏
#define UC_CUNEIFORM_SIGN_GISAL                                                 0x12110  0  // 𒄐
#define UC_CUNEIFORM_SIGN_GISH                                                  0x12111  0  // 𒄑
#define UC_CUNEIFORM_SIGN_GISH_CROSSING_GISH                                    0x12112  0  // 𒄒
#define UC_CUNEIFORM_SIGN_GISH_TIMES_BAD                                        0x12113  0  // 𒄓
#define UC_CUNEIFORM_SIGN_GISH_TIMES_TAK4                                       0x12114  0  // 𒄔
#define UC_CUNEIFORM_SIGN_GISH_TENU                                             0x12115  0  // 𒄕
#define UC_CUNEIFORM_SIGN_GU                                                    0x12116  0  // 𒄖
#define UC_CUNEIFORM_SIGN_GU_CROSSING_GU                                        0x12117  0  // 𒄗
#define UC_CUNEIFORM_SIGN_GU2                                                   0x12118  0  // 𒄘
#define UC_CUNEIFORM_SIGN_GU2_TIMES_KAK                                         0x12119  0  // 𒄙
#define UC_CUNEIFORM_SIGN_GU2_TIMES_KAK_TIMES_IGI_GUNU                          0x1211A  0  // 𒄚
#define UC_CUNEIFORM_SIGN_GU2_TIMES_NUN                                         0x1211B  0  // 𒄛
#define UC_CUNEIFORM_SIGN_GU2_TIMES_SAL_PLUS_TUG2                               0x1211C  0  // 𒄜
#define UC_CUNEIFORM_SIGN_GU2_GUNU                                              0x1211D  0  // 𒄝
#define UC_CUNEIFORM_SIGN_GUD                                                   0x1211E  0  // 𒄞
#define UC_CUNEIFORM_SIGN_GUD_TIMES_A_PLUS_KUR                                  0x1211F  0  // 𒄟
#define UC_CUNEIFORM_SIGN_GUD_TIMES_KUR                                         0x12120  0  // 𒄠
#define UC_CUNEIFORM_SIGN_GUD_OVER_GUD_LUGAL                                    0x12121  0  // 𒄡
#define UC_CUNEIFORM_SIGN_GUL                                                   0x12122  0  // 𒄢
#define UC_CUNEIFORM_SIGN_GUM                                                   0x12123  0  // 𒄣
#define UC_CUNEIFORM_SIGN_GUM_TIMES_SHE                                         0x12124  0  // 𒄤
#define UC_CUNEIFORM_SIGN_GUR                                                   0x12125  0  // 𒄥
#define UC_CUNEIFORM_SIGN_GUR7                                                  0x12126  0  // 𒄦
#define UC_CUNEIFORM_SIGN_GURUN                                                 0x12127  0  // 𒄧
#define UC_CUNEIFORM_SIGN_GURUSH                                                0x12128  0  // 𒄨
#define UC_CUNEIFORM_SIGN_HA                                                    0x12129  0  // 𒄩
#define UC_CUNEIFORM_SIGN_HA_TENU                                               0x1212A  0  // 𒄪
#define UC_CUNEIFORM_SIGN_HA_GUNU                                               0x1212B  0  // 𒄫
#define UC_CUNEIFORM_SIGN_HAL                                                   0x1212C  0  // 𒄬
#define UC_CUNEIFORM_SIGN_HI                                                    0x1212D  0  // 𒄭
#define UC_CUNEIFORM_SIGN_HI_TIMES_ASH                                          0x1212E  0  // 𒄮
#define UC_CUNEIFORM_SIGN_HI_TIMES_ASH2                                         0x1212F  0  // 𒄯
#define UC_CUNEIFORM_SIGN_HI_TIMES_BAD                                          0x12130  0  // 𒄰
#define UC_CUNEIFORM_SIGN_HI_TIMES_DISH                                         0x12131  0  // 𒄱
#define UC_CUNEIFORM_SIGN_HI_TIMES_GAD                                          0x12132  0  // 𒄲
#define UC_CUNEIFORM_SIGN_HI_TIMES_KIN                                          0x12133  0  // 𒄳
#define UC_CUNEIFORM_SIGN_HI_TIMES_NUN                                          0x12134  0  // 𒄴
#define UC_CUNEIFORM_SIGN_HI_TIMES_SHE                                          0x12135  0  // 𒄵
#define UC_CUNEIFORM_SIGN_HI_TIMES_U                                            0x12136  0  // 𒄶
#define UC_CUNEIFORM_SIGN_HU                                                    0x12137  0  // 𒄷
#define UC_CUNEIFORM_SIGN_HUB2                                                  0x12138  0  // 𒄸
#define UC_CUNEIFORM_SIGN_HUB2_TIMES_AN                                         0x12139  0  // 𒄹
#define UC_CUNEIFORM_SIGN_HUB2_TIMES_HAL                                        0x1213A  0  // 𒄺
#define UC_CUNEIFORM_SIGN_HUB2_TIMES_KASKAL                                     0x1213B  0  // 𒄻
#define UC_CUNEIFORM_SIGN_HUB2_TIMES_LISH                                       0x1213C  0  // 𒄼
#define UC_CUNEIFORM_SIGN_HUB2_TIMES_UD                                         0x1213D  0  // 𒄽
#define UC_CUNEIFORM_SIGN_HUL2                                                  0x1213E  0  // 𒄾
#define UC_CUNEIFORM_SIGN_I                                                     0x1213F  0  // 𒄿
#define UC_CUNEIFORM_SIGN_I_A                                                   0x12140  0  // 𒅀
#define UC_CUNEIFORM_SIGN_IB                                                    0x12141  0  // 𒅁
#define UC_CUNEIFORM_SIGN_IDIM                                                  0x12142  0  // 𒅂
#define UC_CUNEIFORM_SIGN_IDIM_OVER_IDIM_BUR                                    0x12143  0  // 𒅃
#define UC_CUNEIFORM_SIGN_IDIM_OVER_IDIM_SQUARED                                0x12144  0  // 𒅄
#define UC_CUNEIFORM_SIGN_IG                                                    0x12145  0  // 𒅅
#define UC_CUNEIFORM_SIGN_IGI                                                   0x12146  0  // 𒅆
#define UC_CUNEIFORM_SIGN_IGI_DIB                                               0x12147  0  // 𒅇
#define UC_CUNEIFORM_SIGN_IGI_RI                                                0x12148  0  // 𒅈
#define UC_CUNEIFORM_SIGN_IGI_OVER_IGI_SHIR_OVER_SHIR_UD_OVER_UD                0x12149  0  // 𒅉
#define UC_CUNEIFORM_SIGN_IGI_GUNU                                              0x1214A  0  // 𒅊
#define UC_CUNEIFORM_SIGN_IL                                                    0x1214B  0  // 𒅋
#define UC_CUNEIFORM_SIGN_IL_TIMES_GAN2_TENU                                    0x1214C  0  // 𒅌
#define UC_CUNEIFORM_SIGN_IL2                                                   0x1214D  0  // 𒅍
#define UC_CUNEIFORM_SIGN_IM                                                    0x1214E  0  // 𒅎
#define UC_CUNEIFORM_SIGN_IM_TIMES_TAK4                                         0x1214F  0  // 𒅏
#define UC_CUNEIFORM_SIGN_IM_CROSSING_IM                                        0x12150  0  // 𒅐
#define UC_CUNEIFORM_SIGN_IM_OPPOSING_IM                                        0x12151  0  // 𒅑
#define UC_CUNEIFORM_SIGN_IM_SQUARED                                            0x12152  0  // 𒅒
#define UC_CUNEIFORM_SIGN_IMIN                                                  0x12153  0  // 𒅓
#define UC_CUNEIFORM_SIGN_IN                                                    0x12154  0  // 𒅔
#define UC_CUNEIFORM_SIGN_IR                                                    0x12155  0  // 𒅕
#define UC_CUNEIFORM_SIGN_ISH                                                   0x12156  0  // 𒅖
#define UC_CUNEIFORM_SIGN_KA                                                    0x12157  0  // 𒅗
#define UC_CUNEIFORM_SIGN_KA_TIMES_A                                            0x12158  0  // 𒅘
#define UC_CUNEIFORM_SIGN_KA_TIMES_AD                                           0x12159  0  // 𒅙
#define UC_CUNEIFORM_SIGN_KA_TIMES_AD_PLUS_KU3                                  0x1215A  0  // 𒅚
#define UC_CUNEIFORM_SIGN_KA_TIMES_ASH2                                         0x1215B  0  // 𒅛
#define UC_CUNEIFORM_SIGN_KA_TIMES_BAD                                          0x1215C  0  // 𒅜
#define UC_CUNEIFORM_SIGN_KA_TIMES_BALAG                                        0x1215D  0  // 𒅝
#define UC_CUNEIFORM_SIGN_KA_TIMES_BAR                                          0x1215E  0  // 𒅞
#define UC_CUNEIFORM_SIGN_KA_TIMES_BI                                           0x1215F  0  // 𒅟
#define UC_CUNEIFORM_SIGN_KA_TIMES_ERIN2                                        0x12160  0  // 𒅠
#define UC_CUNEIFORM_SIGN_KA_TIMES_ESH2                                         0x12161  0  // 𒅡
#define UC_CUNEIFORM_SIGN_KA_TIMES_GA                                           0x12162  0  // 𒅢
#define UC_CUNEIFORM_SIGN_KA_TIMES_GAL                                          0x12163  0  // 𒅣
#define UC_CUNEIFORM_SIGN_KA_TIMES_GAN2_TENU                                    0x12164  0  // 𒅤
#define UC_CUNEIFORM_SIGN_KA_TIMES_GAR                                          0x12165  0  // 𒅥
#define UC_CUNEIFORM_SIGN_KA_TIMES_GAR_PLUS_SHA3_PLUS_A                         0x12166  0  // 𒅦
#define UC_CUNEIFORM_SIGN_KA_TIMES_GI                                           0x12167  0  // 𒅧
#define UC_CUNEIFORM_SIGN_KA_TIMES_GIR2                                         0x12168  0  // 𒅨
#define UC_CUNEIFORM_SIGN_KA_TIMES_GISH_PLUS_SAR                                0x12169  0  // 𒅩
#define UC_CUNEIFORM_SIGN_KA_TIMES_GISH_CROSSING_GISH                           0x1216A  0  // 𒅪
#define UC_CUNEIFORM_SIGN_KA_TIMES_GU                                           0x1216B  0  // 𒅫
#define UC_CUNEIFORM_SIGN_KA_TIMES_GUR7                                         0x1216C  0  // 𒅬
#define UC_CUNEIFORM_SIGN_KA_TIMES_IGI                                          0x1216D  0  // 𒅭
#define UC_CUNEIFORM_SIGN_KA_TIMES_IM                                           0x1216E  0  // 𒅮
#define UC_CUNEIFORM_SIGN_KA_TIMES_KAK                                          0x1216F  0  // 𒅯
#define UC_CUNEIFORM_SIGN_KA_TIMES_KI                                           0x12170  0  // 𒅰
#define UC_CUNEIFORM_SIGN_KA_TIMES_KID                                          0x12171  0  // 𒅱
#define UC_CUNEIFORM_SIGN_KA_TIMES_LI                                           0x12172  0  // 𒅲
#define UC_CUNEIFORM_SIGN_KA_TIMES_LU                                           0x12173  0  // 𒅳
#define UC_CUNEIFORM_SIGN_KA_TIMES_ME                                           0x12174  0  // 𒅴
#define UC_CUNEIFORM_SIGN_KA_TIMES_ME_PLUS_DU                                   0x12175  0  // 𒅵
#define UC_CUNEIFORM_SIGN_KA_TIMES_ME_PLUS_GI                                   0x12176  0  // 𒅶
#define UC_CUNEIFORM_SIGN_KA_TIMES_ME_PLUS_TE                                   0x12177  0  // 𒅷
#define UC_CUNEIFORM_SIGN_KA_TIMES_MI                                           0x12178  0  // 𒅸
#define UC_CUNEIFORM_SIGN_KA_TIMES_MI_PLUS_NUNUZ                                0x12179  0  // 𒅹
#define UC_CUNEIFORM_SIGN_KA_TIMES_NE                                           0x1217A  0  // 𒅺
#define UC_CUNEIFORM_SIGN_KA_TIMES_NUN                                          0x1217B  0  // 𒅻
#define UC_CUNEIFORM_SIGN_KA_TIMES_PI                                           0x1217C  0  // 𒅼
#define UC_CUNEIFORM_SIGN_KA_TIMES_RU                                           0x1217D  0  // 𒅽
#define UC_CUNEIFORM_SIGN_KA_TIMES_SA                                           0x1217E  0  // 𒅾
#define UC_CUNEIFORM_SIGN_KA_TIMES_SAR                                          0x1217F  0  // 𒅿
#define UC_CUNEIFORM_SIGN_KA_TIMES_SHA                                          0x12180  0  // 𒆀
#define UC_CUNEIFORM_SIGN_KA_TIMES_SHE                                          0x12181  0  // 𒆁
#define UC_CUNEIFORM_SIGN_KA_TIMES_SHID                                         0x12182  0  // 𒆂
#define UC_CUNEIFORM_SIGN_KA_TIMES_SHU                                          0x12183  0  // 𒆃
#define UC_CUNEIFORM_SIGN_KA_TIMES_SIG                                          0x12184  0  // 𒆄
#define UC_CUNEIFORM_SIGN_KA_TIMES_SUHUR                                        0x12185  0  // 𒆅
#define UC_CUNEIFORM_SIGN_KA_TIMES_TAR                                          0x12186  0  // 𒆆
#define UC_CUNEIFORM_SIGN_KA_TIMES_U                                            0x12187  0  // 𒆇
#define UC_CUNEIFORM_SIGN_KA_TIMES_U2                                           0x12188  0  // 𒆈
#define UC_CUNEIFORM_SIGN_KA_TIMES_UD                                           0x12189  0  // 𒆉
#define UC_CUNEIFORM_SIGN_KA_TIMES_UMUM_TIMES_PA                                0x1218A  0  // 𒆊
#define UC_CUNEIFORM_SIGN_KA_TIMES_USH                                          0x1218B  0  // 𒆋
#define UC_CUNEIFORM_SIGN_KA_TIMES_ZI                                           0x1218C  0  // 𒆌
#define UC_CUNEIFORM_SIGN_KA2                                                   0x1218D  0  // 𒆍
#define UC_CUNEIFORM_SIGN_KA2_CROSSING_KA2                                      0x1218E  0  // 𒆎
#define UC_CUNEIFORM_SIGN_KAB                                                   0x1218F  0  // 𒆏
#define UC_CUNEIFORM_SIGN_KAD2                                                  0x12190  0  // 𒆐
#define UC_CUNEIFORM_SIGN_KAD3                                                  0x12191  0  // 𒆑
#define UC_CUNEIFORM_SIGN_KAD4                                                  0x12192  0  // 𒆒
#define UC_CUNEIFORM_SIGN_KAD5                                                  0x12193  0  // 𒆓
#define UC_CUNEIFORM_SIGN_KAD5_OVER_KAD5                                        0x12194  0  // 𒆔
#define UC_CUNEIFORM_SIGN_KAK                                                   0x12195  0  // 𒆕
#define UC_CUNEIFORM_SIGN_KAK_TIMES_IGI_GUNU                                    0x12196  0  // 𒆖
#define UC_CUNEIFORM_SIGN_KAL                                                   0x12197  0  // 𒆗
#define UC_CUNEIFORM_SIGN_KAL_TIMES_BAD                                         0x12198  0  // 𒆘
#define UC_CUNEIFORM_SIGN_KAL_CROSSING_KAL                                      0x12199  0  // 𒆙
#define UC_CUNEIFORM_SIGN_KAM2                                                  0x1219A  0  // 𒆚
#define UC_CUNEIFORM_SIGN_KAM4                                                  0x1219B  0  // 𒆛
#define UC_CUNEIFORM_SIGN_KASKAL                                                0x1219C  0  // 𒆜
#define UC_CUNEIFORM_SIGN_KASKAL_LAGAB_TIMES_U_OVER_LAGAB_TIMES_U               0x1219D  0  // 𒆝
#define UC_CUNEIFORM_SIGN_KASKAL_OVER_KASKAL_LAGAB_TIMES_U_OVER_LAGAB_TIMES_U   0x1219E  0  // 𒆞
#define UC_CUNEIFORM_SIGN_KESH2                                                 0x1219F  0  // 𒆟
#define UC_CUNEIFORM_SIGN_KI                                                    0x121A0  0  // 𒆠
#define UC_CUNEIFORM_SIGN_KI_TIMES_BAD                                          0x121A1  0  // 𒆡
#define UC_CUNEIFORM_SIGN_KI_TIMES_U                                            0x121A2  0  // 𒆢
#define UC_CUNEIFORM_SIGN_KI_TIMES_UD                                           0x121A3  0  // 𒆣
#define UC_CUNEIFORM_SIGN_KID                                                   0x121A4  0  // 𒆤
#define UC_CUNEIFORM_SIGN_KIN                                                   0x121A5  0  // 𒆥
#define UC_CUNEIFORM_SIGN_KISAL                                                 0x121A6  0  // 𒆦
#define UC_CUNEIFORM_SIGN_KISH                                                  0x121A7  0  // 𒆧
#define UC_CUNEIFORM_SIGN_KISIM5                                                0x121A8  0  // 𒆨
#define UC_CUNEIFORM_SIGN_KISIM5_OVER_KISIM5                                    0x121A9  0  // 𒆩
#define UC_CUNEIFORM_SIGN_KU                                                    0x121AA  0  // 𒆪
#define UC_CUNEIFORM_SIGN_KU_OVER_HI_TIMES_ASH2_KU_OVER_HI_TIMES_ASH2           0x121AB  0  // 𒆫
#define UC_CUNEIFORM_SIGN_KU3                                                   0x121AC  0  // 𒆬
#define UC_CUNEIFORM_SIGN_KU4                                                   0x121AD  0  // 𒆭
#define UC_CUNEIFORM_SIGN_KU4_VARIANT_FORM                                      0x121AE  0  // 𒆮
#define UC_CUNEIFORM_SIGN_KU7                                                   0x121AF  0  // 𒆯
#define UC_CUNEIFORM_SIGN_KUL                                                   0x121B0  0  // 𒆰
#define UC_CUNEIFORM_SIGN_KUL_GUNU                                              0x121B1  0  // 𒆱
#define UC_CUNEIFORM_SIGN_KUN                                                   0x121B2  0  // 𒆲
#define UC_CUNEIFORM_SIGN_KUR                                                   0x121B3  0  // 𒆳
#define UC_CUNEIFORM_SIGN_KUR_OPPOSING_KUR                                      0x121B4  0  // 𒆴
#define UC_CUNEIFORM_SIGN_KUSHU2                                                0x121B5  0  // 𒆵
#define UC_CUNEIFORM_SIGN_KWU318                                                0x121B6  0  // 𒆶
#define UC_CUNEIFORM_SIGN_LA                                                    0x121B7  0  // 𒆷
#define UC_CUNEIFORM_SIGN_LAGAB                                                 0x121B8  0  // 𒆸
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_A                                         0x121B9  0  // 𒆹
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_A_PLUS_DA_PLUS_HA                         0x121BA  0  // 𒆺
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_A_PLUS_GAR                                0x121BB  0  // 𒆻
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_A_PLUS_LAL                                0x121BC  0  // 𒆼
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_AL                                        0x121BD  0  // 𒆽
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_AN                                        0x121BE  0  // 𒆾
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_ASH_ZIDA_TENU                             0x121BF  0  // 𒆿
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_BAD                                       0x121C0  0  // 𒇀
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_BI                                        0x121C1  0  // 𒇁
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_DAR                                       0x121C2  0  // 𒇂
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_EN                                        0x121C3  0  // 𒇃
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_GA                                        0x121C4  0  // 𒇄
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_GAR                                       0x121C5  0  // 𒇅
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_GUD                                       0x121C6  0  // 𒇆
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_GUD_PLUS_GUD                              0x121C7  0  // 𒇇
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_HA                                        0x121C8  0  // 𒇈
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_HAL                                       0x121C9  0  // 𒇉
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_HI_TIMES_NUN                              0x121CA  0  // 𒇊
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_IGI_GUNU                                  0x121CB  0  // 𒇋
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_IM                                        0x121CC  0  // 𒇌
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_IM_PLUS_HA                                0x121CD  0  // 𒇍
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_IM_PLUS_LU                                0x121CE  0  // 𒇎
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_KI                                        0x121CF  0  // 𒇏
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_KIN                                       0x121D0  0  // 𒇐
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_KU3                                       0x121D1  0  // 𒇑
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_KUL                                       0x121D2  0  // 𒇒
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_KUL_PLUS_HI_PLUS_A                        0x121D3  0  // 𒇓
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_LAGAB                                     0x121D4  0  // 𒇔
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_LISH                                      0x121D5  0  // 𒇕
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_LU                                        0x121D6  0  // 𒇖
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_LUL                                       0x121D7  0  // 𒇗
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_ME                                        0x121D8  0  // 𒇘
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_ME_PLUS_EN                                0x121D9  0  // 𒇙
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_MUSH                                      0x121DA  0  // 𒇚
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_NE                                        0x121DB  0  // 𒇛
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_SHE_PLUS_SUM                              0x121DC  0  // 𒇜
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_SHITA_PLUS_GISH_PLUS_ERIN2                0x121DD  0  // 𒇝
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_SHITA_PLUS_GISH_TENU                      0x121DE  0  // 𒇞
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_SHU2                                      0x121DF  0  // 𒇟
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_SHU2_PLUS_SHU2                            0x121E0  0  // 𒇠
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_SUM                                       0x121E1  0  // 𒇡
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_TAG                                       0x121E2  0  // 𒇢
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_TAK4                                      0x121E3  0  // 𒇣
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_TE_PLUS_A_PLUS_SU_PLUS_NA                 0x121E4  0  // 𒇤
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_U                                         0x121E5  0  // 𒇥
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_U_PLUS_A                                  0x121E6  0  // 𒇦
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_U_PLUS_U_PLUS_U                           0x121E7  0  // 𒇧
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_U2_PLUS_ASH                               0x121E8  0  // 𒇨
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_UD                                        0x121E9  0  // 𒇩
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_USH                                       0x121EA  0  // 𒇪
#define UC_CUNEIFORM_SIGN_LAGAB_SQUARED                                         0x121EB  0  // 𒇫
#define UC_CUNEIFORM_SIGN_LAGAR                                                 0x121EC  0  // 𒇬
#define UC_CUNEIFORM_SIGN_LAGAR_TIMES_SHE                                       0x121ED  0  // 𒇭
#define UC_CUNEIFORM_SIGN_LAGAR_TIMES_SHE_PLUS_SUM                              0x121EE  0  // 𒇮
#define UC_CUNEIFORM_SIGN_LAGAR_GUNU                                            0x121EF  0  // 𒇯
#define UC_CUNEIFORM_SIGN_LAGAR_GUNU_OVER_LAGAR_GUNU_SHE                        0x121F0  0  // 𒇰
#define UC_CUNEIFORM_SIGN_LAHSHU                                                0x121F1  0  // 𒇱
#define UC_CUNEIFORM_SIGN_LAL                                                   0x121F2  0  // 𒇲
#define UC_CUNEIFORM_SIGN_LAL_TIMES_LAL                                         0x121F3  0  // 𒇳
#define UC_CUNEIFORM_SIGN_LAM                                                   0x121F4  0  // 𒇴
#define UC_CUNEIFORM_SIGN_LAM_TIMES_KUR                                         0x121F5  0  // 𒇵
#define UC_CUNEIFORM_SIGN_LAM_TIMES_KUR_PLUS_RU                                 0x121F6  0  // 𒇶
#define UC_CUNEIFORM_SIGN_LI                                                    0x121F7  0  // 𒇷
#define UC_CUNEIFORM_SIGN_LIL                                                   0x121F8  0  // 𒇸
#define UC_CUNEIFORM_SIGN_LIMMU2                                                0x121F9  0  // 𒇹
#define UC_CUNEIFORM_SIGN_LISH                                                  0x121FA  0  // 𒇺
#define UC_CUNEIFORM_SIGN_LU                                                    0x121FB  0  // 𒇻
#define UC_CUNEIFORM_SIGN_LU_TIMES_BAD                                          0x121FC  0  // 𒇼
#define UC_CUNEIFORM_SIGN_LU2                                                   0x121FD  0  // 𒇽
#define UC_CUNEIFORM_SIGN_LU2_TIMES_AL                                          0x121FE  0  // 𒇾
#define UC_CUNEIFORM_SIGN_LU2_TIMES_BAD                                         0x121FF  0  // 𒇿
#define UC_CUNEIFORM_SIGN_LU2_TIMES_ESH2                                        0x12200  0  // 𒈀
#define UC_CUNEIFORM_SIGN_LU2_TIMES_ESH2_TENU                                   0x12201  0  // 𒈁
#define UC_CUNEIFORM_SIGN_LU2_TIMES_GAN2_TENU                                   0x12202  0  // 𒈂
#define UC_CUNEIFORM_SIGN_LU2_TIMES_HI_TIMES_BAD                                0x12203  0  // 𒈃
#define UC_CUNEIFORM_SIGN_LU2_TIMES_IM                                          0x12204  0  // 𒈄
#define UC_CUNEIFORM_SIGN_LU2_TIMES_KAD2                                        0x12205  0  // 𒈅
#define UC_CUNEIFORM_SIGN_LU2_TIMES_KAD3                                        0x12206  0  // 𒈆
#define UC_CUNEIFORM_SIGN_LU2_TIMES_KAD3_PLUS_ASH                               0x12207  0  // 𒈇
#define UC_CUNEIFORM_SIGN_LU2_TIMES_KI                                          0x12208  0  // 𒈈
#define UC_CUNEIFORM_SIGN_LU2_TIMES_LA_PLUS_ASH                                 0x12209  0  // 𒈉
#define UC_CUNEIFORM_SIGN_LU2_TIMES_LAGAB                                       0x1220A  0  // 𒈊
#define UC_CUNEIFORM_SIGN_LU2_TIMES_ME_PLUS_EN                                  0x1220B  0  // 𒈋
#define UC_CUNEIFORM_SIGN_LU2_TIMES_NE                                          0x1220C  0  // 𒈌
#define UC_CUNEIFORM_SIGN_LU2_TIMES_NU                                          0x1220D  0  // 𒈍
#define UC_CUNEIFORM_SIGN_LU2_TIMES_SI_PLUS_ASH                                 0x1220E  0  // 𒈎
#define UC_CUNEIFORM_SIGN_LU2_TIMES_SIK2_PLUS_BU                                0x1220F  0  // 𒈏
#define UC_CUNEIFORM_SIGN_LU2_TIMES_TUG2                                        0x12210  0  // 𒈐
#define UC_CUNEIFORM_SIGN_LU2_TENU                                              0x12211  0  // 𒈑
#define UC_CUNEIFORM_SIGN_LU2_CROSSING_LU2                                      0x12212  0  // 𒈒
#define UC_CUNEIFORM_SIGN_LU2_OPPOSING_LU2                                      0x12213  0  // 𒈓
#define UC_CUNEIFORM_SIGN_LU2_SQUARED                                           0x12214  0  // 𒈔
#define UC_CUNEIFORM_SIGN_LU2_SHESHIG                                           0x12215  0  // 𒈕
#define UC_CUNEIFORM_SIGN_LU3                                                   0x12216  0  // 𒈖
#define UC_CUNEIFORM_SIGN_LUGAL                                                 0x12217  0  // 𒈗
#define UC_CUNEIFORM_SIGN_LUGAL_OVER_LUGAL                                      0x12218  0  // 𒈘
#define UC_CUNEIFORM_SIGN_LUGAL_OPPOSING_LUGAL                                  0x12219  0  // 𒈙
#define UC_CUNEIFORM_SIGN_LUGAL_SHESHIG                                         0x1221A  0  // 𒈚
#define UC_CUNEIFORM_SIGN_LUH                                                   0x1221B  0  // 𒈛
#define UC_CUNEIFORM_SIGN_LUL                                                   0x1221C  0  // 𒈜
#define UC_CUNEIFORM_SIGN_LUM                                                   0x1221D  0  // 𒈝
#define UC_CUNEIFORM_SIGN_LUM_OVER_LUM                                          0x1221E  0  // 𒈞
#define UC_CUNEIFORM_SIGN_LUM_OVER_LUM_GAR_OVER_GAR                             0x1221F  0  // 𒈟
#define UC_CUNEIFORM_SIGN_MA                                                    0x12220  0  // 𒈠
#define UC_CUNEIFORM_SIGN_MA_TIMES_TAK4                                         0x12221  0  // 𒈡
#define UC_CUNEIFORM_SIGN_MA_GUNU                                               0x12222  0  // 𒈢
#define UC_CUNEIFORM_SIGN_MA2                                                   0x12223  0  // 𒈣
#define UC_CUNEIFORM_SIGN_MAH                                                   0x12224  0  // 𒈤
#define UC_CUNEIFORM_SIGN_MAR                                                   0x12225  0  // 𒈥
#define UC_CUNEIFORM_SIGN_MASH                                                  0x12226  0  // 𒈦
#define UC_CUNEIFORM_SIGN_MASH2                                                 0x12227  0  // 𒈧
#define UC_CUNEIFORM_SIGN_ME                                                    0x12228  0  // 𒈨
#define UC_CUNEIFORM_SIGN_MES                                                   0x12229  0  // 𒈩
#define UC_CUNEIFORM_SIGN_MI                                                    0x1222A  0  // 𒈪
#define UC_CUNEIFORM_SIGN_MIN                                                   0x1222B  0  // 𒈫
#define UC_CUNEIFORM_SIGN_MU                                                    0x1222C  0  // 𒈬
#define UC_CUNEIFORM_SIGN_MU_OVER_MU                                            0x1222D  0  // 𒈭
#define UC_CUNEIFORM_SIGN_MUG                                                   0x1222E  0  // 𒈮
#define UC_CUNEIFORM_SIGN_MUG_GUNU                                              0x1222F  0  // 𒈯
#define UC_CUNEIFORM_SIGN_MUNSUB                                                0x12230  0  // 𒈰
#define UC_CUNEIFORM_SIGN_MURGU2                                                0x12231  0  // 𒈱
#define UC_CUNEIFORM_SIGN_MUSH                                                  0x12232  0  // 𒈲
#define UC_CUNEIFORM_SIGN_MUSH_TIMES_A                                          0x12233  0  // 𒈳
#define UC_CUNEIFORM_SIGN_MUSH_TIMES_KUR                                        0x12234  0  // 𒈴
#define UC_CUNEIFORM_SIGN_MUSH_TIMES_ZA                                         0x12235  0  // 𒈵
#define UC_CUNEIFORM_SIGN_MUSH_OVER_MUSH                                        0x12236  0  // 𒈶
#define UC_CUNEIFORM_SIGN_MUSH_OVER_MUSH_TIMES_A_PLUS_NA                        0x12237  0  // 𒈷
#define UC_CUNEIFORM_SIGN_MUSH_CROSSING_MUSH                                    0x12238  0  // 𒈸
#define UC_CUNEIFORM_SIGN_MUSH3                                                 0x12239  0  // 𒈹
#define UC_CUNEIFORM_SIGN_MUSH3_TIMES_A                                         0x1223A  0  // 𒈺
#define UC_CUNEIFORM_SIGN_MUSH3_TIMES_A_PLUS_DI                                 0x1223B  0  // 𒈻
#define UC_CUNEIFORM_SIGN_MUSH3_TIMES_DI                                        0x1223C  0  // 𒈼
#define UC_CUNEIFORM_SIGN_MUSH3_GUNU                                            0x1223D  0  // 𒈽
#define UC_CUNEIFORM_SIGN_NA                                                    0x1223E  0  // 𒈾
#define UC_CUNEIFORM_SIGN_NA2                                                   0x1223F  0  // 𒈿
#define UC_CUNEIFORM_SIGN_NAGA                                                  0x12240  0  // 𒉀
#define UC_CUNEIFORM_SIGN_NAGA_INVERTED                                         0x12241  0  // 𒉁
#define UC_CUNEIFORM_SIGN_NAGA_TIMES_SHU_TENU                                   0x12242  0  // 𒉂
#define UC_CUNEIFORM_SIGN_NAGA_OPPOSING_NAGA                                    0x12243  0  // 𒉃
#define UC_CUNEIFORM_SIGN_NAGAR                                                 0x12244  0  // 𒉄
#define UC_CUNEIFORM_SIGN_NAM_NUTILLU                                           0x12245  0  // 𒉅
#define UC_CUNEIFORM_SIGN_NAM                                                   0x12246  0  // 𒉆
#define UC_CUNEIFORM_SIGN_NAM2                                                  0x12247  0  // 𒉇
#define UC_CUNEIFORM_SIGN_NE                                                    0x12248  0  // 𒉈
#define UC_CUNEIFORM_SIGN_NE_TIMES_A                                            0x12249  0  // 𒉉
#define UC_CUNEIFORM_SIGN_NE_TIMES_UD                                           0x1224A  0  // 𒉊
#define UC_CUNEIFORM_SIGN_NE_SHESHIG                                            0x1224B  0  // 𒉋
#define UC_CUNEIFORM_SIGN_NI                                                    0x1224C  0  // 𒉌
#define UC_CUNEIFORM_SIGN_NI_TIMES_E                                            0x1224D  0  // 𒉍
#define UC_CUNEIFORM_SIGN_NI2                                                   0x1224E  0  // 𒉎
#define UC_CUNEIFORM_SIGN_NIM                                                   0x1224F  0  // 𒉏
#define UC_CUNEIFORM_SIGN_NIM_TIMES_GAN2_TENU                                   0x12250  0  // 𒉐
#define UC_CUNEIFORM_SIGN_NIM_TIMES_GAR_PLUS_GAN2_TENU                          0x12251  0  // 𒉑
#define UC_CUNEIFORM_SIGN_NINDA2                                                0x12252  0  // 𒉒
#define UC_CUNEIFORM_SIGN_NINDA2_TIMES_AN                                       0x12253  0  // 𒉓
#define UC_CUNEIFORM_SIGN_NINDA2_TIMES_ASH                                      0x12254  0  // 𒉔
#define UC_CUNEIFORM_SIGN_NINDA2_TIMES_ASH_PLUS_ASH                             0x12255  0  // 𒉕
#define UC_CUNEIFORM_SIGN_NINDA2_TIMES_GUD                                      0x12256  0  // 𒉖
#define UC_CUNEIFORM_SIGN_NINDA2_TIMES_ME_PLUS_GAN2_TENU                        0x12257  0  // 𒉗
#define UC_CUNEIFORM_SIGN_NINDA2_TIMES_NE                                       0x12258  0  // 𒉘
#define UC_CUNEIFORM_SIGN_NINDA2_TIMES_NUN                                      0x12259  0  // 𒉙
#define UC_CUNEIFORM_SIGN_NINDA2_TIMES_SHE                                      0x1225A  0  // 𒉚
#define UC_CUNEIFORM_SIGN_NINDA2_TIMES_SHE_PLUS_A_AN                            0x1225B  0  // 𒉛
#define UC_CUNEIFORM_SIGN_NINDA2_TIMES_SHE_PLUS_ASH                             0x1225C  0  // 𒉜
#define UC_CUNEIFORM_SIGN_NINDA2_TIMES_SHE_PLUS_ASH_PLUS_ASH                    0x1225D  0  // 𒉝
#define UC_CUNEIFORM_SIGN_NINDA2_TIMES_U2_PLUS_ASH                              0x1225E  0  // 𒉞
#define UC_CUNEIFORM_SIGN_NINDA2_TIMES_USH                                      0x1225F  0  // 𒉟
#define UC_CUNEIFORM_SIGN_NISAG                                                 0x12260  0  // 𒉠
#define UC_CUNEIFORM_SIGN_NU                                                    0x12261  0  // 𒉡
#define UC_CUNEIFORM_SIGN_NU11                                                  0x12262  0  // 𒉢
#define UC_CUNEIFORM_SIGN_NUN                                                   0x12263  0  // 𒉣
#define UC_CUNEIFORM_SIGN_NUN_LAGAR_TIMES_GAR                                   0x12264  0  // 𒉤
#define UC_CUNEIFORM_SIGN_NUN_LAGAR_TIMES_MASH                                  0x12265  0  // 𒉥
#define UC_CUNEIFORM_SIGN_NUN_LAGAR_TIMES_SAL                                   0x12266  0  // 𒉦
#define UC_CUNEIFORM_SIGN_NUN_LAGAR_TIMES_SAL_OVER_NUN_LAGAR_TIMES_SAL          0x12267  0  // 𒉧
#define UC_CUNEIFORM_SIGN_NUN_LAGAR_TIMES_USH                                   0x12268  0  // 𒉨
#define UC_CUNEIFORM_SIGN_NUN_TENU                                              0x12269  0  // 𒉩
#define UC_CUNEIFORM_SIGN_NUN_OVER_NUN                                          0x1226A  0  // 𒉪
#define UC_CUNEIFORM_SIGN_NUN_CROSSING_NUN                                      0x1226B  0  // 𒉫
#define UC_CUNEIFORM_SIGN_NUN_CROSSING_NUN_LAGAR_OVER_LAGAR                     0x1226C  0  // 𒉬
#define UC_CUNEIFORM_SIGN_NUNUZ                                                 0x1226D  0  // 𒉭
#define UC_CUNEIFORM_SIGN_NUNUZ_AB2_TIMES_ASHGAB                                0x1226E  0  // 𒉮
#define UC_CUNEIFORM_SIGN_NUNUZ_AB2_TIMES_BI                                    0x1226F  0  // 𒉯
#define UC_CUNEIFORM_SIGN_NUNUZ_AB2_TIMES_DUG                                   0x12270  0  // 𒉰
#define UC_CUNEIFORM_SIGN_NUNUZ_AB2_TIMES_GUD                                   0x12271  0  // 𒉱
#define UC_CUNEIFORM_SIGN_NUNUZ_AB2_TIMES_IGI_GUNU                              0x12272  0  // 𒉲
#define UC_CUNEIFORM_SIGN_NUNUZ_AB2_TIMES_KAD3                                  0x12273  0  // 𒉳
#define UC_CUNEIFORM_SIGN_NUNUZ_AB2_TIMES_LA                                    0x12274  0  // 𒉴
#define UC_CUNEIFORM_SIGN_NUNUZ_AB2_TIMES_NE                                    0x12275  0  // 𒉵
#define UC_CUNEIFORM_SIGN_NUNUZ_AB2_TIMES_SILA3                                 0x12276  0  // 𒉶
#define UC_CUNEIFORM_SIGN_NUNUZ_AB2_TIMES_U2                                    0x12277  0  // 𒉷
#define UC_CUNEIFORM_SIGN_NUNUZ_KISIM5_TIMES_BI                                 0x12278  0  // 𒉸
#define UC_CUNEIFORM_SIGN_NUNUZ_KISIM5_TIMES_BI_U                               0x12279  0  // 𒉹
#define UC_CUNEIFORM_SIGN_PA                                                    0x1227A  0  // 𒉺
#define UC_CUNEIFORM_SIGN_PAD                                                   0x1227B  0  // 𒉻
#define UC_CUNEIFORM_SIGN_PAN                                                   0x1227C  0  // 𒉼
#define UC_CUNEIFORM_SIGN_PAP                                                   0x1227D  0  // 𒉽
#define UC_CUNEIFORM_SIGN_PESH2                                                 0x1227E  0  // 𒉾
#define UC_CUNEIFORM_SIGN_PI                                                    0x1227F  0  // 𒉿
#define UC_CUNEIFORM_SIGN_PI_TIMES_A                                            0x12280  0  // 𒊀
#define UC_CUNEIFORM_SIGN_PI_TIMES_AB                                           0x12281  0  // 𒊁
#define UC_CUNEIFORM_SIGN_PI_TIMES_BI                                           0x12282  0  // 𒊂
#define UC_CUNEIFORM_SIGN_PI_TIMES_BU                                           0x12283  0  // 𒊃
#define UC_CUNEIFORM_SIGN_PI_TIMES_E                                            0x12284  0  // 𒊄
#define UC_CUNEIFORM_SIGN_PI_TIMES_I                                            0x12285  0  // 𒊅
#define UC_CUNEIFORM_SIGN_PI_TIMES_IB                                           0x12286  0  // 𒊆
#define UC_CUNEIFORM_SIGN_PI_TIMES_U                                            0x12287  0  // 𒊇
#define UC_CUNEIFORM_SIGN_PI_TIMES_U2                                           0x12288  0  // 𒊈
#define UC_CUNEIFORM_SIGN_PI_CROSSING_PI                                        0x12289  0  // 𒊉
#define UC_CUNEIFORM_SIGN_PIRIG                                                 0x1228A  0  // 𒊊
#define UC_CUNEIFORM_SIGN_PIRIG_TIMES_KAL                                       0x1228B  0  // 𒊋
#define UC_CUNEIFORM_SIGN_PIRIG_TIMES_UD                                        0x1228C  0  // 𒊌
#define UC_CUNEIFORM_SIGN_PIRIG_TIMES_ZA                                        0x1228D  0  // 𒊍
#define UC_CUNEIFORM_SIGN_PIRIG_OPPOSING_PIRIG                                  0x1228E  0  // 𒊎
#define UC_CUNEIFORM_SIGN_RA                                                    0x1228F  0  // 𒊏
#define UC_CUNEIFORM_SIGN_RAB                                                   0x12290  0  // 𒊐
#define UC_CUNEIFORM_SIGN_RI                                                    0x12291  0  // 𒊑
#define UC_CUNEIFORM_SIGN_RU                                                    0x12292  0  // 𒊒
#define UC_CUNEIFORM_SIGN_SA                                                    0x12293  0  // 𒊓
#define UC_CUNEIFORM_SIGN_SAG_NUTILLU                                           0x12294  0  // 𒊔
#define UC_CUNEIFORM_SIGN_SAG                                                   0x12295  0  // 𒊕
#define UC_CUNEIFORM_SIGN_SAG_TIMES_A                                           0x12296  0  // 𒊖
#define UC_CUNEIFORM_SIGN_SAG_TIMES_DU                                          0x12297  0  // 𒊗
#define UC_CUNEIFORM_SIGN_SAG_TIMES_DUB                                         0x12298  0  // 𒊘
#define UC_CUNEIFORM_SIGN_SAG_TIMES_HA                                          0x12299  0  // 𒊙
#define UC_CUNEIFORM_SIGN_SAG_TIMES_KAK                                         0x1229A  0  // 𒊚
#define UC_CUNEIFORM_SIGN_SAG_TIMES_KUR                                         0x1229B  0  // 𒊛
#define UC_CUNEIFORM_SIGN_SAG_TIMES_LUM                                         0x1229C  0  // 𒊜
#define UC_CUNEIFORM_SIGN_SAG_TIMES_MI                                          0x1229D  0  // 𒊝
#define UC_CUNEIFORM_SIGN_SAG_TIMES_NUN                                         0x1229E  0  // 𒊞
#define UC_CUNEIFORM_SIGN_SAG_TIMES_SAL                                         0x1229F  0  // 𒊟
#define UC_CUNEIFORM_SIGN_SAG_TIMES_SHID                                        0x122A0  0  // 𒊠
#define UC_CUNEIFORM_SIGN_SAG_TIMES_TAB                                         0x122A1  0  // 𒊡
#define UC_CUNEIFORM_SIGN_SAG_TIMES_U2                                          0x122A2  0  // 𒊢
#define UC_CUNEIFORM_SIGN_SAG_TIMES_UB                                          0x122A3  0  // 𒊣
#define UC_CUNEIFORM_SIGN_SAG_TIMES_UM                                          0x122A4  0  // 𒊤
#define UC_CUNEIFORM_SIGN_SAG_TIMES_UR                                          0x122A5  0  // 𒊥
#define UC_CUNEIFORM_SIGN_SAG_TIMES_USH                                         0x122A6  0  // 𒊦
#define UC_CUNEIFORM_SIGN_SAG_OVER_SAG                                          0x122A7  0  // 𒊧
#define UC_CUNEIFORM_SIGN_SAG_GUNU                                              0x122A8  0  // 𒊨
#define UC_CUNEIFORM_SIGN_SAL                                                   0x122A9  0  // 𒊩
#define UC_CUNEIFORM_SIGN_SAL_LAGAB_TIMES_ASH2                                  0x122AA  0  // 𒊪
#define UC_CUNEIFORM_SIGN_SANGA2                                                0x122AB  0  // 𒊫
#define UC_CUNEIFORM_SIGN_SAR                                                   0x122AC  0  // 𒊬
#define UC_CUNEIFORM_SIGN_SHA                                                   0x122AD  0  // 𒊭
#define UC_CUNEIFORM_SIGN_SHA3                                                  0x122AE  0  // 𒊮
#define UC_CUNEIFORM_SIGN_SHA3_TIMES_A                                          0x122AF  0  // 𒊯
#define UC_CUNEIFORM_SIGN_SHA3_TIMES_BAD                                        0x122B0  0  // 𒊰
#define UC_CUNEIFORM_SIGN_SHA3_TIMES_GISH                                       0x122B1  0  // 𒊱
#define UC_CUNEIFORM_SIGN_SHA3_TIMES_NE                                         0x122B2  0  // 𒊲
#define UC_CUNEIFORM_SIGN_SHA3_TIMES_SHU2                                       0x122B3  0  // 𒊳
#define UC_CUNEIFORM_SIGN_SHA3_TIMES_TUR                                        0x122B4  0  // 𒊴
#define UC_CUNEIFORM_SIGN_SHA3_TIMES_U                                          0x122B5  0  // 𒊵
#define UC_CUNEIFORM_SIGN_SHA3_TIMES_U_PLUS_A                                   0x122B6  0  // 𒊶
#define UC_CUNEIFORM_SIGN_SHA6                                                  0x122B7  0  // 𒊷
#define UC_CUNEIFORM_SIGN_SHAB6                                                 0x122B8  0  // 𒊸
#define UC_CUNEIFORM_SIGN_SHAR2                                                 0x122B9  0  // 𒊹
#define UC_CUNEIFORM_SIGN_SHE                                                   0x122BA  0  // 𒊺
#define UC_CUNEIFORM_SIGN_SHE_HU                                                0x122BB  0  // 𒊻
#define UC_CUNEIFORM_SIGN_SHE_OVER_SHE_GAD_OVER_GAD_GAR_OVER_GAR                0x122BC  0  // 𒊼
#define UC_CUNEIFORM_SIGN_SHE_OVER_SHE_TAB_OVER_TAB_GAR_OVER_GAR                0x122BD  0  // 𒊽
#define UC_CUNEIFORM_SIGN_SHEG9                                                 0x122BE  0  // 𒊾
#define UC_CUNEIFORM_SIGN_SHEN                                                  0x122BF  0  // 𒊿
#define UC_CUNEIFORM_SIGN_SHESH                                                 0x122C0  0  // 𒋀
#define UC_CUNEIFORM_SIGN_SHESH2                                                0x122C1  0  // 𒋁
#define UC_CUNEIFORM_SIGN_SHESHLAM                                              0x122C2  0  // 𒋂
#define UC_CUNEIFORM_SIGN_SHID                                                  0x122C3  0  // 𒋃
#define UC_CUNEIFORM_SIGN_SHID_TIMES_A                                          0x122C4  0  // 𒋄
#define UC_CUNEIFORM_SIGN_SHID_TIMES_IM                                         0x122C5  0  // 𒋅
#define UC_CUNEIFORM_SIGN_SHIM                                                  0x122C6  0  // 𒋆
#define UC_CUNEIFORM_SIGN_SHIM_TIMES_A                                          0x122C7  0  // 𒋇
#define UC_CUNEIFORM_SIGN_SHIM_TIMES_BAL                                        0x122C8  0  // 𒋈
#define UC_CUNEIFORM_SIGN_SHIM_TIMES_BULUG                                      0x122C9  0  // 𒋉
#define UC_CUNEIFORM_SIGN_SHIM_TIMES_DIN                                        0x122CA  0  // 𒋊
#define UC_CUNEIFORM_SIGN_SHIM_TIMES_GAR                                        0x122CB  0  // 𒋋
#define UC_CUNEIFORM_SIGN_SHIM_TIMES_IGI                                        0x122CC  0  // 𒋌
#define UC_CUNEIFORM_SIGN_SHIM_TIMES_IGI_GUNU                                   0x122CD  0  // 𒋍
#define UC_CUNEIFORM_SIGN_SHIM_TIMES_KUSHU2                                     0x122CE  0  // 𒋎
#define UC_CUNEIFORM_SIGN_SHIM_TIMES_LUL                                        0x122CF  0  // 𒋏
#define UC_CUNEIFORM_SIGN_SHIM_TIMES_MUG                                        0x122D0  0  // 𒋐
#define UC_CUNEIFORM_SIGN_SHIM_TIMES_SAL                                        0x122D1  0  // 𒋑
#define UC_CUNEIFORM_SIGN_SHINIG                                                0x122D2  0  // 𒋒
#define UC_CUNEIFORM_SIGN_SHIR                                                  0x122D3  0  // 𒋓
#define UC_CUNEIFORM_SIGN_SHIR_TENU                                             0x122D4  0  // 𒋔
#define UC_CUNEIFORM_SIGN_SHIR_OVER_SHIR_BUR_OVER_BUR                           0x122D5  0  // 𒋕
#define UC_CUNEIFORM_SIGN_SHITA                                                 0x122D6  0  // 𒋖
#define UC_CUNEIFORM_SIGN_SHU                                                   0x122D7  0  // 𒋗
#define UC_CUNEIFORM_SIGN_SHU_OVER_INVERTED_SHU                                 0x122D8  0  // 𒋘
#define UC_CUNEIFORM_SIGN_SHU2                                                  0x122D9  0  // 𒋙
#define UC_CUNEIFORM_SIGN_SHUBUR                                                0x122DA  0  // 𒋚
#define UC_CUNEIFORM_SIGN_SI                                                    0x122DB  0  // 𒋛
#define UC_CUNEIFORM_SIGN_SI_GUNU                                               0x122DC  0  // 𒋜
#define UC_CUNEIFORM_SIGN_SIG                                                   0x122DD  0  // 𒋝
#define UC_CUNEIFORM_SIGN_SIG4                                                  0x122DE  0  // 𒋞
#define UC_CUNEIFORM_SIGN_SIG4_OVER_SIG4_SHU2                                   0x122DF  0  // 𒋟
#define UC_CUNEIFORM_SIGN_SIK2                                                  0x122E0  0  // 𒋠
#define UC_CUNEIFORM_SIGN_SILA3                                                 0x122E1  0  // 𒋡
#define UC_CUNEIFORM_SIGN_SU                                                    0x122E2  0  // 𒋢
#define UC_CUNEIFORM_SIGN_SU_OVER_SU                                            0x122E3  0  // 𒋣
#define UC_CUNEIFORM_SIGN_SUD                                                   0x122E4  0  // 𒋤
#define UC_CUNEIFORM_SIGN_SUD2                                                  0x122E5  0  // 𒋥
#define UC_CUNEIFORM_SIGN_SUHUR                                                 0x122E6  0  // 𒋦
#define UC_CUNEIFORM_SIGN_SUM                                                   0x122E7  0  // 𒋧
#define UC_CUNEIFORM_SIGN_SUMASH                                                0x122E8  0  // 𒋨
#define UC_CUNEIFORM_SIGN_SUR                                                   0x122E9  0  // 𒋩
#define UC_CUNEIFORM_SIGN_SUR9                                                  0x122EA  0  // 𒋪
#define UC_CUNEIFORM_SIGN_TA                                                    0x122EB  0  // 𒋫
#define UC_CUNEIFORM_SIGN_TA_ASTERISK                                           0x122EC  0  // 𒋬
#define UC_CUNEIFORM_SIGN_TA_TIMES_HI                                           0x122ED  0  // 𒋭
#define UC_CUNEIFORM_SIGN_TA_TIMES_MI                                           0x122EE  0  // 𒋮
#define UC_CUNEIFORM_SIGN_TA_GUNU                                               0x122EF  0  // 𒋯
#define UC_CUNEIFORM_SIGN_TAB                                                   0x122F0  0  // 𒋰
#define UC_CUNEIFORM_SIGN_TAB_OVER_TAB_NI_OVER_NI_DISH_OVER_DISH                0x122F1  0  // 𒋱
#define UC_CUNEIFORM_SIGN_TAB_SQUARED                                           0x122F2  0  // 𒋲
#define UC_CUNEIFORM_SIGN_TAG                                                   0x122F3  0  // 𒋳
#define UC_CUNEIFORM_SIGN_TAG_TIMES_BI                                          0x122F4  0  // 𒋴
#define UC_CUNEIFORM_SIGN_TAG_TIMES_GUD                                         0x122F5  0  // 𒋵
#define UC_CUNEIFORM_SIGN_TAG_TIMES_SHE                                         0x122F6  0  // 𒋶
#define UC_CUNEIFORM_SIGN_TAG_TIMES_SHU                                         0x122F7  0  // 𒋷
#define UC_CUNEIFORM_SIGN_TAG_TIMES_TUG2                                        0x122F8  0  // 𒋸
#define UC_CUNEIFORM_SIGN_TAG_TIMES_UD                                          0x122F9  0  // 𒋹
#define UC_CUNEIFORM_SIGN_TAK4                                                  0x122FA  0  // 𒋺
#define UC_CUNEIFORM_SIGN_TAR                                                   0x122FB  0  // 𒋻
#define UC_CUNEIFORM_SIGN_TE                                                    0x122FC  0  // 𒋼
#define UC_CUNEIFORM_SIGN_TE_GUNU                                               0x122FD  0  // 𒋽
#define UC_CUNEIFORM_SIGN_TI                                                    0x122FE  0  // 𒋾
#define UC_CUNEIFORM_SIGN_TI_TENU                                               0x122FF  0  // 𒋿
#define UC_CUNEIFORM_SIGN_TIL                                                   0x12300  0  // 𒌀
#define UC_CUNEIFORM_SIGN_TIR                                                   0x12301  0  // 𒌁
#define UC_CUNEIFORM_SIGN_TIR_TIMES_TAK4                                        0x12302  0  // 𒌂
#define UC_CUNEIFORM_SIGN_TIR_OVER_TIR                                          0x12303  0  // 𒌃
#define UC_CUNEIFORM_SIGN_TIR_OVER_TIR_GAD_OVER_GAD_GAR_OVER_GAR                0x12304  0  // 𒌄
#define UC_CUNEIFORM_SIGN_TU                                                    0x12305  0  // 𒌅
#define UC_CUNEIFORM_SIGN_TUG2                                                  0x12306  0  // 𒌆
#define UC_CUNEIFORM_SIGN_TUK                                                   0x12307  0  // 𒌇
#define UC_CUNEIFORM_SIGN_TUM                                                   0x12308  0  // 𒌈
#define UC_CUNEIFORM_SIGN_TUR                                                   0x12309  0  // 𒌉
#define UC_CUNEIFORM_SIGN_TUR_OVER_TUR_ZA_OVER_ZA                               0x1230A  0  // 𒌊
#define UC_CUNEIFORM_SIGN_U                                                     0x1230B  0  // 𒌋
#define UC_CUNEIFORM_SIGN_U_GUD                                                 0x1230C  0  // 𒌌
#define UC_CUNEIFORM_SIGN_U_U_U                                                 0x1230D  0  // 𒌍
#define UC_CUNEIFORM_SIGN_U_OVER_U_PA_OVER_PA_GAR_OVER_GAR                      0x1230E  0  // 𒌎
#define UC_CUNEIFORM_SIGN_U_OVER_U_SUR_OVER_SUR                                 0x1230F  0  // 𒌏
#define UC_CUNEIFORM_SIGN_U_OVER_U_U_REVERSED_OVER_U_REVERSED                   0x12310  0  // 𒌐
#define UC_CUNEIFORM_SIGN_U2                                                    0x12311  0  // 𒌑
#define UC_CUNEIFORM_SIGN_UB                                                    0x12312  0  // 𒌒
#define UC_CUNEIFORM_SIGN_UD                                                    0x12313  0  // 𒌓
#define UC_CUNEIFORM_SIGN_UD_KUSHU2                                             0x12314  0  // 𒌔
#define UC_CUNEIFORM_SIGN_UD_TIMES_BAD                                          0x12315  0  // 𒌕
#define UC_CUNEIFORM_SIGN_UD_TIMES_MI                                           0x12316  0  // 𒌖
#define UC_CUNEIFORM_SIGN_UD_TIMES_U_PLUS_U_PLUS_U                              0x12317  0  // 𒌗
#define UC_CUNEIFORM_SIGN_UD_TIMES_U_PLUS_U_PLUS_U_GUNU                         0x12318  0  // 𒌘
#define UC_CUNEIFORM_SIGN_UD_GUNU                                               0x12319  0  // 𒌙
#define UC_CUNEIFORM_SIGN_UD_SHESHIG                                            0x1231A  0  // 𒌚
#define UC_CUNEIFORM_SIGN_UD_SHESHIG_TIMES_BAD                                  0x1231B  0  // 𒌛
#define UC_CUNEIFORM_SIGN_UDUG                                                  0x1231C  0  // 𒌜
#define UC_CUNEIFORM_SIGN_UM                                                    0x1231D  0  // 𒌝
#define UC_CUNEIFORM_SIGN_UM_TIMES_LAGAB                                        0x1231E  0  // 𒌞
#define UC_CUNEIFORM_SIGN_UM_TIMES_ME_PLUS_DA                                   0x1231F  0  // 𒌟
#define UC_CUNEIFORM_SIGN_UM_TIMES_SHA3                                         0x12320  0  // 𒌠
#define UC_CUNEIFORM_SIGN_UM_TIMES_U                                            0x12321  0  // 𒌡
#define UC_CUNEIFORM_SIGN_UMBIN                                                 0x12322  0  // 𒌢
#define UC_CUNEIFORM_SIGN_UMUM                                                  0x12323  0  // 𒌣
#define UC_CUNEIFORM_SIGN_UMUM_TIMES_KASKAL                                     0x12324  0  // 𒌤
#define UC_CUNEIFORM_SIGN_UMUM_TIMES_PA                                         0x12325  0  // 𒌥
#define UC_CUNEIFORM_SIGN_UN                                                    0x12326  0  // 𒌦
#define UC_CUNEIFORM_SIGN_UN_GUNU                                               0x12327  0  // 𒌧
#define UC_CUNEIFORM_SIGN_UR                                                    0x12328  0  // 𒌨
#define UC_CUNEIFORM_SIGN_UR_CROSSING_UR                                        0x12329  0  // 𒌩
#define UC_CUNEIFORM_SIGN_UR_SHESHIG                                            0x1232A  0  // 𒌪
#define UC_CUNEIFORM_SIGN_UR2                                                   0x1232B  0  // 𒌫
#define UC_CUNEIFORM_SIGN_UR2_TIMES_A_PLUS_HA                                   0x1232C  0  // 𒌬
#define UC_CUNEIFORM_SIGN_UR2_TIMES_A_PLUS_NA                                   0x1232D  0  // 𒌭
#define UC_CUNEIFORM_SIGN_UR2_TIMES_AL                                          0x1232E  0  // 𒌮
#define UC_CUNEIFORM_SIGN_UR2_TIMES_HA                                          0x1232F  0  // 𒌯
#define UC_CUNEIFORM_SIGN_UR2_TIMES_NUN                                         0x12330  0  // 𒌰
#define UC_CUNEIFORM_SIGN_UR2_TIMES_U2                                          0x12331  0  // 𒌱
#define UC_CUNEIFORM_SIGN_UR2_TIMES_U2_PLUS_ASH                                 0x12332  0  // 𒌲
#define UC_CUNEIFORM_SIGN_UR2_TIMES_U2_PLUS_BI                                  0x12333  0  // 𒌳
#define UC_CUNEIFORM_SIGN_UR4                                                   0x12334  0  // 𒌴
#define UC_CUNEIFORM_SIGN_URI                                                   0x12335  0  // 𒌵
#define UC_CUNEIFORM_SIGN_URI3                                                  0x12336  0  // 𒌶
#define UC_CUNEIFORM_SIGN_URU                                                   0x12337  0  // 𒌷
#define UC_CUNEIFORM_SIGN_URU_TIMES_A                                           0x12338  0  // 𒌸
#define UC_CUNEIFORM_SIGN_URU_TIMES_ASHGAB                                      0x12339  0  // 𒌹
#define UC_CUNEIFORM_SIGN_URU_TIMES_BAR                                         0x1233A  0  // 𒌺
#define UC_CUNEIFORM_SIGN_URU_TIMES_DUN                                         0x1233B  0  // 𒌻
#define UC_CUNEIFORM_SIGN_URU_TIMES_GA                                          0x1233C  0  // 𒌼
#define UC_CUNEIFORM_SIGN_URU_TIMES_GAL                                         0x1233D  0  // 𒌽
#define UC_CUNEIFORM_SIGN_URU_TIMES_GAN2_TENU                                   0x1233E  0  // 𒌾
#define UC_CUNEIFORM_SIGN_URU_TIMES_GAR                                         0x1233F  0  // 𒌿
#define UC_CUNEIFORM_SIGN_URU_TIMES_GU                                          0x12340  0  // 𒍀
#define UC_CUNEIFORM_SIGN_URU_TIMES_HA                                          0x12341  0  // 𒍁
#define UC_CUNEIFORM_SIGN_URU_TIMES_IGI                                         0x12342  0  // 𒍂
#define UC_CUNEIFORM_SIGN_URU_TIMES_IM                                          0x12343  0  // 𒍃
#define UC_CUNEIFORM_SIGN_URU_TIMES_ISH                                         0x12344  0  // 𒍄
#define UC_CUNEIFORM_SIGN_URU_TIMES_KI                                          0x12345  0  // 𒍅
#define UC_CUNEIFORM_SIGN_URU_TIMES_LUM                                         0x12346  0  // 𒍆
#define UC_CUNEIFORM_SIGN_URU_TIMES_MIN                                         0x12347  0  // 𒍇
#define UC_CUNEIFORM_SIGN_URU_TIMES_PA                                          0x12348  0  // 𒍈
#define UC_CUNEIFORM_SIGN_URU_TIMES_SHE                                         0x12349  0  // 𒍉
#define UC_CUNEIFORM_SIGN_URU_TIMES_SIG4                                        0x1234A  0  // 𒍊
#define UC_CUNEIFORM_SIGN_URU_TIMES_TU                                          0x1234B  0  // 𒍋
#define UC_CUNEIFORM_SIGN_URU_TIMES_U_PLUS_GUD                                  0x1234C  0  // 𒍌
#define UC_CUNEIFORM_SIGN_URU_TIMES_UD                                          0x1234D  0  // 𒍍
#define UC_CUNEIFORM_SIGN_URU_TIMES_URUDA                                       0x1234E  0  // 𒍎
#define UC_CUNEIFORM_SIGN_URUDA                                                 0x1234F  0  // 𒍏
#define UC_CUNEIFORM_SIGN_URUDA_TIMES_U                                         0x12350  0  // 𒍐
#define UC_CUNEIFORM_SIGN_USH                                                   0x12351  0  // 𒍑
#define UC_CUNEIFORM_SIGN_USH_TIMES_A                                           0x12352  0  // 𒍒
#define UC_CUNEIFORM_SIGN_USH_TIMES_KU                                          0x12353  0  // 𒍓
#define UC_CUNEIFORM_SIGN_USH_TIMES_KUR                                         0x12354  0  // 𒍔
#define UC_CUNEIFORM_SIGN_USH_TIMES_TAK4                                        0x12355  0  // 𒍕
#define UC_CUNEIFORM_SIGN_USHX                                                  0x12356  0  // 𒍖
#define UC_CUNEIFORM_SIGN_USH2                                                  0x12357  0  // 𒍗
#define UC_CUNEIFORM_SIGN_USHUMX                                                0x12358  0  // 𒍘
#define UC_CUNEIFORM_SIGN_UTUKI                                                 0x12359  0  // 𒍙
#define UC_CUNEIFORM_SIGN_UZ3                                                   0x1235A  0  // 𒍚
#define UC_CUNEIFORM_SIGN_UZ3_TIMES_KASKAL                                      0x1235B  0  // 𒍛
#define UC_CUNEIFORM_SIGN_UZU                                                   0x1235C  0  // 𒍜
#define UC_CUNEIFORM_SIGN_ZA                                                    0x1235D  0  // 𒍝
#define UC_CUNEIFORM_SIGN_ZA_TENU                                               0x1235E  0  // 𒍞
#define UC_CUNEIFORM_SIGN_ZA_SQUARED_TIMES_KUR                                  0x1235F  0  // 𒍟
#define UC_CUNEIFORM_SIGN_ZAG                                                   0x12360  0  // 𒍠
#define UC_CUNEIFORM_SIGN_ZAMX                                                  0x12361  0  // 𒍡
#define UC_CUNEIFORM_SIGN_ZE2                                                   0x12362  0  // 𒍢
#define UC_CUNEIFORM_SIGN_ZI                                                    0x12363  0  // 𒍣
#define UC_CUNEIFORM_SIGN_ZI_OVER_ZI                                            0x12364  0  // 𒍤
#define UC_CUNEIFORM_SIGN_ZI3                                                   0x12365  0  // 𒍥
#define UC_CUNEIFORM_SIGN_ZIB                                                   0x12366  0  // 𒍦
#define UC_CUNEIFORM_SIGN_ZIB_KABA_TENU                                         0x12367  0  // 𒍧
#define UC_CUNEIFORM_SIGN_ZIG                                                   0x12368  0  // 𒍨
#define UC_CUNEIFORM_SIGN_ZIZ2                                                  0x12369  0  // 𒍩
#define UC_CUNEIFORM_SIGN_ZU                                                    0x1236A  0  // 𒍪
#define UC_CUNEIFORM_SIGN_ZU5                                                   0x1236B  0  // 𒍫
#define UC_CUNEIFORM_SIGN_ZU5_TIMES_A                                           0x1236C  0  // 𒍬
#define UC_CUNEIFORM_SIGN_ZUBUR                                                 0x1236D  0  // 𒍭
#define UC_CUNEIFORM_SIGN_ZUM                                                   0x1236E  0  // 𒍮
#define UC_CUNEIFORM_SIGN_KAP_ELAMITE                                           0x1236F  0  // 𒍯
#define UC_CUNEIFORM_SIGN_AB_TIMES_NUN                                          0x12370  0  // 𒍰
#define UC_CUNEIFORM_SIGN_AB2_TIMES_A                                           0x12371  0  // 𒍱
#define UC_CUNEIFORM_SIGN_AMAR_TIMES_KUG                                        0x12372  0  // 𒍲
#define UC_CUNEIFORM_SIGN_DAG_KISIM5_TIMES_U2_PLUS_MASH                         0x12373  0  // 𒍳
#define UC_CUNEIFORM_SIGN_DAG3                                                  0x12374  0  // 𒍴
#define UC_CUNEIFORM_SIGN_DISH_PLUS_SHU                                         0x12375  0  // 𒍵
#define UC_CUNEIFORM_SIGN_DUB_TIMES_SHE                                         0x12376  0  // 𒍶
#define UC_CUNEIFORM_SIGN_EZEN_TIMES_GUD                                        0x12377  0  // 𒍷
#define UC_CUNEIFORM_SIGN_EZEN_TIMES_SHE                                        0x12378  0  // 𒍸
#define UC_CUNEIFORM_SIGN_GA2_TIMES_AN_PLUS_KAK_PLUS_A                          0x12379  0  // 𒍹
#define UC_CUNEIFORM_SIGN_GA2_TIMES_ASH2                                        0x1237A  0  // 𒍺
#define UC_CUNEIFORM_SIGN_GE22                                                  0x1237B  0  // 𒍻
#define UC_CUNEIFORM_SIGN_GIG                                                   0x1237C  0  // 𒍼
#define UC_CUNEIFORM_SIGN_HUSH                                                  0x1237D  0  // 𒍽
#define UC_CUNEIFORM_SIGN_KA_TIMES_ANSHE                                        0x1237E  0  // 𒍾
#define UC_CUNEIFORM_SIGN_KA_TIMES_ASH3                                         0x1237F  0  // 𒍿
#define UC_CUNEIFORM_SIGN_KA_TIMES_GISH                                         0x12380  0  // 𒎀
#define UC_CUNEIFORM_SIGN_KA_TIMES_GUD                                          0x12381  0  // 𒎁
#define UC_CUNEIFORM_SIGN_KA_TIMES_HI_TIMES_ASH2                                0x12382  0  // 𒎂
#define UC_CUNEIFORM_SIGN_KA_TIMES_LUM                                          0x12383  0  // 𒎃
#define UC_CUNEIFORM_SIGN_KA_TIMES_PA                                           0x12384  0  // 𒎄
#define UC_CUNEIFORM_SIGN_KA_TIMES_SHUL                                         0x12385  0  // 𒎅
#define UC_CUNEIFORM_SIGN_KA_TIMES_TU                                           0x12386  0  // 𒎆
#define UC_CUNEIFORM_SIGN_KA_TIMES_UR2                                          0x12387  0  // 𒎇
#define UC_CUNEIFORM_SIGN_LAGAB_TIMES_GI                                        0x12388  0  // 𒎈
#define UC_CUNEIFORM_SIGN_LU2_SHESHIG_TIMES_BAD                                 0x12389  0  // 𒎉
#define UC_CUNEIFORM_SIGN_LU2_TIMES_ESH2_PLUS_LAL                               0x1238A  0  // 𒎊
#define UC_CUNEIFORM_SIGN_LU2_TIMES_SHU                                         0x1238B  0  // 𒎋
#define UC_CUNEIFORM_SIGN_MESH                                                  0x1238C  0  // 𒎌
#define UC_CUNEIFORM_SIGN_MUSH3_TIMES_ZA                                        0x1238D  0  // 𒎍
#define UC_CUNEIFORM_SIGN_NA4                                                   0x1238E  0  // 𒎎
#define UC_CUNEIFORM_SIGN_NIN                                                   0x1238F  0  // 𒎏
#define UC_CUNEIFORM_SIGN_NIN9                                                  0x12390  0  // 𒎐
#define UC_CUNEIFORM_SIGN_NINDA2_TIMES_BAL                                      0x12391  0  // 𒎑
#define UC_CUNEIFORM_SIGN_NINDA2_TIMES_GI                                       0x12392  0  // 𒎒
#define UC_CUNEIFORM_SIGN_NU11_ROTATED_NINETY_DEGREES                           0x12393  0  // 𒎓
#define UC_CUNEIFORM_SIGN_PESH2_ASTERISK                                        0x12394  0  // 𒎔
#define UC_CUNEIFORM_SIGN_PIR2                                                  0x12395  0  // 𒎕
#define UC_CUNEIFORM_SIGN_SAG_TIMES_IGI_GUNU                                    0x12396  0  // 𒎖
#define UC_CUNEIFORM_SIGN_TI2                                                   0x12397  0  // 𒎗
#define UC_CUNEIFORM_SIGN_UM_TIMES_ME                                           0x12398  0  // 𒎘
#define UC_CUNEIFORM_SIGN_U_U                                                   0x12399  0  // 𒎙
