/*
 * Unicode keys for U+1E7E0 .. U+1E7FF
 *
 * This file was generated from Unicode 16.0.0.
 *
 * See http://www.unicode.org/versions/Unicode16.0.0 for source data.
 */

#pragma once

#define UC_ETHIOPIC_SYLLABLE_HHYA         0x1E7E0  0  // 𞟠
#define UC_ETHIOPIC_SYLLABLE_HHYU         0x1E7E1  0  // 𞟡
#define UC_ETHIOPIC_SYLLABLE_HHYI         0x1E7E2  0  // 𞟢
#define UC_ETHIOPIC_SYLLABLE_HHYAA        0x1E7E3  0  // 𞟣
#define UC_ETHIOPIC_SYLLABLE_HHYEE        0x1E7E4  0  // 𞟤
#define UC_ETHIOPIC_SYLLABLE_HHYE         0x1E7E5  0  // 𞟥
#define UC_ETHIOPIC_SYLLABLE_HHYO         0x1E7E6  0  // 𞟦
#define UC_ETHIOPIC_SYLLABLE_GURAGE_HHWA  0x1E7E8  0  // 𞟨
#define UC_ETHIOPIC_SYLLABLE_HHWI         0x1E7E9  0  // 𞟩
#define UC_ETHIOPIC_SYLLABLE_HHWEE        0x1E7EA  0  // 𞟪
#define UC_ETHIOPIC_SYLLABLE_HHWE         0x1E7EB  0  // 𞟫
#define UC_ETHIOPIC_SYLLABLE_GURAGE_MWI   0x1E7ED  0  // 𞟭
#define UC_ETHIOPIC_SYLLABLE_GURAGE_MWEE  0x1E7EE  0  // 𞟮
#define UC_ETHIOPIC_SYLLABLE_GURAGE_QWI   0x1E7F0  0  // 𞟰
#define UC_ETHIOPIC_SYLLABLE_GURAGE_QWEE  0x1E7F1  0  // 𞟱
#define UC_ETHIOPIC_SYLLABLE_GURAGE_QWE   0x1E7F2  0  // 𞟲
#define UC_ETHIOPIC_SYLLABLE_GURAGE_BWI   0x1E7F3  0  // 𞟳
#define UC_ETHIOPIC_SYLLABLE_GURAGE_BWEE  0x1E7F4  0  // 𞟴
#define UC_ETHIOPIC_SYLLABLE_GURAGE_KWI   0x1E7F5  0  // 𞟵
#define UC_ETHIOPIC_SYLLABLE_GURAGE_KWEE  0x1E7F6  0  // 𞟶
#define UC_ETHIOPIC_SYLLABLE_GURAGE_KWE   0x1E7F7  0  // 𞟷
#define UC_ETHIOPIC_SYLLABLE_GURAGE_GWI   0x1E7F8  0  // 𞟸
#define UC_ETHIOPIC_SYLLABLE_GURAGE_GWEE  0x1E7F9  0  // 𞟹
#define UC_ETHIOPIC_SYLLABLE_GURAGE_GWE   0x1E7FA  0  // 𞟺
#define UC_ETHIOPIC_SYLLABLE_GURAGE_FWI   0x1E7FB  0  // 𞟻
#define UC_ETHIOPIC_SYLLABLE_GURAGE_FWEE  0x1E7FC  0  // 𞟼
#define UC_ETHIOPIC_SYLLABLE_GURAGE_PWI   0x1E7FD  0  // 𞟽
#define UC_ETHIOPIC_SYLLABLE_GURAGE_PWEE  0x1E7FE  0  // 𞟾