/*
 * Unicode keys for U+1F780 .. U+1F7FF
 *
 * This file was generated from Unicode 16.0.0.
 *
 * See http://www.unicode.org/versions/Unicode16.0.0 for source data.
 */

#pragma once

#define UC_BLACK_LEFT_POINTING_ISOSCELES_RIGHT_TRIANGLE       0x1F780  0  // 🞀
#define UC_BLACK_UP_POINTING_ISOSCELES_RIGHT_TRIANGLE         0x1F781  0  // 🞁
#define UC_BLACK_RIGHT_POINTING_ISOSCELES_RIGHT_TRIANGLE      0x1F782  0  // 🞂
#define UC_BLACK_DOWN_POINTING_ISOSCELES_RIGHT_TRIANGLE       0x1F783  0  // 🞃
#define UC_BLACK_SLIGHTLY_SMALL_CIRCLE                        0x1F784  0  // 🞄
#define UC_MEDIUM_BOLD_WHITE_CIRCLE                           0x1F785  0  // 🞅
#define UC_BOLD_WHITE_CIRCLE                                  0x1F786  0  // 🞆
#define UC_HEAVY_WHITE_CIRCLE                                 0x1F787  0  // 🞇
#define UC_VERY_HEAVY_WHITE_CIRCLE                            0x1F788  0  // 🞈
#define UC_EXTREMELY_HEAVY_WHITE_CIRCLE                       0x1F789  0  // 🞉
#define UC_WHITE_CIRCLE_CONTAINING_BLACK_SMALL_CIRCLE         0x1F78A  0  // 🞊
#define UC_ROUND_TARGET                                       0x1F78B  0  // 🞋
#define UC_BLACK_TINY_SQUARE                                  0x1F78C  0  // 🞌
#define UC_BLACK_SLIGHTLY_SMALL_SQUARE                        0x1F78D  0  // 🞍
#define UC_LIGHT_WHITE_SQUARE                                 0x1F78E  0  // 🞎
#define UC_MEDIUM_WHITE_SQUARE                                0x1F78F  0  // 🞏
#define UC_BOLD_WHITE_SQUARE                                  0x1F790  0  // 🞐
#define UC_HEAVY_WHITE_SQUARE                                 0x1F791  0  // 🞑
#define UC_VERY_HEAVY_WHITE_SQUARE                            0x1F792  0  // 🞒
#define UC_EXTREMELY_HEAVY_WHITE_SQUARE                       0x1F793  0  // 🞓
#define UC_WHITE_SQUARE_CONTAINING_BLACK_VERY_SMALL_SQUARE    0x1F794  0  // 🞔
#define UC_WHITE_SQUARE_CONTAINING_BLACK_MEDIUM_SQUARE        0x1F795  0  // 🞕
#define UC_SQUARE_TARGET                                      0x1F796  0  // 🞖
#define UC_BLACK_TINY_DIAMOND                                 0x1F797  0  // 🞗
#define UC_BLACK_VERY_SMALL_DIAMOND                           0x1F798  0  // 🞘
#define UC_BLACK_MEDIUM_SMALL_DIAMOND                         0x1F799  0  // 🞙
#define UC_WHITE_DIAMOND_CONTAINING_BLACK_VERY_SMALL_DIAMOND  0x1F79A  0  // 🞚
#define UC_WHITE_DIAMOND_CONTAINING_BLACK_MEDIUM_DIAMOND      0x1F79B  0  // 🞛
#define UC_DIAMOND_TARGET                                     0x1F79C  0  // 🞜
#define UC_BLACK_TINY_LOZENGE                                 0x1F79D  0  // 🞝
#define UC_BLACK_VERY_SMALL_LOZENGE                           0x1F79E  0  // 🞞
#define UC_BLACK_MEDIUM_SMALL_LOZENGE                         0x1F79F  0  // 🞟
#define UC_WHITE_LOZENGE_CONTAINING_BLACK_SMALL_LOZENGE       0x1F7A0  0  // 🞠
#define UC_THIN_GREEK_CROSS                                   0x1F7A1  0  // 🞡
#define UC_LIGHT_GREEK_CROSS                                  0x1F7A2  0  // 🞢
#define UC_MEDIUM_GREEK_CROSS                                 0x1F7A3  0  // 🞣
#define UC_BOLD_GREEK_CROSS                                   0x1F7A4  0  // 🞤
#define UC_VERY_BOLD_GREEK_CROSS                              0x1F7A5  0  // 🞥
#define UC_VERY_HEAVY_GREEK_CROSS                             0x1F7A6  0  // 🞦
#define UC_EXTREMELY_HEAVY_GREEK_CROSS                        0x1F7A7  0  // 🞧
#define UC_THIN_SALTIRE                                       0x1F7A8  0  // 🞨
#define UC_LIGHT_SALTIRE                                      0x1F7A9  0  // 🞩
#define UC_MEDIUM_SALTIRE                                     0x1F7AA  0  // 🞪
#define UC_BOLD_SALTIRE                                       0x1F7AB  0  // 🞫
#define UC_HEAVY_SALTIRE                                      0x1F7AC  0  // 🞬
#define UC_VERY_HEAVY_SALTIRE                                 0x1F7AD  0  // 🞭
#define UC_EXTREMELY_HEAVY_SALTIRE                            0x1F7AE  0  // 🞮
#define UC_LIGHT_FIVE_SPOKED_ASTERISK                         0x1F7AF  0  // 🞯
#define UC_MEDIUM_FIVE_SPOKED_ASTERISK                        0x1F7B0  0  // 🞰
#define UC_BOLD_FIVE_SPOKED_ASTERISK                          0x1F7B1  0  // 🞱
#define UC_HEAVY_FIVE_SPOKED_ASTERISK                         0x1F7B2  0  // 🞲
#define UC_VERY_HEAVY_FIVE_SPOKED_ASTERISK                    0x1F7B3  0  // 🞳
#define UC_EXTREMELY_HEAVY_FIVE_SPOKED_ASTERISK               0x1F7B4  0  // 🞴
#define UC_LIGHT_SIX_SPOKED_ASTERISK                          0x1F7B5  0  // 🞵
#define UC_MEDIUM_SIX_SPOKED_ASTERISK                         0x1F7B6  0  // 🞶
#define UC_BOLD_SIX_SPOKED_ASTERISK                           0x1F7B7  0  // 🞷
#define UC_HEAVY_SIX_SPOKED_ASTERISK                          0x1F7B8  0  // 🞸
#define UC_VERY_HEAVY_SIX_SPOKED_ASTERISK                     0x1F7B9  0  // 🞹
#define UC_EXTREMELY_HEAVY_SIX_SPOKED_ASTERISK                0x1F7BA  0  // 🞺
#define UC_LIGHT_EIGHT_SPOKED_ASTERISK                        0x1F7BB  0  // 🞻
#define UC_MEDIUM_EIGHT_SPOKED_ASTERISK                       0x1F7BC  0  // 🞼
#define UC_BOLD_EIGHT_SPOKED_ASTERISK                         0x1F7BD  0  // 🞽
#define UC_HEAVY_EIGHT_SPOKED_ASTERISK                        0x1F7BE  0  // 🞾
#define UC_VERY_HEAVY_EIGHT_SPOKED_ASTERISK                   0x1F7BF  0  // 🞿
#define UC_LIGHT_THREE_POINTED_BLACK_STAR                     0x1F7C0  0  // 🟀
#define UC_MEDIUM_THREE_POINTED_BLACK_STAR                    0x1F7C1  0  // 🟁
#define UC_THREE_POINTED_BLACK_STAR                           0x1F7C2  0  // 🟂
#define UC_MEDIUM_THREE_POINTED_PINWHEEL_STAR                 0x1F7C3  0  // 🟃
#define UC_LIGHT_FOUR_POINTED_BLACK_STAR                      0x1F7C4  0  // 🟄
#define UC_MEDIUM_FOUR_POINTED_BLACK_STAR                     0x1F7C5  0  // 🟅
#define UC_FOUR_POINTED_BLACK_STAR                            0x1F7C6  0  // 🟆
#define UC_MEDIUM_FOUR_POINTED_PINWHEEL_STAR                  0x1F7C7  0  // 🟇
#define UC_REVERSE_LIGHT_FOUR_POINTED_PINWHEEL_STAR           0x1F7C8  0  // 🟈
#define UC_LIGHT_FIVE_POINTED_BLACK_STAR                      0x1F7C9  0  // 🟉
#define UC_HEAVY_FIVE_POINTED_BLACK_STAR                      0x1F7CA  0  // 🟊
#define UC_MEDIUM_SIX_POINTED_BLACK_STAR                      0x1F7CB  0  // 🟋
#define UC_HEAVY_SIX_POINTED_BLACK_STAR                       0x1F7CC  0  // 🟌
#define UC_SIX_POINTED_PINWHEEL_STAR                          0x1F7CD  0  // 🟍
#define UC_MEDIUM_EIGHT_POINTED_BLACK_STAR                    0x1F7CE  0  // 🟎
#define UC_HEAVY_EIGHT_POINTED_BLACK_STAR                     0x1F7CF  0  // 🟏
#define UC_VERY_HEAVY_EIGHT_POINTED_BLACK_STAR                0x1F7D0  0  // 🟐
#define UC_HEAVY_EIGHT_POINTED_PINWHEEL_STAR                  0x1F7D1  0  // 🟑
#define UC_LIGHT_TWELVE_POINTED_BLACK_STAR                    0x1F7D2  0  // 🟒
#define UC_HEAVY_TWELVE_POINTED_BLACK_STAR                    0x1F7D3  0  // 🟓
#define UC_HEAVY_TWELVE_POINTED_PINWHEEL_STAR                 0x1F7D4  0  // 🟔
#define UC_CIRCLED_TRIANGLE                                   0x1F7D5  0  // 🟕
#define UC_NEGATIVE_CIRCLED_TRIANGLE                          0x1F7D6  0  // 🟖
#define UC_CIRCLED_SQUARE                                     0x1F7D7  0  // 🟗
#define UC_NEGATIVE_CIRCLED_SQUARE                            0x1F7D8  0  // 🟘
#define UC_NINE_POINTED_WHITE_STAR                            0x1F7D9  0  // 🟙
#define UC_LARGE_ORANGE_CIRCLE                                0x1F7E0  0  // 🟠
#define UC_LARGE_YELLOW_CIRCLE                                0x1F7E1  0  // 🟡
#define UC_LARGE_GREEN_CIRCLE                                 0x1F7E2  0  // 🟢
#define UC_LARGE_PURPLE_CIRCLE                                0x1F7E3  0  // 🟣
#define UC_LARGE_BROWN_CIRCLE                                 0x1F7E4  0  // 🟤
#define UC_LARGE_RED_SQUARE                                   0x1F7E5  0  // 🟥
#define UC_LARGE_BLUE_SQUARE                                  0x1F7E6  0  // 🟦
#define UC_LARGE_ORANGE_SQUARE                                0x1F7E7  0  // 🟧
#define UC_LARGE_YELLOW_SQUARE                                0x1F7E8  0  // 🟨
#define UC_LARGE_GREEN_SQUARE                                 0x1F7E9  0  // 🟩
#define UC_LARGE_PURPLE_SQUARE                                0x1F7EA  0  // 🟪
#define UC_LARGE_BROWN_SQUARE                                 0x1F7EB  0  // 🟫
#define UC_HEAVY_EQUALS_SIGN                                  0x1F7F0  0  // 🟰