/*
 * Unicode keys for U+FF00 .. U+FFEF
 *
 * This file was generated from Unicode 16.0.0.
 *
 * See http://www.unicode.org/versions/Unicode16.0.0 for source data.
 */

#pragma once

#define UC_FULLWIDTH_EXCLAMATION_MARK                        0xFF01  0       // ！
#define UC_FULLWIDTH_QUOTATION_MARK                          0xFF02  0       // ＂
#define UC_FULLWIDTH_NUMBER_SIGN                             0xFF03  0       // ＃
#define UC_FULLWIDTH_DOLLAR_SIGN                             0xFF04  0       // ＄
#define UC_FULLWIDTH_PERCENT_SIGN                            0xFF05  0       // ％
#define UC_FULLWIDTH_AMPERSAND                               0xFF06  0       // ＆
#define UC_FULLWIDTH_APOSTROPHE                              0xFF07  0       // ＇
#define UC_FULLWIDTH_LEFT_PARENTHESIS                        0xFF08  0       // （
#define UC_FULLWIDTH_RIGHT_PARENTHESIS                       0xFF09  0       // ）
#define UC_FULLWIDTH_ASTERISK                                0xFF0A  0       // ＊
#define UC_FULLWIDTH_PLUS_SIGN                               0xFF0B  0       // ＋
#define UC_FULLWIDTH_COMMA                                   0xFF0C  0       // ，
#define UC_FULLWIDTH_HYPHEN_MINUS                            0xFF0D  0       // －
#define UC_FULLWIDTH_FULL_STOP                               0xFF0E  0       // ．
#define UC_FULLWIDTH_SOLIDUS                                 0xFF0F  0       // ／
#define UC_FULLWIDTH_DIGIT_ZERO                              0xFF10  0       // ０
#define UC_FULLWIDTH_DIGIT_ONE                               0xFF11  0       // １
#define UC_FULLWIDTH_DIGIT_TWO                               0xFF12  0       // ２
#define UC_FULLWIDTH_DIGIT_THREE                             0xFF13  0       // ３
#define UC_FULLWIDTH_DIGIT_FOUR                              0xFF14  0       // ４
#define UC_FULLWIDTH_DIGIT_FIVE                              0xFF15  0       // ５
#define UC_FULLWIDTH_DIGIT_SIX                               0xFF16  0       // ６
#define UC_FULLWIDTH_DIGIT_SEVEN                             0xFF17  0       // ７
#define UC_FULLWIDTH_DIGIT_EIGHT                             0xFF18  0       // ８
#define UC_FULLWIDTH_DIGIT_NINE                              0xFF19  0       // ９
#define UC_FULLWIDTH_COLON                                   0xFF1A  0       // ：
#define UC_FULLWIDTH_SEMICOLON                               0xFF1B  0       // ；
#define UC_FULLWIDTH_LESS_THAN_SIGN                          0xFF1C  0       // ＜
#define UC_FULLWIDTH_EQUALS_SIGN                             0xFF1D  0       // ＝
#define UC_FULLWIDTH_GREATER_THAN_SIGN                       0xFF1E  0       // ＞
#define UC_FULLWIDTH_QUESTION_MARK                           0xFF1F  0       // ？
#define UC_FULLWIDTH_COMMERCIAL_AT                           0xFF20  0       // ＠
#define UC_FULLWIDTH_LATIN_SMALL_LETTER_A                    0xFF41  0xFF21  // ａ/Ａ
#define UC_FULLWIDTH_LATIN_SMALL_LETTER_B                    0xFF42  0xFF22  // ｂ/Ｂ
#define UC_FULLWIDTH_LATIN_SMALL_LETTER_C                    0xFF43  0xFF23  // ｃ/Ｃ
#define UC_FULLWIDTH_LATIN_SMALL_LETTER_D                    0xFF44  0xFF24  // ｄ/Ｄ
#define UC_FULLWIDTH_LATIN_SMALL_LETTER_E                    0xFF45  0xFF25  // ｅ/Ｅ
#define UC_FULLWIDTH_LATIN_SMALL_LETTER_F                    0xFF46  0xFF26  // ｆ/Ｆ
#define UC_FULLWIDTH_LATIN_SMALL_LETTER_G                    0xFF47  0xFF27  // ｇ/Ｇ
#define UC_FULLWIDTH_LATIN_SMALL_LETTER_H                    0xFF48  0xFF28  // ｈ/Ｈ
#define UC_FULLWIDTH_LATIN_SMALL_LETTER_I                    0xFF49  0xFF29  // ｉ/Ｉ
#define UC_FULLWIDTH_LATIN_SMALL_LETTER_J                    0xFF4A  0xFF2A  // ｊ/Ｊ
#define UC_FULLWIDTH_LATIN_SMALL_LETTER_K                    0xFF4B  0xFF2B  // ｋ/Ｋ
#define UC_FULLWIDTH_LATIN_SMALL_LETTER_L                    0xFF4C  0xFF2C  // ｌ/Ｌ
#define UC_FULLWIDTH_LATIN_SMALL_LETTER_M                    0xFF4D  0xFF2D  // ｍ/Ｍ
#define UC_FULLWIDTH_LATIN_SMALL_LETTER_N                    0xFF4E  0xFF2E  // ｎ/Ｎ
#define UC_FULLWIDTH_LATIN_SMALL_LETTER_O                    0xFF4F  0xFF2F  // ｏ/Ｏ
#define UC_FULLWIDTH_LATIN_SMALL_LETTER_P                    0xFF50  0xFF30  // ｐ/Ｐ
#define UC_FULLWIDTH_LATIN_SMALL_LETTER_Q                    0xFF51  0xFF31  // ｑ/Ｑ
#define UC_FULLWIDTH_LATIN_SMALL_LETTER_R                    0xFF52  0xFF32  // ｒ/Ｒ
#define UC_FULLWIDTH_LATIN_SMALL_LETTER_S                    0xFF53  0xFF33  // ｓ/Ｓ
#define UC_FULLWIDTH_LATIN_SMALL_LETTER_T                    0xFF54  0xFF34  // ｔ/Ｔ
#define UC_FULLWIDTH_LATIN_SMALL_LETTER_U                    0xFF55  0xFF35  // ｕ/Ｕ
#define UC_FULLWIDTH_LATIN_SMALL_LETTER_V                    0xFF56  0xFF36  // ｖ/Ｖ
#define UC_FULLWIDTH_LATIN_SMALL_LETTER_W                    0xFF57  0xFF37  // ｗ/Ｗ
#define UC_FULLWIDTH_LATIN_SMALL_LETTER_X                    0xFF58  0xFF38  // ｘ/Ｘ
#define UC_FULLWIDTH_LATIN_SMALL_LETTER_Y                    0xFF59  0xFF39  // ｙ/Ｙ
#define UC_FULLWIDTH_LATIN_SMALL_LETTER_Z                    0xFF5A  0xFF3A  // ｚ/Ｚ
#define UC_FULLWIDTH_LEFT_SQUARE_BRACKET                     0xFF3B  0       // ［
#define UC_FULLWIDTH_REVERSE_SOLIDUS                         0xFF3C  0       // ＼
#define UC_FULLWIDTH_RIGHT_SQUARE_BRACKET                    0xFF3D  0       // ］
#define UC_FULLWIDTH_CIRCUMFLEX_ACCENT                       0xFF3E  0       // ＾
#define UC_FULLWIDTH_LOW_LINE                                0xFF3F  0       // ＿
#define UC_FULLWIDTH_GRAVE_ACCENT                            0xFF40  0       // ｀
#define UC_FULLWIDTH_LEFT_CURLY_BRACKET                      0xFF5B  0       // ｛
#define UC_FULLWIDTH_VERTICAL_LINE                           0xFF5C  0       // ｜
#define UC_FULLWIDTH_RIGHT_CURLY_BRACKET                     0xFF5D  0       // ｝
#define UC_FULLWIDTH_TILDE                                   0xFF5E  0       // ～
#define UC_FULLWIDTH_LEFT_WHITE_PARENTHESIS                  0xFF5F  0       // ｟
#define UC_FULLWIDTH_RIGHT_WHITE_PARENTHESIS                 0xFF60  0       // ｠
#define UC_HALFWIDTH_IDEOGRAPHIC_FULL_STOP                   0xFF61  0       // ｡
#define UC_HALFWIDTH_LEFT_CORNER_BRACKET                     0xFF62  0       // ｢
#define UC_HALFWIDTH_RIGHT_CORNER_BRACKET                    0xFF63  0       // ｣
#define UC_HALFWIDTH_IDEOGRAPHIC_COMMA                       0xFF64  0       // ､
#define UC_HALFWIDTH_KATAKANA_MIDDLE_DOT                     0xFF65  0       // ･
#define UC_HALFWIDTH_KATAKANA_LETTER_WO                      0xFF66  0       // ｦ
#define UC_HALFWIDTH_KATAKANA_LETTER_SMALL_A                 0xFF67  0       // ｧ
#define UC_HALFWIDTH_KATAKANA_LETTER_SMALL_I                 0xFF68  0       // ｨ
#define UC_HALFWIDTH_KATAKANA_LETTER_SMALL_U                 0xFF69  0       // ｩ
#define UC_HALFWIDTH_KATAKANA_LETTER_SMALL_E                 0xFF6A  0       // ｪ
#define UC_HALFWIDTH_KATAKANA_LETTER_SMALL_O                 0xFF6B  0       // ｫ
#define UC_HALFWIDTH_KATAKANA_LETTER_SMALL_YA                0xFF6C  0       // ｬ
#define UC_HALFWIDTH_KATAKANA_LETTER_SMALL_YU                0xFF6D  0       // ｭ
#define UC_HALFWIDTH_KATAKANA_LETTER_SMALL_YO                0xFF6E  0       // ｮ
#define UC_HALFWIDTH_KATAKANA_LETTER_SMALL_TU                0xFF6F  0       // ｯ
#define UC_HALFWIDTH_KATAKANA_HIRAGANA_PROLONGED_SOUND_MARK  0xFF70  0       // ｰ
#define UC_HALFWIDTH_KATAKANA_LETTER_A                       0xFF71  0       // ｱ
#define UC_HALFWIDTH_KATAKANA_LETTER_I                       0xFF72  0       // ｲ
#define UC_HALFWIDTH_KATAKANA_LETTER_U                       0xFF73  0       // ｳ
#define UC_HALFWIDTH_KATAKANA_LETTER_E                       0xFF74  0       // ｴ
#define UC_HALFWIDTH_KATAKANA_LETTER_O                       0xFF75  0       // ｵ
#define UC_HALFWIDTH_KATAKANA_LETTER_KA                      0xFF76  0       // ｶ
#define UC_HALFWIDTH_KATAKANA_LETTER_KI                      0xFF77  0       // ｷ
#define UC_HALFWIDTH_KATAKANA_LETTER_KU                      0xFF78  0       // ｸ
#define UC_HALFWIDTH_KATAKANA_LETTER_KE                      0xFF79  0       // ｹ
#define UC_HALFWIDTH_KATAKANA_LETTER_KO                      0xFF7A  0       // ｺ
#define UC_HALFWIDTH_KATAKANA_LETTER_SA                      0xFF7B  0       // ｻ
#define UC_HALFWIDTH_KATAKANA_LETTER_SI                      0xFF7C  0       // ｼ
#define UC_HALFWIDTH_KATAKANA_LETTER_SU                      0xFF7D  0       // ｽ
#define UC_HALFWIDTH_KATAKANA_LETTER_SE                      0xFF7E  0       // ｾ
#define UC_HALFWIDTH_KATAKANA_LETTER_SO                      0xFF7F  0       // ｿ
#define UC_HALFWIDTH_KATAKANA_LETTER_TA                      0xFF80  0       // ﾀ
#define UC_HALFWIDTH_KATAKANA_LETTER_TI                      0xFF81  0       // ﾁ
#define UC_HALFWIDTH_KATAKANA_LETTER_TU                      0xFF82  0       // ﾂ
#define UC_HALFWIDTH_KATAKANA_LETTER_TE                      0xFF83  0       // ﾃ
#define UC_HALFWIDTH_KATAKANA_LETTER_TO                      0xFF84  0       // ﾄ
#define UC_HALFWIDTH_KATAKANA_LETTER_NA                      0xFF85  0       // ﾅ
#define UC_HALFWIDTH_KATAKANA_LETTER_NI                      0xFF86  0       // ﾆ
#define UC_HALFWIDTH_KATAKANA_LETTER_NU                      0xFF87  0       // ﾇ
#define UC_HALFWIDTH_KATAKANA_LETTER_NE                      0xFF88  0       // ﾈ
#define UC_HALFWIDTH_KATAKANA_LETTER_NO                      0xFF89  0       // ﾉ
#define UC_HALFWIDTH_KATAKANA_LETTER_HA                      0xFF8A  0       // ﾊ
#define UC_HALFWIDTH_KATAKANA_LETTER_HI                      0xFF8B  0       // ﾋ
#define UC_HALFWIDTH_KATAKANA_LETTER_HU                      0xFF8C  0       // ﾌ
#define UC_HALFWIDTH_KATAKANA_LETTER_HE                      0xFF8D  0       // ﾍ
#define UC_HALFWIDTH_KATAKANA_LETTER_HO                      0xFF8E  0       // ﾎ
#define UC_HALFWIDTH_KATAKANA_LETTER_MA                      0xFF8F  0       // ﾏ
#define UC_HALFWIDTH_KATAKANA_LETTER_MI                      0xFF90  0       // ﾐ
#define UC_HALFWIDTH_KATAKANA_LETTER_MU                      0xFF91  0       // ﾑ
#define UC_HALFWIDTH_KATAKANA_LETTER_ME                      0xFF92  0       // ﾒ
#define UC_HALFWIDTH_KATAKANA_LETTER_MO                      0xFF93  0       // ﾓ
#define UC_HALFWIDTH_KATAKANA_LETTER_YA                      0xFF94  0       // ﾔ
#define UC_HALFWIDTH_KATAKANA_LETTER_YU                      0xFF95  0       // ﾕ
#define UC_HALFWIDTH_KATAKANA_LETTER_YO                      0xFF96  0       // ﾖ
#define UC_HALFWIDTH_KATAKANA_LETTER_RA                      0xFF97  0       // ﾗ
#define UC_HALFWIDTH_KATAKANA_LETTER_RI                      0xFF98  0       // ﾘ
#define UC_HALFWIDTH_KATAKANA_LETTER_RU                      0xFF99  0       // ﾙ
#define UC_HALFWIDTH_KATAKANA_LETTER_RE                      0xFF9A  0       // ﾚ
#define UC_HALFWIDTH_KATAKANA_LETTER_RO                      0xFF9B  0       // ﾛ
#define UC_HALFWIDTH_KATAKANA_LETTER_WA                      0xFF9C  0       // ﾜ
#define UC_HALFWIDTH_KATAKANA_LETTER_N                       0xFF9D  0       // ﾝ
#define UC_HALFWIDTH_KATAKANA_VOICED_SOUND_MARK              0xFF9E  0       // ﾞ
#define UC_HALFWIDTH_KATAKANA_SEMI_VOICED_SOUND_MARK         0xFF9F  0       // ﾟ
#define UC_HALFWIDTH_HANGUL_FILLER                           0xFFA0  0       // ﾠ
#define UC_HALFWIDTH_HANGUL_LETTER_KIYEOK                    0xFFA1  0       // ﾡ
#define UC_HALFWIDTH_HANGUL_LETTER_SSANGKIYEOK               0xFFA2  0       // ﾢ
#define UC_HALFWIDTH_HANGUL_LETTER_KIYEOK_SIOS               0xFFA3  0       // ﾣ
#define UC_HALFWIDTH_HANGUL_LETTER_NIEUN                     0xFFA4  0       // ﾤ
#define UC_HALFWIDTH_HANGUL_LETTER_NIEUN_CIEUC               0xFFA5  0       // ﾥ
#define UC_HALFWIDTH_HANGUL_LETTER_NIEUN_HIEUH               0xFFA6  0       // ﾦ
#define UC_HALFWIDTH_HANGUL_LETTER_TIKEUT                    0xFFA7  0       // ﾧ
#define UC_HALFWIDTH_HANGUL_LETTER_SSANGTIKEUT               0xFFA8  0       // ﾨ
#define UC_HALFWIDTH_HANGUL_LETTER_RIEUL                     0xFFA9  0       // ﾩ
#define UC_HALFWIDTH_HANGUL_LETTER_RIEUL_KIYEOK              0xFFAA  0       // ﾪ
#define UC_HALFWIDTH_HANGUL_LETTER_RIEUL_MIEUM               0xFFAB  0       // ﾫ
#define UC_HALFWIDTH_HANGUL_LETTER_RIEUL_PIEUP               0xFFAC  0       // ﾬ
#define UC_HALFWIDTH_HANGUL_LETTER_RIEUL_SIOS                0xFFAD  0       // ﾭ
#define UC_HALFWIDTH_HANGUL_LETTER_RIEUL_THIEUTH             0xFFAE  0       // ﾮ
#define UC_HALFWIDTH_HANGUL_LETTER_RIEUL_PHIEUPH             0xFFAF  0       // ﾯ
#define UC_HALFWIDTH_HANGUL_LETTER_RIEUL_HIEUH               0xFFB0  0       // ﾰ
#define UC_HALFWIDTH_HANGUL_LETTER_MIEUM                     0xFFB1  0       // ﾱ
#define UC_HALFWIDTH_HANGUL_LETTER_PIEUP                     0xFFB2  0       // ﾲ
#define UC_HALFWIDTH_HANGUL_LETTER_SSANGPIEUP                0xFFB3  0       // ﾳ
#define UC_HALFWIDTH_HANGUL_LETTER_PIEUP_SIOS                0xFFB4  0       // ﾴ
#define UC_HALFWIDTH_HANGUL_LETTER_SIOS                      0xFFB5  0       // ﾵ
#define UC_HALFWIDTH_HANGUL_LETTER_SSANGSIOS                 0xFFB6  0       // ﾶ
#define UC_HALFWIDTH_HANGUL_LETTER_IEUNG                     0xFFB7  0       // ﾷ
#define UC_HALFWIDTH_HANGUL_LETTER_CIEUC                     0xFFB8  0       // ﾸ
#define UC_HALFWIDTH_HANGUL_LETTER_SSANGCIEUC                0xFFB9  0       // ﾹ
#define UC_HALFWIDTH_HANGUL_LETTER_CHIEUCH                   0xFFBA  0       // ﾺ
#define UC_HALFWIDTH_HANGUL_LETTER_KHIEUKH                   0xFFBB  0       // ﾻ
#define UC_HALFWIDTH_HANGUL_LETTER_THIEUTH                   0xFFBC  0       // ﾼ
#define UC_HALFWIDTH_HANGUL_LETTER_PHIEUPH                   0xFFBD  0       // ﾽ
#define UC_HALFWIDTH_HANGUL_LETTER_HIEUH                     0xFFBE  0       // ﾾ
#define UC_HALFWIDTH_HANGUL_LETTER_A                         0xFFC2  0       // ￂ
#define UC_HALFWIDTH_HANGUL_LETTER_AE                        0xFFC3  0       // ￃ
#define UC_HALFWIDTH_HANGUL_LETTER_YA                        0xFFC4  0       // ￄ
#define UC_HALFWIDTH_HANGUL_LETTER_YAE                       0xFFC5  0       // ￅ
#define UC_HALFWIDTH_HANGUL_LETTER_EO                        0xFFC6  0       // ￆ
#define UC_HALFWIDTH_HANGUL_LETTER_E                         0xFFC7  0       // ￇ
#define UC_HALFWIDTH_HANGUL_LETTER_YEO                       0xFFCA  0       // ￊ
#define UC_HALFWIDTH_HANGUL_LETTER_YE                        0xFFCB  0       // ￋ
#define UC_HALFWIDTH_HANGUL_LETTER_O                         0xFFCC  0       // ￌ
#define UC_HALFWIDTH_HANGUL_LETTER_WA                        0xFFCD  0       // ￍ
#define UC_HALFWIDTH_HANGUL_LETTER_WAE                       0xFFCE  0       // ￎ
#define UC_HALFWIDTH_HANGUL_LETTER_OE                        0xFFCF  0       // ￏ
#define UC_HALFWIDTH_HANGUL_LETTER_YO                        0xFFD2  0       // ￒ
#define UC_HALFWIDTH_HANGUL_LETTER_U                         0xFFD3  0       // ￓ
#define UC_HALFWIDTH_HANGUL_LETTER_WEO                       0xFFD4  0       // ￔ
#define UC_HALFWIDTH_HANGUL_LETTER_WE                        0xFFD5  0       // ￕ
#define UC_HALFWIDTH_HANGUL_LETTER_WI                        0xFFD6  0       // ￖ
#define UC_HALFWIDTH_HANGUL_LETTER_YU                        0xFFD7  0       // ￗ
#define UC_HALFWIDTH_HANGUL_LETTER_EU                        0xFFDA  0       // ￚ
#define UC_HALFWIDTH_HANGUL_LETTER_YI                        0xFFDB  0       // ￛ
#define UC_HALFWIDTH_HANGUL_LETTER_I                         0xFFDC  0       // ￜ
#define UC_FULLWIDTH_CENT_SIGN                               0xFFE0  0       // ￠
#define UC_FULLWIDTH_POUND_SIGN                              0xFFE1  0       // ￡
#define UC_FULLWIDTH_NOT_SIGN                                0xFFE2  0       // ￢
#define UC_FULLWIDTH_MACRON                                  0xFFE3  0       // ￣
#define UC_FULLWIDTH_BROKEN_BAR                              0xFFE4  0       // ￤
#define UC_FULLWIDTH_YEN_SIGN                                0xFFE5  0       // ￥
#define UC_FULLWIDTH_WON_SIGN                                0xFFE6  0       // ￦
#define UC_HALFWIDTH_FORMS_LIGHT_VERTICAL                    0xFFE8  0       // ￨
#define UC_HALFWIDTH_LEFTWARDS_ARROW                         0xFFE9  0       // ￩
#define UC_HALFWIDTH_UPWARDS_ARROW                           0xFFEA  0       // ￪
#define UC_HALFWIDTH_RIGHTWARDS_ARROW                        0xFFEB  0       // ￫
#define UC_HALFWIDTH_DOWNWARDS_ARROW                         0xFFEC  0       // ￬
#define UC_HALFWIDTH_BLACK_SQUARE                            0xFFED  0       // ￭
#define UC_HALFWIDTH_WHITE_CIRCLE                            0xFFEE  0       // ￮