/*
 * Unicode keys for U+2FF0 .. U+2FFF
 *
 * This file was generated from Unicode 16.0.0.
 *
 * See http://www.unicode.org/versions/Unicode16.0.0 for source data.
 */

#pragma once

#define UC_IDEOGRAPHIC_DESCRIPTION_CHARACTER_LEFT_TO_RIGHT              0x2FF0  0  // ⿰
#define UC_IDEOGRAPHIC_DESCRIPTION_CHARACTER_ABOVE_TO_BELOW             0x2FF1  0  // ⿱
#define UC_IDEOGRAPHIC_DESCRIPTION_CHARACTER_LEFT_TO_MIDDLE_AND_RIGHT   0x2FF2  0  // ⿲
#define UC_IDEOGRAPHIC_DESCRIPTION_CHARACTER_ABOVE_TO_MIDDLE_AND_BELOW  0x2FF3  0  // ⿳
#define UC_IDEOGRAPHIC_DESCRIPTION_CHARACTER_FULL_SURROUND              0x2FF4  0  // ⿴
#define UC_IDEOGRAPHIC_DESCRIPTION_CHARACTER_SURROUND_FROM_ABOVE        0x2FF5  0  // ⿵
#define UC_IDEOGRAPHIC_DESCRIPTION_CHARACTER_SURROUND_FROM_BELOW        0x2FF6  0  // ⿶
#define UC_IDEOGRAPHIC_DESCRIPTION_CHARACTER_SURROUND_FROM_LEFT         0x2FF7  0  // ⿷
#define UC_IDEOGRAPHIC_DESCRIPTION_CHARACTER_SURROUND_FROM_UPPER_LEFT   0x2FF8  0  // ⿸
#define UC_IDEOGRAPHIC_DESCRIPTION_CHARACTER_SURROUND_FROM_UPPER_RIGHT  0x2FF9  0  // ⿹
#define UC_IDEOGRAPHIC_DESCRIPTION_CHARACTER_SURROUND_FROM_LOWER_LEFT   0x2FFA  0  // ⿺
#define UC_IDEOGRAPHIC_DESCRIPTION_CHARACTER_OVERLAID                   0x2FFB  0  // ⿻
#define UC_IDEOGRAPHIC_DESCRIPTION_CHARACTER_SURROUND_FROM_RIGHT        0x2FFC  0  // ⿼
#define UC_IDEOGRAPHIC_DESCRIPTION_CHARACTER_SURROUND_FROM_LOWER_RIGHT  0x2FFD  0  // ⿽
#define UC_IDEOGRAPHIC_DESCRIPTION_CHARACTER_HORIZONTAL_REFLECTION      0x2FFE  0  // ⿾
#define UC_IDEOGRAPHIC_DESCRIPTION_CHARACTER_ROTATION                   0x2FFF  0  // ⿿