/*
 * Unicode keys for U+10B60 .. U+10B7F
 *
 * This file was generated from Unicode 16.0.0.
 *
 * See http://www.unicode.org/versions/Unicode16.0.0 for source data.
 */

#pragma once

#define UC_INSCRIPTIONAL_PAHLAVI_LETTER_ALEPH          0x10B60  0  // 𐭠
#define UC_INSCRIPTIONAL_PAHLAVI_LETTER_BETH           0x10B61  0  // 𐭡
#define UC_INSCRIPTIONAL_PAHLAVI_LETTER_GIMEL          0x10B62  0  // 𐭢
#define UC_INSCRIPTIONAL_PAHLAVI_LETTER_DALETH         0x10B63  0  // 𐭣
#define UC_INSCRIPTIONAL_PAHLAVI_LETTER_HE             0x10B64  0  // 𐭤
#define UC_INSCRIPTIONAL_PAHLAVI_LETTER_WAW_AYIN_RESH  0x10B65  0  // 𐭥
#define UC_INSCRIPTIONAL_PAHLAVI_LETTER_ZAYIN          0x10B66  0  // 𐭦
#define UC_INSCRIPTIONAL_PAHLAVI_LETTER_HETH           0x10B67  0  // 𐭧
#define UC_INSCRIPTIONAL_PAHLAVI_LETTER_TETH           0x10B68  0  // 𐭨
#define UC_INSCRIPTIONAL_PAHLAVI_LETTER_YODH           0x10B69  0  // 𐭩
#define UC_INSCRIPTIONAL_PAHLAVI_LETTER_KAPH           0x10B6A  0  // 𐭪
#define UC_INSCRIPTIONAL_PAHLAVI_LETTER_LAMEDH         0x10B6B  0  // 𐭫
#define UC_INSCRIPTIONAL_PAHLAVI_LETTER_MEM_QOPH       0x10B6C  0  // 𐭬
#define UC_INSCRIPTIONAL_PAHLAVI_LETTER_NUN            0x10B6D  0  // 𐭭
#define UC_INSCRIPTIONAL_PAHLAVI_LETTER_SAMEKH         0x10B6E  0  // 𐭮
#define UC_INSCRIPTIONAL_PAHLAVI_LETTER_PE             0x10B6F  0  // 𐭯
#define UC_INSCRIPTIONAL_PAHLAVI_LETTER_SADHE          0x10B70  0  // 𐭰
#define UC_INSCRIPTIONAL_PAHLAVI_LETTER_SHIN           0x10B71  0  // 𐭱
#define UC_INSCRIPTIONAL_PAHLAVI_LETTER_TAW            0x10B72  0  // 𐭲
#define UC_INSCRIPTIONAL_PAHLAVI_NUMBER_ONE            0x10B78  0  // 𐭸
#define UC_INSCRIPTIONAL_PAHLAVI_NUMBER_TWO            0x10B79  0  // 𐭹
#define UC_INSCRIPTIONAL_PAHLAVI_NUMBER_THREE          0x10B7A  0  // 𐭺
#define UC_INSCRIPTIONAL_PAHLAVI_NUMBER_FOUR           0x10B7B  0  // 𐭻
#define UC_INSCRIPTIONAL_PAHLAVI_NUMBER_TEN            0x10B7C  0  // 𐭼
#define UC_INSCRIPTIONAL_PAHLAVI_NUMBER_TWENTY         0x10B7D  0  // 𐭽
#define UC_INSCRIPTIONAL_PAHLAVI_NUMBER_ONE_HUNDRED    0x10B7E  0  // 𐭾
#define UC_INSCRIPTIONAL_PAHLAVI_NUMBER_ONE_THOUSAND   0x10B7F  0  // 𐭿