/*
 * Unicode keys for U+10B40 .. U+10B5F
 *
 * This file was generated from Unicode 16.0.0.
 *
 * See http://www.unicode.org/versions/Unicode16.0.0 for source data.
 */

#pragma once

#define UC_INSCRIPTIONAL_PARTHIAN_LETTER_ALEPH         0x10B40  0  // 𐭀
#define UC_INSCRIPTIONAL_PARTHIAN_LETTER_BETH          0x10B41  0  // 𐭁
#define UC_INSCRIPTIONAL_PARTHIAN_LETTER_GIMEL         0x10B42  0  // 𐭂
#define UC_INSCRIPTIONAL_PARTHIAN_LETTER_DALETH        0x10B43  0  // 𐭃
#define UC_INSCRIPTIONAL_PARTHIAN_LETTER_HE            0x10B44  0  // 𐭄
#define UC_INSCRIPTIONAL_PARTHIAN_LETTER_WAW           0x10B45  0  // 𐭅
#define UC_INSCRIPTIONAL_PARTHIAN_LETTER_ZAYIN         0x10B46  0  // 𐭆
#define UC_INSCRIPTIONAL_PARTHIAN_LETTER_HETH          0x10B47  0  // 𐭇
#define UC_INSCRIPTIONAL_PARTHIAN_LETTER_TETH          0x10B48  0  // 𐭈
#define UC_INSCRIPTIONAL_PARTHIAN_LETTER_YODH          0x10B49  0  // 𐭉
#define UC_INSCRIPTIONAL_PARTHIAN_LETTER_KAPH          0x10B4A  0  // 𐭊
#define UC_INSCRIPTIONAL_PARTHIAN_LETTER_LAMEDH        0x10B4B  0  // 𐭋
#define UC_INSCRIPTIONAL_PARTHIAN_LETTER_MEM           0x10B4C  0  // 𐭌
#define UC_INSCRIPTIONAL_PARTHIAN_LETTER_NUN           0x10B4D  0  // 𐭍
#define UC_INSCRIPTIONAL_PARTHIAN_LETTER_SAMEKH        0x10B4E  0  // 𐭎
#define UC_INSCRIPTIONAL_PARTHIAN_LETTER_AYIN          0x10B4F  0  // 𐭏
#define UC_INSCRIPTIONAL_PARTHIAN_LETTER_PE            0x10B50  0  // 𐭐
#define UC_INSCRIPTIONAL_PARTHIAN_LETTER_SADHE         0x10B51  0  // 𐭑
#define UC_INSCRIPTIONAL_PARTHIAN_LETTER_QOPH          0x10B52  0  // 𐭒
#define UC_INSCRIPTIONAL_PARTHIAN_LETTER_RESH          0x10B53  0  // 𐭓
#define UC_INSCRIPTIONAL_PARTHIAN_LETTER_SHIN          0x10B54  0  // 𐭔
#define UC_INSCRIPTIONAL_PARTHIAN_LETTER_TAW           0x10B55  0  // 𐭕
#define UC_INSCRIPTIONAL_PARTHIAN_NUMBER_ONE           0x10B58  0  // 𐭘
#define UC_INSCRIPTIONAL_PARTHIAN_NUMBER_TWO           0x10B59  0  // 𐭙
#define UC_INSCRIPTIONAL_PARTHIAN_NUMBER_THREE         0x10B5A  0  // 𐭚
#define UC_INSCRIPTIONAL_PARTHIAN_NUMBER_FOUR          0x10B5B  0  // 𐭛
#define UC_INSCRIPTIONAL_PARTHIAN_NUMBER_TEN           0x10B5C  0  // 𐭜
#define UC_INSCRIPTIONAL_PARTHIAN_NUMBER_TWENTY        0x10B5D  0  // 𐭝
#define UC_INSCRIPTIONAL_PARTHIAN_NUMBER_ONE_HUNDRED   0x10B5E  0  // 𐭞
#define UC_INSCRIPTIONAL_PARTHIAN_NUMBER_ONE_THOUSAND  0x10B5F  0  // 𐭟