/*
 * Unicode keys for U+3190 .. U+319F
 *
 * This file was generated from Unicode 16.0.0.
 *
 * See http://www.unicode.org/versions/Unicode16.0.0 for source data.
 */

#pragma once

#define UC_IDEOGRAPHIC_ANNOTATION_LINKING_MARK  0x3190  0  // ㆐
#define UC_IDEOGRAPHIC_ANNOTATION_REVERSE_MARK  0x3191  0  // ㆑
#define UC_IDEOGRAPHIC_ANNOTATION_ONE_MARK      0x3192  0  // ㆒
#define UC_IDEOGRAPHIC_ANNOTATION_TWO_MARK      0x3193  0  // ㆓
#define UC_IDEOGRAPHIC_ANNOTATION_THREE_MARK    0x3194  0  // ㆔
#define UC_IDEOGRAPHIC_ANNOTATION_FOUR_MARK     0x3195  0  // ㆕
#define UC_IDEOGRAPHIC_ANNOTATION_TOP_MARK      0x3196  0  // ㆖
#define UC_IDEOGRAPHIC_ANNOTATION_MIDDLE_MARK   0x3197  0  // ㆗
#define UC_IDEOGRAPHIC_ANNOTATION_BOTTOM_MARK   0x3198  0  // ㆘
#define UC_IDEOGRAPHIC_ANNOTATION_FIRST_MARK    0x3199  0  // ㆙
#define UC_IDEOGRAPHIC_ANNOTATION_SECOND_MARK   0x319A  0  // ㆚
#define UC_IDEOGRAPHIC_ANNOTATION_THIRD_MARK    0x319B  0  // ㆛
#define UC_IDEOGRAPHIC_ANNOTATION_FOURTH_MARK   0x319C  0  // ㆜
#define UC_IDEOGRAPHIC_ANNOTATION_HEAVEN_MARK   0x319D  0  // ㆝
#define UC_IDEOGRAPHIC_ANNOTATION_EARTH_MARK    0x319E  0  // ㆞
#define UC_IDEOGRAPHIC_ANNOTATION_MAN_MARK      0x319F  0  // ㆟