/*
 * Unicode keys for U+0180 .. U+024F
 *
 * This file was generated from Unicode 16.0.0.
 *
 * See http://www.unicode.org/versions/Unicode16.0.0 for source data.
 */

#pragma once

#define UC_LATIN_LETTER_B_WITH_STROKE                      0x180   0x243   // ƀ/Ƀ
#define UC_LATIN_LETTER_B_WITH_HOOK                        0x253   0x181   // ɓ/Ɓ
#define UC_LATIN_LETTER_B_WITH_TOPBAR                      0x183   0x182   // ƃ/Ƃ
#define UC_LATIN_LETTER_TONE_SIX                           0x185   0x184   // ƅ/Ƅ
#define UC_LATIN_LETTER_OPEN_O                             0x254   0x186   // ɔ/Ɔ
#define UC_LATIN_LETTER_C_WITH_HOOK                        0x188   0x187   // ƈ/Ƈ
#define UC_LATIN_LETTER_D_WITH_TAIL                        0x256   0x189   // ɖ/Ɖ
#define UC_LATIN_LETTER_D_WITH_HOOK                        0x257   0x18A   // ɗ/Ɗ
#define UC_LATIN_LETTER_D_WITH_TOPBAR                      0x18C   0x18B   // ƌ/Ƌ
#define UC_LATIN_SMALL_LETTER_TURNED_DELTA                 0x18D   0       // ƍ
#define UC_LATIN_LETTER_TURNED_E                           0x1DD   0x18E   // ǝ/Ǝ
#define UC_LATIN_LETTER_SCHWA                              0x259   0x18F   // ə/Ə
#define UC_LATIN_LETTER_OPEN_E                             0x25B   0x190   // ɛ/Ɛ
#define UC_LATIN_LETTER_F_WITH_HOOK                        0x192   0x191   // ƒ/Ƒ
#define UC_LATIN_LETTER_G_WITH_HOOK                        0x260   0x193   // ɠ/Ɠ
#define UC_LATIN_LETTER_GAMMA                              0x263   0x194   // ɣ/Ɣ
#define UC_LATIN_LETTER_HV                                 0x195   0x1F6   // ƕ/Ƕ
#define UC_LATIN_LETTER_IOTA                               0x269   0x196   // ɩ/Ɩ
#define UC_LATIN_LETTER_I_WITH_STROKE                      0x268   0x197   // ɨ/Ɨ
#define UC_LATIN_LETTER_K_WITH_HOOK                        0x199   0x198   // ƙ/Ƙ
#define UC_LATIN_LETTER_L_WITH_BAR                         0x19A   0x23D   // ƚ/Ƚ
#define UC_LATIN_LETTER_LAMBDA_WITH_STROKE                 0x19B   0xA7DC  // ƛ/Ƛ
#define UC_LATIN_LETTER_TURNED_M                           0x26F   0x19C   // ɯ/Ɯ
#define UC_LATIN_LETTER_N_WITH_LEFT_HOOK                   0x272   0x19D   // ɲ/Ɲ
#define UC_LATIN_LETTER_N_WITH_LONG_RIGHT_LEG              0x19E   0x220   // ƞ/Ƞ
#define UC_LATIN_LETTER_BARRED_O                           0x275   0x19F   // ɵ/Ɵ
#define UC_LATIN_LETTER_O_WITH_HORN                        0x1A1   0x1A0   // ơ/Ơ
#define UC_LATIN_LETTER_OI                                 0x1A3   0x1A2   // ƣ/Ƣ
#define UC_LATIN_LETTER_P_WITH_HOOK                        0x1A5   0x1A4   // ƥ/Ƥ
#define UC_LATIN_LETTER_SMALL_CAPITAL_R                    0x280   0x1A6   // ʀ/Ʀ
#define UC_LATIN_LETTER_TONE_TWO                           0x1A8   0x1A7   // ƨ/Ƨ
#define UC_LATIN_LETTER_ESH                                0x283   0x1A9   // ʃ/Ʃ
#define UC_LATIN_LETTER_REVERSED_ESH_LOOP                  0x1AA   0       // ƪ
#define UC_LATIN_SMALL_LETTER_T_WITH_PALATAL_HOOK          0x1AB   0       // ƫ
#define UC_LATIN_LETTER_T_WITH_HOOK                        0x1AD   0x1AC   // ƭ/Ƭ
#define UC_LATIN_LETTER_T_WITH_RETROFLEX_HOOK              0x288   0x1AE   // ʈ/Ʈ
#define UC_LATIN_LETTER_U_WITH_HORN                        0x1B0   0x1AF   // ư/Ư
#define UC_LATIN_LETTER_UPSILON                            0x28A   0x1B1   // ʊ/Ʊ
#define UC_LATIN_LETTER_V_WITH_HOOK                        0x28B   0x1B2   // ʋ/Ʋ
#define UC_LATIN_LETTER_Y_WITH_HOOK                        0x1B4   0x1B3   // ƴ/Ƴ
#define UC_LATIN_LETTER_Z_WITH_STROKE                      0x1B6   0x1B5   // ƶ/Ƶ
#define UC_LATIN_LETTER_EZH                                0x292   0x1B7   // ʒ/Ʒ
#define UC_LATIN_LETTER_EZH_REVERSED                       0x1B9   0x1B8   // ƹ/Ƹ
#define UC_LATIN_SMALL_LETTER_EZH_WITH_TAIL                0x1BA   0       // ƺ
#define UC_LATIN_LETTER_TWO_WITH_STROKE                    0x1BB   0       // ƻ
#define UC_LATIN_LETTER_TONE_FIVE                          0x1BD   0x1BC   // ƽ/Ƽ
#define UC_LATIN_LETTER_INVERTED_GLOTTAL_STOP_WITH_STROKE  0x1BE   0       // ƾ
#define UC_LATIN_LETTER_WYNN                               0x1BF   0x1F7   // ƿ/Ƿ
#define UC_LATIN_LETTER_DENTAL_CLICK                       0x1C0   0       // ǀ
#define UC_LATIN_LETTER_LATERAL_CLICK                      0x1C1   0       // ǁ
#define UC_LATIN_LETTER_ALVEOLAR_CLICK                     0x1C2   0       // ǂ
#define UC_LATIN_LETTER_RETROFLEX_CLICK                    0x1C3   0       // ǃ
#define UC_LATIN_LETTER_DZ_WITH_CARON                      0x1C6   0x1C4   // ǆ/Ǆ
#define UC_LATIN_LETTER_LJ                                 0x1C9   0x1C7   // ǉ/Ǉ
#define UC_LATIN_LETTER_NJ                                 0x1CC   0x1CA   // ǌ/Ǌ
#define UC_LATIN_LETTER_A_WITH_CARON                       0x1CE   0x1CD   // ǎ/Ǎ
#define UC_LATIN_LETTER_I_WITH_CARON                       0x1D0   0x1CF   // ǐ/Ǐ
#define UC_LATIN_LETTER_O_WITH_CARON                       0x1D2   0x1D1   // ǒ/Ǒ
#define UC_LATIN_LETTER_U_WITH_CARON                       0x1D4   0x1D3   // ǔ/Ǔ
#define UC_LATIN_LETTER_U_WITH_DIAERESIS_AND_MACRON        0x1D6   0x1D5   // ǖ/Ǖ
#define UC_LATIN_LETTER_U_WITH_DIAERESIS_AND_ACUTE         0x1D8   0x1D7   // ǘ/Ǘ
#define UC_LATIN_LETTER_U_WITH_DIAERESIS_AND_CARON         0x1DA   0x1D9   // ǚ/Ǚ
#define UC_LATIN_LETTER_U_WITH_DIAERESIS_AND_GRAVE         0x1DC   0x1DB   // ǜ/Ǜ
#define UC_LATIN_LETTER_A_WITH_DIAERESIS_AND_MACRON        0x1DF   0x1DE   // ǟ/Ǟ
#define UC_LATIN_LETTER_A_WITH_DOT_ABOVE_AND_MACRON        0x1E1   0x1E0   // ǡ/Ǡ
#define UC_LATIN_LETTER_AE_WITH_MACRON                     0x1E3   0x1E2   // ǣ/Ǣ
#define UC_LATIN_LETTER_G_WITH_STROKE                      0x1E5   0x1E4   // ǥ/Ǥ
#define UC_LATIN_LETTER_G_WITH_CARON                       0x1E7   0x1E6   // ǧ/Ǧ
#define UC_LATIN_LETTER_K_WITH_CARON                       0x1E9   0x1E8   // ǩ/Ǩ
#define UC_LATIN_LETTER_O_WITH_OGONEK                      0x1EB   0x1EA   // ǫ/Ǫ
#define UC_LATIN_LETTER_O_WITH_OGONEK_AND_MACRON           0x1ED   0x1EC   // ǭ/Ǭ
#define UC_LATIN_LETTER_EZH_WITH_CARON                     0x1EF   0x1EE   // ǯ/Ǯ
#define UC_LATIN_SMALL_LETTER_J_WITH_CARON                 0x1F0   0       // ǰ
#define UC_LATIN_LETTER_DZ                                 0x1F3   0x1F1   // ǳ/Ǳ
#define UC_LATIN_LETTER_G_WITH_ACUTE                       0x1F5   0x1F4   // ǵ/Ǵ
#define UC_LATIN_LETTER_N_WITH_GRAVE                       0x1F9   0x1F8   // ǹ/Ǹ
#define UC_LATIN_LETTER_A_WITH_RING_ABOVE_AND_ACUTE        0x1FB   0x1FA   // ǻ/Ǻ
#define UC_LATIN_LETTER_AE_WITH_ACUTE                      0x1FD   0x1FC   // ǽ/Ǽ
#define UC_LATIN_LETTER_O_WITH_STROKE_AND_ACUTE            0x1FF   0x1FE   // ǿ/Ǿ
#define UC_LATIN_LETTER_A_WITH_DOUBLE_GRAVE                0x201   0x200   // ȁ/Ȁ
#define UC_LATIN_LETTER_A_WITH_INVERTED_BREVE              0x203   0x202   // ȃ/Ȃ
#define UC_LATIN_LETTER_E_WITH_DOUBLE_GRAVE                0x205   0x204   // ȅ/Ȅ
#define UC_LATIN_LETTER_E_WITH_INVERTED_BREVE              0x207   0x206   // ȇ/Ȇ
#define UC_LATIN_LETTER_I_WITH_DOUBLE_GRAVE                0x209   0x208   // ȉ/Ȉ
#define UC_LATIN_LETTER_I_WITH_INVERTED_BREVE              0x20B   0x20A   // ȋ/Ȋ
#define UC_LATIN_LETTER_O_WITH_DOUBLE_GRAVE                0x20D   0x20C   // ȍ/Ȍ
#define UC_LATIN_LETTER_O_WITH_INVERTED_BREVE              0x20F   0x20E   // ȏ/Ȏ
#define UC_LATIN_LETTER_R_WITH_DOUBLE_GRAVE                0x211   0x210   // ȑ/Ȑ
#define UC_LATIN_LETTER_R_WITH_INVERTED_BREVE              0x213   0x212   // ȓ/Ȓ
#define UC_LATIN_LETTER_U_WITH_DOUBLE_GRAVE                0x215   0x214   // ȕ/Ȕ
#define UC_LATIN_LETTER_U_WITH_INVERTED_BREVE              0x217   0x216   // ȗ/Ȗ
#define UC_LATIN_LETTER_S_WITH_COMMA_BELOW                 0x219   0x218   // ș/Ș
#define UC_LATIN_LETTER_T_WITH_COMMA_BELOW                 0x21B   0x21A   // ț/Ț
#define UC_LATIN_LETTER_YOGH                               0x21D   0x21C   // ȝ/Ȝ
#define UC_LATIN_LETTER_H_WITH_CARON                       0x21F   0x21E   // ȟ/Ȟ
#define UC_LATIN_SMALL_LETTER_D_WITH_CURL                  0x221   0       // ȡ
#define UC_LATIN_LETTER_OU                                 0x223   0x222   // ȣ/Ȣ
#define UC_LATIN_LETTER_Z_WITH_HOOK                        0x225   0x224   // ȥ/Ȥ
#define UC_LATIN_LETTER_A_WITH_DOT_ABOVE                   0x227   0x226   // ȧ/Ȧ
#define UC_LATIN_LETTER_E_WITH_CEDILLA                     0x229   0x228   // ȩ/Ȩ
#define UC_LATIN_LETTER_O_WITH_DIAERESIS_AND_MACRON        0x22B   0x22A   // ȫ/Ȫ
#define UC_LATIN_LETTER_O_WITH_TILDE_AND_MACRON            0x22D   0x22C   // ȭ/Ȭ
#define UC_LATIN_LETTER_O_WITH_DOT_ABOVE                   0x22F   0x22E   // ȯ/Ȯ
#define UC_LATIN_LETTER_O_WITH_DOT_ABOVE_AND_MACRON        0x231   0x230   // ȱ/Ȱ
#define UC_LATIN_LETTER_Y_WITH_MACRON                      0x233   0x232   // ȳ/Ȳ
#define UC_LATIN_SMALL_LETTER_L_WITH_CURL                  0x234   0       // ȴ
#define UC_LATIN_SMALL_LETTER_N_WITH_CURL                  0x235   0       // ȵ
#define UC_LATIN_SMALL_LETTER_T_WITH_CURL                  0x236   0       // ȶ
#define UC_LATIN_SMALL_LETTER_DOTLESS_J                    0x237   0       // ȷ
#define UC_LATIN_SMALL_LETTER_DB_DIGRAPH                   0x238   0       // ȸ
#define UC_LATIN_SMALL_LETTER_QP_DIGRAPH                   0x239   0       // ȹ
#define UC_LATIN_LETTER_A_WITH_STROKE                      0x2C65  0x23A   // ⱥ/Ⱥ
#define UC_LATIN_LETTER_C_WITH_STROKE                      0x23C   0x23B   // ȼ/Ȼ
#define UC_LATIN_LETTER_T_WITH_DIAGONAL_STROKE             0x2C66  0x23E   // ⱦ/Ⱦ
#define UC_LATIN_LETTER_S_WITH_SWASH_TAIL                  0x23F   0x2C7E  // ȿ/Ȿ
#define UC_LATIN_LETTER_Z_WITH_SWASH_TAIL                  0x240   0x2C7F  // ɀ/Ɀ
#define UC_LATIN_LETTER_GLOTTAL_STOP                       0x242   0x241   // ɂ/Ɂ
#define UC_LATIN_LETTER_U_BAR                              0x289   0x244   // ʉ/Ʉ
#define UC_LATIN_LETTER_TURNED_V                           0x28C   0x245   // ʌ/Ʌ
#define UC_LATIN_LETTER_E_WITH_STROKE                      0x247   0x246   // ɇ/Ɇ
#define UC_LATIN_LETTER_J_WITH_STROKE                      0x249   0x248   // ɉ/Ɉ
#define UC_LATIN_LETTER_Q_WITH_HOOK_TAIL                   0x24B   0x24A   // ɋ/Ɋ
#define UC_LATIN_LETTER_R_WITH_STROKE                      0x24D   0x24C   // ɍ/Ɍ
#define UC_LATIN_LETTER_Y_WITH_STROKE                      0x24F   0x24E   // ɏ/Ɏ