/*
 * Unicode keys for U+1E00 .. U+1EFF
 *
 * This file was generated from Unicode 16.0.0.
 *
 * See http://www.unicode.org/versions/Unicode16.0.0 for source data.
 */

#pragma once

#define UC_LATIN_LETTER_A_WITH_RING_BELOW                  0x1E01  0x1E00  // ḁ/Ḁ
#define UC_LATIN_LETTER_B_WITH_DOT_ABOVE                   0x1E03  0x1E02  // ḃ/Ḃ
#define UC_LATIN_LETTER_B_WITH_DOT_BELOW                   0x1E05  0x1E04  // ḅ/Ḅ
#define UC_LATIN_LETTER_B_WITH_LINE_BELOW                  0x1E07  0x1E06  // ḇ/Ḇ
#define UC_LATIN_LETTER_C_WITH_CEDILLA_AND_ACUTE           0x1E09  0x1E08  // ḉ/Ḉ
#define UC_LATIN_LETTER_D_WITH_DOT_ABOVE                   0x1E0B  0x1E0A  // ḋ/Ḋ
#define UC_LATIN_LETTER_D_WITH_DOT_BELOW                   0x1E0D  0x1E0C  // ḍ/Ḍ
#define UC_LATIN_LETTER_D_WITH_LINE_BELOW                  0x1E0F  0x1E0E  // ḏ/Ḏ
#define UC_LATIN_LETTER_D_WITH_CEDILLA                     0x1E11  0x1E10  // ḑ/Ḑ
#define UC_LATIN_LETTER_D_WITH_CIRCUMFLEX_BELOW            0x1E13  0x1E12  // ḓ/Ḓ
#define UC_LATIN_LETTER_E_WITH_MACRON_AND_GRAVE            0x1E15  0x1E14  // ḕ/Ḕ
#define UC_LATIN_LETTER_E_WITH_MACRON_AND_ACUTE            0x1E17  0x1E16  // ḗ/Ḗ
#define UC_LATIN_LETTER_E_WITH_CIRCUMFLEX_BELOW            0x1E19  0x1E18  // ḙ/Ḙ
#define UC_LATIN_LETTER_E_WITH_TILDE_BELOW                 0x1E1B  0x1E1A  // ḛ/Ḛ
#define UC_LATIN_LETTER_E_WITH_CEDILLA_AND_BREVE           0x1E1D  0x1E1C  // ḝ/Ḝ
#define UC_LATIN_LETTER_F_WITH_DOT_ABOVE                   0x1E1F  0x1E1E  // ḟ/Ḟ
#define UC_LATIN_LETTER_G_WITH_MACRON                      0x1E21  0x1E20  // ḡ/Ḡ
#define UC_LATIN_LETTER_H_WITH_DOT_ABOVE                   0x1E23  0x1E22  // ḣ/Ḣ
#define UC_LATIN_LETTER_H_WITH_DOT_BELOW                   0x1E25  0x1E24  // ḥ/Ḥ
#define UC_LATIN_LETTER_H_WITH_DIAERESIS                   0x1E27  0x1E26  // ḧ/Ḧ
#define UC_LATIN_LETTER_H_WITH_CEDILLA                     0x1E29  0x1E28  // ḩ/Ḩ
#define UC_LATIN_LETTER_H_WITH_BREVE_BELOW                 0x1E2B  0x1E2A  // ḫ/Ḫ
#define UC_LATIN_LETTER_I_WITH_TILDE_BELOW                 0x1E2D  0x1E2C  // ḭ/Ḭ
#define UC_LATIN_LETTER_I_WITH_DIAERESIS_AND_ACUTE         0x1E2F  0x1E2E  // ḯ/Ḯ
#define UC_LATIN_LETTER_K_WITH_ACUTE                       0x1E31  0x1E30  // ḱ/Ḱ
#define UC_LATIN_LETTER_K_WITH_DOT_BELOW                   0x1E33  0x1E32  // ḳ/Ḳ
#define UC_LATIN_LETTER_K_WITH_LINE_BELOW                  0x1E35  0x1E34  // ḵ/Ḵ
#define UC_LATIN_LETTER_L_WITH_DOT_BELOW                   0x1E37  0x1E36  // ḷ/Ḷ
#define UC_LATIN_LETTER_L_WITH_DOT_BELOW_AND_MACRON        0x1E39  0x1E38  // ḹ/Ḹ
#define UC_LATIN_LETTER_L_WITH_LINE_BELOW                  0x1E3B  0x1E3A  // ḻ/Ḻ
#define UC_LATIN_LETTER_L_WITH_CIRCUMFLEX_BELOW            0x1E3D  0x1E3C  // ḽ/Ḽ
#define UC_LATIN_LETTER_M_WITH_ACUTE                       0x1E3F  0x1E3E  // ḿ/Ḿ
#define UC_LATIN_LETTER_M_WITH_DOT_ABOVE                   0x1E41  0x1E40  // ṁ/Ṁ
#define UC_LATIN_LETTER_M_WITH_DOT_BELOW                   0x1E43  0x1E42  // ṃ/Ṃ
#define UC_LATIN_LETTER_N_WITH_DOT_ABOVE                   0x1E45  0x1E44  // ṅ/Ṅ
#define UC_LATIN_LETTER_N_WITH_DOT_BELOW                   0x1E47  0x1E46  // ṇ/Ṇ
#define UC_LATIN_LETTER_N_WITH_LINE_BELOW                  0x1E49  0x1E48  // ṉ/Ṉ
#define UC_LATIN_LETTER_N_WITH_CIRCUMFLEX_BELOW            0x1E4B  0x1E4A  // ṋ/Ṋ
#define UC_LATIN_LETTER_O_WITH_TILDE_AND_ACUTE             0x1E4D  0x1E4C  // ṍ/Ṍ
#define UC_LATIN_LETTER_O_WITH_TILDE_AND_DIAERESIS         0x1E4F  0x1E4E  // ṏ/Ṏ
#define UC_LATIN_LETTER_O_WITH_MACRON_AND_GRAVE            0x1E51  0x1E50  // ṑ/Ṑ
#define UC_LATIN_LETTER_O_WITH_MACRON_AND_ACUTE            0x1E53  0x1E52  // ṓ/Ṓ
#define UC_LATIN_LETTER_P_WITH_ACUTE                       0x1E55  0x1E54  // ṕ/Ṕ
#define UC_LATIN_LETTER_P_WITH_DOT_ABOVE                   0x1E57  0x1E56  // ṗ/Ṗ
#define UC_LATIN_LETTER_R_WITH_DOT_ABOVE                   0x1E59  0x1E58  // ṙ/Ṙ
#define UC_LATIN_LETTER_R_WITH_DOT_BELOW                   0x1E5B  0x1E5A  // ṛ/Ṛ
#define UC_LATIN_LETTER_R_WITH_DOT_BELOW_AND_MACRON        0x1E5D  0x1E5C  // ṝ/Ṝ
#define UC_LATIN_LETTER_R_WITH_LINE_BELOW                  0x1E5F  0x1E5E  // ṟ/Ṟ
#define UC_LATIN_LETTER_S_WITH_DOT_ABOVE                   0x1E61  0x1E60  // ṡ/Ṡ
#define UC_LATIN_LETTER_S_WITH_DOT_BELOW                   0x1E63  0x1E62  // ṣ/Ṣ
#define UC_LATIN_LETTER_S_WITH_ACUTE_AND_DOT_ABOVE         0x1E65  0x1E64  // ṥ/Ṥ
#define UC_LATIN_LETTER_S_WITH_CARON_AND_DOT_ABOVE         0x1E67  0x1E66  // ṧ/Ṧ
#define UC_LATIN_LETTER_S_WITH_DOT_BELOW_AND_DOT_ABOVE     0x1E69  0x1E68  // ṩ/Ṩ
#define UC_LATIN_LETTER_T_WITH_DOT_ABOVE                   0x1E6B  0x1E6A  // ṫ/Ṫ
#define UC_LATIN_LETTER_T_WITH_DOT_BELOW                   0x1E6D  0x1E6C  // ṭ/Ṭ
#define UC_LATIN_LETTER_T_WITH_LINE_BELOW                  0x1E6F  0x1E6E  // ṯ/Ṯ
#define UC_LATIN_LETTER_T_WITH_CIRCUMFLEX_BELOW            0x1E71  0x1E70  // ṱ/Ṱ
#define UC_LATIN_LETTER_U_WITH_DIAERESIS_BELOW             0x1E73  0x1E72  // ṳ/Ṳ
#define UC_LATIN_LETTER_U_WITH_TILDE_BELOW                 0x1E75  0x1E74  // ṵ/Ṵ
#define UC_LATIN_LETTER_U_WITH_CIRCUMFLEX_BELOW            0x1E77  0x1E76  // ṷ/Ṷ
#define UC_LATIN_LETTER_U_WITH_TILDE_AND_ACUTE             0x1E79  0x1E78  // ṹ/Ṹ
#define UC_LATIN_LETTER_U_WITH_MACRON_AND_DIAERESIS        0x1E7B  0x1E7A  // ṻ/Ṻ
#define UC_LATIN_LETTER_V_WITH_TILDE                       0x1E7D  0x1E7C  // ṽ/Ṽ
#define UC_LATIN_LETTER_V_WITH_DOT_BELOW                   0x1E7F  0x1E7E  // ṿ/Ṿ
#define UC_LATIN_LETTER_W_WITH_GRAVE                       0x1E81  0x1E80  // ẁ/Ẁ
#define UC_LATIN_LETTER_W_WITH_ACUTE                       0x1E83  0x1E82  // ẃ/Ẃ
#define UC_LATIN_LETTER_W_WITH_DIAERESIS                   0x1E85  0x1E84  // ẅ/Ẅ
#define UC_LATIN_LETTER_W_WITH_DOT_ABOVE                   0x1E87  0x1E86  // ẇ/Ẇ
#define UC_LATIN_LETTER_W_WITH_DOT_BELOW                   0x1E89  0x1E88  // ẉ/Ẉ
#define UC_LATIN_LETTER_X_WITH_DOT_ABOVE                   0x1E8B  0x1E8A  // ẋ/Ẋ
#define UC_LATIN_LETTER_X_WITH_DIAERESIS                   0x1E8D  0x1E8C  // ẍ/Ẍ
#define UC_LATIN_LETTER_Y_WITH_DOT_ABOVE                   0x1E8F  0x1E8E  // ẏ/Ẏ
#define UC_LATIN_LETTER_Z_WITH_CIRCUMFLEX                  0x1E91  0x1E90  // ẑ/Ẑ
#define UC_LATIN_LETTER_Z_WITH_DOT_BELOW                   0x1E93  0x1E92  // ẓ/Ẓ
#define UC_LATIN_LETTER_Z_WITH_LINE_BELOW                  0x1E95  0x1E94  // ẕ/Ẕ
#define UC_LATIN_SMALL_LETTER_H_WITH_LINE_BELOW            0x1E96  0       // ẖ
#define UC_LATIN_SMALL_LETTER_T_WITH_DIAERESIS             0x1E97  0       // ẗ
#define UC_LATIN_SMALL_LETTER_W_WITH_RING_ABOVE            0x1E98  0       // ẘ
#define UC_LATIN_SMALL_LETTER_Y_WITH_RING_ABOVE            0x1E99  0       // ẙ
#define UC_LATIN_SMALL_LETTER_A_WITH_RIGHT_HALF_RING       0x1E9A  0       // ẚ
#define UC_LATIN_SMALL_LETTER_LONG_S_WITH_DOT_ABOVE        0x1E9B  0       // ẛ
#define UC_LATIN_SMALL_LETTER_LONG_S_WITH_DIAGONAL_STROKE  0x1E9C  0       // ẜ
#define UC_LATIN_SMALL_LETTER_LONG_S_WITH_HIGH_STROKE      0x1E9D  0       // ẝ
#define UC_LATIN_CAPITAL_LETTER_SHARP_S                    0x1E9E  0       // ẞ
#define UC_LATIN_SMALL_LETTER_DELTA                        0x1E9F  0       // ẟ
#define UC_LATIN_LETTER_A_WITH_DOT_BELOW                   0x1EA1  0x1EA0  // ạ/Ạ
#define UC_LATIN_LETTER_A_WITH_HOOK_ABOVE                  0x1EA3  0x1EA2  // ả/Ả
#define UC_LATIN_LETTER_A_WITH_CIRCUMFLEX_AND_ACUTE        0x1EA5  0x1EA4  // ấ/Ấ
#define UC_LATIN_LETTER_A_WITH_CIRCUMFLEX_AND_GRAVE        0x1EA7  0x1EA6  // ầ/Ầ
#define UC_LATIN_LETTER_A_WITH_CIRCUMFLEX_AND_HOOK_ABOVE   0x1EA9  0x1EA8  // ẩ/Ẩ
#define UC_LATIN_LETTER_A_WITH_CIRCUMFLEX_AND_TILDE        0x1EAB  0x1EAA  // ẫ/Ẫ
#define UC_LATIN_LETTER_A_WITH_CIRCUMFLEX_AND_DOT_BELOW    0x1EAD  0x1EAC  // ậ/Ậ
#define UC_LATIN_LETTER_A_WITH_BREVE_AND_ACUTE             0x1EAF  0x1EAE  // ắ/Ắ
#define UC_LATIN_LETTER_A_WITH_BREVE_AND_GRAVE             0x1EB1  0x1EB0  // ằ/Ằ
#define UC_LATIN_LETTER_A_WITH_BREVE_AND_HOOK_ABOVE        0x1EB3  0x1EB2  // ẳ/Ẳ
#define UC_LATIN_LETTER_A_WITH_BREVE_AND_TILDE             0x1EB5  0x1EB4  // ẵ/Ẵ
#define UC_LATIN_LETTER_A_WITH_BREVE_AND_DOT_BELOW         0x1EB7  0x1EB6  // ặ/Ặ
#define UC_LATIN_LETTER_E_WITH_DOT_BELOW                   0x1EB9  0x1EB8  // ẹ/Ẹ
#define UC_LATIN_LETTER_E_WITH_HOOK_ABOVE                  0x1EBB  0x1EBA  // ẻ/Ẻ
#define UC_LATIN_LETTER_E_WITH_TILDE                       0x1EBD  0x1EBC  // ẽ/Ẽ
#define UC_LATIN_LETTER_E_WITH_CIRCUMFLEX_AND_ACUTE        0x1EBF  0x1EBE  // ế/Ế
#define UC_LATIN_LETTER_E_WITH_CIRCUMFLEX_AND_GRAVE        0x1EC1  0x1EC0  // ề/Ề
#define UC_LATIN_LETTER_E_WITH_CIRCUMFLEX_AND_HOOK_ABOVE   0x1EC3  0x1EC2  // ể/Ể
#define UC_LATIN_LETTER_E_WITH_CIRCUMFLEX_AND_TILDE        0x1EC5  0x1EC4  // ễ/Ễ
#define UC_LATIN_LETTER_E_WITH_CIRCUMFLEX_AND_DOT_BELOW    0x1EC7  0x1EC6  // ệ/Ệ
#define UC_LATIN_LETTER_I_WITH_HOOK_ABOVE                  0x1EC9  0x1EC8  // ỉ/Ỉ
#define UC_LATIN_LETTER_I_WITH_DOT_BELOW                   0x1ECB  0x1ECA  // ị/Ị
#define UC_LATIN_LETTER_O_WITH_DOT_BELOW                   0x1ECD  0x1ECC  // ọ/Ọ
#define UC_LATIN_LETTER_O_WITH_HOOK_ABOVE                  0x1ECF  0x1ECE  // ỏ/Ỏ
#define UC_LATIN_LETTER_O_WITH_CIRCUMFLEX_AND_ACUTE        0x1ED1  0x1ED0  // ố/Ố
#define UC_LATIN_LETTER_O_WITH_CIRCUMFLEX_AND_GRAVE        0x1ED3  0x1ED2  // ồ/Ồ
#define UC_LATIN_LETTER_O_WITH_CIRCUMFLEX_AND_HOOK_ABOVE   0x1ED5  0x1ED4  // ổ/Ổ
#define UC_LATIN_LETTER_O_WITH_CIRCUMFLEX_AND_TILDE        0x1ED7  0x1ED6  // ỗ/Ỗ
#define UC_LATIN_LETTER_O_WITH_CIRCUMFLEX_AND_DOT_BELOW    0x1ED9  0x1ED8  // ộ/Ộ
#define UC_LATIN_LETTER_O_WITH_HORN_AND_ACUTE              0x1EDB  0x1EDA  // ớ/Ớ
#define UC_LATIN_LETTER_O_WITH_HORN_AND_GRAVE              0x1EDD  0x1EDC  // ờ/Ờ
#define UC_LATIN_LETTER_O_WITH_HORN_AND_HOOK_ABOVE         0x1EDF  0x1EDE  // ở/Ở
#define UC_LATIN_LETTER_O_WITH_HORN_AND_TILDE              0x1EE1  0x1EE0  // ỡ/Ỡ
#define UC_LATIN_LETTER_O_WITH_HORN_AND_DOT_BELOW          0x1EE3  0x1EE2  // ợ/Ợ
#define UC_LATIN_LETTER_U_WITH_DOT_BELOW                   0x1EE5  0x1EE4  // ụ/Ụ
#define UC_LATIN_LETTER_U_WITH_HOOK_ABOVE                  0x1EE7  0x1EE6  // ủ/Ủ
#define UC_LATIN_LETTER_U_WITH_HORN_AND_ACUTE              0x1EE9  0x1EE8  // ứ/Ứ
#define UC_LATIN_LETTER_U_WITH_HORN_AND_GRAVE              0x1EEB  0x1EEA  // ừ/Ừ
#define UC_LATIN_LETTER_U_WITH_HORN_AND_HOOK_ABOVE         0x1EED  0x1EEC  // ử/Ử
#define UC_LATIN_LETTER_U_WITH_HORN_AND_TILDE              0x1EEF  0x1EEE  // ữ/Ữ
#define UC_LATIN_LETTER_U_WITH_HORN_AND_DOT_BELOW          0x1EF1  0x1EF0  // ự/Ự
#define UC_LATIN_LETTER_Y_WITH_GRAVE                       0x1EF3  0x1EF2  // ỳ/Ỳ
#define UC_LATIN_LETTER_Y_WITH_DOT_BELOW                   0x1EF5  0x1EF4  // ỵ/Ỵ
#define UC_LATIN_LETTER_Y_WITH_HOOK_ABOVE                  0x1EF7  0x1EF6  // ỷ/Ỷ
#define UC_LATIN_LETTER_Y_WITH_TILDE                       0x1EF9  0x1EF8  // ỹ/Ỹ
#define UC_LATIN_LETTER_MIDDLE_WELSH_LL                    0x1EFB  0x1EFA  // ỻ/Ỻ
#define UC_LATIN_LETTER_MIDDLE_WELSH_V                     0x1EFD  0x1EFC  // ỽ/Ỽ
#define UC_LATIN_LETTER_Y_WITH_LOOP                        0x1EFF  0x1EFE  // ỿ/Ỿ