/*
 * Unicode keys for U+1D400 .. U+1D7FF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 */

#pragma once

#define UC_MATHEMATICAL_BOLD_CAPITAL_A                               0x1D400  0  // 𝐀
#define UC_MATHEMATICAL_BOLD_CAPITAL_B                               0x1D401  0  // 𝐁
#define UC_MATHEMATICAL_BOLD_CAPITAL_C                               0x1D402  0  // 𝐂
#define UC_MATHEMATICAL_BOLD_CAPITAL_D                               0x1D403  0  // 𝐃
#define UC_MATHEMATICAL_BOLD_CAPITAL_E                               0x1D404  0  // 𝐄
#define UC_MATHEMATICAL_BOLD_CAPITAL_F                               0x1D405  0  // 𝐅
#define UC_MATHEMATICAL_BOLD_CAPITAL_G                               0x1D406  0  // 𝐆
#define UC_MATHEMATICAL_BOLD_CAPITAL_H                               0x1D407  0  // 𝐇
#define UC_MATHEMATICAL_BOLD_CAPITAL_I                               0x1D408  0  // 𝐈
#define UC_MATHEMATICAL_BOLD_CAPITAL_J                               0x1D409  0  // 𝐉
#define UC_MATHEMATICAL_BOLD_CAPITAL_K                               0x1D40A  0  // 𝐊
#define UC_MATHEMATICAL_BOLD_CAPITAL_L                               0x1D40B  0  // 𝐋
#define UC_MATHEMATICAL_BOLD_CAPITAL_M                               0x1D40C  0  // 𝐌
#define UC_MATHEMATICAL_BOLD_CAPITAL_N                               0x1D40D  0  // 𝐍
#define UC_MATHEMATICAL_BOLD_CAPITAL_O                               0x1D40E  0  // 𝐎
#define UC_MATHEMATICAL_BOLD_CAPITAL_P                               0x1D40F  0  // 𝐏
#define UC_MATHEMATICAL_BOLD_CAPITAL_Q                               0x1D410  0  // 𝐐
#define UC_MATHEMATICAL_BOLD_CAPITAL_R                               0x1D411  0  // 𝐑
#define UC_MATHEMATICAL_BOLD_CAPITAL_S                               0x1D412  0  // 𝐒
#define UC_MATHEMATICAL_BOLD_CAPITAL_T                               0x1D413  0  // 𝐓
#define UC_MATHEMATICAL_BOLD_CAPITAL_U                               0x1D414  0  // 𝐔
#define UC_MATHEMATICAL_BOLD_CAPITAL_V                               0x1D415  0  // 𝐕
#define UC_MATHEMATICAL_BOLD_CAPITAL_W                               0x1D416  0  // 𝐖
#define UC_MATHEMATICAL_BOLD_CAPITAL_X                               0x1D417  0  // 𝐗
#define UC_MATHEMATICAL_BOLD_CAPITAL_Y                               0x1D418  0  // 𝐘
#define UC_MATHEMATICAL_BOLD_CAPITAL_Z                               0x1D419  0  // 𝐙
#define UC_MATHEMATICAL_BOLD_SMALL_A                                 0x1D41A  0  // 𝐚
#define UC_MATHEMATICAL_BOLD_SMALL_B                                 0x1D41B  0  // 𝐛
#define UC_MATHEMATICAL_BOLD_SMALL_C                                 0x1D41C  0  // 𝐜
#define UC_MATHEMATICAL_BOLD_SMALL_D                                 0x1D41D  0  // 𝐝
#define UC_MATHEMATICAL_BOLD_SMALL_E                                 0x1D41E  0  // 𝐞
#define UC_MATHEMATICAL_BOLD_SMALL_F                                 0x1D41F  0  // 𝐟
#define UC_MATHEMATICAL_BOLD_SMALL_G                                 0x1D420  0  // 𝐠
#define UC_MATHEMATICAL_BOLD_SMALL_H                                 0x1D421  0  // 𝐡
#define UC_MATHEMATICAL_BOLD_SMALL_I                                 0x1D422  0  // 𝐢
#define UC_MATHEMATICAL_BOLD_SMALL_J                                 0x1D423  0  // 𝐣
#define UC_MATHEMATICAL_BOLD_SMALL_K                                 0x1D424  0  // 𝐤
#define UC_MATHEMATICAL_BOLD_SMALL_L                                 0x1D425  0  // 𝐥
#define UC_MATHEMATICAL_BOLD_SMALL_M                                 0x1D426  0  // 𝐦
#define UC_MATHEMATICAL_BOLD_SMALL_N                                 0x1D427  0  // 𝐧
#define UC_MATHEMATICAL_BOLD_SMALL_O                                 0x1D428  0  // 𝐨
#define UC_MATHEMATICAL_BOLD_SMALL_P                                 0x1D429  0  // 𝐩
#define UC_MATHEMATICAL_BOLD_SMALL_Q                                 0x1D42A  0  // 𝐪
#define UC_MATHEMATICAL_BOLD_SMALL_R                                 0x1D42B  0  // 𝐫
#define UC_MATHEMATICAL_BOLD_SMALL_S                                 0x1D42C  0  // 𝐬
#define UC_MATHEMATICAL_BOLD_SMALL_T                                 0x1D42D  0  // 𝐭
#define UC_MATHEMATICAL_BOLD_SMALL_U                                 0x1D42E  0  // 𝐮
#define UC_MATHEMATICAL_BOLD_SMALL_V                                 0x1D42F  0  // 𝐯
#define UC_MATHEMATICAL_BOLD_SMALL_W                                 0x1D430  0  // 𝐰
#define UC_MATHEMATICAL_BOLD_SMALL_X                                 0x1D431  0  // 𝐱
#define UC_MATHEMATICAL_BOLD_SMALL_Y                                 0x1D432  0  // 𝐲
#define UC_MATHEMATICAL_BOLD_SMALL_Z                                 0x1D433  0  // 𝐳
#define UC_MATHEMATICAL_ITALIC_CAPITAL_A                             0x1D434  0  // 𝐴
#define UC_MATHEMATICAL_ITALIC_CAPITAL_B                             0x1D435  0  // 𝐵
#define UC_MATHEMATICAL_ITALIC_CAPITAL_C                             0x1D436  0  // 𝐶
#define UC_MATHEMATICAL_ITALIC_CAPITAL_D                             0x1D437  0  // 𝐷
#define UC_MATHEMATICAL_ITALIC_CAPITAL_E                             0x1D438  0  // 𝐸
#define UC_MATHEMATICAL_ITALIC_CAPITAL_F                             0x1D439  0  // 𝐹
#define UC_MATHEMATICAL_ITALIC_CAPITAL_G                             0x1D43A  0  // 𝐺
#define UC_MATHEMATICAL_ITALIC_CAPITAL_H                             0x1D43B  0  // 𝐻
#define UC_MATHEMATICAL_ITALIC_CAPITAL_I                             0x1D43C  0  // 𝐼
#define UC_MATHEMATICAL_ITALIC_CAPITAL_J                             0x1D43D  0  // 𝐽
#define UC_MATHEMATICAL_ITALIC_CAPITAL_K                             0x1D43E  0  // 𝐾
#define UC_MATHEMATICAL_ITALIC_CAPITAL_L                             0x1D43F  0  // 𝐿
#define UC_MATHEMATICAL_ITALIC_CAPITAL_M                             0x1D440  0  // 𝑀
#define UC_MATHEMATICAL_ITALIC_CAPITAL_N                             0x1D441  0  // 𝑁
#define UC_MATHEMATICAL_ITALIC_CAPITAL_O                             0x1D442  0  // 𝑂
#define UC_MATHEMATICAL_ITALIC_CAPITAL_P                             0x1D443  0  // 𝑃
#define UC_MATHEMATICAL_ITALIC_CAPITAL_Q                             0x1D444  0  // 𝑄
#define UC_MATHEMATICAL_ITALIC_CAPITAL_R                             0x1D445  0  // 𝑅
#define UC_MATHEMATICAL_ITALIC_CAPITAL_S                             0x1D446  0  // 𝑆
#define UC_MATHEMATICAL_ITALIC_CAPITAL_T                             0x1D447  0  // 𝑇
#define UC_MATHEMATICAL_ITALIC_CAPITAL_U                             0x1D448  0  // 𝑈
#define UC_MATHEMATICAL_ITALIC_CAPITAL_V                             0x1D449  0  // 𝑉
#define UC_MATHEMATICAL_ITALIC_CAPITAL_W                             0x1D44A  0  // 𝑊
#define UC_MATHEMATICAL_ITALIC_CAPITAL_X                             0x1D44B  0  // 𝑋
#define UC_MATHEMATICAL_ITALIC_CAPITAL_Y                             0x1D44C  0  // 𝑌
#define UC_MATHEMATICAL_ITALIC_CAPITAL_Z                             0x1D44D  0  // 𝑍
#define UC_MATHEMATICAL_ITALIC_SMALL_A                               0x1D44E  0  // 𝑎
#define UC_MATHEMATICAL_ITALIC_SMALL_B                               0x1D44F  0  // 𝑏
#define UC_MATHEMATICAL_ITALIC_SMALL_C                               0x1D450  0  // 𝑐
#define UC_MATHEMATICAL_ITALIC_SMALL_D                               0x1D451  0  // 𝑑
#define UC_MATHEMATICAL_ITALIC_SMALL_E                               0x1D452  0  // 𝑒
#define UC_MATHEMATICAL_ITALIC_SMALL_F                               0x1D453  0  // 𝑓
#define UC_MATHEMATICAL_ITALIC_SMALL_G                               0x1D454  0  // 𝑔
#define UC_MATHEMATICAL_ITALIC_SMALL_I                               0x1D456  0  // 𝑖
#define UC_MATHEMATICAL_ITALIC_SMALL_J                               0x1D457  0  // 𝑗
#define UC_MATHEMATICAL_ITALIC_SMALL_K                               0x1D458  0  // 𝑘
#define UC_MATHEMATICAL_ITALIC_SMALL_L                               0x1D459  0  // 𝑙
#define UC_MATHEMATICAL_ITALIC_SMALL_M                               0x1D45A  0  // 𝑚
#define UC_MATHEMATICAL_ITALIC_SMALL_N                               0x1D45B  0  // 𝑛
#define UC_MATHEMATICAL_ITALIC_SMALL_O                               0x1D45C  0  // 𝑜
#define UC_MATHEMATICAL_ITALIC_SMALL_P                               0x1D45D  0  // 𝑝
#define UC_MATHEMATICAL_ITALIC_SMALL_Q                               0x1D45E  0  // 𝑞
#define UC_MATHEMATICAL_ITALIC_SMALL_R                               0x1D45F  0  // 𝑟
#define UC_MATHEMATICAL_ITALIC_SMALL_S                               0x1D460  0  // 𝑠
#define UC_MATHEMATICAL_ITALIC_SMALL_T                               0x1D461  0  // 𝑡
#define UC_MATHEMATICAL_ITALIC_SMALL_U                               0x1D462  0  // 𝑢
#define UC_MATHEMATICAL_ITALIC_SMALL_V                               0x1D463  0  // 𝑣
#define UC_MATHEMATICAL_ITALIC_SMALL_W                               0x1D464  0  // 𝑤
#define UC_MATHEMATICAL_ITALIC_SMALL_X                               0x1D465  0  // 𝑥
#define UC_MATHEMATICAL_ITALIC_SMALL_Y                               0x1D466  0  // 𝑦
#define UC_MATHEMATICAL_ITALIC_SMALL_Z                               0x1D467  0  // 𝑧
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_A                        0x1D468  0  // 𝑨
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_B                        0x1D469  0  // 𝑩
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_C                        0x1D46A  0  // 𝑪
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_D                        0x1D46B  0  // 𝑫
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_E                        0x1D46C  0  // 𝑬
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_F                        0x1D46D  0  // 𝑭
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_G                        0x1D46E  0  // 𝑮
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_H                        0x1D46F  0  // 𝑯
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_I                        0x1D470  0  // 𝑰
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_J                        0x1D471  0  // 𝑱
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_K                        0x1D472  0  // 𝑲
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_L                        0x1D473  0  // 𝑳
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_M                        0x1D474  0  // 𝑴
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_N                        0x1D475  0  // 𝑵
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_O                        0x1D476  0  // 𝑶
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_P                        0x1D477  0  // 𝑷
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_Q                        0x1D478  0  // 𝑸
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_R                        0x1D479  0  // 𝑹
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_S                        0x1D47A  0  // 𝑺
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_T                        0x1D47B  0  // 𝑻
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_U                        0x1D47C  0  // 𝑼
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_V                        0x1D47D  0  // 𝑽
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_W                        0x1D47E  0  // 𝑾
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_X                        0x1D47F  0  // 𝑿
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_Y                        0x1D480  0  // 𝒀
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_Z                        0x1D481  0  // 𝒁
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_A                          0x1D482  0  // 𝒂
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_B                          0x1D483  0  // 𝒃
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_C                          0x1D484  0  // 𝒄
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_D                          0x1D485  0  // 𝒅
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_E                          0x1D486  0  // 𝒆
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_F                          0x1D487  0  // 𝒇
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_G                          0x1D488  0  // 𝒈
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_H                          0x1D489  0  // 𝒉
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_I                          0x1D48A  0  // 𝒊
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_J                          0x1D48B  0  // 𝒋
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_K                          0x1D48C  0  // 𝒌
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_L                          0x1D48D  0  // 𝒍
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_M                          0x1D48E  0  // 𝒎
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_N                          0x1D48F  0  // 𝒏
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_O                          0x1D490  0  // 𝒐
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_P                          0x1D491  0  // 𝒑
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_Q                          0x1D492  0  // 𝒒
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_R                          0x1D493  0  // 𝒓
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_S                          0x1D494  0  // 𝒔
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_T                          0x1D495  0  // 𝒕
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_U                          0x1D496  0  // 𝒖
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_V                          0x1D497  0  // 𝒗
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_W                          0x1D498  0  // 𝒘
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_X                          0x1D499  0  // 𝒙
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_Y                          0x1D49A  0  // 𝒚
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_Z                          0x1D49B  0  // 𝒛
#define UC_MATHEMATICAL_SCRIPT_CAPITAL_A                             0x1D49C  0  // 𝒜
#define UC_MATHEMATICAL_SCRIPT_CAPITAL_C                             0x1D49E  0  // 𝒞
#define UC_MATHEMATICAL_SCRIPT_CAPITAL_D                             0x1D49F  0  // 𝒟
#define UC_MATHEMATICAL_SCRIPT_CAPITAL_G                             0x1D4A2  0  // 𝒢
#define UC_MATHEMATICAL_SCRIPT_CAPITAL_J                             0x1D4A5  0  // 𝒥
#define UC_MATHEMATICAL_SCRIPT_CAPITAL_K                             0x1D4A6  0  // 𝒦
#define UC_MATHEMATICAL_SCRIPT_CAPITAL_N                             0x1D4A9  0  // 𝒩
#define UC_MATHEMATICAL_SCRIPT_CAPITAL_O                             0x1D4AA  0  // 𝒪
#define UC_MATHEMATICAL_SCRIPT_CAPITAL_P                             0x1D4AB  0  // 𝒫
#define UC_MATHEMATICAL_SCRIPT_CAPITAL_Q                             0x1D4AC  0  // 𝒬
#define UC_MATHEMATICAL_SCRIPT_CAPITAL_S                             0x1D4AE  0  // 𝒮
#define UC_MATHEMATICAL_SCRIPT_CAPITAL_T                             0x1D4AF  0  // 𝒯
#define UC_MATHEMATICAL_SCRIPT_CAPITAL_U                             0x1D4B0  0  // 𝒰
#define UC_MATHEMATICAL_SCRIPT_CAPITAL_V                             0x1D4B1  0  // 𝒱
#define UC_MATHEMATICAL_SCRIPT_CAPITAL_W                             0x1D4B2  0  // 𝒲
#define UC_MATHEMATICAL_SCRIPT_CAPITAL_X                             0x1D4B3  0  // 𝒳
#define UC_MATHEMATICAL_SCRIPT_CAPITAL_Y                             0x1D4B4  0  // 𝒴
#define UC_MATHEMATICAL_SCRIPT_CAPITAL_Z                             0x1D4B5  0  // 𝒵
#define UC_MATHEMATICAL_SCRIPT_SMALL_A                               0x1D4B6  0  // 𝒶
#define UC_MATHEMATICAL_SCRIPT_SMALL_B                               0x1D4B7  0  // 𝒷
#define UC_MATHEMATICAL_SCRIPT_SMALL_C                               0x1D4B8  0  // 𝒸
#define UC_MATHEMATICAL_SCRIPT_SMALL_D                               0x1D4B9  0  // 𝒹
#define UC_MATHEMATICAL_SCRIPT_SMALL_F                               0x1D4BB  0  // 𝒻
#define UC_MATHEMATICAL_SCRIPT_SMALL_H                               0x1D4BD  0  // 𝒽
#define UC_MATHEMATICAL_SCRIPT_SMALL_I                               0x1D4BE  0  // 𝒾
#define UC_MATHEMATICAL_SCRIPT_SMALL_J                               0x1D4BF  0  // 𝒿
#define UC_MATHEMATICAL_SCRIPT_SMALL_K                               0x1D4C0  0  // 𝓀
#define UC_MATHEMATICAL_SCRIPT_SMALL_L                               0x1D4C1  0  // 𝓁
#define UC_MATHEMATICAL_SCRIPT_SMALL_M                               0x1D4C2  0  // 𝓂
#define UC_MATHEMATICAL_SCRIPT_SMALL_N                               0x1D4C3  0  // 𝓃
#define UC_MATHEMATICAL_SCRIPT_SMALL_P                               0x1D4C5  0  // 𝓅
#define UC_MATHEMATICAL_SCRIPT_SMALL_Q                               0x1D4C6  0  // 𝓆
#define UC_MATHEMATICAL_SCRIPT_SMALL_R                               0x1D4C7  0  // 𝓇
#define UC_MATHEMATICAL_SCRIPT_SMALL_S                               0x1D4C8  0  // 𝓈
#define UC_MATHEMATICAL_SCRIPT_SMALL_T                               0x1D4C9  0  // 𝓉
#define UC_MATHEMATICAL_SCRIPT_SMALL_U                               0x1D4CA  0  // 𝓊
#define UC_MATHEMATICAL_SCRIPT_SMALL_V                               0x1D4CB  0  // 𝓋
#define UC_MATHEMATICAL_SCRIPT_SMALL_W                               0x1D4CC  0  // 𝓌
#define UC_MATHEMATICAL_SCRIPT_SMALL_X                               0x1D4CD  0  // 𝓍
#define UC_MATHEMATICAL_SCRIPT_SMALL_Y                               0x1D4CE  0  // 𝓎
#define UC_MATHEMATICAL_SCRIPT_SMALL_Z                               0x1D4CF  0  // 𝓏
#define UC_MATHEMATICAL_BOLD_SCRIPT_CAPITAL_A                        0x1D4D0  0  // 𝓐
#define UC_MATHEMATICAL_BOLD_SCRIPT_CAPITAL_B                        0x1D4D1  0  // 𝓑
#define UC_MATHEMATICAL_BOLD_SCRIPT_CAPITAL_C                        0x1D4D2  0  // 𝓒
#define UC_MATHEMATICAL_BOLD_SCRIPT_CAPITAL_D                        0x1D4D3  0  // 𝓓
#define UC_MATHEMATICAL_BOLD_SCRIPT_CAPITAL_E                        0x1D4D4  0  // 𝓔
#define UC_MATHEMATICAL_BOLD_SCRIPT_CAPITAL_F                        0x1D4D5  0  // 𝓕
#define UC_MATHEMATICAL_BOLD_SCRIPT_CAPITAL_G                        0x1D4D6  0  // 𝓖
#define UC_MATHEMATICAL_BOLD_SCRIPT_CAPITAL_H                        0x1D4D7  0  // 𝓗
#define UC_MATHEMATICAL_BOLD_SCRIPT_CAPITAL_I                        0x1D4D8  0  // 𝓘
#define UC_MATHEMATICAL_BOLD_SCRIPT_CAPITAL_J                        0x1D4D9  0  // 𝓙
#define UC_MATHEMATICAL_BOLD_SCRIPT_CAPITAL_K                        0x1D4DA  0  // 𝓚
#define UC_MATHEMATICAL_BOLD_SCRIPT_CAPITAL_L                        0x1D4DB  0  // 𝓛
#define UC_MATHEMATICAL_BOLD_SCRIPT_CAPITAL_M                        0x1D4DC  0  // 𝓜
#define UC_MATHEMATICAL_BOLD_SCRIPT_CAPITAL_N                        0x1D4DD  0  // 𝓝
#define UC_MATHEMATICAL_BOLD_SCRIPT_CAPITAL_O                        0x1D4DE  0  // 𝓞
#define UC_MATHEMATICAL_BOLD_SCRIPT_CAPITAL_P                        0x1D4DF  0  // 𝓟
#define UC_MATHEMATICAL_BOLD_SCRIPT_CAPITAL_Q                        0x1D4E0  0  // 𝓠
#define UC_MATHEMATICAL_BOLD_SCRIPT_CAPITAL_R                        0x1D4E1  0  // 𝓡
#define UC_MATHEMATICAL_BOLD_SCRIPT_CAPITAL_S                        0x1D4E2  0  // 𝓢
#define UC_MATHEMATICAL_BOLD_SCRIPT_CAPITAL_T                        0x1D4E3  0  // 𝓣
#define UC_MATHEMATICAL_BOLD_SCRIPT_CAPITAL_U                        0x1D4E4  0  // 𝓤
#define UC_MATHEMATICAL_BOLD_SCRIPT_CAPITAL_V                        0x1D4E5  0  // 𝓥
#define UC_MATHEMATICAL_BOLD_SCRIPT_CAPITAL_W                        0x1D4E6  0  // 𝓦
#define UC_MATHEMATICAL_BOLD_SCRIPT_CAPITAL_X                        0x1D4E7  0  // 𝓧
#define UC_MATHEMATICAL_BOLD_SCRIPT_CAPITAL_Y                        0x1D4E8  0  // 𝓨
#define UC_MATHEMATICAL_BOLD_SCRIPT_CAPITAL_Z                        0x1D4E9  0  // 𝓩
#define UC_MATHEMATICAL_BOLD_SCRIPT_SMALL_A                          0x1D4EA  0  // 𝓪
#define UC_MATHEMATICAL_BOLD_SCRIPT_SMALL_B                          0x1D4EB  0  // 𝓫
#define UC_MATHEMATICAL_BOLD_SCRIPT_SMALL_C                          0x1D4EC  0  // 𝓬
#define UC_MATHEMATICAL_BOLD_SCRIPT_SMALL_D                          0x1D4ED  0  // 𝓭
#define UC_MATHEMATICAL_BOLD_SCRIPT_SMALL_E                          0x1D4EE  0  // 𝓮
#define UC_MATHEMATICAL_BOLD_SCRIPT_SMALL_F                          0x1D4EF  0  // 𝓯
#define UC_MATHEMATICAL_BOLD_SCRIPT_SMALL_G                          0x1D4F0  0  // 𝓰
#define UC_MATHEMATICAL_BOLD_SCRIPT_SMALL_H                          0x1D4F1  0  // 𝓱
#define UC_MATHEMATICAL_BOLD_SCRIPT_SMALL_I                          0x1D4F2  0  // 𝓲
#define UC_MATHEMATICAL_BOLD_SCRIPT_SMALL_J                          0x1D4F3  0  // 𝓳
#define UC_MATHEMATICAL_BOLD_SCRIPT_SMALL_K                          0x1D4F4  0  // 𝓴
#define UC_MATHEMATICAL_BOLD_SCRIPT_SMALL_L                          0x1D4F5  0  // 𝓵
#define UC_MATHEMATICAL_BOLD_SCRIPT_SMALL_M                          0x1D4F6  0  // 𝓶
#define UC_MATHEMATICAL_BOLD_SCRIPT_SMALL_N                          0x1D4F7  0  // 𝓷
#define UC_MATHEMATICAL_BOLD_SCRIPT_SMALL_O                          0x1D4F8  0  // 𝓸
#define UC_MATHEMATICAL_BOLD_SCRIPT_SMALL_P                          0x1D4F9  0  // 𝓹
#define UC_MATHEMATICAL_BOLD_SCRIPT_SMALL_Q                          0x1D4FA  0  // 𝓺
#define UC_MATHEMATICAL_BOLD_SCRIPT_SMALL_R                          0x1D4FB  0  // 𝓻
#define UC_MATHEMATICAL_BOLD_SCRIPT_SMALL_S                          0x1D4FC  0  // 𝓼
#define UC_MATHEMATICAL_BOLD_SCRIPT_SMALL_T                          0x1D4FD  0  // 𝓽
#define UC_MATHEMATICAL_BOLD_SCRIPT_SMALL_U                          0x1D4FE  0  // 𝓾
#define UC_MATHEMATICAL_BOLD_SCRIPT_SMALL_V                          0x1D4FF  0  // 𝓿
#define UC_MATHEMATICAL_BOLD_SCRIPT_SMALL_W                          0x1D500  0  // 𝔀
#define UC_MATHEMATICAL_BOLD_SCRIPT_SMALL_X                          0x1D501  0  // 𝔁
#define UC_MATHEMATICAL_BOLD_SCRIPT_SMALL_Y                          0x1D502  0  // 𝔂
#define UC_MATHEMATICAL_BOLD_SCRIPT_SMALL_Z                          0x1D503  0  // 𝔃
#define UC_MATHEMATICAL_FRAKTUR_CAPITAL_A                            0x1D504  0  // 𝔄
#define UC_MATHEMATICAL_FRAKTUR_CAPITAL_B                            0x1D505  0  // 𝔅
#define UC_MATHEMATICAL_FRAKTUR_CAPITAL_D                            0x1D507  0  // 𝔇
#define UC_MATHEMATICAL_FRAKTUR_CAPITAL_E                            0x1D508  0  // 𝔈
#define UC_MATHEMATICAL_FRAKTUR_CAPITAL_F                            0x1D509  0  // 𝔉
#define UC_MATHEMATICAL_FRAKTUR_CAPITAL_G                            0x1D50A  0  // 𝔊
#define UC_MATHEMATICAL_FRAKTUR_CAPITAL_J                            0x1D50D  0  // 𝔍
#define UC_MATHEMATICAL_FRAKTUR_CAPITAL_K                            0x1D50E  0  // 𝔎
#define UC_MATHEMATICAL_FRAKTUR_CAPITAL_L                            0x1D50F  0  // 𝔏
#define UC_MATHEMATICAL_FRAKTUR_CAPITAL_M                            0x1D510  0  // 𝔐
#define UC_MATHEMATICAL_FRAKTUR_CAPITAL_N                            0x1D511  0  // 𝔑
#define UC_MATHEMATICAL_FRAKTUR_CAPITAL_O                            0x1D512  0  // 𝔒
#define UC_MATHEMATICAL_FRAKTUR_CAPITAL_P                            0x1D513  0  // 𝔓
#define UC_MATHEMATICAL_FRAKTUR_CAPITAL_Q                            0x1D514  0  // 𝔔
#define UC_MATHEMATICAL_FRAKTUR_CAPITAL_S                            0x1D516  0  // 𝔖
#define UC_MATHEMATICAL_FRAKTUR_CAPITAL_T                            0x1D517  0  // 𝔗
#define UC_MATHEMATICAL_FRAKTUR_CAPITAL_U                            0x1D518  0  // 𝔘
#define UC_MATHEMATICAL_FRAKTUR_CAPITAL_V                            0x1D519  0  // 𝔙
#define UC_MATHEMATICAL_FRAKTUR_CAPITAL_W                            0x1D51A  0  // 𝔚
#define UC_MATHEMATICAL_FRAKTUR_CAPITAL_X                            0x1D51B  0  // 𝔛
#define UC_MATHEMATICAL_FRAKTUR_CAPITAL_Y                            0x1D51C  0  // 𝔜
#define UC_MATHEMATICAL_FRAKTUR_SMALL_A                              0x1D51E  0  // 𝔞
#define UC_MATHEMATICAL_FRAKTUR_SMALL_B                              0x1D51F  0  // 𝔟
#define UC_MATHEMATICAL_FRAKTUR_SMALL_C                              0x1D520  0  // 𝔠
#define UC_MATHEMATICAL_FRAKTUR_SMALL_D                              0x1D521  0  // 𝔡
#define UC_MATHEMATICAL_FRAKTUR_SMALL_E                              0x1D522  0  // 𝔢
#define UC_MATHEMATICAL_FRAKTUR_SMALL_F                              0x1D523  0  // 𝔣
#define UC_MATHEMATICAL_FRAKTUR_SMALL_G                              0x1D524  0  // 𝔤
#define UC_MATHEMATICAL_FRAKTUR_SMALL_H                              0x1D525  0  // 𝔥
#define UC_MATHEMATICAL_FRAKTUR_SMALL_I                              0x1D526  0  // 𝔦
#define UC_MATHEMATICAL_FRAKTUR_SMALL_J                              0x1D527  0  // 𝔧
#define UC_MATHEMATICAL_FRAKTUR_SMALL_K                              0x1D528  0  // 𝔨
#define UC_MATHEMATICAL_FRAKTUR_SMALL_L                              0x1D529  0  // 𝔩
#define UC_MATHEMATICAL_FRAKTUR_SMALL_M                              0x1D52A  0  // 𝔪
#define UC_MATHEMATICAL_FRAKTUR_SMALL_N                              0x1D52B  0  // 𝔫
#define UC_MATHEMATICAL_FRAKTUR_SMALL_O                              0x1D52C  0  // 𝔬
#define UC_MATHEMATICAL_FRAKTUR_SMALL_P                              0x1D52D  0  // 𝔭
#define UC_MATHEMATICAL_FRAKTUR_SMALL_Q                              0x1D52E  0  // 𝔮
#define UC_MATHEMATICAL_FRAKTUR_SMALL_R                              0x1D52F  0  // 𝔯
#define UC_MATHEMATICAL_FRAKTUR_SMALL_S                              0x1D530  0  // 𝔰
#define UC_MATHEMATICAL_FRAKTUR_SMALL_T                              0x1D531  0  // 𝔱
#define UC_MATHEMATICAL_FRAKTUR_SMALL_U                              0x1D532  0  // 𝔲
#define UC_MATHEMATICAL_FRAKTUR_SMALL_V                              0x1D533  0  // 𝔳
#define UC_MATHEMATICAL_FRAKTUR_SMALL_W                              0x1D534  0  // 𝔴
#define UC_MATHEMATICAL_FRAKTUR_SMALL_X                              0x1D535  0  // 𝔵
#define UC_MATHEMATICAL_FRAKTUR_SMALL_Y                              0x1D536  0  // 𝔶
#define UC_MATHEMATICAL_FRAKTUR_SMALL_Z                              0x1D537  0  // 𝔷
#define UC_MATHEMATICAL_DOUBLE_STRUCK_CAPITAL_A                      0x1D538  0  // 𝔸
#define UC_MATHEMATICAL_DOUBLE_STRUCK_CAPITAL_B                      0x1D539  0  // 𝔹
#define UC_MATHEMATICAL_DOUBLE_STRUCK_CAPITAL_D                      0x1D53B  0  // 𝔻
#define UC_MATHEMATICAL_DOUBLE_STRUCK_CAPITAL_E                      0x1D53C  0  // 𝔼
#define UC_MATHEMATICAL_DOUBLE_STRUCK_CAPITAL_F                      0x1D53D  0  // 𝔽
#define UC_MATHEMATICAL_DOUBLE_STRUCK_CAPITAL_G                      0x1D53E  0  // 𝔾
#define UC_MATHEMATICAL_DOUBLE_STRUCK_CAPITAL_I                      0x1D540  0  // 𝕀
#define UC_MATHEMATICAL_DOUBLE_STRUCK_CAPITAL_J                      0x1D541  0  // 𝕁
#define UC_MATHEMATICAL_DOUBLE_STRUCK_CAPITAL_K                      0x1D542  0  // 𝕂
#define UC_MATHEMATICAL_DOUBLE_STRUCK_CAPITAL_L                      0x1D543  0  // 𝕃
#define UC_MATHEMATICAL_DOUBLE_STRUCK_CAPITAL_M                      0x1D544  0  // 𝕄
#define UC_MATHEMATICAL_DOUBLE_STRUCK_CAPITAL_O                      0x1D546  0  // 𝕆
#define UC_MATHEMATICAL_DOUBLE_STRUCK_CAPITAL_S                      0x1D54A  0  // 𝕊
#define UC_MATHEMATICAL_DOUBLE_STRUCK_CAPITAL_T                      0x1D54B  0  // 𝕋
#define UC_MATHEMATICAL_DOUBLE_STRUCK_CAPITAL_U                      0x1D54C  0  // 𝕌
#define UC_MATHEMATICAL_DOUBLE_STRUCK_CAPITAL_V                      0x1D54D  0  // 𝕍
#define UC_MATHEMATICAL_DOUBLE_STRUCK_CAPITAL_W                      0x1D54E  0  // 𝕎
#define UC_MATHEMATICAL_DOUBLE_STRUCK_CAPITAL_X                      0x1D54F  0  // 𝕏
#define UC_MATHEMATICAL_DOUBLE_STRUCK_CAPITAL_Y                      0x1D550  0  // 𝕐
#define UC_MATHEMATICAL_DOUBLE_STRUCK_SMALL_A                        0x1D552  0  // 𝕒
#define UC_MATHEMATICAL_DOUBLE_STRUCK_SMALL_B                        0x1D553  0  // 𝕓
#define UC_MATHEMATICAL_DOUBLE_STRUCK_SMALL_C                        0x1D554  0  // 𝕔
#define UC_MATHEMATICAL_DOUBLE_STRUCK_SMALL_D                        0x1D555  0  // 𝕕
#define UC_MATHEMATICAL_DOUBLE_STRUCK_SMALL_E                        0x1D556  0  // 𝕖
#define UC_MATHEMATICAL_DOUBLE_STRUCK_SMALL_F                        0x1D557  0  // 𝕗
#define UC_MATHEMATICAL_DOUBLE_STRUCK_SMALL_G                        0x1D558  0  // 𝕘
#define UC_MATHEMATICAL_DOUBLE_STRUCK_SMALL_H                        0x1D559  0  // 𝕙
#define UC_MATHEMATICAL_DOUBLE_STRUCK_SMALL_I                        0x1D55A  0  // 𝕚
#define UC_MATHEMATICAL_DOUBLE_STRUCK_SMALL_J                        0x1D55B  0  // 𝕛
#define UC_MATHEMATICAL_DOUBLE_STRUCK_SMALL_K                        0x1D55C  0  // 𝕜
#define UC_MATHEMATICAL_DOUBLE_STRUCK_SMALL_L                        0x1D55D  0  // 𝕝
#define UC_MATHEMATICAL_DOUBLE_STRUCK_SMALL_M                        0x1D55E  0  // 𝕞
#define UC_MATHEMATICAL_DOUBLE_STRUCK_SMALL_N                        0x1D55F  0  // 𝕟
#define UC_MATHEMATICAL_DOUBLE_STRUCK_SMALL_O                        0x1D560  0  // 𝕠
#define UC_MATHEMATICAL_DOUBLE_STRUCK_SMALL_P                        0x1D561  0  // 𝕡
#define UC_MATHEMATICAL_DOUBLE_STRUCK_SMALL_Q                        0x1D562  0  // 𝕢
#define UC_MATHEMATICAL_DOUBLE_STRUCK_SMALL_R                        0x1D563  0  // 𝕣
#define UC_MATHEMATICAL_DOUBLE_STRUCK_SMALL_S                        0x1D564  0  // 𝕤
#define UC_MATHEMATICAL_DOUBLE_STRUCK_SMALL_T                        0x1D565  0  // 𝕥
#define UC_MATHEMATICAL_DOUBLE_STRUCK_SMALL_U                        0x1D566  0  // 𝕦
#define UC_MATHEMATICAL_DOUBLE_STRUCK_SMALL_V                        0x1D567  0  // 𝕧
#define UC_MATHEMATICAL_DOUBLE_STRUCK_SMALL_W                        0x1D568  0  // 𝕨
#define UC_MATHEMATICAL_DOUBLE_STRUCK_SMALL_X                        0x1D569  0  // 𝕩
#define UC_MATHEMATICAL_DOUBLE_STRUCK_SMALL_Y                        0x1D56A  0  // 𝕪
#define UC_MATHEMATICAL_DOUBLE_STRUCK_SMALL_Z                        0x1D56B  0  // 𝕫
#define UC_MATHEMATICAL_BOLD_FRAKTUR_CAPITAL_A                       0x1D56C  0  // 𝕬
#define UC_MATHEMATICAL_BOLD_FRAKTUR_CAPITAL_B                       0x1D56D  0  // 𝕭
#define UC_MATHEMATICAL_BOLD_FRAKTUR_CAPITAL_C                       0x1D56E  0  // 𝕮
#define UC_MATHEMATICAL_BOLD_FRAKTUR_CAPITAL_D                       0x1D56F  0  // 𝕯
#define UC_MATHEMATICAL_BOLD_FRAKTUR_CAPITAL_E                       0x1D570  0  // 𝕰
#define UC_MATHEMATICAL_BOLD_FRAKTUR_CAPITAL_F                       0x1D571  0  // 𝕱
#define UC_MATHEMATICAL_BOLD_FRAKTUR_CAPITAL_G                       0x1D572  0  // 𝕲
#define UC_MATHEMATICAL_BOLD_FRAKTUR_CAPITAL_H                       0x1D573  0  // 𝕳
#define UC_MATHEMATICAL_BOLD_FRAKTUR_CAPITAL_I                       0x1D574  0  // 𝕴
#define UC_MATHEMATICAL_BOLD_FRAKTUR_CAPITAL_J                       0x1D575  0  // 𝕵
#define UC_MATHEMATICAL_BOLD_FRAKTUR_CAPITAL_K                       0x1D576  0  // 𝕶
#define UC_MATHEMATICAL_BOLD_FRAKTUR_CAPITAL_L                       0x1D577  0  // 𝕷
#define UC_MATHEMATICAL_BOLD_FRAKTUR_CAPITAL_M                       0x1D578  0  // 𝕸
#define UC_MATHEMATICAL_BOLD_FRAKTUR_CAPITAL_N                       0x1D579  0  // 𝕹
#define UC_MATHEMATICAL_BOLD_FRAKTUR_CAPITAL_O                       0x1D57A  0  // 𝕺
#define UC_MATHEMATICAL_BOLD_FRAKTUR_CAPITAL_P                       0x1D57B  0  // 𝕻
#define UC_MATHEMATICAL_BOLD_FRAKTUR_CAPITAL_Q                       0x1D57C  0  // 𝕼
#define UC_MATHEMATICAL_BOLD_FRAKTUR_CAPITAL_R                       0x1D57D  0  // 𝕽
#define UC_MATHEMATICAL_BOLD_FRAKTUR_CAPITAL_S                       0x1D57E  0  // 𝕾
#define UC_MATHEMATICAL_BOLD_FRAKTUR_CAPITAL_T                       0x1D57F  0  // 𝕿
#define UC_MATHEMATICAL_BOLD_FRAKTUR_CAPITAL_U                       0x1D580  0  // 𝖀
#define UC_MATHEMATICAL_BOLD_FRAKTUR_CAPITAL_V                       0x1D581  0  // 𝖁
#define UC_MATHEMATICAL_BOLD_FRAKTUR_CAPITAL_W                       0x1D582  0  // 𝖂
#define UC_MATHEMATICAL_BOLD_FRAKTUR_CAPITAL_X                       0x1D583  0  // 𝖃
#define UC_MATHEMATICAL_BOLD_FRAKTUR_CAPITAL_Y                       0x1D584  0  // 𝖄
#define UC_MATHEMATICAL_BOLD_FRAKTUR_CAPITAL_Z                       0x1D585  0  // 𝖅
#define UC_MATHEMATICAL_BOLD_FRAKTUR_SMALL_A                         0x1D586  0  // 𝖆
#define UC_MATHEMATICAL_BOLD_FRAKTUR_SMALL_B                         0x1D587  0  // 𝖇
#define UC_MATHEMATICAL_BOLD_FRAKTUR_SMALL_C                         0x1D588  0  // 𝖈
#define UC_MATHEMATICAL_BOLD_FRAKTUR_SMALL_D                         0x1D589  0  // 𝖉
#define UC_MATHEMATICAL_BOLD_FRAKTUR_SMALL_E                         0x1D58A  0  // 𝖊
#define UC_MATHEMATICAL_BOLD_FRAKTUR_SMALL_F                         0x1D58B  0  // 𝖋
#define UC_MATHEMATICAL_BOLD_FRAKTUR_SMALL_G                         0x1D58C  0  // 𝖌
#define UC_MATHEMATICAL_BOLD_FRAKTUR_SMALL_H                         0x1D58D  0  // 𝖍
#define UC_MATHEMATICAL_BOLD_FRAKTUR_SMALL_I                         0x1D58E  0  // 𝖎
#define UC_MATHEMATICAL_BOLD_FRAKTUR_SMALL_J                         0x1D58F  0  // 𝖏
#define UC_MATHEMATICAL_BOLD_FRAKTUR_SMALL_K                         0x1D590  0  // 𝖐
#define UC_MATHEMATICAL_BOLD_FRAKTUR_SMALL_L                         0x1D591  0  // 𝖑
#define UC_MATHEMATICAL_BOLD_FRAKTUR_SMALL_M                         0x1D592  0  // 𝖒
#define UC_MATHEMATICAL_BOLD_FRAKTUR_SMALL_N                         0x1D593  0  // 𝖓
#define UC_MATHEMATICAL_BOLD_FRAKTUR_SMALL_O                         0x1D594  0  // 𝖔
#define UC_MATHEMATICAL_BOLD_FRAKTUR_SMALL_P                         0x1D595  0  // 𝖕
#define UC_MATHEMATICAL_BOLD_FRAKTUR_SMALL_Q                         0x1D596  0  // 𝖖
#define UC_MATHEMATICAL_BOLD_FRAKTUR_SMALL_R                         0x1D597  0  // 𝖗
#define UC_MATHEMATICAL_BOLD_FRAKTUR_SMALL_S                         0x1D598  0  // 𝖘
#define UC_MATHEMATICAL_BOLD_FRAKTUR_SMALL_T                         0x1D599  0  // 𝖙
#define UC_MATHEMATICAL_BOLD_FRAKTUR_SMALL_U                         0x1D59A  0  // 𝖚
#define UC_MATHEMATICAL_BOLD_FRAKTUR_SMALL_V                         0x1D59B  0  // 𝖛
#define UC_MATHEMATICAL_BOLD_FRAKTUR_SMALL_W                         0x1D59C  0  // 𝖜
#define UC_MATHEMATICAL_BOLD_FRAKTUR_SMALL_X                         0x1D59D  0  // 𝖝
#define UC_MATHEMATICAL_BOLD_FRAKTUR_SMALL_Y                         0x1D59E  0  // 𝖞
#define UC_MATHEMATICAL_BOLD_FRAKTUR_SMALL_Z                         0x1D59F  0  // 𝖟
#define UC_MATHEMATICAL_SANS_SERIF_CAPITAL_A                         0x1D5A0  0  // 𝖠
#define UC_MATHEMATICAL_SANS_SERIF_CAPITAL_B                         0x1D5A1  0  // 𝖡
#define UC_MATHEMATICAL_SANS_SERIF_CAPITAL_C                         0x1D5A2  0  // 𝖢
#define UC_MATHEMATICAL_SANS_SERIF_CAPITAL_D                         0x1D5A3  0  // 𝖣
#define UC_MATHEMATICAL_SANS_SERIF_CAPITAL_E                         0x1D5A4  0  // 𝖤
#define UC_MATHEMATICAL_SANS_SERIF_CAPITAL_F                         0x1D5A5  0  // 𝖥
#define UC_MATHEMATICAL_SANS_SERIF_CAPITAL_G                         0x1D5A6  0  // 𝖦
#define UC_MATHEMATICAL_SANS_SERIF_CAPITAL_H                         0x1D5A7  0  // 𝖧
#define UC_MATHEMATICAL_SANS_SERIF_CAPITAL_I                         0x1D5A8  0  // 𝖨
#define UC_MATHEMATICAL_SANS_SERIF_CAPITAL_J                         0x1D5A9  0  // 𝖩
#define UC_MATHEMATICAL_SANS_SERIF_CAPITAL_K                         0x1D5AA  0  // 𝖪
#define UC_MATHEMATICAL_SANS_SERIF_CAPITAL_L                         0x1D5AB  0  // 𝖫
#define UC_MATHEMATICAL_SANS_SERIF_CAPITAL_M                         0x1D5AC  0  // 𝖬
#define UC_MATHEMATICAL_SANS_SERIF_CAPITAL_N                         0x1D5AD  0  // 𝖭
#define UC_MATHEMATICAL_SANS_SERIF_CAPITAL_O                         0x1D5AE  0  // 𝖮
#define UC_MATHEMATICAL_SANS_SERIF_CAPITAL_P                         0x1D5AF  0  // 𝖯
#define UC_MATHEMATICAL_SANS_SERIF_CAPITAL_Q                         0x1D5B0  0  // 𝖰
#define UC_MATHEMATICAL_SANS_SERIF_CAPITAL_R                         0x1D5B1  0  // 𝖱
#define UC_MATHEMATICAL_SANS_SERIF_CAPITAL_S                         0x1D5B2  0  // 𝖲
#define UC_MATHEMATICAL_SANS_SERIF_CAPITAL_T                         0x1D5B3  0  // 𝖳
#define UC_MATHEMATICAL_SANS_SERIF_CAPITAL_U                         0x1D5B4  0  // 𝖴
#define UC_MATHEMATICAL_SANS_SERIF_CAPITAL_V                         0x1D5B5  0  // 𝖵
#define UC_MATHEMATICAL_SANS_SERIF_CAPITAL_W                         0x1D5B6  0  // 𝖶
#define UC_MATHEMATICAL_SANS_SERIF_CAPITAL_X                         0x1D5B7  0  // 𝖷
#define UC_MATHEMATICAL_SANS_SERIF_CAPITAL_Y                         0x1D5B8  0  // 𝖸
#define UC_MATHEMATICAL_SANS_SERIF_CAPITAL_Z                         0x1D5B9  0  // 𝖹
#define UC_MATHEMATICAL_SANS_SERIF_SMALL_A                           0x1D5BA  0  // 𝖺
#define UC_MATHEMATICAL_SANS_SERIF_SMALL_B                           0x1D5BB  0  // 𝖻
#define UC_MATHEMATICAL_SANS_SERIF_SMALL_C                           0x1D5BC  0  // 𝖼
#define UC_MATHEMATICAL_SANS_SERIF_SMALL_D                           0x1D5BD  0  // 𝖽
#define UC_MATHEMATICAL_SANS_SERIF_SMALL_E                           0x1D5BE  0  // 𝖾
#define UC_MATHEMATICAL_SANS_SERIF_SMALL_F                           0x1D5BF  0  // 𝖿
#define UC_MATHEMATICAL_SANS_SERIF_SMALL_G                           0x1D5C0  0  // 𝗀
#define UC_MATHEMATICAL_SANS_SERIF_SMALL_H                           0x1D5C1  0  // 𝗁
#define UC_MATHEMATICAL_SANS_SERIF_SMALL_I                           0x1D5C2  0  // 𝗂
#define UC_MATHEMATICAL_SANS_SERIF_SMALL_J                           0x1D5C3  0  // 𝗃
#define UC_MATHEMATICAL_SANS_SERIF_SMALL_K                           0x1D5C4  0  // 𝗄
#define UC_MATHEMATICAL_SANS_SERIF_SMALL_L                           0x1D5C5  0  // 𝗅
#define UC_MATHEMATICAL_SANS_SERIF_SMALL_M                           0x1D5C6  0  // 𝗆
#define UC_MATHEMATICAL_SANS_SERIF_SMALL_N                           0x1D5C7  0  // 𝗇
#define UC_MATHEMATICAL_SANS_SERIF_SMALL_O                           0x1D5C8  0  // 𝗈
#define UC_MATHEMATICAL_SANS_SERIF_SMALL_P                           0x1D5C9  0  // 𝗉
#define UC_MATHEMATICAL_SANS_SERIF_SMALL_Q                           0x1D5CA  0  // 𝗊
#define UC_MATHEMATICAL_SANS_SERIF_SMALL_R                           0x1D5CB  0  // 𝗋
#define UC_MATHEMATICAL_SANS_SERIF_SMALL_S                           0x1D5CC  0  // 𝗌
#define UC_MATHEMATICAL_SANS_SERIF_SMALL_T                           0x1D5CD  0  // 𝗍
#define UC_MATHEMATICAL_SANS_SERIF_SMALL_U                           0x1D5CE  0  // 𝗎
#define UC_MATHEMATICAL_SANS_SERIF_SMALL_V                           0x1D5CF  0  // 𝗏
#define UC_MATHEMATICAL_SANS_SERIF_SMALL_W                           0x1D5D0  0  // 𝗐
#define UC_MATHEMATICAL_SANS_SERIF_SMALL_X                           0x1D5D1  0  // 𝗑
#define UC_MATHEMATICAL_SANS_SERIF_SMALL_Y                           0x1D5D2  0  // 𝗒
#define UC_MATHEMATICAL_SANS_SERIF_SMALL_Z                           0x1D5D3  0  // 𝗓
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_A                    0x1D5D4  0  // 𝗔
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_B                    0x1D5D5  0  // 𝗕
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_C                    0x1D5D6  0  // 𝗖
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_D                    0x1D5D7  0  // 𝗗
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_E                    0x1D5D8  0  // 𝗘
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_F                    0x1D5D9  0  // 𝗙
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_G                    0x1D5DA  0  // 𝗚
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_H                    0x1D5DB  0  // 𝗛
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_I                    0x1D5DC  0  // 𝗜
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_J                    0x1D5DD  0  // 𝗝
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_K                    0x1D5DE  0  // 𝗞
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_L                    0x1D5DF  0  // 𝗟
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_M                    0x1D5E0  0  // 𝗠
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_N                    0x1D5E1  0  // 𝗡
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_O                    0x1D5E2  0  // 𝗢
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_P                    0x1D5E3  0  // 𝗣
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_Q                    0x1D5E4  0  // 𝗤
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_R                    0x1D5E5  0  // 𝗥
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_S                    0x1D5E6  0  // 𝗦
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_T                    0x1D5E7  0  // 𝗧
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_U                    0x1D5E8  0  // 𝗨
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_V                    0x1D5E9  0  // 𝗩
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_W                    0x1D5EA  0  // 𝗪
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_X                    0x1D5EB  0  // 𝗫
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_Y                    0x1D5EC  0  // 𝗬
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_Z                    0x1D5ED  0  // 𝗭
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_A                      0x1D5EE  0  // 𝗮
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_B                      0x1D5EF  0  // 𝗯
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_C                      0x1D5F0  0  // 𝗰
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_D                      0x1D5F1  0  // 𝗱
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_E                      0x1D5F2  0  // 𝗲
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_F                      0x1D5F3  0  // 𝗳
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_G                      0x1D5F4  0  // 𝗴
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_H                      0x1D5F5  0  // 𝗵
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_I                      0x1D5F6  0  // 𝗶
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_J                      0x1D5F7  0  // 𝗷
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_K                      0x1D5F8  0  // 𝗸
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_L                      0x1D5F9  0  // 𝗹
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_M                      0x1D5FA  0  // 𝗺
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_N                      0x1D5FB  0  // 𝗻
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_O                      0x1D5FC  0  // 𝗼
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_P                      0x1D5FD  0  // 𝗽
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_Q                      0x1D5FE  0  // 𝗾
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_R                      0x1D5FF  0  // 𝗿
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_S                      0x1D600  0  // 𝘀
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_T                      0x1D601  0  // 𝘁
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_U                      0x1D602  0  // 𝘂
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_V                      0x1D603  0  // 𝘃
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_W                      0x1D604  0  // 𝘄
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_X                      0x1D605  0  // 𝘅
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_Y                      0x1D606  0  // 𝘆
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_Z                      0x1D607  0  // 𝘇
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_CAPITAL_A                  0x1D608  0  // 𝘈
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_CAPITAL_B                  0x1D609  0  // 𝘉
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_CAPITAL_C                  0x1D60A  0  // 𝘊
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_CAPITAL_D                  0x1D60B  0  // 𝘋
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_CAPITAL_E                  0x1D60C  0  // 𝘌
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_CAPITAL_F                  0x1D60D  0  // 𝘍
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_CAPITAL_G                  0x1D60E  0  // 𝘎
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_CAPITAL_H                  0x1D60F  0  // 𝘏
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_CAPITAL_I                  0x1D610  0  // 𝘐
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_CAPITAL_J                  0x1D611  0  // 𝘑
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_CAPITAL_K                  0x1D612  0  // 𝘒
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_CAPITAL_L                  0x1D613  0  // 𝘓
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_CAPITAL_M                  0x1D614  0  // 𝘔
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_CAPITAL_N                  0x1D615  0  // 𝘕
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_CAPITAL_O                  0x1D616  0  // 𝘖
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_CAPITAL_P                  0x1D617  0  // 𝘗
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_CAPITAL_Q                  0x1D618  0  // 𝘘
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_CAPITAL_R                  0x1D619  0  // 𝘙
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_CAPITAL_S                  0x1D61A  0  // 𝘚
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_CAPITAL_T                  0x1D61B  0  // 𝘛
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_CAPITAL_U                  0x1D61C  0  // 𝘜
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_CAPITAL_V                  0x1D61D  0  // 𝘝
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_CAPITAL_W                  0x1D61E  0  // 𝘞
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_CAPITAL_X                  0x1D61F  0  // 𝘟
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_CAPITAL_Y                  0x1D620  0  // 𝘠
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_CAPITAL_Z                  0x1D621  0  // 𝘡
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_SMALL_A                    0x1D622  0  // 𝘢
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_SMALL_B                    0x1D623  0  // 𝘣
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_SMALL_C                    0x1D624  0  // 𝘤
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_SMALL_D                    0x1D625  0  // 𝘥
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_SMALL_E                    0x1D626  0  // 𝘦
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_SMALL_F                    0x1D627  0  // 𝘧
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_SMALL_G                    0x1D628  0  // 𝘨
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_SMALL_H                    0x1D629  0  // 𝘩
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_SMALL_I                    0x1D62A  0  // 𝘪
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_SMALL_J                    0x1D62B  0  // 𝘫
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_SMALL_K                    0x1D62C  0  // 𝘬
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_SMALL_L                    0x1D62D  0  // 𝘭
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_SMALL_M                    0x1D62E  0  // 𝘮
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_SMALL_N                    0x1D62F  0  // 𝘯
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_SMALL_O                    0x1D630  0  // 𝘰
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_SMALL_P                    0x1D631  0  // 𝘱
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_SMALL_Q                    0x1D632  0  // 𝘲
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_SMALL_R                    0x1D633  0  // 𝘳
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_SMALL_S                    0x1D634  0  // 𝘴
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_SMALL_T                    0x1D635  0  // 𝘵
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_SMALL_U                    0x1D636  0  // 𝘶
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_SMALL_V                    0x1D637  0  // 𝘷
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_SMALL_W                    0x1D638  0  // 𝘸
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_SMALL_X                    0x1D639  0  // 𝘹
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_SMALL_Y                    0x1D63A  0  // 𝘺
#define UC_MATHEMATICAL_SANS_SERIF_ITALIC_SMALL_Z                    0x1D63B  0  // 𝘻
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_A             0x1D63C  0  // 𝘼
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_B             0x1D63D  0  // 𝘽
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_C             0x1D63E  0  // 𝘾
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_D             0x1D63F  0  // 𝘿
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_E             0x1D640  0  // 𝙀
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_F             0x1D641  0  // 𝙁
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_G             0x1D642  0  // 𝙂
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_H             0x1D643  0  // 𝙃
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_I             0x1D644  0  // 𝙄
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_J             0x1D645  0  // 𝙅
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_K             0x1D646  0  // 𝙆
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_L             0x1D647  0  // 𝙇
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_M             0x1D648  0  // 𝙈
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_N             0x1D649  0  // 𝙉
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_O             0x1D64A  0  // 𝙊
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_P             0x1D64B  0  // 𝙋
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_Q             0x1D64C  0  // 𝙌
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_R             0x1D64D  0  // 𝙍
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_S             0x1D64E  0  // 𝙎
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_T             0x1D64F  0  // 𝙏
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_U             0x1D650  0  // 𝙐
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_V             0x1D651  0  // 𝙑
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_W             0x1D652  0  // 𝙒
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_X             0x1D653  0  // 𝙓
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_Y             0x1D654  0  // 𝙔
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_Z             0x1D655  0  // 𝙕
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_A               0x1D656  0  // 𝙖
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_B               0x1D657  0  // 𝙗
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_C               0x1D658  0  // 𝙘
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_D               0x1D659  0  // 𝙙
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_E               0x1D65A  0  // 𝙚
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_F               0x1D65B  0  // 𝙛
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_G               0x1D65C  0  // 𝙜
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_H               0x1D65D  0  // 𝙝
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_I               0x1D65E  0  // 𝙞
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_J               0x1D65F  0  // 𝙟
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_K               0x1D660  0  // 𝙠
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_L               0x1D661  0  // 𝙡
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_M               0x1D662  0  // 𝙢
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_N               0x1D663  0  // 𝙣
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_O               0x1D664  0  // 𝙤
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_P               0x1D665  0  // 𝙥
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_Q               0x1D666  0  // 𝙦
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_R               0x1D667  0  // 𝙧
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_S               0x1D668  0  // 𝙨
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_T               0x1D669  0  // 𝙩
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_U               0x1D66A  0  // 𝙪
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_V               0x1D66B  0  // 𝙫
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_W               0x1D66C  0  // 𝙬
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_X               0x1D66D  0  // 𝙭
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_Y               0x1D66E  0  // 𝙮
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_Z               0x1D66F  0  // 𝙯
#define UC_MATHEMATICAL_MONOSPACE_CAPITAL_A                          0x1D670  0  // 𝙰
#define UC_MATHEMATICAL_MONOSPACE_CAPITAL_B                          0x1D671  0  // 𝙱
#define UC_MATHEMATICAL_MONOSPACE_CAPITAL_C                          0x1D672  0  // 𝙲
#define UC_MATHEMATICAL_MONOSPACE_CAPITAL_D                          0x1D673  0  // 𝙳
#define UC_MATHEMATICAL_MONOSPACE_CAPITAL_E                          0x1D674  0  // 𝙴
#define UC_MATHEMATICAL_MONOSPACE_CAPITAL_F                          0x1D675  0  // 𝙵
#define UC_MATHEMATICAL_MONOSPACE_CAPITAL_G                          0x1D676  0  // 𝙶
#define UC_MATHEMATICAL_MONOSPACE_CAPITAL_H                          0x1D677  0  // 𝙷
#define UC_MATHEMATICAL_MONOSPACE_CAPITAL_I                          0x1D678  0  // 𝙸
#define UC_MATHEMATICAL_MONOSPACE_CAPITAL_J                          0x1D679  0  // 𝙹
#define UC_MATHEMATICAL_MONOSPACE_CAPITAL_K                          0x1D67A  0  // 𝙺
#define UC_MATHEMATICAL_MONOSPACE_CAPITAL_L                          0x1D67B  0  // 𝙻
#define UC_MATHEMATICAL_MONOSPACE_CAPITAL_M                          0x1D67C  0  // 𝙼
#define UC_MATHEMATICAL_MONOSPACE_CAPITAL_N                          0x1D67D  0  // 𝙽
#define UC_MATHEMATICAL_MONOSPACE_CAPITAL_O                          0x1D67E  0  // 𝙾
#define UC_MATHEMATICAL_MONOSPACE_CAPITAL_P                          0x1D67F  0  // 𝙿
#define UC_MATHEMATICAL_MONOSPACE_CAPITAL_Q                          0x1D680  0  // 𝚀
#define UC_MATHEMATICAL_MONOSPACE_CAPITAL_R                          0x1D681  0  // 𝚁
#define UC_MATHEMATICAL_MONOSPACE_CAPITAL_S                          0x1D682  0  // 𝚂
#define UC_MATHEMATICAL_MONOSPACE_CAPITAL_T                          0x1D683  0  // 𝚃
#define UC_MATHEMATICAL_MONOSPACE_CAPITAL_U                          0x1D684  0  // 𝚄
#define UC_MATHEMATICAL_MONOSPACE_CAPITAL_V                          0x1D685  0  // 𝚅
#define UC_MATHEMATICAL_MONOSPACE_CAPITAL_W                          0x1D686  0  // 𝚆
#define UC_MATHEMATICAL_MONOSPACE_CAPITAL_X                          0x1D687  0  // 𝚇
#define UC_MATHEMATICAL_MONOSPACE_CAPITAL_Y                          0x1D688  0  // 𝚈
#define UC_MATHEMATICAL_MONOSPACE_CAPITAL_Z                          0x1D689  0  // 𝚉
#define UC_MATHEMATICAL_MONOSPACE_SMALL_A                            0x1D68A  0  // 𝚊
#define UC_MATHEMATICAL_MONOSPACE_SMALL_B                            0x1D68B  0  // 𝚋
#define UC_MATHEMATICAL_MONOSPACE_SMALL_C                            0x1D68C  0  // 𝚌
#define UC_MATHEMATICAL_MONOSPACE_SMALL_D                            0x1D68D  0  // 𝚍
#define UC_MATHEMATICAL_MONOSPACE_SMALL_E                            0x1D68E  0  // 𝚎
#define UC_MATHEMATICAL_MONOSPACE_SMALL_F                            0x1D68F  0  // 𝚏
#define UC_MATHEMATICAL_MONOSPACE_SMALL_G                            0x1D690  0  // 𝚐
#define UC_MATHEMATICAL_MONOSPACE_SMALL_H                            0x1D691  0  // 𝚑
#define UC_MATHEMATICAL_MONOSPACE_SMALL_I                            0x1D692  0  // 𝚒
#define UC_MATHEMATICAL_MONOSPACE_SMALL_J                            0x1D693  0  // 𝚓
#define UC_MATHEMATICAL_MONOSPACE_SMALL_K                            0x1D694  0  // 𝚔
#define UC_MATHEMATICAL_MONOSPACE_SMALL_L                            0x1D695  0  // 𝚕
#define UC_MATHEMATICAL_MONOSPACE_SMALL_M                            0x1D696  0  // 𝚖
#define UC_MATHEMATICAL_MONOSPACE_SMALL_N                            0x1D697  0  // 𝚗
#define UC_MATHEMATICAL_MONOSPACE_SMALL_O                            0x1D698  0  // 𝚘
#define UC_MATHEMATICAL_MONOSPACE_SMALL_P                            0x1D699  0  // 𝚙
#define UC_MATHEMATICAL_MONOSPACE_SMALL_Q                            0x1D69A  0  // 𝚚
#define UC_MATHEMATICAL_MONOSPACE_SMALL_R                            0x1D69B  0  // 𝚛
#define UC_MATHEMATICAL_MONOSPACE_SMALL_S                            0x1D69C  0  // 𝚜
#define UC_MATHEMATICAL_MONOSPACE_SMALL_T                            0x1D69D  0  // 𝚝
#define UC_MATHEMATICAL_MONOSPACE_SMALL_U                            0x1D69E  0  // 𝚞
#define UC_MATHEMATICAL_MONOSPACE_SMALL_V                            0x1D69F  0  // 𝚟
#define UC_MATHEMATICAL_MONOSPACE_SMALL_W                            0x1D6A0  0  // 𝚠
#define UC_MATHEMATICAL_MONOSPACE_SMALL_X                            0x1D6A1  0  // 𝚡
#define UC_MATHEMATICAL_MONOSPACE_SMALL_Y                            0x1D6A2  0  // 𝚢
#define UC_MATHEMATICAL_MONOSPACE_SMALL_Z                            0x1D6A3  0  // 𝚣
#define UC_MATHEMATICAL_ITALIC_SMALL_DOTLESS_I                       0x1D6A4  0  // 𝚤
#define UC_MATHEMATICAL_ITALIC_SMALL_DOTLESS_J                       0x1D6A5  0  // 𝚥
#define UC_MATHEMATICAL_BOLD_CAPITAL_ALPHA                           0x1D6A8  0  // 𝚨
#define UC_MATHEMATICAL_BOLD_CAPITAL_BETA                            0x1D6A9  0  // 𝚩
#define UC_MATHEMATICAL_BOLD_CAPITAL_GAMMA                           0x1D6AA  0  // 𝚪
#define UC_MATHEMATICAL_BOLD_CAPITAL_DELTA                           0x1D6AB  0  // 𝚫
#define UC_MATHEMATICAL_BOLD_CAPITAL_EPSILON                         0x1D6AC  0  // 𝚬
#define UC_MATHEMATICAL_BOLD_CAPITAL_ZETA                            0x1D6AD  0  // 𝚭
#define UC_MATHEMATICAL_BOLD_CAPITAL_ETA                             0x1D6AE  0  // 𝚮
#define UC_MATHEMATICAL_BOLD_CAPITAL_THETA                           0x1D6AF  0  // 𝚯
#define UC_MATHEMATICAL_BOLD_CAPITAL_IOTA                            0x1D6B0  0  // 𝚰
#define UC_MATHEMATICAL_BOLD_CAPITAL_KAPPA                           0x1D6B1  0  // 𝚱
#define UC_MATHEMATICAL_BOLD_CAPITAL_LAMDA                           0x1D6B2  0  // 𝚲
#define UC_MATHEMATICAL_BOLD_CAPITAL_MU                              0x1D6B3  0  // 𝚳
#define UC_MATHEMATICAL_BOLD_CAPITAL_NU                              0x1D6B4  0  // 𝚴
#define UC_MATHEMATICAL_BOLD_CAPITAL_XI                              0x1D6B5  0  // 𝚵
#define UC_MATHEMATICAL_BOLD_CAPITAL_OMICRON                         0x1D6B6  0  // 𝚶
#define UC_MATHEMATICAL_BOLD_CAPITAL_PI                              0x1D6B7  0  // 𝚷
#define UC_MATHEMATICAL_BOLD_CAPITAL_RHO                             0x1D6B8  0  // 𝚸
#define UC_MATHEMATICAL_BOLD_CAPITAL_THETA_SYMBOL                    0x1D6B9  0  // 𝚹
#define UC_MATHEMATICAL_BOLD_CAPITAL_SIGMA                           0x1D6BA  0  // 𝚺
#define UC_MATHEMATICAL_BOLD_CAPITAL_TAU                             0x1D6BB  0  // 𝚻
#define UC_MATHEMATICAL_BOLD_CAPITAL_UPSILON                         0x1D6BC  0  // 𝚼
#define UC_MATHEMATICAL_BOLD_CAPITAL_PHI                             0x1D6BD  0  // 𝚽
#define UC_MATHEMATICAL_BOLD_CAPITAL_CHI                             0x1D6BE  0  // 𝚾
#define UC_MATHEMATICAL_BOLD_CAPITAL_PSI                             0x1D6BF  0  // 𝚿
#define UC_MATHEMATICAL_BOLD_CAPITAL_OMEGA                           0x1D6C0  0  // 𝛀
#define UC_MATHEMATICAL_BOLD_NABLA                                   0x1D6C1  0  // 𝛁
#define UC_MATHEMATICAL_BOLD_SMALL_ALPHA                             0x1D6C2  0  // 𝛂
#define UC_MATHEMATICAL_BOLD_SMALL_BETA                              0x1D6C3  0  // 𝛃
#define UC_MATHEMATICAL_BOLD_SMALL_GAMMA                             0x1D6C4  0  // 𝛄
#define UC_MATHEMATICAL_BOLD_SMALL_DELTA                             0x1D6C5  0  // 𝛅
#define UC_MATHEMATICAL_BOLD_SMALL_EPSILON                           0x1D6C6  0  // 𝛆
#define UC_MATHEMATICAL_BOLD_SMALL_ZETA                              0x1D6C7  0  // 𝛇
#define UC_MATHEMATICAL_BOLD_SMALL_ETA                               0x1D6C8  0  // 𝛈
#define UC_MATHEMATICAL_BOLD_SMALL_THETA                             0x1D6C9  0  // 𝛉
#define UC_MATHEMATICAL_BOLD_SMALL_IOTA                              0x1D6CA  0  // 𝛊
#define UC_MATHEMATICAL_BOLD_SMALL_KAPPA                             0x1D6CB  0  // 𝛋
#define UC_MATHEMATICAL_BOLD_SMALL_LAMDA                             0x1D6CC  0  // 𝛌
#define UC_MATHEMATICAL_BOLD_SMALL_MU                                0x1D6CD  0  // 𝛍
#define UC_MATHEMATICAL_BOLD_SMALL_NU                                0x1D6CE  0  // 𝛎
#define UC_MATHEMATICAL_BOLD_SMALL_XI                                0x1D6CF  0  // 𝛏
#define UC_MATHEMATICAL_BOLD_SMALL_OMICRON                           0x1D6D0  0  // 𝛐
#define UC_MATHEMATICAL_BOLD_SMALL_PI                                0x1D6D1  0  // 𝛑
#define UC_MATHEMATICAL_BOLD_SMALL_RHO                               0x1D6D2  0  // 𝛒
#define UC_MATHEMATICAL_BOLD_SMALL_FINAL_SIGMA                       0x1D6D3  0  // 𝛓
#define UC_MATHEMATICAL_BOLD_SMALL_SIGMA                             0x1D6D4  0  // 𝛔
#define UC_MATHEMATICAL_BOLD_SMALL_TAU                               0x1D6D5  0  // 𝛕
#define UC_MATHEMATICAL_BOLD_SMALL_UPSILON                           0x1D6D6  0  // 𝛖
#define UC_MATHEMATICAL_BOLD_SMALL_PHI                               0x1D6D7  0  // 𝛗
#define UC_MATHEMATICAL_BOLD_SMALL_CHI                               0x1D6D8  0  // 𝛘
#define UC_MATHEMATICAL_BOLD_SMALL_PSI                               0x1D6D9  0  // 𝛙
#define UC_MATHEMATICAL_BOLD_SMALL_OMEGA                             0x1D6DA  0  // 𝛚
#define UC_MATHEMATICAL_BOLD_PARTIAL_DIFFERENTIAL                    0x1D6DB  0  // 𝛛
#define UC_MATHEMATICAL_BOLD_EPSILON_SYMBOL                          0x1D6DC  0  // 𝛜
#define UC_MATHEMATICAL_BOLD_THETA_SYMBOL                            0x1D6DD  0  // 𝛝
#define UC_MATHEMATICAL_BOLD_KAPPA_SYMBOL                            0x1D6DE  0  // 𝛞
#define UC_MATHEMATICAL_BOLD_PHI_SYMBOL                              0x1D6DF  0  // 𝛟
#define UC_MATHEMATICAL_BOLD_RHO_SYMBOL                              0x1D6E0  0  // 𝛠
#define UC_MATHEMATICAL_BOLD_PI_SYMBOL                               0x1D6E1  0  // 𝛡
#define UC_MATHEMATICAL_ITALIC_CAPITAL_ALPHA                         0x1D6E2  0  // 𝛢
#define UC_MATHEMATICAL_ITALIC_CAPITAL_BETA                          0x1D6E3  0  // 𝛣
#define UC_MATHEMATICAL_ITALIC_CAPITAL_GAMMA                         0x1D6E4  0  // 𝛤
#define UC_MATHEMATICAL_ITALIC_CAPITAL_DELTA                         0x1D6E5  0  // 𝛥
#define UC_MATHEMATICAL_ITALIC_CAPITAL_EPSILON                       0x1D6E6  0  // 𝛦
#define UC_MATHEMATICAL_ITALIC_CAPITAL_ZETA                          0x1D6E7  0  // 𝛧
#define UC_MATHEMATICAL_ITALIC_CAPITAL_ETA                           0x1D6E8  0  // 𝛨
#define UC_MATHEMATICAL_ITALIC_CAPITAL_THETA                         0x1D6E9  0  // 𝛩
#define UC_MATHEMATICAL_ITALIC_CAPITAL_IOTA                          0x1D6EA  0  // 𝛪
#define UC_MATHEMATICAL_ITALIC_CAPITAL_KAPPA                         0x1D6EB  0  // 𝛫
#define UC_MATHEMATICAL_ITALIC_CAPITAL_LAMDA                         0x1D6EC  0  // 𝛬
#define UC_MATHEMATICAL_ITALIC_CAPITAL_MU                            0x1D6ED  0  // 𝛭
#define UC_MATHEMATICAL_ITALIC_CAPITAL_NU                            0x1D6EE  0  // 𝛮
#define UC_MATHEMATICAL_ITALIC_CAPITAL_XI                            0x1D6EF  0  // 𝛯
#define UC_MATHEMATICAL_ITALIC_CAPITAL_OMICRON                       0x1D6F0  0  // 𝛰
#define UC_MATHEMATICAL_ITALIC_CAPITAL_PI                            0x1D6F1  0  // 𝛱
#define UC_MATHEMATICAL_ITALIC_CAPITAL_RHO                           0x1D6F2  0  // 𝛲
#define UC_MATHEMATICAL_ITALIC_CAPITAL_THETA_SYMBOL                  0x1D6F3  0  // 𝛳
#define UC_MATHEMATICAL_ITALIC_CAPITAL_SIGMA                         0x1D6F4  0  // 𝛴
#define UC_MATHEMATICAL_ITALIC_CAPITAL_TAU                           0x1D6F5  0  // 𝛵
#define UC_MATHEMATICAL_ITALIC_CAPITAL_UPSILON                       0x1D6F6  0  // 𝛶
#define UC_MATHEMATICAL_ITALIC_CAPITAL_PHI                           0x1D6F7  0  // 𝛷
#define UC_MATHEMATICAL_ITALIC_CAPITAL_CHI                           0x1D6F8  0  // 𝛸
#define UC_MATHEMATICAL_ITALIC_CAPITAL_PSI                           0x1D6F9  0  // 𝛹
#define UC_MATHEMATICAL_ITALIC_CAPITAL_OMEGA                         0x1D6FA  0  // 𝛺
#define UC_MATHEMATICAL_ITALIC_NABLA                                 0x1D6FB  0  // 𝛻
#define UC_MATHEMATICAL_ITALIC_SMALL_ALPHA                           0x1D6FC  0  // 𝛼
#define UC_MATHEMATICAL_ITALIC_SMALL_BETA                            0x1D6FD  0  // 𝛽
#define UC_MATHEMATICAL_ITALIC_SMALL_GAMMA                           0x1D6FE  0  // 𝛾
#define UC_MATHEMATICAL_ITALIC_SMALL_DELTA                           0x1D6FF  0  // 𝛿
#define UC_MATHEMATICAL_ITALIC_SMALL_EPSILON                         0x1D700  0  // 𝜀
#define UC_MATHEMATICAL_ITALIC_SMALL_ZETA                            0x1D701  0  // 𝜁
#define UC_MATHEMATICAL_ITALIC_SMALL_ETA                             0x1D702  0  // 𝜂
#define UC_MATHEMATICAL_ITALIC_SMALL_THETA                           0x1D703  0  // 𝜃
#define UC_MATHEMATICAL_ITALIC_SMALL_IOTA                            0x1D704  0  // 𝜄
#define UC_MATHEMATICAL_ITALIC_SMALL_KAPPA                           0x1D705  0  // 𝜅
#define UC_MATHEMATICAL_ITALIC_SMALL_LAMDA                           0x1D706  0  // 𝜆
#define UC_MATHEMATICAL_ITALIC_SMALL_MU                              0x1D707  0  // 𝜇
#define UC_MATHEMATICAL_ITALIC_SMALL_NU                              0x1D708  0  // 𝜈
#define UC_MATHEMATICAL_ITALIC_SMALL_XI                              0x1D709  0  // 𝜉
#define UC_MATHEMATICAL_ITALIC_SMALL_OMICRON                         0x1D70A  0  // 𝜊
#define UC_MATHEMATICAL_ITALIC_SMALL_PI                              0x1D70B  0  // 𝜋
#define UC_MATHEMATICAL_ITALIC_SMALL_RHO                             0x1D70C  0  // 𝜌
#define UC_MATHEMATICAL_ITALIC_SMALL_FINAL_SIGMA                     0x1D70D  0  // 𝜍
#define UC_MATHEMATICAL_ITALIC_SMALL_SIGMA                           0x1D70E  0  // 𝜎
#define UC_MATHEMATICAL_ITALIC_SMALL_TAU                             0x1D70F  0  // 𝜏
#define UC_MATHEMATICAL_ITALIC_SMALL_UPSILON                         0x1D710  0  // 𝜐
#define UC_MATHEMATICAL_ITALIC_SMALL_PHI                             0x1D711  0  // 𝜑
#define UC_MATHEMATICAL_ITALIC_SMALL_CHI                             0x1D712  0  // 𝜒
#define UC_MATHEMATICAL_ITALIC_SMALL_PSI                             0x1D713  0  // 𝜓
#define UC_MATHEMATICAL_ITALIC_SMALL_OMEGA                           0x1D714  0  // 𝜔
#define UC_MATHEMATICAL_ITALIC_PARTIAL_DIFFERENTIAL                  0x1D715  0  // 𝜕
#define UC_MATHEMATICAL_ITALIC_EPSILON_SYMBOL                        0x1D716  0  // 𝜖
#define UC_MATHEMATICAL_ITALIC_THETA_SYMBOL                          0x1D717  0  // 𝜗
#define UC_MATHEMATICAL_ITALIC_KAPPA_SYMBOL                          0x1D718  0  // 𝜘
#define UC_MATHEMATICAL_ITALIC_PHI_SYMBOL                            0x1D719  0  // 𝜙
#define UC_MATHEMATICAL_ITALIC_RHO_SYMBOL                            0x1D71A  0  // 𝜚
#define UC_MATHEMATICAL_ITALIC_PI_SYMBOL                             0x1D71B  0  // 𝜛
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_ALPHA                    0x1D71C  0  // 𝜜
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_BETA                     0x1D71D  0  // 𝜝
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_GAMMA                    0x1D71E  0  // 𝜞
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_DELTA                    0x1D71F  0  // 𝜟
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_EPSILON                  0x1D720  0  // 𝜠
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_ZETA                     0x1D721  0  // 𝜡
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_ETA                      0x1D722  0  // 𝜢
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_THETA                    0x1D723  0  // 𝜣
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_IOTA                     0x1D724  0  // 𝜤
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_KAPPA                    0x1D725  0  // 𝜥
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_LAMDA                    0x1D726  0  // 𝜦
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_MU                       0x1D727  0  // 𝜧
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_NU                       0x1D728  0  // 𝜨
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_XI                       0x1D729  0  // 𝜩
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_OMICRON                  0x1D72A  0  // 𝜪
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_PI                       0x1D72B  0  // 𝜫
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_RHO                      0x1D72C  0  // 𝜬
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_THETA_SYMBOL             0x1D72D  0  // 𝜭
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_SIGMA                    0x1D72E  0  // 𝜮
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_TAU                      0x1D72F  0  // 𝜯
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_UPSILON                  0x1D730  0  // 𝜰
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_PHI                      0x1D731  0  // 𝜱
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_CHI                      0x1D732  0  // 𝜲
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_PSI                      0x1D733  0  // 𝜳
#define UC_MATHEMATICAL_BOLD_ITALIC_CAPITAL_OMEGA                    0x1D734  0  // 𝜴
#define UC_MATHEMATICAL_BOLD_ITALIC_NABLA                            0x1D735  0  // 𝜵
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_ALPHA                      0x1D736  0  // 𝜶
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_BETA                       0x1D737  0  // 𝜷
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_GAMMA                      0x1D738  0  // 𝜸
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_DELTA                      0x1D739  0  // 𝜹
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_EPSILON                    0x1D73A  0  // 𝜺
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_ZETA                       0x1D73B  0  // 𝜻
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_ETA                        0x1D73C  0  // 𝜼
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_THETA                      0x1D73D  0  // 𝜽
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_IOTA                       0x1D73E  0  // 𝜾
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_KAPPA                      0x1D73F  0  // 𝜿
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_LAMDA                      0x1D740  0  // 𝝀
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_MU                         0x1D741  0  // 𝝁
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_NU                         0x1D742  0  // 𝝂
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_XI                         0x1D743  0  // 𝝃
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_OMICRON                    0x1D744  0  // 𝝄
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_PI                         0x1D745  0  // 𝝅
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_RHO                        0x1D746  0  // 𝝆
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_FINAL_SIGMA                0x1D747  0  // 𝝇
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_SIGMA                      0x1D748  0  // 𝝈
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_TAU                        0x1D749  0  // 𝝉
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_UPSILON                    0x1D74A  0  // 𝝊
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_PHI                        0x1D74B  0  // 𝝋
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_CHI                        0x1D74C  0  // 𝝌
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_PSI                        0x1D74D  0  // 𝝍
#define UC_MATHEMATICAL_BOLD_ITALIC_SMALL_OMEGA                      0x1D74E  0  // 𝝎
#define UC_MATHEMATICAL_BOLD_ITALIC_PARTIAL_DIFFERENTIAL             0x1D74F  0  // 𝝏
#define UC_MATHEMATICAL_BOLD_ITALIC_EPSILON_SYMBOL                   0x1D750  0  // 𝝐
#define UC_MATHEMATICAL_BOLD_ITALIC_THETA_SYMBOL                     0x1D751  0  // 𝝑
#define UC_MATHEMATICAL_BOLD_ITALIC_KAPPA_SYMBOL                     0x1D752  0  // 𝝒
#define UC_MATHEMATICAL_BOLD_ITALIC_PHI_SYMBOL                       0x1D753  0  // 𝝓
#define UC_MATHEMATICAL_BOLD_ITALIC_RHO_SYMBOL                       0x1D754  0  // 𝝔
#define UC_MATHEMATICAL_BOLD_ITALIC_PI_SYMBOL                        0x1D755  0  // 𝝕
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_ALPHA                0x1D756  0  // 𝝖
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_BETA                 0x1D757  0  // 𝝗
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_GAMMA                0x1D758  0  // 𝝘
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_DELTA                0x1D759  0  // 𝝙
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_EPSILON              0x1D75A  0  // 𝝚
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_ZETA                 0x1D75B  0  // 𝝛
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_ETA                  0x1D75C  0  // 𝝜
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_THETA                0x1D75D  0  // 𝝝
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_IOTA                 0x1D75E  0  // 𝝞
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_KAPPA                0x1D75F  0  // 𝝟
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_LAMDA                0x1D760  0  // 𝝠
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_MU                   0x1D761  0  // 𝝡
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_NU                   0x1D762  0  // 𝝢
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_XI                   0x1D763  0  // 𝝣
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_OMICRON              0x1D764  0  // 𝝤
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_PI                   0x1D765  0  // 𝝥
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_RHO                  0x1D766  0  // 𝝦
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_THETA_SYMBOL         0x1D767  0  // 𝝧
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_SIGMA                0x1D768  0  // 𝝨
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_TAU                  0x1D769  0  // 𝝩
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_UPSILON              0x1D76A  0  // 𝝪
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_PHI                  0x1D76B  0  // 𝝫
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_CHI                  0x1D76C  0  // 𝝬
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_PSI                  0x1D76D  0  // 𝝭
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_CAPITAL_OMEGA                0x1D76E  0  // 𝝮
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_NABLA                        0x1D76F  0  // 𝝯
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_ALPHA                  0x1D770  0  // 𝝰
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_BETA                   0x1D771  0  // 𝝱
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_GAMMA                  0x1D772  0  // 𝝲
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_DELTA                  0x1D773  0  // 𝝳
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_EPSILON                0x1D774  0  // 𝝴
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_ZETA                   0x1D775  0  // 𝝵
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_ETA                    0x1D776  0  // 𝝶
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_THETA                  0x1D777  0  // 𝝷
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_IOTA                   0x1D778  0  // 𝝸
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_KAPPA                  0x1D779  0  // 𝝹
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_LAMDA                  0x1D77A  0  // 𝝺
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_MU                     0x1D77B  0  // 𝝻
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_NU                     0x1D77C  0  // 𝝼
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_XI                     0x1D77D  0  // 𝝽
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_OMICRON                0x1D77E  0  // 𝝾
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_PI                     0x1D77F  0  // 𝝿
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_RHO                    0x1D780  0  // 𝞀
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_FINAL_SIGMA            0x1D781  0  // 𝞁
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_SIGMA                  0x1D782  0  // 𝞂
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_TAU                    0x1D783  0  // 𝞃
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_UPSILON                0x1D784  0  // 𝞄
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_PHI                    0x1D785  0  // 𝞅
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_CHI                    0x1D786  0  // 𝞆
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_PSI                    0x1D787  0  // 𝞇
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_SMALL_OMEGA                  0x1D788  0  // 𝞈
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_PARTIAL_DIFFERENTIAL         0x1D789  0  // 𝞉
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_EPSILON_SYMBOL               0x1D78A  0  // 𝞊
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_THETA_SYMBOL                 0x1D78B  0  // 𝞋
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_KAPPA_SYMBOL                 0x1D78C  0  // 𝞌
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_PHI_SYMBOL                   0x1D78D  0  // 𝞍
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_RHO_SYMBOL                   0x1D78E  0  // 𝞎
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_PI_SYMBOL                    0x1D78F  0  // 𝞏
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_ALPHA         0x1D790  0  // 𝞐
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_BETA          0x1D791  0  // 𝞑
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_GAMMA         0x1D792  0  // 𝞒
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_DELTA         0x1D793  0  // 𝞓
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_EPSILON       0x1D794  0  // 𝞔
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_ZETA          0x1D795  0  // 𝞕
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_ETA           0x1D796  0  // 𝞖
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_THETA         0x1D797  0  // 𝞗
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_IOTA          0x1D798  0  // 𝞘
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_KAPPA         0x1D799  0  // 𝞙
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_LAMDA         0x1D79A  0  // 𝞚
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_MU            0x1D79B  0  // 𝞛
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_NU            0x1D79C  0  // 𝞜
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_XI            0x1D79D  0  // 𝞝
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_OMICRON       0x1D79E  0  // 𝞞
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_PI            0x1D79F  0  // 𝞟
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_RHO           0x1D7A0  0  // 𝞠
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_THETA_SYMBOL  0x1D7A1  0  // 𝞡
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_SIGMA         0x1D7A2  0  // 𝞢
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_TAU           0x1D7A3  0  // 𝞣
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_UPSILON       0x1D7A4  0  // 𝞤
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_PHI           0x1D7A5  0  // 𝞥
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_CHI           0x1D7A6  0  // 𝞦
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_PSI           0x1D7A7  0  // 𝞧
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_CAPITAL_OMEGA         0x1D7A8  0  // 𝞨
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_NABLA                 0x1D7A9  0  // 𝞩
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_ALPHA           0x1D7AA  0  // 𝞪
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_BETA            0x1D7AB  0  // 𝞫
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_GAMMA           0x1D7AC  0  // 𝞬
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_DELTA           0x1D7AD  0  // 𝞭
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_EPSILON         0x1D7AE  0  // 𝞮
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_ZETA            0x1D7AF  0  // 𝞯
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_ETA             0x1D7B0  0  // 𝞰
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_THETA           0x1D7B1  0  // 𝞱
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_IOTA            0x1D7B2  0  // 𝞲
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_KAPPA           0x1D7B3  0  // 𝞳
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_LAMDA           0x1D7B4  0  // 𝞴
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_MU              0x1D7B5  0  // 𝞵
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_NU              0x1D7B6  0  // 𝞶
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_XI              0x1D7B7  0  // 𝞷
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_OMICRON         0x1D7B8  0  // 𝞸
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_PI              0x1D7B9  0  // 𝞹
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_RHO             0x1D7BA  0  // 𝞺
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_FINAL_SIGMA     0x1D7BB  0  // 𝞻
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_SIGMA           0x1D7BC  0  // 𝞼
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_TAU             0x1D7BD  0  // 𝞽
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_UPSILON         0x1D7BE  0  // 𝞾
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_PHI             0x1D7BF  0  // 𝞿
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_CHI             0x1D7C0  0  // 𝟀
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_PSI             0x1D7C1  0  // 𝟁
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_SMALL_OMEGA           0x1D7C2  0  // 𝟂
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_PARTIAL_DIFFERENTIAL  0x1D7C3  0  // 𝟃
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_EPSILON_SYMBOL        0x1D7C4  0  // 𝟄
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_THETA_SYMBOL          0x1D7C5  0  // 𝟅
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_KAPPA_SYMBOL          0x1D7C6  0  // 𝟆
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_PHI_SYMBOL            0x1D7C7  0  // 𝟇
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_RHO_SYMBOL            0x1D7C8  0  // 𝟈
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_ITALIC_PI_SYMBOL             0x1D7C9  0  // 𝟉
#define UC_MATHEMATICAL_BOLD_CAPITAL_DIGAMMA                         0x1D7CA  0  // 𝟊
#define UC_MATHEMATICAL_BOLD_SMALL_DIGAMMA                           0x1D7CB  0  // 𝟋
#define UC_MATHEMATICAL_BOLD_DIGIT_ZERO                              0x1D7CE  0  // 𝟎
#define UC_MATHEMATICAL_BOLD_DIGIT_ONE                               0x1D7CF  0  // 𝟏
#define UC_MATHEMATICAL_BOLD_DIGIT_TWO                               0x1D7D0  0  // 𝟐
#define UC_MATHEMATICAL_BOLD_DIGIT_THREE                             0x1D7D1  0  // 𝟑
#define UC_MATHEMATICAL_BOLD_DIGIT_FOUR                              0x1D7D2  0  // 𝟒
#define UC_MATHEMATICAL_BOLD_DIGIT_FIVE                              0x1D7D3  0  // 𝟓
#define UC_MATHEMATICAL_BOLD_DIGIT_SIX                               0x1D7D4  0  // 𝟔
#define UC_MATHEMATICAL_BOLD_DIGIT_SEVEN                             0x1D7D5  0  // 𝟕
#define UC_MATHEMATICAL_BOLD_DIGIT_EIGHT                             0x1D7D6  0  // 𝟖
#define UC_MATHEMATICAL_BOLD_DIGIT_NINE                              0x1D7D7  0  // 𝟗
#define UC_MATHEMATICAL_DOUBLE_STRUCK_DIGIT_ZERO                     0x1D7D8  0  // 𝟘
#define UC_MATHEMATICAL_DOUBLE_STRUCK_DIGIT_ONE                      0x1D7D9  0  // 𝟙
#define UC_MATHEMATICAL_DOUBLE_STRUCK_DIGIT_TWO                      0x1D7DA  0  // 𝟚
#define UC_MATHEMATICAL_DOUBLE_STRUCK_DIGIT_THREE                    0x1D7DB  0  // 𝟛
#define UC_MATHEMATICAL_DOUBLE_STRUCK_DIGIT_FOUR                     0x1D7DC  0  // 𝟜
#define UC_MATHEMATICAL_DOUBLE_STRUCK_DIGIT_FIVE                     0x1D7DD  0  // 𝟝
#define UC_MATHEMATICAL_DOUBLE_STRUCK_DIGIT_SIX                      0x1D7DE  0  // 𝟞
#define UC_MATHEMATICAL_DOUBLE_STRUCK_DIGIT_SEVEN                    0x1D7DF  0  // 𝟟
#define UC_MATHEMATICAL_DOUBLE_STRUCK_DIGIT_EIGHT                    0x1D7E0  0  // 𝟠
#define UC_MATHEMATICAL_DOUBLE_STRUCK_DIGIT_NINE                     0x1D7E1  0  // 𝟡
#define UC_MATHEMATICAL_SANS_SERIF_DIGIT_ZERO                        0x1D7E2  0  // 𝟢
#define UC_MATHEMATICAL_SANS_SERIF_DIGIT_ONE                         0x1D7E3  0  // 𝟣
#define UC_MATHEMATICAL_SANS_SERIF_DIGIT_TWO                         0x1D7E4  0  // 𝟤
#define UC_MATHEMATICAL_SANS_SERIF_DIGIT_THREE                       0x1D7E5  0  // 𝟥
#define UC_MATHEMATICAL_SANS_SERIF_DIGIT_FOUR                        0x1D7E6  0  // 𝟦
#define UC_MATHEMATICAL_SANS_SERIF_DIGIT_FIVE                        0x1D7E7  0  // 𝟧
#define UC_MATHEMATICAL_SANS_SERIF_DIGIT_SIX                         0x1D7E8  0  // 𝟨
#define UC_MATHEMATICAL_SANS_SERIF_DIGIT_SEVEN                       0x1D7E9  0  // 𝟩
#define UC_MATHEMATICAL_SANS_SERIF_DIGIT_EIGHT                       0x1D7EA  0  // 𝟪
#define UC_MATHEMATICAL_SANS_SERIF_DIGIT_NINE                        0x1D7EB  0  // 𝟫
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_DIGIT_ZERO                   0x1D7EC  0  // 𝟬
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_DIGIT_ONE                    0x1D7ED  0  // 𝟭
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_DIGIT_TWO                    0x1D7EE  0  // 𝟮
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_DIGIT_THREE                  0x1D7EF  0  // 𝟯
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_DIGIT_FOUR                   0x1D7F0  0  // 𝟰
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_DIGIT_FIVE                   0x1D7F1  0  // 𝟱
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_DIGIT_SIX                    0x1D7F2  0  // 𝟲
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_DIGIT_SEVEN                  0x1D7F3  0  // 𝟳
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_DIGIT_EIGHT                  0x1D7F4  0  // 𝟴
#define UC_MATHEMATICAL_SANS_SERIF_BOLD_DIGIT_NINE                   0x1D7F5  0  // 𝟵
#define UC_MATHEMATICAL_MONOSPACE_DIGIT_ZERO                         0x1D7F6  0  // 𝟶
#define UC_MATHEMATICAL_MONOSPACE_DIGIT_ONE                          0x1D7F7  0  // 𝟷
#define UC_MATHEMATICAL_MONOSPACE_DIGIT_TWO                          0x1D7F8  0  // 𝟸
#define UC_MATHEMATICAL_MONOSPACE_DIGIT_THREE                        0x1D7F9  0  // 𝟹
#define UC_MATHEMATICAL_MONOSPACE_DIGIT_FOUR                         0x1D7FA  0  // 𝟺
#define UC_MATHEMATICAL_MONOSPACE_DIGIT_FIVE                         0x1D7FB  0  // 𝟻
#define UC_MATHEMATICAL_MONOSPACE_DIGIT_SIX                          0x1D7FC  0  // 𝟼
#define UC_MATHEMATICAL_MONOSPACE_DIGIT_SEVEN                        0x1D7FD  0  // 𝟽
#define UC_MATHEMATICAL_MONOSPACE_DIGIT_EIGHT                        0x1D7FE  0  // 𝟾
#define UC_MATHEMATICAL_MONOSPACE_DIGIT_NINE                         0x1D7FF  0  // 𝟿
