/*
 * Unicode keys for U+1F300 .. U+1F5FF
 *
 * This file was generated from Unidata 17.0.0 with the following license:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2025 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * See http://www.unicode.org/versions/Unicode17.0.0 for source data.
 */

#pragma once

#define UC_CYCLONE                                                                         0x1F300  0  // 🌀
#define UC_FOGGY                                                                           0x1F301  0  // 🌁
#define UC_CLOSED_UMBRELLA                                                                 0x1F302  0  // 🌂
#define UC_NIGHT_WITH_STARS                                                                0x1F303  0  // 🌃
#define UC_SUNRISE_OVER_MOUNTAINS                                                          0x1F304  0  // 🌄
#define UC_SUNRISE                                                                         0x1F305  0  // 🌅
#define UC_CITYSCAPE_AT_DUSK                                                               0x1F306  0  // 🌆
#define UC_SUNSET_OVER_BUILDINGS                                                           0x1F307  0  // 🌇
#define UC_RAINBOW                                                                         0x1F308  0  // 🌈
#define UC_BRIDGE_AT_NIGHT                                                                 0x1F309  0  // 🌉
#define UC_WATER_WAVE                                                                      0x1F30A  0  // 🌊
#define UC_VOLCANO                                                                         0x1F30B  0  // 🌋
#define UC_MILKY_WAY                                                                       0x1F30C  0  // 🌌
#define UC_EARTH_GLOBE_EUROPE_AFRICA                                                       0x1F30D  0  // 🌍
#define UC_EARTH_GLOBE_AMERICAS                                                            0x1F30E  0  // 🌎
#define UC_EARTH_GLOBE_ASIA_AUSTRALIA                                                      0x1F30F  0  // 🌏
#define UC_GLOBE_WITH_MERIDIANS                                                            0x1F310  0  // 🌐
#define UC_NEW_MOON_SYMBOL                                                                 0x1F311  0  // 🌑
#define UC_WAXING_CRESCENT_MOON_SYMBOL                                                     0x1F312  0  // 🌒
#define UC_FIRST_QUARTER_MOON_SYMBOL                                                       0x1F313  0  // 🌓
#define UC_WAXING_GIBBOUS_MOON_SYMBOL                                                      0x1F314  0  // 🌔
#define UC_FULL_MOON_SYMBOL                                                                0x1F315  0  // 🌕
#define UC_WANING_GIBBOUS_MOON_SYMBOL                                                      0x1F316  0  // 🌖
#define UC_LAST_QUARTER_MOON_SYMBOL                                                        0x1F317  0  // 🌗
#define UC_WANING_CRESCENT_MOON_SYMBOL                                                     0x1F318  0  // 🌘
#define UC_CRESCENT_MOON                                                                   0x1F319  0  // 🌙
#define UC_NEW_MOON_WITH_FACE                                                              0x1F31A  0  // 🌚
#define UC_FIRST_QUARTER_MOON_WITH_FACE                                                    0x1F31B  0  // 🌛
#define UC_LAST_QUARTER_MOON_WITH_FACE                                                     0x1F31C  0  // 🌜
#define UC_FULL_MOON_WITH_FACE                                                             0x1F31D  0  // 🌝
#define UC_SUN_WITH_FACE                                                                   0x1F31E  0  // 🌞
#define UC_GLOWING_STAR                                                                    0x1F31F  0  // 🌟
#define UC_SHOOTING_STAR                                                                   0x1F320  0  // 🌠
#define UC_THERMOMETER                                                                     0x1F321  0  // 🌡
#define UC_BLACK_DROPLET                                                                   0x1F322  0  // 🌢
#define UC_WHITE_SUN                                                                       0x1F323  0  // 🌣
#define UC_WHITE_SUN_WITH_SMALL_CLOUD                                                      0x1F324  0  // 🌤
#define UC_WHITE_SUN_BEHIND_CLOUD                                                          0x1F325  0  // 🌥
#define UC_WHITE_SUN_BEHIND_CLOUD_WITH_RAIN                                                0x1F326  0  // 🌦
#define UC_CLOUD_WITH_RAIN                                                                 0x1F327  0  // 🌧
#define UC_CLOUD_WITH_SNOW                                                                 0x1F328  0  // 🌨
#define UC_CLOUD_WITH_LIGHTNING                                                            0x1F329  0  // 🌩
#define UC_CLOUD_WITH_TORNADO                                                              0x1F32A  0  // 🌪
#define UC_FOG                                                                             0x1F32B  0  // 🌫
#define UC_WIND_BLOWING_FACE                                                               0x1F32C  0  // 🌬
#define UC_HOT_DOG                                                                         0x1F32D  0  // 🌭
#define UC_TACO                                                                            0x1F32E  0  // 🌮
#define UC_BURRITO                                                                         0x1F32F  0  // 🌯
#define UC_CHESTNUT                                                                        0x1F330  0  // 🌰
#define UC_SEEDLING                                                                        0x1F331  0  // 🌱
#define UC_EVERGREEN_TREE                                                                  0x1F332  0  // 🌲
#define UC_DECIDUOUS_TREE                                                                  0x1F333  0  // 🌳
#define UC_PALM_TREE                                                                       0x1F334  0  // 🌴
#define UC_CACTUS                                                                          0x1F335  0  // 🌵
#define UC_HOT_PEPPER                                                                      0x1F336  0  // 🌶
#define UC_TULIP                                                                           0x1F337  0  // 🌷
#define UC_CHERRY_BLOSSOM                                                                  0x1F338  0  // 🌸
#define UC_ROSE                                                                            0x1F339  0  // 🌹
#define UC_HIBISCUS                                                                        0x1F33A  0  // 🌺
#define UC_SUNFLOWER                                                                       0x1F33B  0  // 🌻
#define UC_BLOSSOM                                                                         0x1F33C  0  // 🌼
#define UC_EAR_OF_MAIZE                                                                    0x1F33D  0  // 🌽
#define UC_EAR_OF_RICE                                                                     0x1F33E  0  // 🌾
#define UC_HERB                                                                            0x1F33F  0  // 🌿
#define UC_FOUR_LEAF_CLOVER                                                                0x1F340  0  // 🍀
#define UC_MAPLE_LEAF                                                                      0x1F341  0  // 🍁
#define UC_FALLEN_LEAF                                                                     0x1F342  0  // 🍂
#define UC_LEAF_FLUTTERING_IN_WIND                                                         0x1F343  0  // 🍃
#define UC_MUSHROOM                                                                        0x1F344  0  // 🍄
#define UC_TOMATO                                                                          0x1F345  0  // 🍅
#define UC_AUBERGINE                                                                       0x1F346  0  // 🍆
#define UC_GRAPES                                                                          0x1F347  0  // 🍇
#define UC_MELON                                                                           0x1F348  0  // 🍈
#define UC_WATERMELON                                                                      0x1F349  0  // 🍉
#define UC_TANGERINE                                                                       0x1F34A  0  // 🍊
#define UC_LEMON                                                                           0x1F34B  0  // 🍋
#define UC_BANANA                                                                          0x1F34C  0  // 🍌
#define UC_PINEAPPLE                                                                       0x1F34D  0  // 🍍
#define UC_RED_APPLE                                                                       0x1F34E  0  // 🍎
#define UC_GREEN_APPLE                                                                     0x1F34F  0  // 🍏
#define UC_PEAR                                                                            0x1F350  0  // 🍐
#define UC_PEACH                                                                           0x1F351  0  // 🍑
#define UC_CHERRIES                                                                        0x1F352  0  // 🍒
#define UC_STRAWBERRY                                                                      0x1F353  0  // 🍓
#define UC_HAMBURGER                                                                       0x1F354  0  // 🍔
#define UC_SLICE_OF_PIZZA                                                                  0x1F355  0  // 🍕
#define UC_MEAT_ON_BONE                                                                    0x1F356  0  // 🍖
#define UC_POULTRY_LEG                                                                     0x1F357  0  // 🍗
#define UC_RICE_CRACKER                                                                    0x1F358  0  // 🍘
#define UC_RICE_BALL                                                                       0x1F359  0  // 🍙
#define UC_COOKED_RICE                                                                     0x1F35A  0  // 🍚
#define UC_CURRY_AND_RICE                                                                  0x1F35B  0  // 🍛
#define UC_STEAMING_BOWL                                                                   0x1F35C  0  // 🍜
#define UC_SPAGHETTI                                                                       0x1F35D  0  // 🍝
#define UC_BREAD                                                                           0x1F35E  0  // 🍞
#define UC_FRENCH_FRIES                                                                    0x1F35F  0  // 🍟
#define UC_ROASTED_SWEET_POTATO                                                            0x1F360  0  // 🍠
#define UC_DANGO                                                                           0x1F361  0  // 🍡
#define UC_ODEN                                                                            0x1F362  0  // 🍢
#define UC_SUSHI                                                                           0x1F363  0  // 🍣
#define UC_FRIED_SHRIMP                                                                    0x1F364  0  // 🍤
#define UC_FISH_CAKE_WITH_SWIRL_DESIGN                                                     0x1F365  0  // 🍥
#define UC_SOFT_ICE_CREAM                                                                  0x1F366  0  // 🍦
#define UC_SHAVED_ICE                                                                      0x1F367  0  // 🍧
#define UC_ICE_CREAM                                                                       0x1F368  0  // 🍨
#define UC_DOUGHNUT                                                                        0x1F369  0  // 🍩
#define UC_COOKIE                                                                          0x1F36A  0  // 🍪
#define UC_CHOCOLATE_BAR                                                                   0x1F36B  0  // 🍫
#define UC_CANDY                                                                           0x1F36C  0  // 🍬
#define UC_LOLLIPOP                                                                        0x1F36D  0  // 🍭
#define UC_CUSTARD                                                                         0x1F36E  0  // 🍮
#define UC_HONEY_POT                                                                       0x1F36F  0  // 🍯
#define UC_SHORTCAKE                                                                       0x1F370  0  // 🍰
#define UC_BENTO_BOX                                                                       0x1F371  0  // 🍱
#define UC_POT_OF_FOOD                                                                     0x1F372  0  // 🍲
#define UC_COOKING                                                                         0x1F373  0  // 🍳
#define UC_FORK_AND_KNIFE                                                                  0x1F374  0  // 🍴
#define UC_TEACUP_WITHOUT_HANDLE                                                           0x1F375  0  // 🍵
#define UC_SAKE_BOTTLE_AND_CUP                                                             0x1F376  0  // 🍶
#define UC_WINE_GLASS                                                                      0x1F377  0  // 🍷
#define UC_COCKTAIL_GLASS                                                                  0x1F378  0  // 🍸
#define UC_TROPICAL_DRINK                                                                  0x1F379  0  // 🍹
#define UC_BEER_MUG                                                                        0x1F37A  0  // 🍺
#define UC_CLINKING_BEER_MUGS                                                              0x1F37B  0  // 🍻
#define UC_BABY_BOTTLE                                                                     0x1F37C  0  // 🍼
#define UC_FORK_AND_KNIFE_WITH_PLATE                                                       0x1F37D  0  // 🍽
#define UC_BOTTLE_WITH_POPPING_CORK                                                        0x1F37E  0  // 🍾
#define UC_POPCORN                                                                         0x1F37F  0  // 🍿
#define UC_RIBBON                                                                          0x1F380  0  // 🎀
#define UC_WRAPPED_PRESENT                                                                 0x1F381  0  // 🎁
#define UC_BIRTHDAY_CAKE                                                                   0x1F382  0  // 🎂
#define UC_JACK_O_LANTERN                                                                  0x1F383  0  // 🎃
#define UC_CHRISTMAS_TREE                                                                  0x1F384  0  // 🎄
#define UC_FATHER_CHRISTMAS                                                                0x1F385  0  // 🎅
#define UC_FIREWORKS                                                                       0x1F386  0  // 🎆
#define UC_FIREWORK_SPARKLER                                                               0x1F387  0  // 🎇
#define UC_BALLOON                                                                         0x1F388  0  // 🎈
#define UC_PARTY_POPPER                                                                    0x1F389  0  // 🎉
#define UC_CONFETTI_BALL                                                                   0x1F38A  0  // 🎊
#define UC_TANABATA_TREE                                                                   0x1F38B  0  // 🎋
#define UC_CROSSED_FLAGS                                                                   0x1F38C  0  // 🎌
#define UC_PINE_DECORATION                                                                 0x1F38D  0  // 🎍
#define UC_JAPANESE_DOLLS                                                                  0x1F38E  0  // 🎎
#define UC_CARP_STREAMER                                                                   0x1F38F  0  // 🎏
#define UC_WIND_CHIME                                                                      0x1F390  0  // 🎐
#define UC_MOON_VIEWING_CEREMONY                                                           0x1F391  0  // 🎑
#define UC_SCHOOL_SATCHEL                                                                  0x1F392  0  // 🎒
#define UC_GRADUATION_CAP                                                                  0x1F393  0  // 🎓
#define UC_HEART_WITH_TIP_ON_THE_LEFT                                                      0x1F394  0  // 🎔
#define UC_BOUQUET_OF_FLOWERS                                                              0x1F395  0  // 🎕
#define UC_MILITARY_MEDAL                                                                  0x1F396  0  // 🎖
#define UC_REMINDER_RIBBON                                                                 0x1F397  0  // 🎗
#define UC_MUSICAL_KEYBOARD_WITH_JACKS                                                     0x1F398  0  // 🎘
#define UC_STUDIO_MICROPHONE                                                               0x1F399  0  // 🎙
#define UC_LEVEL_SLIDER                                                                    0x1F39A  0  // 🎚
#define UC_CONTROL_KNOBS                                                                   0x1F39B  0  // 🎛
#define UC_BEAMED_ASCENDING_MUSICAL_NOTES                                                  0x1F39C  0  // 🎜
#define UC_BEAMED_DESCENDING_MUSICAL_NOTES                                                 0x1F39D  0  // 🎝
#define UC_FILM_FRAMES                                                                     0x1F39E  0  // 🎞
#define UC_ADMISSION_TICKETS                                                               0x1F39F  0  // 🎟
#define UC_CAROUSEL_HORSE                                                                  0x1F3A0  0  // 🎠
#define UC_FERRIS_WHEEL                                                                    0x1F3A1  0  // 🎡
#define UC_ROLLER_COASTER                                                                  0x1F3A2  0  // 🎢
#define UC_FISHING_POLE_AND_FISH                                                           0x1F3A3  0  // 🎣
#define UC_MICROPHONE                                                                      0x1F3A4  0  // 🎤
#define UC_MOVIE_CAMERA                                                                    0x1F3A5  0  // 🎥
#define UC_CINEMA                                                                          0x1F3A6  0  // 🎦
#define UC_HEADPHONE                                                                       0x1F3A7  0  // 🎧
#define UC_ARTIST_PALETTE                                                                  0x1F3A8  0  // 🎨
#define UC_TOP_HAT                                                                         0x1F3A9  0  // 🎩
#define UC_CIRCUS_TENT                                                                     0x1F3AA  0  // 🎪
#define UC_TICKET                                                                          0x1F3AB  0  // 🎫
#define UC_CLAPPER_BOARD                                                                   0x1F3AC  0  // 🎬
#define UC_PERFORMING_ARTS                                                                 0x1F3AD  0  // 🎭
#define UC_VIDEO_GAME                                                                      0x1F3AE  0  // 🎮
#define UC_DIRECT_HIT                                                                      0x1F3AF  0  // 🎯
#define UC_SLOT_MACHINE                                                                    0x1F3B0  0  // 🎰
#define UC_BILLIARDS                                                                       0x1F3B1  0  // 🎱
#define UC_GAME_DIE                                                                        0x1F3B2  0  // 🎲
#define UC_BOWLING                                                                         0x1F3B3  0  // 🎳
#define UC_FLOWER_PLAYING_CARDS                                                            0x1F3B4  0  // 🎴
#define UC_MUSICAL_NOTE                                                                    0x1F3B5  0  // 🎵
#define UC_MULTIPLE_MUSICAL_NOTES                                                          0x1F3B6  0  // 🎶
#define UC_SAXOPHONE                                                                       0x1F3B7  0  // 🎷
#define UC_GUITAR                                                                          0x1F3B8  0  // 🎸
#define UC_MUSICAL_KEYBOARD                                                                0x1F3B9  0  // 🎹
#define UC_TRUMPET                                                                         0x1F3BA  0  // 🎺
#define UC_VIOLIN                                                                          0x1F3BB  0  // 🎻
#define UC_MUSICAL_SCORE                                                                   0x1F3BC  0  // 🎼
#define UC_RUNNING_SHIRT_WITH_SASH                                                         0x1F3BD  0  // 🎽
#define UC_TENNIS_RACQUET_AND_BALL                                                         0x1F3BE  0  // 🎾
#define UC_SKI_AND_SKI_BOOT                                                                0x1F3BF  0  // 🎿
#define UC_BASKETBALL_AND_HOOP                                                             0x1F3C0  0  // 🏀
#define UC_CHEQUERED_FLAG                                                                  0x1F3C1  0  // 🏁
#define UC_SNOWBOARDER                                                                     0x1F3C2  0  // 🏂
#define UC_RUNNER                                                                          0x1F3C3  0  // 🏃
#define UC_SURFER                                                                          0x1F3C4  0  // 🏄
#define UC_SPORTS_MEDAL                                                                    0x1F3C5  0  // 🏅
#define UC_TROPHY                                                                          0x1F3C6  0  // 🏆
#define UC_HORSE_RACING                                                                    0x1F3C7  0  // 🏇
#define UC_AMERICAN_FOOTBALL                                                               0x1F3C8  0  // 🏈
#define UC_RUGBY_FOOTBALL                                                                  0x1F3C9  0  // 🏉
#define UC_SWIMMER                                                                         0x1F3CA  0  // 🏊
#define UC_WEIGHT_LIFTER                                                                   0x1F3CB  0  // 🏋
#define UC_GOLFER                                                                          0x1F3CC  0  // 🏌
#define UC_RACING_MOTORCYCLE                                                               0x1F3CD  0  // 🏍
#define UC_RACING_CAR                                                                      0x1F3CE  0  // 🏎
#define UC_CRICKET_BAT_AND_BALL                                                            0x1F3CF  0  // 🏏
#define UC_VOLLEYBALL                                                                      0x1F3D0  0  // 🏐
#define UC_FIELD_HOCKEY_STICK_AND_BALL                                                     0x1F3D1  0  // 🏑
#define UC_ICE_HOCKEY_STICK_AND_PUCK                                                       0x1F3D2  0  // 🏒
#define UC_TABLE_TENNIS_PADDLE_AND_BALL                                                    0x1F3D3  0  // 🏓
#define UC_SNOW_CAPPED_MOUNTAIN                                                            0x1F3D4  0  // 🏔
#define UC_CAMPING                                                                         0x1F3D5  0  // 🏕
#define UC_BEACH_WITH_UMBRELLA                                                             0x1F3D6  0  // 🏖
#define UC_BUILDING_CONSTRUCTION                                                           0x1F3D7  0  // 🏗
#define UC_HOUSE_BUILDINGS                                                                 0x1F3D8  0  // 🏘
#define UC_CITYSCAPE                                                                       0x1F3D9  0  // 🏙
#define UC_DERELICT_HOUSE_BUILDING                                                         0x1F3DA  0  // 🏚
#define UC_CLASSICAL_BUILDING                                                              0x1F3DB  0  // 🏛
#define UC_DESERT                                                                          0x1F3DC  0  // 🏜
#define UC_DESERT_ISLAND                                                                   0x1F3DD  0  // 🏝
#define UC_NATIONAL_PARK                                                                   0x1F3DE  0  // 🏞
#define UC_STADIUM                                                                         0x1F3DF  0  // 🏟
#define UC_HOUSE_BUILDING                                                                  0x1F3E0  0  // 🏠
#define UC_HOUSE_WITH_GARDEN                                                               0x1F3E1  0  // 🏡
#define UC_OFFICE_BUILDING                                                                 0x1F3E2  0  // 🏢
#define UC_JAPANESE_POST_OFFICE                                                            0x1F3E3  0  // 🏣
#define UC_EUROPEAN_POST_OFFICE                                                            0x1F3E4  0  // 🏤
#define UC_HOSPITAL                                                                        0x1F3E5  0  // 🏥
#define UC_BANK                                                                            0x1F3E6  0  // 🏦
#define UC_AUTOMATED_TELLER_MACHINE                                                        0x1F3E7  0  // 🏧
#define UC_HOTEL                                                                           0x1F3E8  0  // 🏨
#define UC_LOVE_HOTEL                                                                      0x1F3E9  0  // 🏩
#define UC_CONVENIENCE_STORE                                                               0x1F3EA  0  // 🏪
#define UC_SCHOOL                                                                          0x1F3EB  0  // 🏫
#define UC_DEPARTMENT_STORE                                                                0x1F3EC  0  // 🏬
#define UC_FACTORY                                                                         0x1F3ED  0  // 🏭
#define UC_IZAKAYA_LANTERN                                                                 0x1F3EE  0  // 🏮
#define UC_JAPANESE_CASTLE                                                                 0x1F3EF  0  // 🏯
#define UC_EUROPEAN_CASTLE                                                                 0x1F3F0  0  // 🏰
#define UC_WHITE_PENNANT                                                                   0x1F3F1  0  // 🏱
#define UC_BLACK_PENNANT                                                                   0x1F3F2  0  // 🏲
#define UC_WAVING_WHITE_FLAG                                                               0x1F3F3  0  // 🏳
#define UC_WAVING_BLACK_FLAG                                                               0x1F3F4  0  // 🏴
#define UC_ROSETTE                                                                         0x1F3F5  0  // 🏵
#define UC_BLACK_ROSETTE                                                                   0x1F3F6  0  // 🏶
#define UC_LABEL                                                                           0x1F3F7  0  // 🏷
#define UC_BADMINTON_RACQUET_AND_SHUTTLECOCK                                               0x1F3F8  0  // 🏸
#define UC_BOW_AND_ARROW                                                                   0x1F3F9  0  // 🏹
#define UC_AMPHORA                                                                         0x1F3FA  0  // 🏺
#define UC_EMOJI_MODIFIER_FITZPATRICK_TYPE_1_2                                             0x1F3FB  0  // 🏻
#define UC_EMOJI_MODIFIER_FITZPATRICK_TYPE_3                                               0x1F3FC  0  // 🏼
#define UC_EMOJI_MODIFIER_FITZPATRICK_TYPE_4                                               0x1F3FD  0  // 🏽
#define UC_EMOJI_MODIFIER_FITZPATRICK_TYPE_5                                               0x1F3FE  0  // 🏾
#define UC_EMOJI_MODIFIER_FITZPATRICK_TYPE_6                                               0x1F3FF  0  // 🏿
#define UC_RAT                                                                             0x1F400  0  // 🐀
#define UC_MOUSE                                                                           0x1F401  0  // 🐁
#define UC_OX                                                                              0x1F402  0  // 🐂
#define UC_WATER_BUFFALO                                                                   0x1F403  0  // 🐃
#define UC_COW                                                                             0x1F404  0  // 🐄
#define UC_TIGER                                                                           0x1F405  0  // 🐅
#define UC_LEOPARD                                                                         0x1F406  0  // 🐆
#define UC_RABBIT                                                                          0x1F407  0  // 🐇
#define UC_CAT                                                                             0x1F408  0  // 🐈
#define UC_DRAGON                                                                          0x1F409  0  // 🐉
#define UC_CROCODILE                                                                       0x1F40A  0  // 🐊
#define UC_WHALE                                                                           0x1F40B  0  // 🐋
#define UC_SNAIL                                                                           0x1F40C  0  // 🐌
#define UC_SNAKE                                                                           0x1F40D  0  // 🐍
#define UC_HORSE                                                                           0x1F40E  0  // 🐎
#define UC_RAM                                                                             0x1F40F  0  // 🐏
#define UC_GOAT                                                                            0x1F410  0  // 🐐
#define UC_SHEEP                                                                           0x1F411  0  // 🐑
#define UC_MONKEY                                                                          0x1F412  0  // 🐒
#define UC_ROOSTER                                                                         0x1F413  0  // 🐓
#define UC_CHICKEN                                                                         0x1F414  0  // 🐔
#define UC_DOG                                                                             0x1F415  0  // 🐕
#define UC_PIG                                                                             0x1F416  0  // 🐖
#define UC_BOAR                                                                            0x1F417  0  // 🐗
#define UC_ELEPHANT                                                                        0x1F418  0  // 🐘
#define UC_OCTOPUS                                                                         0x1F419  0  // 🐙
#define UC_SPIRAL_SHELL                                                                    0x1F41A  0  // 🐚
#define UC_BUG                                                                             0x1F41B  0  // 🐛
#define UC_ANT                                                                             0x1F41C  0  // 🐜
#define UC_HONEYBEE                                                                        0x1F41D  0  // 🐝
#define UC_LADY_BEETLE                                                                     0x1F41E  0  // 🐞
#define UC_FISH                                                                            0x1F41F  0  // 🐟
#define UC_TROPICAL_FISH                                                                   0x1F420  0  // 🐠
#define UC_BLOWFISH                                                                        0x1F421  0  // 🐡
#define UC_TURTLE                                                                          0x1F422  0  // 🐢
#define UC_HATCHING_CHICK                                                                  0x1F423  0  // 🐣
#define UC_BABY_CHICK                                                                      0x1F424  0  // 🐤
#define UC_FRONT_FACING_BABY_CHICK                                                         0x1F425  0  // 🐥
#define UC_BIRD                                                                            0x1F426  0  // 🐦
#define UC_PENGUIN                                                                         0x1F427  0  // 🐧
#define UC_KOALA                                                                           0x1F428  0  // 🐨
#define UC_POODLE                                                                          0x1F429  0  // 🐩
#define UC_DROMEDARY_CAMEL                                                                 0x1F42A  0  // 🐪
#define UC_BACTRIAN_CAMEL                                                                  0x1F42B  0  // 🐫
#define UC_DOLPHIN                                                                         0x1F42C  0  // 🐬
#define UC_MOUSE_FACE                                                                      0x1F42D  0  // 🐭
#define UC_COW_FACE                                                                        0x1F42E  0  // 🐮
#define UC_TIGER_FACE                                                                      0x1F42F  0  // 🐯
#define UC_RABBIT_FACE                                                                     0x1F430  0  // 🐰
#define UC_CAT_FACE                                                                        0x1F431  0  // 🐱
#define UC_DRAGON_FACE                                                                     0x1F432  0  // 🐲
#define UC_SPOUTING_WHALE                                                                  0x1F433  0  // 🐳
#define UC_HORSE_FACE                                                                      0x1F434  0  // 🐴
#define UC_MONKEY_FACE                                                                     0x1F435  0  // 🐵
#define UC_DOG_FACE                                                                        0x1F436  0  // 🐶
#define UC_PIG_FACE                                                                        0x1F437  0  // 🐷
#define UC_FROG_FACE                                                                       0x1F438  0  // 🐸
#define UC_HAMSTER_FACE                                                                    0x1F439  0  // 🐹
#define UC_WOLF_FACE                                                                       0x1F43A  0  // 🐺
#define UC_BEAR_FACE                                                                       0x1F43B  0  // 🐻
#define UC_PANDA_FACE                                                                      0x1F43C  0  // 🐼
#define UC_PIG_NOSE                                                                        0x1F43D  0  // 🐽
#define UC_PAW_PRINTS                                                                      0x1F43E  0  // 🐾
#define UC_CHIPMUNK                                                                        0x1F43F  0  // 🐿
#define UC_EYES                                                                            0x1F440  0  // 👀
#define UC_EYE                                                                             0x1F441  0  // 👁
#define UC_EAR                                                                             0x1F442  0  // 👂
#define UC_NOSE                                                                            0x1F443  0  // 👃
#define UC_MOUTH                                                                           0x1F444  0  // 👄
#define UC_TONGUE                                                                          0x1F445  0  // 👅
#define UC_WHITE_UP_POINTING_BACKHAND_INDEX                                                0x1F446  0  // 👆
#define UC_WHITE_DOWN_POINTING_BACKHAND_INDEX                                              0x1F447  0  // 👇
#define UC_WHITE_LEFT_POINTING_BACKHAND_INDEX                                              0x1F448  0  // 👈
#define UC_WHITE_RIGHT_POINTING_BACKHAND_INDEX                                             0x1F449  0  // 👉
#define UC_FISTED_HAND_SIGN                                                                0x1F44A  0  // 👊
#define UC_WAVING_HAND_SIGN                                                                0x1F44B  0  // 👋
#define UC_OK_HAND_SIGN                                                                    0x1F44C  0  // 👌
#define UC_THUMBS_UP_SIGN                                                                  0x1F44D  0  // 👍
#define UC_THUMBS_DOWN_SIGN                                                                0x1F44E  0  // 👎
#define UC_CLAPPING_HANDS_SIGN                                                             0x1F44F  0  // 👏
#define UC_OPEN_HANDS_SIGN                                                                 0x1F450  0  // 👐
#define UC_CROWN                                                                           0x1F451  0  // 👑
#define UC_WOMANS_HAT                                                                      0x1F452  0  // 👒
#define UC_EYEGLASSES                                                                      0x1F453  0  // 👓
#define UC_NECKTIE                                                                         0x1F454  0  // 👔
#define UC_T_SHIRT                                                                         0x1F455  0  // 👕
#define UC_JEANS                                                                           0x1F456  0  // 👖
#define UC_DRESS                                                                           0x1F457  0  // 👗
#define UC_KIMONO                                                                          0x1F458  0  // 👘
#define UC_BIKINI                                                                          0x1F459  0  // 👙
#define UC_WOMANS_CLOTHES                                                                  0x1F45A  0  // 👚
#define UC_PURSE                                                                           0x1F45B  0  // 👛
#define UC_HANDBAG                                                                         0x1F45C  0  // 👜
#define UC_POUCH                                                                           0x1F45D  0  // 👝
#define UC_MANS_SHOE                                                                       0x1F45E  0  // 👞
#define UC_ATHLETIC_SHOE                                                                   0x1F45F  0  // 👟
#define UC_HIGH_HEELED_SHOE                                                                0x1F460  0  // 👠
#define UC_WOMANS_SANDAL                                                                   0x1F461  0  // 👡
#define UC_WOMANS_BOOTS                                                                    0x1F462  0  // 👢
#define UC_FOOTPRINTS                                                                      0x1F463  0  // 👣
#define UC_BUST_IN_SILHOUETTE                                                              0x1F464  0  // 👤
#define UC_BUSTS_IN_SILHOUETTE                                                             0x1F465  0  // 👥
#define UC_BOY                                                                             0x1F466  0  // 👦
#define UC_GIRL                                                                            0x1F467  0  // 👧
#define UC_MAN                                                                             0x1F468  0  // 👨
#define UC_WOMAN                                                                           0x1F469  0  // 👩
#define UC_FAMILY                                                                          0x1F46A  0  // 👪
#define UC_MAN_AND_WOMAN_HOLDING_HANDS                                                     0x1F46B  0  // 👫
#define UC_TWO_MEN_HOLDING_HANDS                                                           0x1F46C  0  // 👬
#define UC_TWO_WOMEN_HOLDING_HANDS                                                         0x1F46D  0  // 👭
#define UC_POLICE_OFFICER                                                                  0x1F46E  0  // 👮
#define UC_WOMAN_WITH_BUNNY_EARS                                                           0x1F46F  0  // 👯
#define UC_BRIDE_WITH_VEIL                                                                 0x1F470  0  // 👰
#define UC_PERSON_WITH_BLOND_HAIR                                                          0x1F471  0  // 👱
#define UC_MAN_WITH_GUA_PI_MAO                                                             0x1F472  0  // 👲
#define UC_MAN_WITH_TURBAN                                                                 0x1F473  0  // 👳
#define UC_OLDER_MAN                                                                       0x1F474  0  // 👴
#define UC_OLDER_WOMAN                                                                     0x1F475  0  // 👵
#define UC_BABY                                                                            0x1F476  0  // 👶
#define UC_CONSTRUCTION_WORKER                                                             0x1F477  0  // 👷
#define UC_PRINCESS                                                                        0x1F478  0  // 👸
#define UC_JAPANESE_OGRE                                                                   0x1F479  0  // 👹
#define UC_JAPANESE_GOBLIN                                                                 0x1F47A  0  // 👺
#define UC_GHOST                                                                           0x1F47B  0  // 👻
#define UC_BABY_ANGEL                                                                      0x1F47C  0  // 👼
#define UC_EXTRATERRESTRIAL_ALIEN                                                          0x1F47D  0  // 👽
#define UC_ALIEN_MONSTER                                                                   0x1F47E  0  // 👾
#define UC_IMP                                                                             0x1F47F  0  // 👿
#define UC_SKULL                                                                           0x1F480  0  // 💀
#define UC_INFORMATION_DESK_PERSON                                                         0x1F481  0  // 💁
#define UC_GUARDSMAN                                                                       0x1F482  0  // 💂
#define UC_DANCER                                                                          0x1F483  0  // 💃
#define UC_LIPSTICK                                                                        0x1F484  0  // 💄
#define UC_NAIL_POLISH                                                                     0x1F485  0  // 💅
#define UC_FACE_MASSAGE                                                                    0x1F486  0  // 💆
#define UC_HAIRCUT                                                                         0x1F487  0  // 💇
#define UC_BARBER_POLE                                                                     0x1F488  0  // 💈
#define UC_SYRINGE                                                                         0x1F489  0  // 💉
#define UC_PILL                                                                            0x1F48A  0  // 💊
#define UC_KISS_MARK                                                                       0x1F48B  0  // 💋
#define UC_LOVE_LETTER                                                                     0x1F48C  0  // 💌
#define UC_RING                                                                            0x1F48D  0  // 💍
#define UC_GEM_STONE                                                                       0x1F48E  0  // 💎
#define UC_KISS                                                                            0x1F48F  0  // 💏
#define UC_BOUQUET                                                                         0x1F490  0  // 💐
#define UC_COUPLE_WITH_HEART                                                               0x1F491  0  // 💑
#define UC_WEDDING                                                                         0x1F492  0  // 💒
#define UC_BEATING_HEART                                                                   0x1F493  0  // 💓
#define UC_BROKEN_HEART                                                                    0x1F494  0  // 💔
#define UC_TWO_HEARTS                                                                      0x1F495  0  // 💕
#define UC_SPARKLING_HEART                                                                 0x1F496  0  // 💖
#define UC_GROWING_HEART                                                                   0x1F497  0  // 💗
#define UC_HEART_WITH_ARROW                                                                0x1F498  0  // 💘
#define UC_BLUE_HEART                                                                      0x1F499  0  // 💙
#define UC_GREEN_HEART                                                                     0x1F49A  0  // 💚
#define UC_YELLOW_HEART                                                                    0x1F49B  0  // 💛
#define UC_PURPLE_HEART                                                                    0x1F49C  0  // 💜
#define UC_HEART_WITH_RIBBON                                                               0x1F49D  0  // 💝
#define UC_REVOLVING_HEARTS                                                                0x1F49E  0  // 💞
#define UC_HEART_DECORATION                                                                0x1F49F  0  // 💟
#define UC_DIAMOND_SHAPE_WITH_A_DOT_INSIDE                                                 0x1F4A0  0  // 💠
#define UC_ELECTRIC_LIGHT_BULB                                                             0x1F4A1  0  // 💡
#define UC_ANGER_SYMBOL                                                                    0x1F4A2  0  // 💢
#define UC_BOMB                                                                            0x1F4A3  0  // 💣
#define UC_SLEEPING_SYMBOL                                                                 0x1F4A4  0  // 💤
#define UC_COLLISION_SYMBOL                                                                0x1F4A5  0  // 💥
#define UC_SPLASHING_SWEAT_SYMBOL                                                          0x1F4A6  0  // 💦
#define UC_DROPLET                                                                         0x1F4A7  0  // 💧
#define UC_DASH_SYMBOL                                                                     0x1F4A8  0  // 💨
#define UC_PILE_OF_POO                                                                     0x1F4A9  0  // 💩
#define UC_FLEXED_BICEPS                                                                   0x1F4AA  0  // 💪
#define UC_DIZZY_SYMBOL                                                                    0x1F4AB  0  // 💫
#define UC_SPEECH_BALLOON                                                                  0x1F4AC  0  // 💬
#define UC_THOUGHT_BALLOON                                                                 0x1F4AD  0  // 💭
#define UC_WHITE_FLOWER                                                                    0x1F4AE  0  // 💮
#define UC_HUNDRED_POINTS_SYMBOL                                                           0x1F4AF  0  // 💯
#define UC_MONEY_BAG                                                                       0x1F4B0  0  // 💰
#define UC_CURRENCY_EXCHANGE                                                               0x1F4B1  0  // 💱
#define UC_HEAVY_DOLLAR_SIGN                                                               0x1F4B2  0  // 💲
#define UC_CREDIT_CARD                                                                     0x1F4B3  0  // 💳
#define UC_BANKNOTE_WITH_YEN_SIGN                                                          0x1F4B4  0  // 💴
#define UC_BANKNOTE_WITH_DOLLAR_SIGN                                                       0x1F4B5  0  // 💵
#define UC_BANKNOTE_WITH_EURO_SIGN                                                         0x1F4B6  0  // 💶
#define UC_BANKNOTE_WITH_POUND_SIGN                                                        0x1F4B7  0  // 💷
#define UC_MONEY_WITH_WINGS                                                                0x1F4B8  0  // 💸
#define UC_CHART_WITH_UPWARDS_TREND_AND_YEN_SIGN                                           0x1F4B9  0  // 💹
#define UC_SEAT                                                                            0x1F4BA  0  // 💺
#define UC_PERSONAL_COMPUTER                                                               0x1F4BB  0  // 💻
#define UC_BRIEFCASE                                                                       0x1F4BC  0  // 💼
#define UC_MINIDISC                                                                        0x1F4BD  0  // 💽
#define UC_FLOPPY_DISK                                                                     0x1F4BE  0  // 💾
#define UC_OPTICAL_DISC                                                                    0x1F4BF  0  // 💿
#define UC_DVD                                                                             0x1F4C0  0  // 📀
#define UC_FILE_FOLDER                                                                     0x1F4C1  0  // 📁
#define UC_OPEN_FILE_FOLDER                                                                0x1F4C2  0  // 📂
#define UC_PAGE_WITH_CURL                                                                  0x1F4C3  0  // 📃
#define UC_PAGE_FACING_UP                                                                  0x1F4C4  0  // 📄
#define UC_CALENDAR                                                                        0x1F4C5  0  // 📅
#define UC_TEAR_OFF_CALENDAR                                                               0x1F4C6  0  // 📆
#define UC_CARD_INDEX                                                                      0x1F4C7  0  // 📇
#define UC_CHART_WITH_UPWARDS_TREND                                                        0x1F4C8  0  // 📈
#define UC_CHART_WITH_DOWNWARDS_TREND                                                      0x1F4C9  0  // 📉
#define UC_BAR_CHART                                                                       0x1F4CA  0  // 📊
#define UC_CLIPBOARD                                                                       0x1F4CB  0  // 📋
#define UC_PUSHPIN                                                                         0x1F4CC  0  // 📌
#define UC_ROUND_PUSHPIN                                                                   0x1F4CD  0  // 📍
#define UC_PAPERCLIP                                                                       0x1F4CE  0  // 📎
#define UC_STRAIGHT_RULER                                                                  0x1F4CF  0  // 📏
#define UC_TRIANGULAR_RULER                                                                0x1F4D0  0  // 📐
#define UC_BOOKMARK_TABS                                                                   0x1F4D1  0  // 📑
#define UC_LEDGER                                                                          0x1F4D2  0  // 📒
#define UC_NOTEBOOK                                                                        0x1F4D3  0  // 📓
#define UC_NOTEBOOK_WITH_DECORATIVE_COVER                                                  0x1F4D4  0  // 📔
#define UC_CLOSED_BOOK                                                                     0x1F4D5  0  // 📕
#define UC_OPEN_BOOK                                                                       0x1F4D6  0  // 📖
#define UC_GREEN_BOOK                                                                      0x1F4D7  0  // 📗
#define UC_BLUE_BOOK                                                                       0x1F4D8  0  // 📘
#define UC_ORANGE_BOOK                                                                     0x1F4D9  0  // 📙
#define UC_BOOKS                                                                           0x1F4DA  0  // 📚
#define UC_NAME_BADGE                                                                      0x1F4DB  0  // 📛
#define UC_SCROLL                                                                          0x1F4DC  0  // 📜
#define UC_MEMO                                                                            0x1F4DD  0  // 📝
#define UC_TELEPHONE_RECEIVER                                                              0x1F4DE  0  // 📞
#define UC_PAGER                                                                           0x1F4DF  0  // 📟
#define UC_FAX_MACHINE                                                                     0x1F4E0  0  // 📠
#define UC_SATELLITE_ANTENNA                                                               0x1F4E1  0  // 📡
#define UC_PUBLIC_ADDRESS_LOUDSPEAKER                                                      0x1F4E2  0  // 📢
#define UC_CHEERING_MEGAPHONE                                                              0x1F4E3  0  // 📣
#define UC_OUTBOX_TRAY                                                                     0x1F4E4  0  // 📤
#define UC_INBOX_TRAY                                                                      0x1F4E5  0  // 📥
#define UC_PACKAGE                                                                         0x1F4E6  0  // 📦
#define UC_E_MAIL_SYMBOL                                                                   0x1F4E7  0  // 📧
#define UC_INCOMING_ENVELOPE                                                               0x1F4E8  0  // 📨
#define UC_ENVELOPE_WITH_DOWNWARDS_ARROW_ABOVE                                             0x1F4E9  0  // 📩
#define UC_CLOSED_MAILBOX_WITH_LOWERED_FLAG                                                0x1F4EA  0  // 📪
#define UC_CLOSED_MAILBOX_WITH_RAISED_FLAG                                                 0x1F4EB  0  // 📫
#define UC_OPEN_MAILBOX_WITH_RAISED_FLAG                                                   0x1F4EC  0  // 📬
#define UC_OPEN_MAILBOX_WITH_LOWERED_FLAG                                                  0x1F4ED  0  // 📭
#define UC_POSTBOX                                                                         0x1F4EE  0  // 📮
#define UC_POSTAL_HORN                                                                     0x1F4EF  0  // 📯
#define UC_NEWSPAPER                                                                       0x1F4F0  0  // 📰
#define UC_MOBILE_PHONE                                                                    0x1F4F1  0  // 📱
#define UC_MOBILE_PHONE_WITH_RIGHTWARDS_ARROW_AT_LEFT                                      0x1F4F2  0  // 📲
#define UC_VIBRATION_MODE                                                                  0x1F4F3  0  // 📳
#define UC_MOBILE_PHONE_OFF                                                                0x1F4F4  0  // 📴
#define UC_NO_MOBILE_PHONES                                                                0x1F4F5  0  // 📵
#define UC_ANTENNA_WITH_BARS                                                               0x1F4F6  0  // 📶
#define UC_CAMERA                                                                          0x1F4F7  0  // 📷
#define UC_CAMERA_WITH_FLASH                                                               0x1F4F8  0  // 📸
#define UC_VIDEO_CAMERA                                                                    0x1F4F9  0  // 📹
#define UC_TELEVISION                                                                      0x1F4FA  0  // 📺
#define UC_RADIO                                                                           0x1F4FB  0  // 📻
#define UC_VIDEOCASSETTE                                                                   0x1F4FC  0  // 📼
#define UC_FILM_PROJECTOR                                                                  0x1F4FD  0  // 📽
#define UC_PORTABLE_STEREO                                                                 0x1F4FE  0  // 📾
#define UC_PRAYER_BEADS                                                                    0x1F4FF  0  // 📿
#define UC_TWISTED_RIGHTWARDS_ARROWS                                                       0x1F500  0  // 🔀
#define UC_CLOCKWISE_RIGHTWARDS_AND_LEFTWARDS_OPEN_CIRCLE_ARROWS                           0x1F501  0  // 🔁
#define UC_CLOCKWISE_RIGHTWARDS_AND_LEFTWARDS_OPEN_CIRCLE_ARROWS_WITH_CIRCLED_ONE_OVERLAY  0x1F502  0  // 🔂
#define UC_CLOCKWISE_DOWNWARDS_AND_UPWARDS_OPEN_CIRCLE_ARROWS                              0x1F503  0  // 🔃
#define UC_ANTICLOCKWISE_DOWNWARDS_AND_UPWARDS_OPEN_CIRCLE_ARROWS                          0x1F504  0  // 🔄
#define UC_LOW_BRIGHTNESS_SYMBOL                                                           0x1F505  0  // 🔅
#define UC_HIGH_BRIGHTNESS_SYMBOL                                                          0x1F506  0  // 🔆
#define UC_SPEAKER_WITH_CANCELLATION_STROKE                                                0x1F507  0  // 🔇
#define UC_SPEAKER                                                                         0x1F508  0  // 🔈
#define UC_SPEAKER_WITH_ONE_SOUND_WAVE                                                     0x1F509  0  // 🔉
#define UC_SPEAKER_WITH_THREE_SOUND_WAVES                                                  0x1F50A  0  // 🔊
#define UC_BATTERY                                                                         0x1F50B  0  // 🔋
#define UC_ELECTRIC_PLUG                                                                   0x1F50C  0  // 🔌
#define UC_LEFT_POINTING_MAGNIFYING_GLASS                                                  0x1F50D  0  // 🔍
#define UC_RIGHT_POINTING_MAGNIFYING_GLASS                                                 0x1F50E  0  // 🔎
#define UC_LOCK_WITH_INK_PEN                                                               0x1F50F  0  // 🔏
#define UC_CLOSED_LOCK_WITH_KEY                                                            0x1F510  0  // 🔐
#define UC_KEY                                                                             0x1F511  0  // 🔑
#define UC_LOCK                                                                            0x1F512  0  // 🔒
#define UC_OPEN_LOCK                                                                       0x1F513  0  // 🔓
#define UC_BELL                                                                            0x1F514  0  // 🔔
#define UC_BELL_WITH_CANCELLATION_STROKE                                                   0x1F515  0  // 🔕
#define UC_BOOKMARK                                                                        0x1F516  0  // 🔖
#define UC_LINK_SYMBOL                                                                     0x1F517  0  // 🔗
#define UC_RADIO_BUTTON                                                                    0x1F518  0  // 🔘
#define UC_BACK_WITH_LEFTWARDS_ARROW_ABOVE                                                 0x1F519  0  // 🔙
#define UC_END_WITH_LEFTWARDS_ARROW_ABOVE                                                  0x1F51A  0  // 🔚
#define UC_ON_WITH_EXCLAMATION_MARK_WITH_LEFT_RIGHT_ARROW_ABOVE                            0x1F51B  0  // 🔛
#define UC_SOON_WITH_RIGHTWARDS_ARROW_ABOVE                                                0x1F51C  0  // 🔜
#define UC_TOP_WITH_UPWARDS_ARROW_ABOVE                                                    0x1F51D  0  // 🔝
#define UC_NO_ONE_UNDER_EIGHTEEN_SYMBOL                                                    0x1F51E  0  // 🔞
#define UC_KEYCAP_TEN                                                                      0x1F51F  0  // 🔟
#define UC_INPUT_SYMBOL_FOR_LATIN_CAPITAL_LETTERS                                          0x1F520  0  // 🔠
#define UC_INPUT_SYMBOL_FOR_LATIN_SMALL_LETTERS                                            0x1F521  0  // 🔡
#define UC_INPUT_SYMBOL_FOR_NUMBERS                                                        0x1F522  0  // 🔢
#define UC_INPUT_SYMBOL_FOR_SYMBOLS                                                        0x1F523  0  // 🔣
#define UC_INPUT_SYMBOL_FOR_LATIN_LETTERS                                                  0x1F524  0  // 🔤
#define UC_FIRE                                                                            0x1F525  0  // 🔥
#define UC_ELECTRIC_TORCH                                                                  0x1F526  0  // 🔦
#define UC_WRENCH                                                                          0x1F527  0  // 🔧
#define UC_HAMMER                                                                          0x1F528  0  // 🔨
#define UC_NUT_AND_BOLT                                                                    0x1F529  0  // 🔩
#define UC_HOCHO                                                                           0x1F52A  0  // 🔪
#define UC_PISTOL                                                                          0x1F52B  0  // 🔫
#define UC_MICROSCOPE                                                                      0x1F52C  0  // 🔬
#define UC_TELESCOPE                                                                       0x1F52D  0  // 🔭
#define UC_CRYSTAL_BALL                                                                    0x1F52E  0  // 🔮
#define UC_SIX_POINTED_STAR_WITH_MIDDLE_DOT                                                0x1F52F  0  // 🔯
#define UC_JAPANESE_SYMBOL_FOR_BEGINNER                                                    0x1F530  0  // 🔰
#define UC_TRIDENT_EMBLEM                                                                  0x1F531  0  // 🔱
#define UC_BLACK_SQUARE_BUTTON                                                             0x1F532  0  // 🔲
#define UC_WHITE_SQUARE_BUTTON                                                             0x1F533  0  // 🔳
#define UC_LARGE_RED_CIRCLE                                                                0x1F534  0  // 🔴
#define UC_LARGE_BLUE_CIRCLE                                                               0x1F535  0  // 🔵
#define UC_LARGE_ORANGE_DIAMOND                                                            0x1F536  0  // 🔶
#define UC_LARGE_BLUE_DIAMOND                                                              0x1F537  0  // 🔷
#define UC_SMALL_ORANGE_DIAMOND                                                            0x1F538  0  // 🔸
#define UC_SMALL_BLUE_DIAMOND                                                              0x1F539  0  // 🔹
#define UC_UP_POINTING_RED_TRIANGLE                                                        0x1F53A  0  // 🔺
#define UC_DOWN_POINTING_RED_TRIANGLE                                                      0x1F53B  0  // 🔻
#define UC_UP_POINTING_SMALL_RED_TRIANGLE                                                  0x1F53C  0  // 🔼
#define UC_DOWN_POINTING_SMALL_RED_TRIANGLE                                                0x1F53D  0  // 🔽
#define UC_LOWER_RIGHT_SHADOWED_WHITE_CIRCLE                                               0x1F53E  0  // 🔾
#define UC_UPPER_RIGHT_SHADOWED_WHITE_CIRCLE                                               0x1F53F  0  // 🔿
#define UC_CIRCLED_CROSS_POMMEE                                                            0x1F540  0  // 🕀
#define UC_CROSS_POMMEE_WITH_HALF_CIRCLE_BELOW                                             0x1F541  0  // 🕁
#define UC_CROSS_POMMEE                                                                    0x1F542  0  // 🕂
#define UC_NOTCHED_LEFT_SEMICIRCLE_WITH_THREE_DOTS                                         0x1F543  0  // 🕃
#define UC_NOTCHED_RIGHT_SEMICIRCLE_WITH_THREE_DOTS                                        0x1F544  0  // 🕄
#define UC_SYMBOL_FOR_MARKS_CHAPTER                                                        0x1F545  0  // 🕅
#define UC_WHITE_LATIN_CROSS                                                               0x1F546  0  // 🕆
#define UC_HEAVY_LATIN_CROSS                                                               0x1F547  0  // 🕇
#define UC_CELTIC_CROSS                                                                    0x1F548  0  // 🕈
#define UC_OM_SYMBOL                                                                       0x1F549  0  // 🕉
#define UC_DOVE_OF_PEACE                                                                   0x1F54A  0  // 🕊
#define UC_KAABA                                                                           0x1F54B  0  // 🕋
#define UC_MOSQUE                                                                          0x1F54C  0  // 🕌
#define UC_SYNAGOGUE                                                                       0x1F54D  0  // 🕍
#define UC_MENORAH_WITH_NINE_BRANCHES                                                      0x1F54E  0  // 🕎
#define UC_BOWL_OF_HYGIEIA                                                                 0x1F54F  0  // 🕏
#define UC_CLOCK_FACE_ONE_OCLOCK                                                           0x1F550  0  // 🕐
#define UC_CLOCK_FACE_TWO_OCLOCK                                                           0x1F551  0  // 🕑
#define UC_CLOCK_FACE_THREE_OCLOCK                                                         0x1F552  0  // 🕒
#define UC_CLOCK_FACE_FOUR_OCLOCK                                                          0x1F553  0  // 🕓
#define UC_CLOCK_FACE_FIVE_OCLOCK                                                          0x1F554  0  // 🕔
#define UC_CLOCK_FACE_SIX_OCLOCK                                                           0x1F555  0  // 🕕
#define UC_CLOCK_FACE_SEVEN_OCLOCK                                                         0x1F556  0  // 🕖
#define UC_CLOCK_FACE_EIGHT_OCLOCK                                                         0x1F557  0  // 🕗
#define UC_CLOCK_FACE_NINE_OCLOCK                                                          0x1F558  0  // 🕘
#define UC_CLOCK_FACE_TEN_OCLOCK                                                           0x1F559  0  // 🕙
#define UC_CLOCK_FACE_ELEVEN_OCLOCK                                                        0x1F55A  0  // 🕚
#define UC_CLOCK_FACE_TWELVE_OCLOCK                                                        0x1F55B  0  // 🕛
#define UC_CLOCK_FACE_ONE_THIRTY                                                           0x1F55C  0  // 🕜
#define UC_CLOCK_FACE_TWO_THIRTY                                                           0x1F55D  0  // 🕝
#define UC_CLOCK_FACE_THREE_THIRTY                                                         0x1F55E  0  // 🕞
#define UC_CLOCK_FACE_FOUR_THIRTY                                                          0x1F55F  0  // 🕟
#define UC_CLOCK_FACE_FIVE_THIRTY                                                          0x1F560  0  // 🕠
#define UC_CLOCK_FACE_SIX_THIRTY                                                           0x1F561  0  // 🕡
#define UC_CLOCK_FACE_SEVEN_THIRTY                                                         0x1F562  0  // 🕢
#define UC_CLOCK_FACE_EIGHT_THIRTY                                                         0x1F563  0  // 🕣
#define UC_CLOCK_FACE_NINE_THIRTY                                                          0x1F564  0  // 🕤
#define UC_CLOCK_FACE_TEN_THIRTY                                                           0x1F565  0  // 🕥
#define UC_CLOCK_FACE_ELEVEN_THIRTY                                                        0x1F566  0  // 🕦
#define UC_CLOCK_FACE_TWELVE_THIRTY                                                        0x1F567  0  // 🕧
#define UC_RIGHT_SPEAKER                                                                   0x1F568  0  // 🕨
#define UC_RIGHT_SPEAKER_WITH_ONE_SOUND_WAVE                                               0x1F569  0  // 🕩
#define UC_RIGHT_SPEAKER_WITH_THREE_SOUND_WAVES                                            0x1F56A  0  // 🕪
#define UC_BULLHORN                                                                        0x1F56B  0  // 🕫
#define UC_BULLHORN_WITH_SOUND_WAVES                                                       0x1F56C  0  // 🕬
#define UC_RINGING_BELL                                                                    0x1F56D  0  // 🕭
#define UC_BOOK                                                                            0x1F56E  0  // 🕮
#define UC_CANDLE                                                                          0x1F56F  0  // 🕯
#define UC_MANTELPIECE_CLOCK                                                               0x1F570  0  // 🕰
#define UC_BLACK_SKULL_AND_CROSSBONES                                                      0x1F571  0  // 🕱
#define UC_NO_PIRACY                                                                       0x1F572  0  // 🕲
#define UC_HOLE                                                                            0x1F573  0  // 🕳
#define UC_MAN_IN_BUSINESS_SUIT_LEVITATING                                                 0x1F574  0  // 🕴
#define UC_SLEUTH_OR_SPY                                                                   0x1F575  0  // 🕵
#define UC_DARK_SUNGLASSES                                                                 0x1F576  0  // 🕶
#define UC_SPIDER                                                                          0x1F577  0  // 🕷
#define UC_SPIDER_WEB                                                                      0x1F578  0  // 🕸
#define UC_JOYSTICK                                                                        0x1F579  0  // 🕹
#define UC_MAN_DANCING                                                                     0x1F57A  0  // 🕺
#define UC_LEFT_HAND_TELEPHONE_RECEIVER                                                    0x1F57B  0  // 🕻
#define UC_TELEPHONE_RECEIVER_WITH_PAGE                                                    0x1F57C  0  // 🕼
#define UC_RIGHT_HAND_TELEPHONE_RECEIVER                                                   0x1F57D  0  // 🕽
#define UC_WHITE_TOUCHTONE_TELEPHONE                                                       0x1F57E  0  // 🕾
#define UC_BLACK_TOUCHTONE_TELEPHONE                                                       0x1F57F  0  // 🕿
#define UC_TELEPHONE_ON_TOP_OF_MODEM                                                       0x1F580  0  // 🖀
#define UC_CLAMSHELL_MOBILE_PHONE                                                          0x1F581  0  // 🖁
#define UC_BACK_OF_ENVELOPE                                                                0x1F582  0  // 🖂
#define UC_STAMPED_ENVELOPE                                                                0x1F583  0  // 🖃
#define UC_ENVELOPE_WITH_LIGHTNING                                                         0x1F584  0  // 🖄
#define UC_FLYING_ENVELOPE                                                                 0x1F585  0  // 🖅
#define UC_PEN_OVER_STAMPED_ENVELOPE                                                       0x1F586  0  // 🖆
#define UC_LINKED_PAPERCLIPS                                                               0x1F587  0  // 🖇
#define UC_BLACK_PUSHPIN                                                                   0x1F588  0  // 🖈
#define UC_LOWER_LEFT_PENCIL                                                               0x1F589  0  // 🖉
#define UC_LOWER_LEFT_BALLPOINT_PEN                                                        0x1F58A  0  // 🖊
#define UC_LOWER_LEFT_FOUNTAIN_PEN                                                         0x1F58B  0  // 🖋
#define UC_LOWER_LEFT_PAINTBRUSH                                                           0x1F58C  0  // 🖌
#define UC_LOWER_LEFT_CRAYON                                                               0x1F58D  0  // 🖍
#define UC_LEFT_WRITING_HAND                                                               0x1F58E  0  // 🖎
#define UC_TURNED_OK_HAND_SIGN                                                             0x1F58F  0  // 🖏
#define UC_RAISED_HAND_WITH_FINGERS_SPLAYED                                                0x1F590  0  // 🖐
#define UC_REVERSED_RAISED_HAND_WITH_FINGERS_SPLAYED                                       0x1F591  0  // 🖑
#define UC_REVERSED_THUMBS_UP_SIGN                                                         0x1F592  0  // 🖒
#define UC_REVERSED_THUMBS_DOWN_SIGN                                                       0x1F593  0  // 🖓
#define UC_REVERSED_VICTORY_HAND                                                           0x1F594  0  // 🖔
#define UC_REVERSED_HAND_WITH_MIDDLE_FINGER_EXTENDED                                       0x1F595  0  // 🖕
#define UC_RAISED_HAND_WITH_PART_BETWEEN_MIDDLE_AND_RING_FINGERS                           0x1F596  0  // 🖖
#define UC_WHITE_DOWN_POINTING_LEFT_HAND_INDEX                                             0x1F597  0  // 🖗
#define UC_SIDEWAYS_WHITE_LEFT_POINTING_INDEX                                              0x1F598  0  // 🖘
#define UC_SIDEWAYS_WHITE_RIGHT_POINTING_INDEX                                             0x1F599  0  // 🖙
#define UC_SIDEWAYS_BLACK_LEFT_POINTING_INDEX                                              0x1F59A  0  // 🖚
#define UC_SIDEWAYS_BLACK_RIGHT_POINTING_INDEX                                             0x1F59B  0  // 🖛
#define UC_BLACK_LEFT_POINTING_BACKHAND_INDEX                                              0x1F59C  0  // 🖜
#define UC_BLACK_RIGHT_POINTING_BACKHAND_INDEX                                             0x1F59D  0  // 🖝
#define UC_SIDEWAYS_WHITE_UP_POINTING_INDEX                                                0x1F59E  0  // 🖞
#define UC_SIDEWAYS_WHITE_DOWN_POINTING_INDEX                                              0x1F59F  0  // 🖟
#define UC_SIDEWAYS_BLACK_UP_POINTING_INDEX                                                0x1F5A0  0  // 🖠
#define UC_SIDEWAYS_BLACK_DOWN_POINTING_INDEX                                              0x1F5A1  0  // 🖡
#define UC_BLACK_UP_POINTING_BACKHAND_INDEX                                                0x1F5A2  0  // 🖢
#define UC_BLACK_DOWN_POINTING_BACKHAND_INDEX                                              0x1F5A3  0  // 🖣
#define UC_BLACK_HEART                                                                     0x1F5A4  0  // 🖤
#define UC_DESKTOP_COMPUTER                                                                0x1F5A5  0  // 🖥
#define UC_KEYBOARD_AND_MOUSE                                                              0x1F5A6  0  // 🖦
#define UC_THREE_NETWORKED_COMPUTERS                                                       0x1F5A7  0  // 🖧
#define UC_PRINTER                                                                         0x1F5A8  0  // 🖨
#define UC_POCKET_CALCULATOR                                                               0x1F5A9  0  // 🖩
#define UC_BLACK_HARD_SHELL_FLOPPY_DISK                                                    0x1F5AA  0  // 🖪
#define UC_WHITE_HARD_SHELL_FLOPPY_DISK                                                    0x1F5AB  0  // 🖫
#define UC_SOFT_SHELL_FLOPPY_DISK                                                          0x1F5AC  0  // 🖬
#define UC_TAPE_CARTRIDGE                                                                  0x1F5AD  0  // 🖭
#define UC_WIRED_KEYBOARD                                                                  0x1F5AE  0  // 🖮
#define UC_ONE_BUTTON_MOUSE                                                                0x1F5AF  0  // 🖯
#define UC_TWO_BUTTON_MOUSE                                                                0x1F5B0  0  // 🖰
#define UC_THREE_BUTTON_MOUSE                                                              0x1F5B1  0  // 🖱
#define UC_TRACKBALL                                                                       0x1F5B2  0  // 🖲
#define UC_OLD_PERSONAL_COMPUTER                                                           0x1F5B3  0  // 🖳
#define UC_HARD_DISK                                                                       0x1F5B4  0  // 🖴
#define UC_SCREEN                                                                          0x1F5B5  0  // 🖵
#define UC_PRINTER_ICON                                                                    0x1F5B6  0  // 🖶
#define UC_FAX_ICON                                                                        0x1F5B7  0  // 🖷
#define UC_OPTICAL_DISC_ICON                                                               0x1F5B8  0  // 🖸
#define UC_DOCUMENT_WITH_TEXT                                                              0x1F5B9  0  // 🖹
#define UC_DOCUMENT_WITH_TEXT_AND_PICTURE                                                  0x1F5BA  0  // 🖺
#define UC_DOCUMENT_WITH_PICTURE                                                           0x1F5BB  0  // 🖻
#define UC_FRAME_WITH_PICTURE                                                              0x1F5BC  0  // 🖼
#define UC_FRAME_WITH_TILES                                                                0x1F5BD  0  // 🖽
#define UC_FRAME_WITH_AN_X                                                                 0x1F5BE  0  // 🖾
#define UC_BLACK_FOLDER                                                                    0x1F5BF  0  // 🖿
#define UC_FOLDER                                                                          0x1F5C0  0  // 🗀
#define UC_OPEN_FOLDER                                                                     0x1F5C1  0  // 🗁
#define UC_CARD_INDEX_DIVIDERS                                                             0x1F5C2  0  // 🗂
#define UC_CARD_FILE_BOX                                                                   0x1F5C3  0  // 🗃
#define UC_FILE_CABINET                                                                    0x1F5C4  0  // 🗄
#define UC_EMPTY_NOTE                                                                      0x1F5C5  0  // 🗅
#define UC_EMPTY_NOTE_PAGE                                                                 0x1F5C6  0  // 🗆
#define UC_EMPTY_NOTE_PAD                                                                  0x1F5C7  0  // 🗇
#define UC_NOTE                                                                            0x1F5C8  0  // 🗈
#define UC_NOTE_PAGE                                                                       0x1F5C9  0  // 🗉
#define UC_NOTE_PAD                                                                        0x1F5CA  0  // 🗊
#define UC_EMPTY_DOCUMENT                                                                  0x1F5CB  0  // 🗋
#define UC_EMPTY_PAGE                                                                      0x1F5CC  0  // 🗌
#define UC_EMPTY_PAGES                                                                     0x1F5CD  0  // 🗍
#define UC_DOCUMENT                                                                        0x1F5CE  0  // 🗎
#define UC_PAGE                                                                            0x1F5CF  0  // 🗏
#define UC_PAGES                                                                           0x1F5D0  0  // 🗐
#define UC_WASTEBASKET                                                                     0x1F5D1  0  // 🗑
#define UC_SPIRAL_NOTE_PAD                                                                 0x1F5D2  0  // 🗒
#define UC_SPIRAL_CALENDAR_PAD                                                             0x1F5D3  0  // 🗓
#define UC_DESKTOP_WINDOW                                                                  0x1F5D4  0  // 🗔
#define UC_MINIMIZE                                                                        0x1F5D5  0  // 🗕
#define UC_MAXIMIZE                                                                        0x1F5D6  0  // 🗖
#define UC_OVERLAP                                                                         0x1F5D7  0  // 🗗
#define UC_CLOCKWISE_RIGHT_AND_LEFT_SEMICIRCLE_ARROWS                                      0x1F5D8  0  // 🗘
#define UC_CANCELLATION_X                                                                  0x1F5D9  0  // 🗙
#define UC_INCREASE_FONT_SIZE_SYMBOL                                                       0x1F5DA  0  // 🗚
#define UC_DECREASE_FONT_SIZE_SYMBOL                                                       0x1F5DB  0  // 🗛
#define UC_COMPRESSION                                                                     0x1F5DC  0  // 🗜
#define UC_OLD_KEY                                                                         0x1F5DD  0  // 🗝
#define UC_ROLLED_UP_NEWSPAPER                                                             0x1F5DE  0  // 🗞
#define UC_PAGE_WITH_CIRCLED_TEXT                                                          0x1F5DF  0  // 🗟
#define UC_STOCK_CHART                                                                     0x1F5E0  0  // 🗠
#define UC_DAGGER_KNIFE                                                                    0x1F5E1  0  // 🗡
#define UC_LIPS                                                                            0x1F5E2  0  // 🗢
#define UC_SPEAKING_HEAD_IN_SILHOUETTE                                                     0x1F5E3  0  // 🗣
#define UC_THREE_RAYS_ABOVE                                                                0x1F5E4  0  // 🗤
#define UC_THREE_RAYS_BELOW                                                                0x1F5E5  0  // 🗥
#define UC_THREE_RAYS_LEFT                                                                 0x1F5E6  0  // 🗦
#define UC_THREE_RAYS_RIGHT                                                                0x1F5E7  0  // 🗧
#define UC_LEFT_SPEECH_BUBBLE                                                              0x1F5E8  0  // 🗨
#define UC_RIGHT_SPEECH_BUBBLE                                                             0x1F5E9  0  // 🗩
#define UC_TWO_SPEECH_BUBBLES                                                              0x1F5EA  0  // 🗪
#define UC_THREE_SPEECH_BUBBLES                                                            0x1F5EB  0  // 🗫
#define UC_LEFT_THOUGHT_BUBBLE                                                             0x1F5EC  0  // 🗬
#define UC_RIGHT_THOUGHT_BUBBLE                                                            0x1F5ED  0  // 🗭
#define UC_LEFT_ANGER_BUBBLE                                                               0x1F5EE  0  // 🗮
#define UC_RIGHT_ANGER_BUBBLE                                                              0x1F5EF  0  // 🗯
#define UC_MOOD_BUBBLE                                                                     0x1F5F0  0  // 🗰
#define UC_LIGHTNING_MOOD_BUBBLE                                                           0x1F5F1  0  // 🗱
#define UC_LIGHTNING_MOOD                                                                  0x1F5F2  0  // 🗲
#define UC_BALLOT_BOX_WITH_BALLOT                                                          0x1F5F3  0  // 🗳
#define UC_BALLOT_SCRIPT_X                                                                 0x1F5F4  0  // 🗴
#define UC_BALLOT_BOX_WITH_SCRIPT_X                                                        0x1F5F5  0  // 🗵
#define UC_BALLOT_BOLD_SCRIPT_X                                                            0x1F5F6  0  // 🗶
#define UC_BALLOT_BOX_WITH_BOLD_SCRIPT_X                                                   0x1F5F7  0  // 🗷
#define UC_LIGHT_CHECK_MARK                                                                0x1F5F8  0  // 🗸
#define UC_BALLOT_BOX_WITH_BOLD_CHECK                                                      0x1F5F9  0  // 🗹
#define UC_WORLD_MAP                                                                       0x1F5FA  0  // 🗺
#define UC_MOUNT_FUJI                                                                      0x1F5FB  0  // 🗻
#define UC_TOKYO_TOWER                                                                     0x1F5FC  0  // 🗼
#define UC_STATUE_OF_LIBERTY                                                               0x1F5FD  0  // 🗽
#define UC_SILHOUETTE_OF_JAPAN                                                             0x1F5FE  0  // 🗾
#define UC_MOYAI                                                                           0x1F5FF  0  // 🗿
