/*
 * Unicode keys for U+2600 .. U+26FF
 *
 * This file was generated from Unicode 16.0.0.
 *
 * See http://www.unicode.org/versions/Unicode16.0.0 for source data.
 */

#pragma once

#define UC_BLACK_SUN_WITH_RAYS                               0x2600  0  // ☀
#define UC_CLOUD                                             0x2601  0  // ☁
#define UC_UMBRELLA                                          0x2602  0  // ☂
#define UC_SNOWMAN                                           0x2603  0  // ☃
#define UC_COMET                                             0x2604  0  // ☄
#define UC_BLACK_STAR                                        0x2605  0  // ★
#define UC_WHITE_STAR                                        0x2606  0  // ☆
#define UC_LIGHTNING                                         0x2607  0  // ☇
#define UC_THUNDERSTORM                                      0x2608  0  // ☈
#define UC_SUN                                               0x2609  0  // ☉
#define UC_ASCENDING_NODE                                    0x260A  0  // ☊
#define UC_DESCENDING_NODE                                   0x260B  0  // ☋
#define UC_CONJUNCTION                                       0x260C  0  // ☌
#define UC_OPPOSITION                                        0x260D  0  // ☍
#define UC_BLACK_TELEPHONE                                   0x260E  0  // ☎
#define UC_WHITE_TELEPHONE                                   0x260F  0  // ☏
#define UC_BALLOT_BOX                                        0x2610  0  // ☐
#define UC_BALLOT_BOX_WITH_CHECK                             0x2611  0  // ☑
#define UC_BALLOT_BOX_WITH_X                                 0x2612  0  // ☒
#define UC_SALTIRE                                           0x2613  0  // ☓
#define UC_UMBRELLA_WITH_RAIN_DROPS                          0x2614  0  // ☔
#define UC_HOT_BEVERAGE                                      0x2615  0  // ☕
#define UC_WHITE_SHOGI_PIECE                                 0x2616  0  // ☖
#define UC_BLACK_SHOGI_PIECE                                 0x2617  0  // ☗
#define UC_SHAMROCK                                          0x2618  0  // ☘
#define UC_REVERSED_ROTATED_FLORAL_HEART_BULLET              0x2619  0  // ☙
#define UC_BLACK_LEFT_POINTING_INDEX                         0x261A  0  // ☚
#define UC_BLACK_RIGHT_POINTING_INDEX                        0x261B  0  // ☛
#define UC_WHITE_LEFT_POINTING_INDEX                         0x261C  0  // ☜
#define UC_WHITE_UP_POINTING_INDEX                           0x261D  0  // ☝
#define UC_WHITE_RIGHT_POINTING_INDEX                        0x261E  0  // ☞
#define UC_WHITE_DOWN_POINTING_INDEX                         0x261F  0  // ☟
#define UC_SKULL_AND_CROSSBONES                              0x2620  0  // ☠
#define UC_CAUTION_SIGN                                      0x2621  0  // ☡
#define UC_RADIOACTIVE_SIGN                                  0x2622  0  // ☢
#define UC_BIOHAZARD_SIGN                                    0x2623  0  // ☣
#define UC_CADUCEUS                                          0x2624  0  // ☤
#define UC_ANKH                                              0x2625  0  // ☥
#define UC_ORTHODOX_CROSS                                    0x2626  0  // ☦
#define UC_CHI_RHO                                           0x2627  0  // ☧
#define UC_CROSS_OF_LORRAINE                                 0x2628  0  // ☨
#define UC_CROSS_OF_JERUSALEM                                0x2629  0  // ☩
#define UC_STAR_AND_CRESCENT                                 0x262A  0  // ☪
#define UC_FARSI_SYMBOL                                      0x262B  0  // ☫
#define UC_ADI_SHAKTI                                        0x262C  0  // ☬
#define UC_HAMMER_AND_SICKLE                                 0x262D  0  // ☭
#define UC_PEACE_SYMBOL                                      0x262E  0  // ☮
#define UC_YIN_YANG                                          0x262F  0  // ☯
#define UC_TRIGRAM_FOR_HEAVEN                                0x2630  0  // ☰
#define UC_TRIGRAM_FOR_LAKE                                  0x2631  0  // ☱
#define UC_TRIGRAM_FOR_FIRE                                  0x2632  0  // ☲
#define UC_TRIGRAM_FOR_THUNDER                               0x2633  0  // ☳
#define UC_TRIGRAM_FOR_WIND                                  0x2634  0  // ☴
#define UC_TRIGRAM_FOR_WATER                                 0x2635  0  // ☵
#define UC_TRIGRAM_FOR_MOUNTAIN                              0x2636  0  // ☶
#define UC_TRIGRAM_FOR_EARTH                                 0x2637  0  // ☷
#define UC_WHEEL_OF_DHARMA                                   0x2638  0  // ☸
#define UC_WHITE_FROWNING_FACE                               0x2639  0  // ☹
#define UC_WHITE_SMILING_FACE                                0x263A  0  // ☺
#define UC_BLACK_SMILING_FACE                                0x263B  0  // ☻
#define UC_WHITE_SUN_WITH_RAYS                               0x263C  0  // ☼
#define UC_FIRST_QUARTER_MOON                                0x263D  0  // ☽
#define UC_LAST_QUARTER_MOON                                 0x263E  0  // ☾
#define UC_MERCURY                                           0x263F  0  // ☿
#define UC_FEMALE_SIGN                                       0x2640  0  // ♀
#define UC_EARTH                                             0x2641  0  // ♁
#define UC_MALE_SIGN                                         0x2642  0  // ♂
#define UC_JUPITER                                           0x2643  0  // ♃
#define UC_SATURN                                            0x2644  0  // ♄
#define UC_URANUS                                            0x2645  0  // ♅
#define UC_NEPTUNE                                           0x2646  0  // ♆
#define UC_PLUTO                                             0x2647  0  // ♇
#define UC_ARIES                                             0x2648  0  // ♈
#define UC_TAURUS                                            0x2649  0  // ♉
#define UC_GEMINI                                            0x264A  0  // ♊
#define UC_CANCER                                            0x264B  0  // ♋
#define UC_LEO                                               0x264C  0  // ♌
#define UC_VIRGO                                             0x264D  0  // ♍
#define UC_LIBRA                                             0x264E  0  // ♎
#define UC_SCORPIUS                                          0x264F  0  // ♏
#define UC_SAGITTARIUS                                       0x2650  0  // ♐
#define UC_CAPRICORN                                         0x2651  0  // ♑
#define UC_AQUARIUS                                          0x2652  0  // ♒
#define UC_PISCES                                            0x2653  0  // ♓
#define UC_WHITE_CHESS_KING                                  0x2654  0  // ♔
#define UC_WHITE_CHESS_QUEEN                                 0x2655  0  // ♕
#define UC_WHITE_CHESS_ROOK                                  0x2656  0  // ♖
#define UC_WHITE_CHESS_BISHOP                                0x2657  0  // ♗
#define UC_WHITE_CHESS_KNIGHT                                0x2658  0  // ♘
#define UC_WHITE_CHESS_PAWN                                  0x2659  0  // ♙
#define UC_BLACK_CHESS_KING                                  0x265A  0  // ♚
#define UC_BLACK_CHESS_QUEEN                                 0x265B  0  // ♛
#define UC_BLACK_CHESS_ROOK                                  0x265C  0  // ♜
#define UC_BLACK_CHESS_BISHOP                                0x265D  0  // ♝
#define UC_BLACK_CHESS_KNIGHT                                0x265E  0  // ♞
#define UC_BLACK_CHESS_PAWN                                  0x265F  0  // ♟
#define UC_BLACK_SPADE_SUIT                                  0x2660  0  // ♠
#define UC_WHITE_HEART_SUIT                                  0x2661  0  // ♡
#define UC_WHITE_DIAMOND_SUIT                                0x2662  0  // ♢
#define UC_BLACK_CLUB_SUIT                                   0x2663  0  // ♣
#define UC_WHITE_SPADE_SUIT                                  0x2664  0  // ♤
#define UC_BLACK_HEART_SUIT                                  0x2665  0  // ♥
#define UC_BLACK_DIAMOND_SUIT                                0x2666  0  // ♦
#define UC_WHITE_CLUB_SUIT                                   0x2667  0  // ♧
#define UC_HOT_SPRINGS                                       0x2668  0  // ♨
#define UC_QUARTER_NOTE                                      0x2669  0  // ♩
#define UC_EIGHTH_NOTE                                       0x266A  0  // ♪
#define UC_BEAMED_EIGHTH_NOTES                               0x266B  0  // ♫
#define UC_BEAMED_SIXTEENTH_NOTES                            0x266C  0  // ♬
#define UC_MUSIC_FLAT_SIGN                                   0x266D  0  // ♭
#define UC_MUSIC_NATURAL_SIGN                                0x266E  0  // ♮
#define UC_MUSIC_SHARP_SIGN                                  0x266F  0  // ♯
#define UC_WEST_SYRIAC_CROSS                                 0x2670  0  // ♰
#define UC_EAST_SYRIAC_CROSS                                 0x2671  0  // ♱
#define UC_UNIVERSAL_RECYCLING_SYMBOL                        0x2672  0  // ♲
#define UC_RECYCLING_SYMBOL_FOR_TYPE_1_PLASTICS              0x2673  0  // ♳
#define UC_RECYCLING_SYMBOL_FOR_TYPE_2_PLASTICS              0x2674  0  // ♴
#define UC_RECYCLING_SYMBOL_FOR_TYPE_3_PLASTICS              0x2675  0  // ♵
#define UC_RECYCLING_SYMBOL_FOR_TYPE_4_PLASTICS              0x2676  0  // ♶
#define UC_RECYCLING_SYMBOL_FOR_TYPE_5_PLASTICS              0x2677  0  // ♷
#define UC_RECYCLING_SYMBOL_FOR_TYPE_6_PLASTICS              0x2678  0  // ♸
#define UC_RECYCLING_SYMBOL_FOR_TYPE_7_PLASTICS              0x2679  0  // ♹
#define UC_RECYCLING_SYMBOL_FOR_GENERIC_MATERIALS            0x267A  0  // ♺
#define UC_BLACK_UNIVERSAL_RECYCLING_SYMBOL                  0x267B  0  // ♻
#define UC_RECYCLED_PAPER_SYMBOL                             0x267C  0  // ♼
#define UC_PARTIALLY_RECYCLED_PAPER_SYMBOL                   0x267D  0  // ♽
#define UC_PERMANENT_PAPER_SIGN                              0x267E  0  // ♾
#define UC_WHEELCHAIR_SYMBOL                                 0x267F  0  // ♿
#define UC_DIE_FACE_1                                        0x2680  0  // ⚀
#define UC_DIE_FACE_2                                        0x2681  0  // ⚁
#define UC_DIE_FACE_3                                        0x2682  0  // ⚂
#define UC_DIE_FACE_4                                        0x2683  0  // ⚃
#define UC_DIE_FACE_5                                        0x2684  0  // ⚄
#define UC_DIE_FACE_6                                        0x2685  0  // ⚅
#define UC_WHITE_CIRCLE_WITH_DOT_RIGHT                       0x2686  0  // ⚆
#define UC_WHITE_CIRCLE_WITH_TWO_DOTS                        0x2687  0  // ⚇
#define UC_BLACK_CIRCLE_WITH_WHITE_DOT_RIGHT                 0x2688  0  // ⚈
#define UC_BLACK_CIRCLE_WITH_TWO_WHITE_DOTS                  0x2689  0  // ⚉
#define UC_MONOGRAM_FOR_YANG                                 0x268A  0  // ⚊
#define UC_MONOGRAM_FOR_YIN                                  0x268B  0  // ⚋
#define UC_DIGRAM_FOR_GREATER_YANG                           0x268C  0  // ⚌
#define UC_DIGRAM_FOR_LESSER_YIN                             0x268D  0  // ⚍
#define UC_DIGRAM_FOR_LESSER_YANG                            0x268E  0  // ⚎
#define UC_DIGRAM_FOR_GREATER_YIN                            0x268F  0  // ⚏
#define UC_WHITE_FLAG                                        0x2690  0  // ⚐
#define UC_BLACK_FLAG                                        0x2691  0  // ⚑
#define UC_HAMMER_AND_PICK                                   0x2692  0  // ⚒
#define UC_ANCHOR                                            0x2693  0  // ⚓
#define UC_CROSSED_SWORDS                                    0x2694  0  // ⚔
#define UC_STAFF_OF_AESCULAPIUS                              0x2695  0  // ⚕
#define UC_SCALES                                            0x2696  0  // ⚖
#define UC_ALEMBIC                                           0x2697  0  // ⚗
#define UC_FLOWER                                            0x2698  0  // ⚘
#define UC_GEAR                                              0x2699  0  // ⚙
#define UC_STAFF_OF_HERMES                                   0x269A  0  // ⚚
#define UC_ATOM_SYMBOL                                       0x269B  0  // ⚛
#define UC_FLEUR_DE_LIS                                      0x269C  0  // ⚜
#define UC_OUTLINED_WHITE_STAR                               0x269D  0  // ⚝
#define UC_THREE_LINES_CONVERGING_RIGHT                      0x269E  0  // ⚞
#define UC_THREE_LINES_CONVERGING_LEFT                       0x269F  0  // ⚟
#define UC_WARNING_SIGN                                      0x26A0  0  // ⚠
#define UC_HIGH_VOLTAGE_SIGN                                 0x26A1  0  // ⚡
#define UC_DOUBLED_FEMALE_SIGN                               0x26A2  0  // ⚢
#define UC_DOUBLED_MALE_SIGN                                 0x26A3  0  // ⚣
#define UC_INTERLOCKED_FEMALE_AND_MALE_SIGN                  0x26A4  0  // ⚤
#define UC_MALE_AND_FEMALE_SIGN                              0x26A5  0  // ⚥
#define UC_MALE_WITH_STROKE_SIGN                             0x26A6  0  // ⚦
#define UC_MALE_WITH_STROKE_AND_MALE_AND_FEMALE_SIGN         0x26A7  0  // ⚧
#define UC_VERTICAL_MALE_WITH_STROKE_SIGN                    0x26A8  0  // ⚨
#define UC_HORIZONTAL_MALE_WITH_STROKE_SIGN                  0x26A9  0  // ⚩
#define UC_MEDIUM_WHITE_CIRCLE                               0x26AA  0  // ⚪
#define UC_MEDIUM_BLACK_CIRCLE                               0x26AB  0  // ⚫
#define UC_MEDIUM_SMALL_WHITE_CIRCLE                         0x26AC  0  // ⚬
#define UC_MARRIAGE_SYMBOL                                   0x26AD  0  // ⚭
#define UC_DIVORCE_SYMBOL                                    0x26AE  0  // ⚮
#define UC_UNMARRIED_PARTNERSHIP_SYMBOL                      0x26AF  0  // ⚯
#define UC_COFFIN                                            0x26B0  0  // ⚰
#define UC_FUNERAL_URN                                       0x26B1  0  // ⚱
#define UC_NEUTER                                            0x26B2  0  // ⚲
#define UC_CERES                                             0x26B3  0  // ⚳
#define UC_PALLAS                                            0x26B4  0  // ⚴
#define UC_JUNO                                              0x26B5  0  // ⚵
#define UC_VESTA                                             0x26B6  0  // ⚶
#define UC_CHIRON                                            0x26B7  0  // ⚷
#define UC_BLACK_MOON_LILITH                                 0x26B8  0  // ⚸
#define UC_SEXTILE                                           0x26B9  0  // ⚹
#define UC_SEMISEXTILE                                       0x26BA  0  // ⚺
#define UC_QUINCUNX                                          0x26BB  0  // ⚻
#define UC_SESQUIQUADRATE                                    0x26BC  0  // ⚼
#define UC_SOCCER_BALL                                       0x26BD  0  // ⚽
#define UC_BASEBALL                                          0x26BE  0  // ⚾
#define UC_SQUARED_KEY                                       0x26BF  0  // ⚿
#define UC_WHITE_DRAUGHTS_MAN                                0x26C0  0  // ⛀
#define UC_WHITE_DRAUGHTS_KING                               0x26C1  0  // ⛁
#define UC_BLACK_DRAUGHTS_MAN                                0x26C2  0  // ⛂
#define UC_BLACK_DRAUGHTS_KING                               0x26C3  0  // ⛃
#define UC_SNOWMAN_WITHOUT_SNOW                              0x26C4  0  // ⛄
#define UC_SUN_BEHIND_CLOUD                                  0x26C5  0  // ⛅
#define UC_RAIN                                              0x26C6  0  // ⛆
#define UC_BLACK_SNOWMAN                                     0x26C7  0  // ⛇
#define UC_THUNDER_CLOUD_AND_RAIN                            0x26C8  0  // ⛈
#define UC_TURNED_WHITE_SHOGI_PIECE                          0x26C9  0  // ⛉
#define UC_TURNED_BLACK_SHOGI_PIECE                          0x26CA  0  // ⛊
#define UC_WHITE_DIAMOND_IN_SQUARE                           0x26CB  0  // ⛋
#define UC_CROSSING_LANES                                    0x26CC  0  // ⛌
#define UC_DISABLED_CAR                                      0x26CD  0  // ⛍
#define UC_OPHIUCHUS                                         0x26CE  0  // ⛎
#define UC_PICK                                              0x26CF  0  // ⛏
#define UC_CAR_SLIDING                                       0x26D0  0  // ⛐
#define UC_HELMET_WITH_WHITE_CROSS                           0x26D1  0  // ⛑
#define UC_CIRCLED_CROSSING_LANES                            0x26D2  0  // ⛒
#define UC_CHAINS                                            0x26D3  0  // ⛓
#define UC_NO_ENTRY                                          0x26D4  0  // ⛔
#define UC_ALTERNATE_ONE_WAY_LEFT_WAY_TRAFFIC                0x26D5  0  // ⛕
#define UC_BLACK_TWO_WAY_LEFT_WAY_TRAFFIC                    0x26D6  0  // ⛖
#define UC_WHITE_TWO_WAY_LEFT_WAY_TRAFFIC                    0x26D7  0  // ⛗
#define UC_BLACK_LEFT_LANE_MERGE                             0x26D8  0  // ⛘
#define UC_WHITE_LEFT_LANE_MERGE                             0x26D9  0  // ⛙
#define UC_DRIVE_SLOW_SIGN                                   0x26DA  0  // ⛚
#define UC_HEAVY_WHITE_DOWN_POINTING_TRIANGLE                0x26DB  0  // ⛛
#define UC_LEFT_CLOSED_ENTRY                                 0x26DC  0  // ⛜
#define UC_SQUARED_SALTIRE                                   0x26DD  0  // ⛝
#define UC_FALLING_DIAGONAL_IN_WHITE_CIRCLE_IN_BLACK_SQUARE  0x26DE  0  // ⛞
#define UC_BLACK_TRUCK                                       0x26DF  0  // ⛟
#define UC_RESTRICTED_LEFT_ENTRY_1                           0x26E0  0  // ⛠
#define UC_RESTRICTED_LEFT_ENTRY_2                           0x26E1  0  // ⛡
#define UC_ASTRONOMICAL_SYMBOL_FOR_URANUS                    0x26E2  0  // ⛢
#define UC_HEAVY_CIRCLE_WITH_STROKE_AND_TWO_DOTS_ABOVE       0x26E3  0  // ⛣
#define UC_PENTAGRAM                                         0x26E4  0  // ⛤
#define UC_RIGHT_HANDED_INTERLACED_PENTAGRAM                 0x26E5  0  // ⛥
#define UC_LEFT_HANDED_INTERLACED_PENTAGRAM                  0x26E6  0  // ⛦
#define UC_INVERTED_PENTAGRAM                                0x26E7  0  // ⛧
#define UC_BLACK_CROSS_ON_SHIELD                             0x26E8  0  // ⛨
#define UC_SHINTO_SHRINE                                     0x26E9  0  // ⛩
#define UC_CHURCH                                            0x26EA  0  // ⛪
#define UC_CASTLE                                            0x26EB  0  // ⛫
#define UC_HISTORIC_SITE                                     0x26EC  0  // ⛬
#define UC_GEAR_WITHOUT_HUB                                  0x26ED  0  // ⛭
#define UC_GEAR_WITH_HANDLES                                 0x26EE  0  // ⛮
#define UC_MAP_SYMBOL_FOR_LIGHTHOUSE                         0x26EF  0  // ⛯
#define UC_MOUNTAIN                                          0x26F0  0  // ⛰
#define UC_UMBRELLA_ON_GROUND                                0x26F1  0  // ⛱
#define UC_FOUNTAIN                                          0x26F2  0  // ⛲
#define UC_FLAG_IN_HOLE                                      0x26F3  0  // ⛳
#define UC_FERRY                                             0x26F4  0  // ⛴
#define UC_SAILBOAT                                          0x26F5  0  // ⛵
#define UC_SQUARE_FOUR_CORNERS                               0x26F6  0  // ⛶
#define UC_SKIER                                             0x26F7  0  // ⛷
#define UC_ICE_SKATE                                         0x26F8  0  // ⛸
#define UC_PERSON_WITH_BALL                                  0x26F9  0  // ⛹
#define UC_TENT                                              0x26FA  0  // ⛺
#define UC_JAPANESE_BANK_SYMBOL                              0x26FB  0  // ⛻
#define UC_HEADSTONE_GRAVEYARD_SYMBOL                        0x26FC  0  // ⛼
#define UC_FUEL_PUMP                                         0x26FD  0  // ⛽
#define UC_CUP_ON_BLACK_SQUARE                               0x26FE  0  // ⛾
#define UC_WHITE_FLAG_WITH_HORIZONTAL_MIDDLE_BLACK_STRIPE    0x26FF  0  // ⛿