/*
 * Unicode keys for U+1E100 .. U+1E14F
 *
 * This file was generated from Unicode 16.0.0.
 *
 * See http://www.unicode.org/versions/Unicode16.0.0 for source data.
 */

#pragma once

#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_MA              0x1E100  0  // 𞄀
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_TSA             0x1E101  0  // 𞄁
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_NTA             0x1E102  0  // 𞄂
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_TA              0x1E103  0  // 𞄃
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_HA              0x1E104  0  // 𞄄
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_NA              0x1E105  0  // 𞄅
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_XA              0x1E106  0  // 𞄆
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_NKA             0x1E107  0  // 𞄇
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_CA              0x1E108  0  // 𞄈
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_LA              0x1E109  0  // 𞄉
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_SA              0x1E10A  0  // 𞄊
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_ZA              0x1E10B  0  // 𞄋
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_NCA             0x1E10C  0  // 𞄌
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_NTSA            0x1E10D  0  // 𞄍
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_KA              0x1E10E  0  // 𞄎
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_DA              0x1E10F  0  // 𞄏
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_NYA             0x1E110  0  // 𞄐
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_NRA             0x1E111  0  // 𞄑
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_VA              0x1E112  0  // 𞄒
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_NTXA            0x1E113  0  // 𞄓
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_TXA             0x1E114  0  // 𞄔
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_FA              0x1E115  0  // 𞄕
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_RA              0x1E116  0  // 𞄖
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_QA              0x1E117  0  // 𞄗
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_YA              0x1E118  0  // 𞄘
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_NQA             0x1E119  0  // 𞄙
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_PA              0x1E11A  0  // 𞄚
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_XYA             0x1E11B  0  // 𞄛
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_NPA             0x1E11C  0  // 𞄜
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_DLA             0x1E11D  0  // 𞄝
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_NPLA            0x1E11E  0  // 𞄞
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_HAH             0x1E11F  0  // 𞄟
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_MLA             0x1E120  0  // 𞄠
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_PLA             0x1E121  0  // 𞄡
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_GA              0x1E122  0  // 𞄢
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_RRA             0x1E123  0  // 𞄣
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_A               0x1E124  0  // 𞄤
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_AA              0x1E125  0  // 𞄥
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_I               0x1E126  0  // 𞄦
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_U               0x1E127  0  // 𞄧
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_O               0x1E128  0  // 𞄨
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_OO              0x1E129  0  // 𞄩
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_E               0x1E12A  0  // 𞄪
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_EE              0x1E12B  0  // 𞄫
#define UC_NYIAKENG_PUACHUE_HMONG_LETTER_W               0x1E12C  0  // 𞄬
#define UC_NYIAKENG_PUACHUE_HMONG_SIGN_FOR_PERSON        0x1E137  0  // 𞄷
#define UC_NYIAKENG_PUACHUE_HMONG_SIGN_FOR_THING         0x1E138  0  // 𞄸
#define UC_NYIAKENG_PUACHUE_HMONG_SIGN_FOR_LOCATION      0x1E139  0  // 𞄹
#define UC_NYIAKENG_PUACHUE_HMONG_SIGN_FOR_ANIMAL        0x1E13A  0  // 𞄺
#define UC_NYIAKENG_PUACHUE_HMONG_SIGN_FOR_INVERTEBRATE  0x1E13B  0  // 𞄻
#define UC_NYIAKENG_PUACHUE_HMONG_SIGN_XW_XW             0x1E13C  0  // 𞄼
#define UC_NYIAKENG_PUACHUE_HMONG_SYLLABLE_LENGTHENER    0x1E13D  0  // 𞄽
#define UC_NYIAKENG_PUACHUE_HMONG_DIGIT_ZERO             0x1E140  0  // 𞅀
#define UC_NYIAKENG_PUACHUE_HMONG_DIGIT_ONE              0x1E141  0  // 𞅁
#define UC_NYIAKENG_PUACHUE_HMONG_DIGIT_TWO              0x1E142  0  // 𞅂
#define UC_NYIAKENG_PUACHUE_HMONG_DIGIT_THREE            0x1E143  0  // 𞅃
#define UC_NYIAKENG_PUACHUE_HMONG_DIGIT_FOUR             0x1E144  0  // 𞅄
#define UC_NYIAKENG_PUACHUE_HMONG_DIGIT_FIVE             0x1E145  0  // 𞅅
#define UC_NYIAKENG_PUACHUE_HMONG_DIGIT_SIX              0x1E146  0  // 𞅆
#define UC_NYIAKENG_PUACHUE_HMONG_DIGIT_SEVEN            0x1E147  0  // 𞅇
#define UC_NYIAKENG_PUACHUE_HMONG_DIGIT_EIGHT            0x1E148  0  // 𞅈
#define UC_NYIAKENG_PUACHUE_HMONG_DIGIT_NINE             0x1E149  0  // 𞅉
#define UC_NYIAKENG_PUACHUE_HMONG_LOGOGRAM_NYAJ          0x1E14E  0  // 𞅎
#define UC_NYIAKENG_PUACHUE_HMONG_CIRCLED_CA             0x1E14F  0  // 𞅏