/*
 * Unicode keys for U+10A80 .. U+10A9F
 *
 * This file was generated from Unicode 16.0.0.
 *
 * See http://www.unicode.org/versions/Unicode16.0.0 for source data.
 */

#pragma once

#define UC_OLD_NORTH_ARABIAN_LETTER_HEH     0x10A80  0  // 𐪀
#define UC_OLD_NORTH_ARABIAN_LETTER_LAM     0x10A81  0  // 𐪁
#define UC_OLD_NORTH_ARABIAN_LETTER_HAH     0x10A82  0  // 𐪂
#define UC_OLD_NORTH_ARABIAN_LETTER_MEEM    0x10A83  0  // 𐪃
#define UC_OLD_NORTH_ARABIAN_LETTER_QAF     0x10A84  0  // 𐪄
#define UC_OLD_NORTH_ARABIAN_LETTER_WAW     0x10A85  0  // 𐪅
#define UC_OLD_NORTH_ARABIAN_LETTER_ES_2    0x10A86  0  // 𐪆
#define UC_OLD_NORTH_ARABIAN_LETTER_REH     0x10A87  0  // 𐪇
#define UC_OLD_NORTH_ARABIAN_LETTER_BEH     0x10A88  0  // 𐪈
#define UC_OLD_NORTH_ARABIAN_LETTER_TEH     0x10A89  0  // 𐪉
#define UC_OLD_NORTH_ARABIAN_LETTER_ES_1    0x10A8A  0  // 𐪊
#define UC_OLD_NORTH_ARABIAN_LETTER_KAF     0x10A8B  0  // 𐪋
#define UC_OLD_NORTH_ARABIAN_LETTER_NOON    0x10A8C  0  // 𐪌
#define UC_OLD_NORTH_ARABIAN_LETTER_KHAH    0x10A8D  0  // 𐪍
#define UC_OLD_NORTH_ARABIAN_LETTER_SAD     0x10A8E  0  // 𐪎
#define UC_OLD_NORTH_ARABIAN_LETTER_ES_3    0x10A8F  0  // 𐪏
#define UC_OLD_NORTH_ARABIAN_LETTER_FEH     0x10A90  0  // 𐪐
#define UC_OLD_NORTH_ARABIAN_LETTER_ALEF    0x10A91  0  // 𐪑
#define UC_OLD_NORTH_ARABIAN_LETTER_AIN     0x10A92  0  // 𐪒
#define UC_OLD_NORTH_ARABIAN_LETTER_DAD     0x10A93  0  // 𐪓
#define UC_OLD_NORTH_ARABIAN_LETTER_GEEM    0x10A94  0  // 𐪔
#define UC_OLD_NORTH_ARABIAN_LETTER_DAL     0x10A95  0  // 𐪕
#define UC_OLD_NORTH_ARABIAN_LETTER_GHAIN   0x10A96  0  // 𐪖
#define UC_OLD_NORTH_ARABIAN_LETTER_TAH     0x10A97  0  // 𐪗
#define UC_OLD_NORTH_ARABIAN_LETTER_ZAIN    0x10A98  0  // 𐪘
#define UC_OLD_NORTH_ARABIAN_LETTER_THAL    0x10A99  0  // 𐪙
#define UC_OLD_NORTH_ARABIAN_LETTER_YEH     0x10A9A  0  // 𐪚
#define UC_OLD_NORTH_ARABIAN_LETTER_THEH    0x10A9B  0  // 𐪛
#define UC_OLD_NORTH_ARABIAN_LETTER_ZAH     0x10A9C  0  // 𐪜
#define UC_OLD_NORTH_ARABIAN_NUMBER_ONE     0x10A9D  0  // 𐪝
#define UC_OLD_NORTH_ARABIAN_NUMBER_TEN     0x10A9E  0  // 𐪞
#define UC_OLD_NORTH_ARABIAN_NUMBER_TWENTY  0x10A9F  0  // 𐪟