/*
 * Unicode keys for U+1CF00 .. U+1CFCF
 *
 * This file was generated from Unicode 16.0.0.
 *
 * See http://www.unicode.org/versions/Unicode16.0.0 for source data.
 */

#pragma once

#define UC_ZNAMENNY_NEUME_KRYUK                                                   0x1CF50  0  // 𜽐
#define UC_ZNAMENNY_NEUME_KRYUK_TIKHY                                             0x1CF51  0  // 𜽑
#define UC_ZNAMENNY_NEUME_PARAKLIT                                                0x1CF52  0  // 𜽒
#define UC_ZNAMENNY_NEUME_DVA_V_CHELNU                                            0x1CF53  0  // 𜽓
#define UC_ZNAMENNY_NEUME_KLYUCH                                                  0x1CF54  0  // 𜽔
#define UC_ZNAMENNY_NEUME_ZANOZHEK                                                0x1CF55  0  // 𜽕
#define UC_ZNAMENNY_NEUME_STOPITSA                                                0x1CF56  0  // 𜽖
#define UC_ZNAMENNY_NEUME_STOPITSA_S_OCHKOM                                       0x1CF57  0  // 𜽗
#define UC_ZNAMENNY_NEUME_PEREVODKA                                               0x1CF58  0  // 𜽘
#define UC_ZNAMENNY_NEUME_PEREVODKA_NEPOSTOYANNAYA                                0x1CF59  0  // 𜽙
#define UC_ZNAMENNY_NEUME_STOPITSA_WITH_SOROCHYA_NOZHKA                           0x1CF5A  0  // 𜽚
#define UC_ZNAMENNY_NEUME_CHELYUSTKA                                              0x1CF5B  0  // 𜽛
#define UC_ZNAMENNY_NEUME_PALKA                                                   0x1CF5C  0  // 𜽜
#define UC_ZNAMENNY_NEUME_ZAPYATAYA                                               0x1CF5D  0  // 𜽝
#define UC_ZNAMENNY_NEUME_GOLUBCHIK_BORZY                                         0x1CF5E  0  // 𜽞
#define UC_ZNAMENNY_NEUME_GOLUBCHIK_TIKHY                                         0x1CF5F  0  // 𜽟
#define UC_ZNAMENNY_NEUME_GOLUBCHIK_MRACHNY                                       0x1CF60  0  // 𜽠
#define UC_ZNAMENNY_NEUME_GOLUBCHIK_SVETLY                                        0x1CF61  0  // 𜽡
#define UC_ZNAMENNY_NEUME_GOLUBCHIK_TRESVETLY                                     0x1CF62  0  // 𜽢
#define UC_ZNAMENNY_NEUME_VRAKHIYA_PROSTAYA                                       0x1CF63  0  // 𜽣
#define UC_ZNAMENNY_NEUME_VRAKHIYA_MRACHNAYA                                      0x1CF64  0  // 𜽤
#define UC_ZNAMENNY_NEUME_VRAKHIYA_SVETLAYA                                       0x1CF65  0  // 𜽥
#define UC_ZNAMENNY_NEUME_VRAKHIYA_TRESVETLAYA                                    0x1CF66  0  // 𜽦
#define UC_ZNAMENNY_NEUME_VRAKHIYA_KLYUCHEVAYA_PROSTAYA                           0x1CF67  0  // 𜽧
#define UC_ZNAMENNY_NEUME_VRAKHIYA_KLYUCHEVAYA_MRACHNAYA                          0x1CF68  0  // 𜽨
#define UC_ZNAMENNY_NEUME_VRAKHIYA_KLYUCHEVAYA_SVETLAYA                           0x1CF69  0  // 𜽩
#define UC_ZNAMENNY_NEUME_VRAKHIYA_KLYUCHEVAYA_TRESVETLAYA                        0x1CF6A  0  // 𜽪
#define UC_ZNAMENNY_NEUME_DOUBLE_ZAPYATAYA                                        0x1CF6B  0  // 𜽫
#define UC_ZNAMENNY_NEUME_REVERSED_CHELYUSTKA                                     0x1CF6C  0  // 𜽬
#define UC_ZNAMENNY_NEUME_DERBITSA                                                0x1CF6D  0  // 𜽭
#define UC_ZNAMENNY_NEUME_KHAMILO                                                 0x1CF6E  0  // 𜽮
#define UC_ZNAMENNY_NEUME_CHASHKA                                                 0x1CF6F  0  // 𜽯
#define UC_ZNAMENNY_NEUME_PODCHASHIE                                              0x1CF70  0  // 𜽰
#define UC_ZNAMENNY_NEUME_SKAMEYTSA_MRACHNAYA                                     0x1CF71  0  // 𜽱
#define UC_ZNAMENNY_NEUME_SKAMEYTSA_SVETLAYA                                      0x1CF72  0  // 𜽲
#define UC_ZNAMENNY_NEUME_SKAMEYTSA_TRESVETLAYA                                   0x1CF73  0  // 𜽳
#define UC_ZNAMENNY_NEUME_SKAMEYTSA_TIKHAYA                                       0x1CF74  0  // 𜽴
#define UC_ZNAMENNY_NEUME_DEMESTVENNY_KLYUCH                                      0x1CF75  0  // 𜽵
#define UC_ZNAMENNY_NEUME_SKAMEYTSA_KLYUCHEVAYA_SVETLAYA                          0x1CF76  0  // 𜽶
#define UC_ZNAMENNY_NEUME_SKAMEYTSA_KLYUCHENEPOSTOYANNAYA                         0x1CF77  0  // 𜽷
#define UC_ZNAMENNY_NEUME_SKAMEYTSA_KLYUCHEVAYA_TIKHAYA                           0x1CF78  0  // 𜽸
#define UC_ZNAMENNY_NEUME_SKAMEYTSA_DVOECHELNAYA_PROSTAYA                         0x1CF79  0  // 𜽹
#define UC_ZNAMENNY_NEUME_SKAMEYTSA_DVOECHELNAYA_SVETLAYA                         0x1CF7A  0  // 𜽺
#define UC_ZNAMENNY_NEUME_SKAMEYTSA_DVOECHELNAYA_NEPOSTOYANNAYA                   0x1CF7B  0  // 𜽻
#define UC_ZNAMENNY_NEUME_SKAMEYTSA_DVOECHELNAYA_KLYUCHEVAYA                      0x1CF7C  0  // 𜽼
#define UC_ZNAMENNY_NEUME_SLOZHITIE                                               0x1CF7D  0  // 𜽽
#define UC_ZNAMENNY_NEUME_SLOZHITIE_S_ZAPYATOY                                    0x1CF7E  0  // 𜽾
#define UC_ZNAMENNY_NEUME_SLOZHITIE_ZAKRYTOE                                      0x1CF7F  0  // 𜽿
#define UC_ZNAMENNY_NEUME_SLOZHITIE_S_KRYZHEM                                     0x1CF80  0  // 𜾀
#define UC_ZNAMENNY_NEUME_KRYZH                                                   0x1CF81  0  // 𜾁
#define UC_ZNAMENNY_NEUME_ROG                                                     0x1CF82  0  // 𜾂
#define UC_ZNAMENNY_NEUME_FITA                                                    0x1CF83  0  // 𜾃
#define UC_ZNAMENNY_NEUME_KOBYLA                                                  0x1CF84  0  // 𜾄
#define UC_ZNAMENNY_NEUME_ZMEYTSA                                                 0x1CF85  0  // 𜾅
#define UC_ZNAMENNY_NEUME_STATYA                                                  0x1CF86  0  // 𜾆
#define UC_ZNAMENNY_NEUME_STATYA_S_ZAPYATOY                                       0x1CF87  0  // 𜾇
#define UC_ZNAMENNY_NEUME_STATYA_S_KRYZHEM                                        0x1CF88  0  // 𜾈
#define UC_ZNAMENNY_NEUME_STATYA_S_ZAPYATOY_I_KRYZHEM                             0x1CF89  0  // 𜾉
#define UC_ZNAMENNY_NEUME_STATYA_S_KRYZHEM_I_ZAPYATOY                             0x1CF8A  0  // 𜾊
#define UC_ZNAMENNY_NEUME_STATYA_ZAKRYTAYA                                        0x1CF8B  0  // 𜾋
#define UC_ZNAMENNY_NEUME_STATYA_ZAKRYTAYA_S_ZAPYATOY                             0x1CF8C  0  // 𜾌
#define UC_ZNAMENNY_NEUME_STATYA_S_ROGOM                                          0x1CF8D  0  // 𜾍
#define UC_ZNAMENNY_NEUME_STATYA_S_DVUMYA_ZAPYATYMI                               0x1CF8E  0  // 𜾎
#define UC_ZNAMENNY_NEUME_STATYA_S_ZAPYATOY_I_PODCHASHIEM                         0x1CF8F  0  // 𜾏
#define UC_ZNAMENNY_NEUME_POLKULIZMY                                              0x1CF90  0  // 𜾐
#define UC_ZNAMENNY_NEUME_STATYA_NEPOSTOYANNAYA                                   0x1CF91  0  // 𜾑
#define UC_ZNAMENNY_NEUME_STRELA_PROSTAYA                                         0x1CF92  0  // 𜾒
#define UC_ZNAMENNY_NEUME_STRELA_MRACHNOTIKHAYA                                   0x1CF93  0  // 𜾓
#define UC_ZNAMENNY_NEUME_STRELA_KRYZHEVAYA                                       0x1CF94  0  // 𜾔
#define UC_ZNAMENNY_NEUME_STRELA_POLUPOVODNAYA                                    0x1CF95  0  // 𜾕
#define UC_ZNAMENNY_NEUME_STRELA_POVODNAYA                                        0x1CF96  0  // 𜾖
#define UC_ZNAMENNY_NEUME_STRELA_NEPOSTOYANNAYA                                   0x1CF97  0  // 𜾗
#define UC_ZNAMENNY_NEUME_STRELA_KLYUCHEPOVODNAYA                                 0x1CF98  0  // 𜾘
#define UC_ZNAMENNY_NEUME_STRELA_KLYUCHENEPOSTOYANNAYA                            0x1CF99  0  // 𜾙
#define UC_ZNAMENNY_NEUME_STRELA_TIKHAYA_PUTNAYA                                  0x1CF9A  0  // 𜾚
#define UC_ZNAMENNY_NEUME_STRELA_DVOECHELNAYA                                     0x1CF9B  0  // 𜾛
#define UC_ZNAMENNY_NEUME_STRELA_DVOECHELNOKRYZHEVAYA                             0x1CF9C  0  // 𜾜
#define UC_ZNAMENNY_NEUME_STRELA_DVOECHELNOPOVODNAYA                              0x1CF9D  0  // 𜾝
#define UC_ZNAMENNY_NEUME_STRELA_DVOECHELNAYA_KLYUCHEVAYA                         0x1CF9E  0  // 𜾞
#define UC_ZNAMENNY_NEUME_STRELA_DVOECHELNOPOVODNAYA_KLYUCHEVAYA                  0x1CF9F  0  // 𜾟
#define UC_ZNAMENNY_NEUME_STRELA_GROMNAYA_WITH_SINGLE_ZAPYATAYA                   0x1CFA0  0  // 𜾠
#define UC_ZNAMENNY_NEUME_STRELA_GROMOPOVODNAYA_WITH_SINGLE_ZAPYATAYA             0x1CFA1  0  // 𜾡
#define UC_ZNAMENNY_NEUME_STRELA_GROMNAYA                                         0x1CFA2  0  // 𜾢
#define UC_ZNAMENNY_NEUME_STRELA_GROMOPOVODNAYA                                   0x1CFA3  0  // 𜾣
#define UC_ZNAMENNY_NEUME_STRELA_GROMOPOVODNAYA_WITH_DOUBLE_ZAPYATAYA             0x1CFA4  0  // 𜾤
#define UC_ZNAMENNY_NEUME_STRELA_GROMOKRYZHEVAYA                                  0x1CFA5  0  // 𜾥
#define UC_ZNAMENNY_NEUME_STRELA_GROMOKRYZHEVAYA_POVODNAYA                        0x1CFA6  0  // 𜾦
#define UC_ZNAMENNY_NEUME_MECHIK                                                  0x1CFA7  0  // 𜾧
#define UC_ZNAMENNY_NEUME_MECHIK_POVODNY                                          0x1CFA8  0  // 𜾨
#define UC_ZNAMENNY_NEUME_MECHIK_KLYUCHEVOY                                       0x1CFA9  0  // 𜾩
#define UC_ZNAMENNY_NEUME_MECHIK_KLYUCHEPOVODNY                                   0x1CFAA  0  // 𜾪
#define UC_ZNAMENNY_NEUME_MECHIK_KLYUCHENEPOSTOYANNY                              0x1CFAB  0  // 𜾫
#define UC_ZNAMENNY_NEUME_STRELA_TRYASOGLASNAYA                                   0x1CFAC  0  // 𜾬
#define UC_ZNAMENNY_NEUME_STRELA_TRYASOPOVODNAYA                                  0x1CFAD  0  // 𜾭
#define UC_ZNAMENNY_NEUME_STRELA_TRYASOSTRELNAYA                                  0x1CFAE  0  // 𜾮
#define UC_ZNAMENNY_NEUME_OSOKA                                                   0x1CFAF  0  // 𜾯
#define UC_ZNAMENNY_NEUME_OSOKA_SVETLAYA                                          0x1CFB0  0  // 𜾰
#define UC_ZNAMENNY_NEUME_OSOKA_TRESVETLAYA                                       0x1CFB1  0  // 𜾱
#define UC_ZNAMENNY_NEUME_OSOKA_KRYUKOVAYA_SVETLAYA                               0x1CFB2  0  // 𜾲
#define UC_ZNAMENNY_NEUME_OSOKA_KLYUCHEVAYA_SVETLAYA                              0x1CFB3  0  // 𜾳
#define UC_ZNAMENNY_NEUME_OSOKA_KLYUCHEVAYA_NEPOSTOYANNAYA                        0x1CFB4  0  // 𜾴
#define UC_ZNAMENNY_NEUME_STRELA_KRYUKOVAYA                                       0x1CFB5  0  // 𜾵
#define UC_ZNAMENNY_NEUME_STRELA_KRYUKOVAYA_POVODNAYA                             0x1CFB6  0  // 𜾶
#define UC_ZNAMENNY_NEUME_STRELA_KRYUKOVAYA_GROMNAYA_WITH_SINGLE_ZAPYATAYA        0x1CFB7  0  // 𜾷
#define UC_ZNAMENNY_NEUME_STRELA_KRYUKOVAYA_GROMOPOVODNAYA_WITH_SINGLE_ZAPYATAYA  0x1CFB8  0  // 𜾸
#define UC_ZNAMENNY_NEUME_STRELA_KRYUKOVAYA_GROMNAYA                              0x1CFB9  0  // 𜾹
#define UC_ZNAMENNY_NEUME_STRELA_KRYUKOVAYA_GROMOPOVODNAYA                        0x1CFBA  0  // 𜾺
#define UC_ZNAMENNY_NEUME_STRELA_KRYUKOVAYA_GROMOPOVODNAYA_WITH_DOUBLE_ZAPYATAYA  0x1CFBB  0  // 𜾻
#define UC_ZNAMENNY_NEUME_STRELA_KRYUKOVAYA_GROMOKRYZHEVAYA                       0x1CFBC  0  // 𜾼
#define UC_ZNAMENNY_NEUME_STRELA_KRYUKOVAYA_GROMOKRYZHEVAYA_POVODNAYA             0x1CFBD  0  // 𜾽
#define UC_ZNAMENNY_NEUME_STRELA_KRYUKOVAYA_TRYASKA                               0x1CFBE  0  // 𜾾
#define UC_ZNAMENNY_NEUME_KUFISMA                                                 0x1CFBF  0  // 𜾿
#define UC_ZNAMENNY_NEUME_OBLAKO                                                  0x1CFC0  0  // 𜿀
#define UC_ZNAMENNY_NEUME_DUDA                                                    0x1CFC1  0  // 𜿁
#define UC_ZNAMENNY_NEUME_NEMKA                                                   0x1CFC2  0  // 𜿂
#define UC_ZNAMENNY_NEUME_PAUK                                                    0x1CFC3  0  // 𜿃